Repository GoogleCloudPlatform/python-docs-samples, pull requests merged in 2018-10, with the labels that each got.

#1720 Added Django sample for App Engine Python 3.7 standard runtime
  appengine/standard_python37/django/.gcloudignore
  appengine/standard_python37/django/README.md
  appengine/standard_python37/django/app.yaml
  appengine/standard_python37/django/main.py
  appengine/standard_python37/django/manage.py
  appengine/standard_python37/django/mysite/__init__.py
  appengine/standard_python37/django/mysite/settings.py
  appengine/standard_python37/django/mysite/urls.py
  appengine/standard_python37/django/mysite/wsgi.py
  appengine/standard_python37/django/polls/__init__.py
  appengine/standard_python37/django/polls/admin.py
  appengine/standard_python37/django/polls/apps.py
  appengine/standard_python37/django/polls/models.py
  appengine/standard_python37/django/polls/templates/polls/detail.html
  appengine/standard_python37/django/polls/templates/polls/index.html
  appengine/standard_python37/django/polls/templates/polls/results.html
  appengine/standard_python37/django/polls/tests.py
  appengine/standard_python37/django/polls/urls.py
  appengine/standard_python37/django/polls/views.py
  appengine/standard_python37/django/requirements.txt
Labels: cla: yes

#1733 Attempt to kickstart Travis CI.
  .travis.yml
Labels: cla: yes

#1735 [Storage] Add spacing in sample code.
  storage/cloud-client/bucket_lock.py
Labels: cla: yes

#1725 GCF: Add samples for billing
  functions/billing/main.py
  functions/billing/main_test.py
  functions/billing/requirements.txt
Labels: cla: yes, needs review

#1652 Added samples for handling CORS requests.
  functions/http/main.py
  functions/http/main_test.py
Labels: cla: yes

#1742 Added Spanner DML/PDML samples.
  spanner/cloud-client/requirements.txt
  spanner/cloud-client/snippets.py
  spanner/cloud-client/snippets_test.py
Labels: cla: yes

#1743 Use explicit URIs for Video Intelligence sample tests
  video/cloud-client/analyze/analyze_test.py
  video/cloud-client/analyze/beta_snippets_test.py
  video/cloud-client/labels/labels_test.py
  video/cloud-client/shotchange/shotchange_test.py
Labels: cla: yes

#1744 update requirements.txt with oauth2client
  iot/api-client/end_to_end_example/requirements.txt
Labels: cla: yes

#1730 Fix serving static files on production
  appengine/standard_python37/django/app.yaml
Labels: cla: yes

#1672 Added samples for using Cloud SQL with App Engine Python 3.7 Standard
  appengine/standard_python37/cloudsql/app.yaml
  appengine/standard_python37/cloudsql/main_mysql.py
  appengine/standard_python37/cloudsql/main_mysql_pooling.py
  appengine/standard_python37/cloudsql/main_postgres.py
  appengine/standard_python37/cloudsql/main_postgres_pooling.py
  appengine/standard_python37/cloudsql/main_test.py
  appengine/standard_python37/cloudsql/requirements.txt
Labels: cla: no

#1728 Fix for error when missing MySQLdb
  appengine/standard_python37/django/mysite/settings.py
Labels: cla: yes

#1750 Update to latest trampoline.sh
  .kokoro/trampoline.sh
Labels: cla: yes

#1751 Add missing requirements.txt for a quickstart
  appengine/standard/endpoints-frameworks-v2/quickstart/requirements.txt
Labels: cla: yes

#1753 Pub/Sub: moved import statements inside region tags
  pubsub/cloud-client/publisher.py
  pubsub/cloud-client/subscriber.py
Labels: cla: yes

#1748 Move GCF tests to Python 3 + Add linting
  .kokoro/presubmit_tests_functions.cfg
Labels: cla: yes

#1740 Add analytics sample
  functions/firebase/main.py
  functions/firebase/main_test.py
Labels: cla: yes, needs review

#1755 Fixed print statements
  bigtable/hello/main.py
  bigtable/instanceadmin/instanceadmin.py
  bigtable/tableadmin/tableadmin.py
Labels: cla: yes, kokoro:force-run, kokoro:run

#1739 Add Firestore reactive sample
  functions/firebase/main.py
  functions/firebase/main_test.py
  functions/firebase/requirements.txt
Labels: cla: yes

#1738 Access Display Names of enum fields via enum object
  language/cloud-client/v1/requirements.txt
  language/cloud-client/v1/snippets.py
  texttospeech/cloud-client/list_voices.py
  video/cloud-client/analyze/analyze.py
Labels: cla: yes

#1764 Making bigtable tests run successfully
  bigtable/hello/main.py
  bigtable/tableadmin/tableadmin.py
  bigtable/tableadmin/tableadmin_test.py
Labels: cla: yes

#1768 Revert to using last successful Trampoline image
  .kokoro/common.cfg
Labels: cla: yes

#1715 Remove unused and outdated Natural Language samples
  language/README.md
  language/cloud-client/v1beta2/README.rst
  language/cloud-client/v1beta2/README.rst.in
  language/cloud-client/v1beta2/quickstart.py
  language/cloud-client/v1beta2/quickstart_test.py
  language/cloud-client/v1beta2/requirements.txt
  language/cloud-client/v1beta2/resources/android_text.txt
  language/cloud-client/v1beta2/resources/text.txt
  language/cloud-client/v1beta2/snippets.py
  language/cloud-client/v1beta2/snippets_test.py
  language/movie_nl/README.md
  language/movie_nl/main.py
  language/movie_nl/main_test.py
  language/movie_nl/requirements.txt
  language/ocr_nl/README.md
  language/ocr_nl/main.py
  language/ocr_nl/main_test.py
  language/ocr_nl/requirements.txt
  language/syntax_triples/README.md
  language/syntax_triples/main.py
  language/syntax_triples/main_test.py
  language/syntax_triples/requirements.txt
  language/syntax_triples/resources/obama_wikipedia.txt
  language/tutorial/README.rst
  language/tutorial/README.rst.in
  language/tutorial/requirements.txt
  language/tutorial/reviews/bladerunner-mixed.txt
  language/tutorial/reviews/bladerunner-neg.txt
  language/tutorial/reviews/bladerunner-neutral.txt
  language/tutorial/reviews/bladerunner-pos.txt
  language/tutorial/tutorial.py
  language/tutorial/tutorial_test.py
Labels: cla: yes

#1746 Iot commands beta
  iot/api-client/beta-features/commands/README.md
  iot/api-client/beta-features/commands/receive/README.rst
  iot/api-client/beta-features/commands/receive/README.rst.in
  iot/api-client/beta-features/commands/receive/receive.py
  iot/api-client/beta-features/commands/receive/receive_test.py
  iot/api-client/beta-features/commands/receive/requirements.txt
  iot/api-client/beta-features/commands/receive/resources/README.md
  iot/api-client/beta-features/commands/receive/resources/roots.pem
  iot/api-client/beta-features/commands/receive/resources/rsa_cert.pem
  iot/api-client/beta-features/commands/receive/resources/rsa_private.pem
  iot/api-client/beta-features/commands/send/README.rst
  iot/api-client/beta-features/commands/send/README.rst.in
  iot/api-client/beta-features/commands/send/requirements.txt
  iot/api-client/beta-features/commands/send/send.py
  iot/api-client/beta-features/commands/send/send_test.py
Labels: cla: no

#1770 Added Bu Sun's updates, fixed some lint errors
  .kokoro/common.cfg
  .travis.yml
  appengine/standard_python37/django/mysite/settings.py
  appengine/standard_python37/django/polls/admin.py
  appengine/standard_python37/django/polls/models.py
  appengine/standard_python37/django/polls/tests.py
  appengine/standard_python37/django/polls/views.py
  bigtable/hello/main.py
  ml_engine/online_prediction/predict.py
  noxfile.py
Labels: cla: yes

#1767 Remove CreateIfMissingOption
  firestore/cloud-client/requirements.txt
  firestore/cloud-client/snippets.py
Labels: cla: yes

#1779 Fixed name of model
  language/automl/predict_test.py
  translate/automl/predict_test.py
  vision/automl/predict_test.py
Labels: cla: yes

#1778 Handle delete Not Found exceptions if needed
  dns/api/main_test.py
Labels: cla: yes

#1777 Use currently available Debian image family
  compute/api/create_instance.py
Labels: cla: yes

#1787 Include the comma in the translation
  translate/cloud-client/quickstart_test.py
Labels: cla: yes

#1752 Add sample for using BigQuery in App Engine Python 3.7 runtime
  appengine/standard_python37/bigquery/app.yaml
  appengine/standard_python37/bigquery/main.py
  appengine/standard_python37/bigquery/main_test.py
  appengine/standard_python37/bigquery/requirements.txt
  appengine/standard_python37/bigquery/templates/query_result.html
Labels: cla: yes

#1757 Added sample for using Cloud Spanner with App Engine Python 3.7 runtime.
  appengine/standard_python37/spanner/app.yaml
  appengine/standard_python37/spanner/main.py
  appengine/standard_python37/spanner/main_test.py
  appengine/standard_python37/spanner/requirements.txt
Labels: cla: yes

#1771 KMS import comments
  kms/api-client/asymmetric.py
Labels: cla: yes

#1780 [Firebase] Add snapshot cursors sample
  firestore/cloud-client/snippets.py
  firestore/cloud-client/snippets_test.py
Labels: cla: yes

#1792 Changed surface of echo API to match the Java version
  appengine/standard/endpoints-frameworks-v2/echo/main.py
  appengine/standard/endpoints-frameworks-v2/echo/main_test.py
Labels: cla: yes

#1794 updating to latest happy base client version.
  bigtable/hello_happybase/requirements.txt
Labels: cla: yes

#1797 Add print statements
  vision/cloud-client/crop_hints/crop_hints.py
Labels: cla: yes

#1799 Address broken test by updating CREATE MODEL options.
  bigquery/bqml/ncaa_tutorial_test.py
Labels: cla: yes

#1783 Add CHC API alpha datasets and FHIR samples and tests.
  healthcare/api-client/datasets/README.rst
  healthcare/api-client/datasets/README.rst.in
  healthcare/api-client/datasets/datasets.py
  healthcare/api-client/datasets/datasets_test.py
  healthcare/api-client/datasets/requirements.txt
  healthcare/api-client/fhir/README.rst
  healthcare/api-client/fhir/README.rst.in
  healthcare/api-client/fhir/fhir_resources.py
  healthcare/api-client/fhir/fhir_resources_test.py
  healthcare/api-client/fhir/fhir_stores.py
  healthcare/api-client/fhir/fhir_stores_test.py
  healthcare/api-client/fhir/requirements.txt
Labels: cla: yes

#1791 more info on alternatives
  video/cloud-client/analyze/beta_snippets.py
Labels: cla: yes
