Repository GoogleCloudPlatform/python-docs-samples, pull requests merged in 2018-07, with the labels that each got.

#1524 Add DLP code samples for custom info types
  dlp/deid.py
  dlp/deid_test.py
  dlp/inspect_content.py
  dlp/inspect_content_test.py
Labels: cla: yes

#1560 Adds code snippets for Jupyter data visualization tutorial
  bigquery/cloud-client/jupyter_tutorial_test.py
  bigquery/cloud-client/requirements.txt
Labels: bigquery, cla: yes

#1538 [DO NOT MERGE] Added Audio Profile sample
  texttospeech/cloud-client/README.rst
  texttospeech/cloud-client/README.rst.in
  texttospeech/cloud-client/audio_profile.py
  texttospeech/cloud-client/audio_profile_test.py
  texttospeech/cloud-client/requirements.txt
Labels: cla: yes

#1556 Diarization
  speech/cloud-client/README.rst
  speech/cloud-client/beta_snippets.py
  speech/cloud-client/beta_snippets_test.py
  speech/cloud-client/requirements.txt
Labels: cla: yes

#1563 Fix run command for Cloud Tasks
  tasks/README.md
Labels: cla: yes

#1561 Multi Channel
  speech/cloud-client/README.rst
  speech/cloud-client/beta_snippets.py
  speech/cloud-client/beta_snippets_test.py
Labels: cla: yes

#1503 modify middleware settings and url paths for django 2.0
  container_engine/django_tutorial/Dockerfile
  container_engine/django_tutorial/mysite/settings.py
  container_engine/django_tutorial/mysite/urls.py
  container_engine/django_tutorial/polls/urls.py
Labels: cla: yes

#1564 Multi Langauge
  speech/cloud-client/README.rst
  speech/cloud-client/beta_snippets.py
  speech/cloud-client/beta_snippets_test.py
  speech/cloud-client/resources/multi.wav
Labels: cla: yes

#1562 Update tableadmin
  bigtable/tableadmin/tableadmin.py
  bigtable/tableadmin/tableadmin_test.py
Labels: cla: yes

#1567 Added the sample for Word Level Confidence
  speech/cloud-client/README.rst
  speech/cloud-client/beta_snippets.py
  speech/cloud-client/beta_snippets_test.py
Labels: cla: yes

#1566 update gcloud command for Cloud Tasks
  appengine/flexible/tasks/README.md
  tasks/README.md
Labels: cla: yes

#1573 require gunicorn for GAE flex Cloud Tasks example
  appengine/flexible/tasks/requirements.txt
Labels: cla: yes

#1578 Updates BQ Tutorial chart to count of births by gestation weeks
  bigquery/cloud-client/jupyter_tutorial_test.py
Labels: bigquery, cla: yes

#1546 Check in Cloud Job Discovery client code samples for python
  jobs/api_client/README.rst
  jobs/api_client/README.rst.in
  jobs/api_client/auto_complete_sample.py
  jobs/api_client/auto_complete_sample_test.py
  jobs/api_client/base_company_sample.py
  jobs/api_client/base_company_sample_test.py
  jobs/api_client/base_job_sample.py
  jobs/api_client/base_job_sample_test.py
  jobs/api_client/batch_operation_sample.py
  jobs/api_client/batch_operation_sample_test.py
  jobs/api_client/commute_search_sample.py
  jobs/api_client/commute_search_sample_test.py
  jobs/api_client/custom_attribute_sample.py
  jobs/api_client/custom_attribute_sample_test.py
  jobs/api_client/email_alert_search_sample.py
  jobs/api_client/email_alert_search_sample_test.py
  jobs/api_client/featured_job_search_sample.py
  jobs/api_client/featured_job_search_sample_test.py
  jobs/api_client/general_search_sample.py
  jobs/api_client/general_search_sample_test.py
  jobs/api_client/histogram_sample.py
  jobs/api_client/histogram_sample_test.py
  jobs/api_client/location_search_sample.py
  jobs/api_client/location_search_sample_test.py
  jobs/api_client/quickstart.py
  jobs/api_client/quickstart_test.py
  jobs/api_client/requirements.txt
Labels: cla: no

#1583 Add Google Cloud Functions Python runtime samples
  functions/README.rst
  functions/README.rst.in
  functions/concepts/README.md
  functions/concepts/main.py
  functions/concepts/main_test.py
  functions/helloworld/README.md
  functions/helloworld/main.py
  functions/helloworld/main_test.py
  functions/helloworld/sample_http_test.py
  functions/helloworld/sample_http_test_system.py
  functions/helloworld/sample_pubsub_test.py
  functions/helloworld/sample_storage_test.py
  functions/log/README.md
  functions/log/main.py
  functions/log/main_test.py
  functions/tips/README.md
  functions/tips/main.py
  functions/tips/main_test.py
  functions/tips/requirements.txt
Labels: cla: yes

#1568 Modified publisher with error handling
  pubsub/cloud-client/publisher.py
  pubsub/cloud-client/publisher_test.py
  pubsub/cloud-client/requirements.txt
Labels: cla: yes

#1584 Add system tests for pubsub and storage GCF
  functions/helloworld/sample_pubsub_test_system.py
  functions/helloworld/sample_storage_test_system.py
Labels: cla: yes

#1572 [DO_NOT_MERGE] Add samples for object localization and handwritten ocr
  vision/cloud-client/detect/README.rst
  vision/cloud-client/detect/README.rst.in
  vision/cloud-client/detect/beta_snippets.py
  vision/cloud-client/detect/beta_snippets_test.py
  vision/cloud-client/detect/requirements.txt
  vision/cloud-client/detect/resources/duck_and_truck.jpg
  vision/cloud-client/detect/resources/handwritten.jpg
  vision/cloud-client/detect/resources/puppies.jpg
Labels: cla: yes

#1576 Add Python dependencies example workflow.
  composer/workflows/README.rst
  composer/workflows/README.rst.in
  composer/workflows/dependencies/__init__.py
  composer/workflows/dependencies/coin_module.py
  composer/workflows/requirements.txt
  composer/workflows/use_local_deps.py
  composer/workflows/use_local_deps_test.py
Labels: cla: yes, kokoro:run

#1585 Added samples for Storage, OCR, and Slack tutorial
  .gitignore
  functions/gcs/README.md
  functions/gcs/main.py
  functions/gcs/main_test.py
  functions/helloworld/sample_pubsub_test_system.py
  functions/ocr/README.md
  functions/ocr/app/config.json
  functions/ocr/app/main.py
  functions/ocr/app/main_test.py
  functions/ocr/app/requirements.txt
  functions/ocr/images/menu.jpg
  functions/ocr/images/sign.png
  functions/slack/README.md
  functions/slack/config.json
  functions/slack/main.py
  functions/slack/main_test.py
  functions/slack/requirements.txt
  testing/requirements.txt
Labels: cla: yes

#1589 Make argument names and docstrings consistent for background functions
  functions/helloworld/main.py
Labels: cla: yes

#1586 Diarization Output Modified
  speech/cloud-client/README.rst
  speech/cloud-client/beta_snippets.py
  speech/cloud-client/beta_snippets_test.py
  texttospeech/cloud-client/audio_profile.py
Labels: cla: yes

#1575 automl beta
  language/automl/automl_natural_language_dataset.py
  language/automl/automl_natural_language_model.py
  language/automl/automl_natural_language_predict.py
  language/automl/dataset_test.py
  language/automl/model_test.py
  language/automl/predict_test.py
  language/automl/requirements.txt
  language/automl/resources/test.txt
  translate/automl/automl_translation_dataset.py
  translate/automl/automl_translation_model.py
  translate/automl/automl_translation_predict.py
  translate/automl/dataset_test.py
  translate/automl/model_test.py
  translate/automl/predict_test.py
  translate/automl/requirements.txt
  translate/automl/resources/input.txt
  vision/automl/automl_vision_dataset.py
  vision/automl/automl_vision_model.py
  vision/automl/automl_vision_predict.py
  vision/automl/dataset_test.py
  vision/automl/model_test.py
  vision/automl/predict_test.py
  vision/automl/requirements.txt
  vision/automl/resources/test.png
Labels: cla: yes

#1580 Product search
  vision/cloud-client/product_search/import_product_sets.py
  vision/cloud-client/product_search/import_product_sets_test.py
  vision/cloud-client/product_search/product_in_product_set_management.py
  vision/cloud-client/product_search/product_in_product_set_management_test.py
  vision/cloud-client/product_search/product_management.py
  vision/cloud-client/product_search/product_management_test.py
  vision/cloud-client/product_search/product_search.py
  vision/cloud-client/product_search/product_search_test.py
  vision/cloud-client/product_search/product_set_management.py
  vision/cloud-client/product_search/product_set_management_test.py
  vision/cloud-client/product_search/reference_image_management.py
  vision/cloud-client/product_search/reference_image_management_test.py
  vision/cloud-client/product_search/requirements.txt
  vision/cloud-client/product_search/resources/indexed_product_sets.csv
  vision/cloud-client/product_search/resources/product_sets.csv
  vision/cloud-client/product_search/resources/shoes_1.jpg
  vision/cloud-client/product_search/resources/shoes_2.jpg
Labels: cla: yes

#1590 Add samples for using GCP connections in an Airflow DAG
  composer/workflows/bq_notify.py
  composer/workflows/connections.py
  composer/workflows/connections_test.py
  composer/workflows/kubernetes_pod_operator.py
  composer/workflows/quickstart.py
  composer/workflows/simple.py
  composer/workflows/use_local_deps.py
Labels: cla: yes

#1597 use lcm instead of vcm
  language/automl/dataset_test.py
Labels: cla: yes

#1598 remove translate prediction fallback
  translate/automl/automl_translation_predict.py
  translate/automl/predict_test.py
Labels: cla: yes

#1599 Fixes port type from argument parser.
  iot/api-client/end_to_end_example/cloudiot_pubsub_example_mqtt_device.py
Labels: cla: yes

#1601 Use example node pool names for affinity argument
  composer/workflows/kubernetes_pod_operator.py
Labels: cla: yes

#1606 Pub/Sub Sample for App Engine Standard
  appengine/standard/pubsub/README.md
  appengine/standard/pubsub/app.yaml
  appengine/standard/pubsub/main.py
  appengine/standard/pubsub/main_test.py
  appengine/standard/pubsub/requirements.txt
  appengine/standard/pubsub/sample_message.json
  appengine/standard/pubsub/templates/index.html
Labels: cla: yes
