Repository GoogleCloudPlatform/python-docs-samples, pull requests merged in 2018-09, with the labels that each got.

#1661 Adding README for Bigtable python samples
  bigtable/README.rst
  bigtable/README.rst.in
Labels: automerge, cla: yes

#1674 Upgrading the metrics query to the latest version
  bigtable/metricscaler/metricscaler.py
  bigtable/metricscaler/metricscaler_test.py
  bigtable/metricscaler/requirements.txt
Labels: automerge, cla: yes

#1687 Fix AutoML region tag typos
  translate/automl/automl_translation_dataset.py
  vision/automl/automl_vision_dataset.py
Labels: cla: yes

#1685 Fixed return object from `subscriber.subscribe()`
  pubsub/cloud-client/subscriber.py
Labels: cla: yes

#1690 KMS test fix
  kms/api-client/asymmetric_test.py
Labels: cla: yes

#1688 Test Composer samples on Python 3
  .kokoro/presubmit_tests_composer.cfg
  .travis.yml
  composer/workflows/use_local_deps_test.py
  nox.py
  testing/test-env.tmpl.sh
Labels: cla: yes, kokoro:run

#1700 Remove appengine BigQuery sample
  appengine/standard/bigquery/.gitignore
  appengine/standard/bigquery/README.md
  appengine/standard/bigquery/app.yaml
  appengine/standard/bigquery/appengine_config.py
  appengine/standard/bigquery/client_secrets.json
  appengine/standard/bigquery/main.py
  appengine/standard/bigquery/main_test.py
  appengine/standard/bigquery/requirements.txt
  appengine/standard/bigquery/resources/datasets-list.json
Labels: cla: yes

#1698 Update Cloud Tasks Push Queue Sample
  appengine/flexible/tasks/README.md
  appengine/flexible/tasks/create_app_engine_queue_task.py
  appengine/flexible/tasks/requirements.txt
  tasks/README.md
  tasks/pull_queue_snippets.py
  tasks/pull_queue_snippets_test.py
  tasks/requirements.txt
Labels: cla: yes

#1655 Add GCF Python SQL samples
  .kokoro/presubmit_tests_functions_sql.cfg
  .kokoro/system_tests.sh
  functions/sql/mysql_sample.py
  functions/sql/mysql_test.py
  functions/sql/postgres_sample.py
  functions/sql/postgres_test.py
  functions/sql/requirements.txt
  testing/secrets.tar.enc
  testing/test-env.tmpl.sh
Labels: cla: yes, kokoro:run

#1705 Add Composer Environment Migration script
  composer/tools/__init__.py
  composer/tools/copy_environment.py
  composer/tools/copy_environment_test.py
  composer/tools/requirements.txt
Labels: cla: yes

#1701 Pub/Sub: synchronous pull with lease management
  pubsub/cloud-client/requirements.txt
  pubsub/cloud-client/subscriber.py
  pubsub/cloud-client/subscriber_test.py
Labels: cla: yes

#1691 Add python samples for BQML tutorials
  bigquery/bqml/data_scientist_tutorial_test.py
  bigquery/bqml/ncaa_tutorial_test.py
  bigquery/bqml/requirements.txt
  bigquery/bqml/resources/feature_input_query.sql
  bigquery/bqml/resources/training_data_query.sql
Labels: bigquery, cla: yes

#1604 Rebrand Cloud Job Discovery to Cloud Talent Solution and add the V3 code samples
  jobs/v2/api_client/README.rst
  jobs/v2/api_client/README.rst.in
  jobs/v2/api_client/auto_complete_sample.py
  jobs/v2/api_client/auto_complete_sample_test.py
  jobs/v2/api_client/base_company_sample.py
  jobs/v2/api_client/base_company_sample_test.py
  jobs/v2/api_client/base_job_sample.py
  jobs/v2/api_client/base_job_sample_test.py
  jobs/v2/api_client/batch_operation_sample.py
  jobs/v2/api_client/batch_operation_sample_test.py
  jobs/v2/api_client/commute_search_sample.py
  jobs/v2/api_client/commute_search_sample_test.py
  jobs/v2/api_client/custom_attribute_sample.py
  jobs/v2/api_client/custom_attribute_sample_test.py
  jobs/v2/api_client/email_alert_search_sample.py
  jobs/v2/api_client/email_alert_search_sample_test.py
  jobs/v2/api_client/featured_job_search_sample.py
  jobs/v2/api_client/featured_job_search_sample_test.py
  jobs/v2/api_client/general_search_sample.py
  jobs/v2/api_client/general_search_sample_test.py
  jobs/v2/api_client/histogram_sample.py
  jobs/v2/api_client/histogram_sample_test.py
  jobs/v2/api_client/location_search_sample.py
  jobs/v2/api_client/location_search_sample_test.py
  jobs/v2/api_client/quickstart.py
  jobs/v2/api_client/quickstart_test.py
  jobs/v2/api_client/requirements.txt
  jobs/v3/api_client/README.rst
  jobs/v3/api_client/README.rst.in
  jobs/v3/api_client/auto_complete_sample.py
  jobs/v3/api_client/auto_complete_sample_test.py
  jobs/v3/api_client/base_company_sample.py
  jobs/v3/api_client/base_company_sample_test.py
  jobs/v3/api_client/base_job_sample.py
  jobs/v3/api_client/base_job_sample_test.py
  jobs/v3/api_client/batch_operation_sample.py
  jobs/v3/api_client/batch_operation_sample_test.py
  jobs/v3/api_client/commute_search_sample.py
  jobs/v3/api_client/commute_search_sample_test.py
  jobs/v3/api_client/custom_attribute_sample.py
  jobs/v3/api_client/custom_attribute_sample_test.py
  jobs/v3/api_client/email_alert_search_sample.py
  jobs/v3/api_client/email_alert_search_sample_test.py
  jobs/v3/api_client/featured_job_search_sample.py
  jobs/v3/api_client/featured_job_search_sample_test.py
  jobs/v3/api_client/general_search_sample.py
  jobs/v3/api_client/general_search_sample_test.py
  jobs/v3/api_client/histogram_sample.py
  jobs/v3/api_client/histogram_sample_test.py
  jobs/v3/api_client/location_search_sample.py
  jobs/v3/api_client/location_search_sample_test.py
  jobs/v3/api_client/quickstart.py
  jobs/v3/api_client/quickstart_test.py
  jobs/v3/api_client/requirements.txt
Labels: cla: no

#1711 Add Composer samples that explicitly call python2
  composer/data/python2_script.py
  composer/workflows/bashoperator_python2.py
  composer/workflows/bashoperator_python2_test.py
  composer/workflows/pythonvirtualenvoperator_python2.py
  composer/workflows/pythonvirtualenvoperator_python2_test.py
Labels: cla: yes

#1702 Update enhanced models and auto punctuation to GA
  speech/cloud-client/README.rst
  speech/cloud-client/README.rst.in
  speech/cloud-client/requirements.txt
  speech/cloud-client/transcribe_auto_punctuation.py
  speech/cloud-client/transcribe_auto_punctuation_test.py
  speech/cloud-client/transcribe_enhanced_model.py
  speech/cloud-client/transcribe_enhanced_model_test.py
  speech/cloud-client/transcribe_model_selection.py
Labels: cla: yes

#1704 Update samples to GA, cleanup tests, delete old samples
  vision/cloud-client/detect/README.rst
  vision/cloud-client/detect/detect.py
  vision/cloud-client/detect/detect_pdf.py
  vision/cloud-client/detect/detect_pdf_test.py
  vision/cloud-client/detect/detect_test.py
  vision/cloud-client/detect/requirements.txt
Labels: cla: yes

#1717 Added k8s config file from endpoints-samples/k8s
  endpoints/getting-started/k8s/esp_echo_http.yaml
Labels: cla: yes

#1714 Test pythonvirtualenvoperator sample in Python 3.
  composer/workflows/pythonvirtualenvoperator_python2_test.py
Labels: cla: yes

#1713 Updates dependencies
  iot/api-client/end_to_end_example/requirements.txt
  iot/api-client/manager/requirements.txt
Labels: cla: yes, kokoro:force-run

#1710 Fix DPEBot auto-update failure
  functions/ocr/app/requirements.txt
  testing/secrets.tar.enc
  testing/test-env.tmpl.sh
Labels: cla: yes

#1684 Add GCF imagemagick samples
  functions/imagemagick/README.md
  functions/imagemagick/main.py
  functions/imagemagick/main_test.py
  functions/imagemagick/requirements.txt
Labels: cla: yes, needs review

#1703 GCF SQL: Use proper environment variables
  functions/sql/mysql_sample.py
  functions/sql/postgres_sample.py
Labels: cla: yes, needs review

#1723 KMS changes
  kms/api-client/asymmetric.py
  kms/api-client/asymmetric_test.py
Labels: cla: yes

#1709 Fix timestamp in avoid_infinite_retries
  functions/tips/main.py
  functions/tips/main_test.py
Labels: cla: yes, needs review

#1707 GCF: Add Stackdriver triggers sample
  functions/log/main.py
  functions/log/main_test.py
Labels: cla: yes, needs review

#1681 Added sample for using Cloud Spanner w/ Cloud Functions
  functions/spanner/README.md
  functions/spanner/main.py
  functions/spanner/main_test.py
  functions/spanner/requirements.txt
Labels: cla: yes
