Repository GoogleCloudPlatform/python-docs-samples, pull requests merged in 2018-06, with the labels that each got.

#1512 Fixed Initialize Firebase section and add snippet
  appengine/standard/firebase/firenotes/frontend/main.js
Labels: cla: yes

#1510 Storage: add KMS samples
  storage/cloud-client/README.rst
  storage/cloud-client/requirements.txt
  storage/cloud-client/snippets.py
  storage/cloud-client/snippets_test.py
  testing/secrets.tar.enc
Labels: cla: yes

#1517 [Storage] Update kms samples
  storage/cloud-client/snippets.py
  storage/cloud-client/snippets_test.py
Labels: cla: yes

#1519 Adding Spanner STRUCT param samples
  spanner/cloud-client/snippets.py
  spanner/cloud-client/snippets_test.py
Labels: cla: yes

#1523 Update library to GA
  texttospeech/cloud-client/requirements.txt
Labels: cla: yes

#1520 Composer: Add schedule to simple workflow.
  composer/workflows/simple.py
Labels: cla: yes

#1522 Move ocr pdf/tiff samples to GA
  vision/cloud-client/detect/README.rst
  vision/cloud-client/detect/detect.py
  vision/cloud-client/detect/detect_test.py
  vision/cloud-client/detect/requirements.txt
Labels: cla: yes

#1529 Update Cloud Tasks Samples
  tasks/pull_queue_snippets.py
  tasks/pull_queue_snippets_test.py
  tasks/requirements.txt
Labels: cla: yes

#1531 Delete unused Datastore region tags / samples.
  datastore/cloud-client/snippets.py
  datastore/cloud-client/snippets_test.py
  datastore/cloud-client/tasks.py
Labels: cla: yes

#1532 Update Region Tags
  tasks/pull_queue_snippets.py
Labels: cla: yes

#1535 BigQuery: Adds authorized view tutorial
  bigquery/cloud-client/authorized_view_tutorial.py
  bigquery/cloud-client/authorized_view_tutorial_test.py
  bigquery/cloud-client/requirements.txt
Labels: bigquery, cla: yes

#1536 Region tag end typo
  bigquery/cloud-client/authorized_view_tutorial.py
Labels: cla: yes

#1440 Add the Pub/Sub handle_publisher_error sample
  pubsub/cloud-client/publisher.py
  pubsub/cloud-client/requirements.txt
Labels: cla: yes

#1537 Adds code owners for bigquery, bigquery data transfer, and composer
  .github/CODEOWNERS
Labels: cla: yes

#1518 Fix the vision geo test.
  vision/cloud-client/detect/detect_test.py
Labels: cla: yes

#1539 Rollback Changes
  texttospeech/cloud-client/requirements.txt
Labels: cla: yes

#1542 Change Endpoints Frameworks samples to import from endpoints
  appengine/standard/endpoints-frameworks-v2/echo/main.py
  appengine/standard/endpoints-frameworks-v2/echo/main_test.py
  appengine/standard/endpoints-frameworks-v2/echo/requirements.txt
  appengine/standard/endpoints-frameworks-v2/iata/main.py
  appengine/standard/endpoints-frameworks-v2/iata/requirements.txt
  appengine/standard/endpoints-frameworks-v2/quickstart/main.py
  appengine/standard/endpoints-frameworks-v2/quickstart/main_test.py
Labels: cla: yes

#1544 Add DLP and Tasks Tests to Kokoro
  .kokoro/presubmit_tests_dlp.cfg
  .kokoro/presubmit_tests_tasks.cfg
  .kokoro/system_tests_dlp.cfg
  .kokoro/system_tests_tasks.cfg
Labels: cla: yes, kokoro:force-run

#1545 Fixes link render typo
  texttospeech/cloud-client/README.rst
Labels: cla: yes

#1543 DLP: Add auto_populate_timespan option for create job trigger.
  dlp/triggers.py
  dlp/triggers_test.py
Labels: cla: yes

#1541 update Tasks Sample for App Engine
  appengine/flexible/tasks/README.md
  appengine/flexible/tasks/app.yaml
  appengine/flexible/tasks/create_app_engine_queue_task.py
  appengine/flexible/tasks/create_app_engine_queue_task_test.py
  appengine/flexible/tasks/main.py
  appengine/flexible/tasks/main_test.py
  appengine/flexible/tasks/requirements.txt
  tasks/README.md
Labels: cla: yes

#1527 fix url
  appengine/standard/README.md
Labels: cla: yes

#1548 Fix python Cloud Spanner tests.
  spanner/cloud-client/snippets_test.py
Labels: cla: yes
