Repository GoogleCloudPlatform/python-docs-samples, pull requests merged in 2019-04, with the labels that each got.

#2076 [CloudAsset] Update client library version to use v1 endpoint.
  asset/cloud-client/quickstart_batchgetassetshistory.py
  asset/cloud-client/quickstart_exportassets.py
  asset/cloud-client/requirements.txt
Labels: cla: yes

#2080 Changes from CHAR to VARCHAR on Cloud SQL example
  cloud-sql/postgres/sqlalchemy/main.py
Labels: cla: yes

#2082 [CloudAsset] Test: Delay seconds between bucket creation and API call.
  asset/cloud-client/quickstart_batchgetassetshistory_test.py
Labels: cla: yes

#2069 Created new route for results and added redirect for main.
  appengine/standard_python37/bigquery/main.py
  appengine/standard_python37/bigquery/main_test.py
Labels: automerge, cla: yes

#2041 storage: Add Boto3 List Objects in GCS
  storage/s3-sdk/README.rst
  storage/s3-sdk/README.rst.in
  storage/s3-sdk/list_gcs_objects.py
  storage/s3-sdk/list_gcs_objects_test.py
Labels: cla: yes

#2088 Remove temporary dataset from bqstorage pandas tutorial
  bigquery_storage/to_dataframe/main_test.py
  bigquery_storage/to_dataframe/requirements.txt
Labels: bigquery, cla: yes

#2089 New healthcare
  healthcare/api-client/datasets/datasets.py
  healthcare/api-client/datasets/datasets_test.py
  healthcare/api-client/dicom/dicom_stores.py
  healthcare/api-client/dicom/dicom_stores_test.py
  healthcare/api-client/dicom/dicomweb.py
  healthcare/api-client/dicom/dicomweb_test.py
  healthcare/api-client/dicom/resources/dicom_00000001_000.dcm
  healthcare/api-client/fhir/fhir_resources.py
  healthcare/api-client/fhir/fhir_resources_test.py
  healthcare/api-client/fhir/fhir_stores.py
  healthcare/api-client/fhir/fhir_stores_test.py
  healthcare/api-client/fhir/requirements.txt
  healthcare/api-client/fhir/resources/Patient.json
  healthcare/api-client/fhir/resources/execute_bundle.json
  healthcare/api-client/hl7v2/hl7v2_messages.py
  healthcare/api-client/hl7v2/hl7v2_messages_test.py
  healthcare/api-client/hl7v2/hl7v2_stores.py
  healthcare/api-client/hl7v2/hl7v2_stores_test.py
Labels: cla: yes

#2096 Data Labeling Beta samples
  datalabeling/README.rst
  datalabeling/README.rst.in
  datalabeling/create_annotation_spec_set.py
  datalabeling/create_annotation_spec_set_test.py
  datalabeling/create_instruction.py
  datalabeling/create_instruction_test.py
  datalabeling/export_data.py
  datalabeling/import_data.py
  datalabeling/import_data_test.py
  datalabeling/label_image.py
  datalabeling/label_image_test.py
  datalabeling/label_text.py
  datalabeling/label_text_test.py
  datalabeling/label_video.py
  datalabeling/label_video_test.py
  datalabeling/manage_dataset.py
  datalabeling/manage_dataset_test.py
  datalabeling/requirements.txt
Labels: cla: yes

#2084 Translation v3beta1 samples
  translate/cloud-client/README.rst
  translate/cloud-client/README.rst.in
  translate/cloud-client/beta_snippets.py
  translate/cloud-client/beta_snippets_test.py
  translate/cloud-client/requirements.txt
Labels: cla: yes

#2090 Tables Notebooks
  tables/automl/notebooks/census_income_prediction/README.md
  tables/automl/notebooks/census_income_prediction/census_income_prediction.ipynb
  tables/automl/notebooks/energy_price_forecasting/README.md
  tables/automl/notebooks/energy_price_forecasting/energy_price_forecasting.ipynb
  tables/automl/notebooks/energy_price_forecasting/energy_price_forecasting:energy_price_forecasting.ipynb
  tables/automl/notebooks/purchase_prediction/README.md
  tables/automl/notebooks/purchase_prediction/purchase_prediction.ipynb
  tables/automl/notebooks/result_slicing/README.md
  tables/automl/notebooks/result_slicing/slicing_eval_results.ipynb
  tables/automl/notebooks/retail_product_stockout_prediction/README.md
  tables/automl/notebooks/retail_product_stockout_prediction/resources/automl_stockout_img/Image 1 2019-03-13 at 1.02.53 PM.png
  tables/automl/notebooks/retail_product_stockout_prediction/resources/automl_stockout_img/Image 12 2019-03-13 at 1.56.43 PM.png
  tables/automl/notebooks/retail_product_stockout_prediction/resources/automl_stockout_img/Image 13 2019-03-13 at 1.59.18 PM.png
  tables/automl/notebooks/retail_product_stockout_prediction/resources/automl_stockout_img/Image 2 2019-03-13 at 1.05.17 PM.png
  tables/automl/notebooks/retail_product_stockout_prediction/resources/automl_stockout_img/Image 3 2019-03-13 at 1.08.44 PM.png
  tables/automl/notebooks/retail_product_stockout_prediction/resources/automl_stockout_img/Image 4 2019-03-13 at 1.09.56 PM.png
  tables/automl/notebooks/retail_product_stockout_prediction/resources/automl_stockout_img/Image 5 2019-03-13 at 1.10.11 PM.png
  tables/automl/notebooks/retail_product_stockout_prediction/resources/automl_stockout_img/Image 6 2019-03-13 at 1.20.57 PM.png
  tables/automl/notebooks/retail_product_stockout_prediction/resources/automl_stockout_img/Image 8 2019-03-13 at 1.34.08 PM.png
  tables/automl/notebooks/retail_product_stockout_prediction/resources/automl_stockout_img/Image new 1 2019-03-25 at 12.43.13 AM.png
  tables/automl/notebooks/retail_product_stockout_prediction/resources/automl_stockout_img/Image new 2 2019-03-25 at 12.44.18 AM.png
  tables/automl/notebooks/retail_product_stockout_prediction/resources/automl_stockout_img/Image new 3 2019-03-25 at 12.49.40 AM.png
  tables/automl/notebooks/retail_product_stockout_prediction/retail_product_stockout_prediction.ipynb
Labels: cla: yes

#2065 Update KubernetesPodOperator kubernetes_min_pod example
  composer/workflows/kubernetes_pod_operator.py
  composer/workflows/pythonvirtualenvoperator_python2_test.py
Labels: cla: yes

#2100 remove the reference to a bug
  tables/automl/notebooks/retail_product_stockout_prediction/retail_product_stockout_prediction.ipynb
Labels: cla: yes

#2102 delete this file.
  tables/automl/notebooks/energy_price_forecasting/energy_price_forecasting.ipynb
Labels: cla: yes

#2103 rename file name
  tables/automl/notebooks/energy_price_forecasting/energy_price_forecasting.ipynb
Labels: cla: yes

#2101 trying to fix images
  tables/automl/notebooks/retail_product_stockout_prediction/README.md
Labels: cla: yes

#2097 Cloud Pub/Sub: authenticated push in GAE Standard for Python 3
  appengine/standard_python37/pubsub/README.md
  appengine/standard_python37/pubsub/app.yaml
  appengine/standard_python37/pubsub/data/privatekey.pem
  appengine/standard_python37/pubsub/data/public_cert.pem
  appengine/standard_python37/pubsub/main.py
  appengine/standard_python37/pubsub/main_test.py
  appengine/standard_python37/pubsub/requirements.txt
  appengine/standard_python37/pubsub/sample_message.json
  appengine/standard_python37/pubsub/templates/index.html
Labels: cla: yes

#2087 Add magics tutorial with BigQuery Storage API integration.
  bigquery_storage/to_dataframe/jupyter_test.py
  bigquery_storage/to_dataframe/requirements.txt
Labels: bigquery, cla: yes

#1992 Add a list of allowed_client_ids to EchoApi.get_user_email.
  appengine/standard/endpoints-frameworks-v2/echo/main.py
Labels: cla: yes

#2111 Authenticated Push: must also verify the `iss` claim
  appengine/standard_python37/pubsub/main.py
  appengine/standard_python37/pubsub/main_test.py
  appengine/standard_python37/pubsub/templates/index.html
Labels: cla: yes

#2110 remove typo in installation
  tables/automl/notebooks/purchase_prediction/purchase_prediction.ipynb
Labels: cla: yes

#2114 [Cloud Tasks] Move samples to new folder
  .kokoro/presubmit_tests_tasks.cfg
  .kokoro/system_tests_tasks.cfg
  tasks/README.md
  tasks/create_http_task.py
  tasks/create_http_task_test.py
  tasks/requirements.txt
Labels: cla: yes

#2105 Rename Cloud ML Engine to AI Platform
  ml_engine/online_prediction/predict.py
  ml_engine/online_prediction/scikit-xg-predict.py
  notebooks/tutorials/cloud-ml-engine/Training and prediction with scikit-learn.ipynb
Labels: cla: yes

#2113 [Cloud Tasks] Add task with authentication sample
  appengine/flexible/tasks/Dockerfile
  appengine/flexible/tasks/README.md
  appengine/flexible/tasks/requirements.txt
  tasks/README.md
  tasks/create_http_task_with_token.py
  tasks/create_http_task_with_token_test.py
  tasks/requirements.txt
Labels: cla: yes, kokoro:force-run

#2018 Cloud Bigtable Region tag consistency
  bigtable/hello/main.py
  bigtable/hello_happybase/main.py
Labels: cla: yes

#2079 Add OpenCensus metrics quickstart
  opencensus/README.md
  opencensus/metrics_quickstart.py
  opencensus/metrics_quickstart_test.py
  opencensus/requirements.txt
Labels: cla: yes

#2121 Add custom prediction routine samples for AI Platform
  ml_engine/custom-prediction-routines/README.md
  ml_engine/custom-prediction-routines/predictor-interface.py
  ml_engine/custom-prediction-routines/preprocess.py
  ml_engine/custom-prediction-routines/scikit-predictor.py
  ml_engine/custom-prediction-routines/setup.py
  ml_engine/custom-prediction-routines/tensorflow-predictor.py
Labels: cla: yes

#2124 Updated beta version of automl
  translate/automl/requirements.txt
Labels: cla: yes

#2128 Update requirements.txt
  language/automl/requirements.txt
Labels: cla: yes

#2119 Remove deprecated migration scripts
  composer/tools/README.md
  composer/tools/README.rst
  composer/tools/README.rst.in
  composer/tools/copy_environment.py
  composer/tools/copy_environment_test.py
  composer/tools/requirements.txt
Labels: cla: yes

#2125 Remove api keys
  healthcare/api-client/datasets/README.rst.in
  healthcare/api-client/datasets/datasets.py
  healthcare/api-client/datasets/datasets_test.py
  healthcare/api-client/dicom/README.rst.in
  healthcare/api-client/dicom/dicom_stores.py
  healthcare/api-client/dicom/dicom_stores_test.py
  healthcare/api-client/dicom/dicomweb_test.py
  healthcare/api-client/fhir/README.rst.in
  healthcare/api-client/fhir/fhir_resources_test.py
  healthcare/api-client/fhir/fhir_stores.py
  healthcare/api-client/fhir/fhir_stores_test.py
  healthcare/api-client/hl7v2/README.rst.in
  healthcare/api-client/hl7v2/hl7v2_messages.py
  healthcare/api-client/hl7v2/hl7v2_messages_test.py
  healthcare/api-client/hl7v2/hl7v2_stores.py
  healthcare/api-client/hl7v2/hl7v2_stores_test.py
Labels: cla: yes

#2132 Regenerated healtcare README.rst files
  healthcare/api-client/datasets/README.rst
  healthcare/api-client/dicom/README.rst
  healthcare/api-client/fhir/README.rst
  healthcare/api-client/hl7v2/README.rst
Labels: cla: yes
