Repository GoogleCloudPlatform/python-docs-samples, pull requests merged in 2019-11, with the labels that each got.

#2507 Adding cloud run image processing tutorial
  run/image-processing/.dockerignore
  run/image-processing/Dockerfile
  run/image-processing/README.md
  run/image-processing/image.py
  run/image-processing/image_test.py
  run/image-processing/main.py
  run/image-processing/main_test.py
  run/image-processing/requirements.txt
Labels: cla: yes

#2506 Fix kubernetespodoperator resources param
  composer/workflows/kubernetes_pod_operator.py
  composer/workflows/requirements.txt
Labels: cla: yes

#2511 Add sample code for Stackdriver Debugger Quickstart
  appengine/standard_python37/cloud_debugger/app.yaml
  appengine/standard_python37/cloud_debugger/main.py
  appengine/standard_python37/cloud_debugger/requirements.txt
Labels: cla: yes

#2335 [Storage] Support rename of BPO to UniformBucketLevelAccess
  storage/cloud-client/README.rst
  storage/cloud-client/README.rst.in
  storage/cloud-client/bucket_policy_only.py
  storage/cloud-client/requirements.txt
  storage/cloud-client/uniform_bucket_level_access.py
  storage/cloud-client/uniform_bucket_level_access_test.py
Labels: DO NOT MERGE, In Progress, cla: yes, kokoro:force-run

#2515 Storage: fix region tag
  storage/cloud-client/uniform_bucket_level_access.py
Labels: cla: yes

#2516 Update Cloud Tasks library version
  appengine/flexible/tasks/requirements.txt
  tasks/create_http_task.py
  tasks/create_http_task_with_token.py
  tasks/requirements.txt
Labels: cla: yes

#2513 Run logging manual
  run/logging-manual/.dockerignore
  run/logging-manual/Dockerfile
  run/logging-manual/README.md
  run/logging-manual/main.py
  run/logging-manual/main_test.py
  run/logging-manual/requirements.txt
Labels: cla: yes

#2517 Adding legacy-endpoint-access sample
  compute/metadata/detect_legacy_usage.py
  compute/metadata/detect_legacy_usage_test.py
Labels: cla: yes

#2518 Separated enabling Debugger and changing log level
  appengine/standard_python37/cloud_debugger/main.py
Labels: cla: yes

#2522 Use latest 2.1.x Django to avoid PyMySql issue
  appengine/standard_python37/django/requirements.txt
Labels: cla: yes

#2526 feat: firestore samples
  firestore/cloud-client/requirements.txt
  firestore/cloud-client/snippets.py
  firestore/cloud-client/snippets_test.py
Labels: cla: yes

#2497 Add Set Endpoint Samples
  automl/beta/requirements.txt
  automl/beta/set_endpoint.py
  automl/beta/set_endpoint_test.py
  language/cloud-client/v1/set_endpoint.py
  language/cloud-client/v1/set_endpoint_test.py
  vision/cloud-client/detect/detect_test.py
Labels: cla: yes, kokoro:force-run

#2537 Update documentation for prefix, delimiter search
  storage/cloud-client/snippets.py
Labels: cla: yes

#2536 feat: adding samples for dataproc - create cluster
  dataproc/create_cluster.py
  dataproc/create_cluster_test.py
  dataproc/dataproc_e2e_donttest.py
  dataproc/requirements.txt
Labels: cla: yes

#2535 update filenames to match the CSV files
  spanner/cloud-client/bulk_load_csv/batch_import.py
Labels: cla: yes

#2542 Revert "Configure Renovate"
  renovate.json
Labels: cla: yes

#2547 Fix pubsub topic name format
  healthcare/api-client/dicom/dicom_stores.py
Labels: cla: yes

#2534 Update Cloud SQL Proxy Docker Image.
  kubernetes_engine/django_tutorial/polls.yaml
Labels: cla: yes

#2549 Fix failing functions test
  functions/helloworld/main_test.py
Labels: cla: yes

#2552 Configure Blunderbuss.
  .github/blunderbuss.yml
Labels: cla: yes

#2466 Add Healthcare API DICOMweb search study by tags sample
  healthcare/api-client/dicom/dicomweb.py
  healthcare/api-client/dicom/dicomweb_test.py
Labels: cla: yes

#2501 fix problems with automl docs
  tables/automl/automl_tables_predict.py
Labels: ML, api: automl, cla: yes

#2412 Firestore distributed counters
  firestore/cloud-client/distributed_counters.py
  firestore/cloud-client/distributed_counters_test.py
Labels: cla: yes, needs review

#2459 Fix typo in GCS URI parameter
  tables/automl/notebooks/census_income_prediction/getting_started_notebook.ipynb
Labels: cla: yes, needs review

#2558 fix: Use different versions of pytest for python 2 and python3
  container_registry/container_analysis/requirements.txt
  functions/imagemagick/requirements-dev.txt
  run/image-processing/requirements.txt
  run/logging-manual/requirements.txt
  run/pubsub/requirements.txt
  testing/requirements.txt
Labels: cla: yes

#2480 Use deploy redirector
  run/README.md
Labels: cla: yes

#2484 Use deploy redirector
  run/pubsub/README.md
Labels: cla: yes

#2528 remove misplaced region tag
  automl/cloud-client/list_datasets.py
Labels: cla: yes

#2575 storage: update ; to & in comment.
  storage/signed_urls/generate_signed_urls.py
Labels: cla: yes
