Repository GoogleCloudPlatform/python-docs-samples, pull requests merged in 2019-01, with the labels that each got.

#1952 Refactor BQ user credentials sample to use region tags
  bigquery/cloud-client/user_credentials.py
  bigquery/cloud-client/user_credentials_test.py
Labels: bigquery, cla: yes

#1957 Set END for detach_listener region tag
  firestore/cloud-client/snippets.py
Labels: cla: yes

#1903 KMS: Updated for new client library
  kms/api-client/README.rst
  kms/api-client/README.rst.in
  kms/api-client/asymmetric.py
  kms/api-client/asymmetric_test.py
  kms/api-client/quickstart.py
  kms/api-client/requirements.txt
  kms/api-client/snippets.py
  kms/api-client/snippets_test.py
Labels: cla: yes, kokoro:force-run

#1956 Update google-endpoints to version 4.8.0.
  appengine/standard/endpoints-frameworks-v2/echo/requirements.txt
Labels: cla: yes, kokoro:force-run

#1959 Firestore array queries
  firestore/cloud-client/snippets.py
  firestore/cloud-client/snippets_test.py
Labels: cla: yes

#1963 Make TODO clearer what action to take.
  bigquery/cloud-client/user_credentials.py
Labels: bigquery, cla: yes

#1966 Create python-api-walkthrough.md
  dataproc/python-api-walkthrough.md
Labels: cla: yes

#1967 iot: update misnamed function in gateway_demo
  iot/api-client/beta-features/gateway/gateway_demo.py
Labels: cla: yes

#1940 Speech continuous
  speech/cloud-client/requirements.txt
  speech/cloud-client/transcribe_streaming_indefinite.py
Labels: cla: yes

#1973 Migrates manager samples for Gateways from beta folder
  iot/api-client/manager/manager.py
  iot/api-client/manager/manager_test.py
Labels: cla: yes

#1953 Add PROJECT_ID
  trace/main.py
  trace/main_test.py
Labels: cla: yes

#1933 Per internal documentation complaint, fix the naming.
  dlp/quickstart.py
Labels: cla: yes

#1913 Fix Pub/Sub comment typo
  appengine/flexible/pubsub/main.py
  appengine/standard/pubsub/main.py
Labels: cla: yes

#1921 Add inspect table code sample for DLP and some nit fixes
  dlp/README.rst
  dlp/deid.py
  dlp/inspect_content.py
  dlp/inspect_content_test.py
  dlp/quickstart.py
  dlp/redact.py
  dlp/risk.py
Labels: cla: yes

#1922 Fix the region tag
  appengine/standard_python37/spanner/main.py
Labels: cla: yes

#1910 Decode base64.b64decode output as string for Python 3 compatibility.
  composer/tools/copy_environment.py
Labels: cla: yes

#1928 Update DLP redact image code sample region to include mimetype import
  dlp/redact.py
Labels: cla: yes

#1919 Miscellaneous updates to copy composer environment script.
  .travis.yml
  composer/tools/copy_environment.py
  composer/tools/copy_environment_test.py
Labels: cla: yes

#1807 Fix encoding issue and comment improvement
  endpoints/getting-started/clients/google-jwt-client.py
Labels: cla: yes

#1978 New trampoline image with new libraries in place.
  .kokoro/common.cfg
Labels: cla: yes

#1898 speech: add missing import for code sample
  speech/cloud-client/transcribe_enhanced_model.py
Labels: cla: yes

#1881 Be consistent about how we run samples locally
  appengine/standard_python37/bigquery/main.py
  appengine/standard_python37/redis/main.py
Labels: cla: yes

#1906 Remove comments about possible maintenance events during live migration
  compute/metadata/main.py
Labels: cla: yes

#1907 Add import statement to memcache snippets
  appengine/standard/memcache/snippets/snippets.py
Labels: Fixit, cla: yes

#1908 Remove unused region tags (Login tests)
  appengine/standard/localtesting/login_test.py
Labels: Fixit, cla: yes

#1887 Update list_clusters.py
  dataproc/list_clusters.py
Labels: cla: yes

#1937 Note that key_filter is a helper for add_filter('__key__').
  datastore/cloud-client/snippets.py
Labels: cla: yes

#1948 Move import statment inside sample
  functions/env_vars/main.py
Labels: cla: yes

#1950 Typo in `comoser_sample_bq_copy_across_locations`
  composer/workflows/bq_copy_across_locations.py
Labels: cla: yes

#1951 fixing help text unnecessary linebreak
  storage/transfer_service/aws_request.py
Labels: cla: yes

#1977 Migrates Gateway code to MQTT example
  iot/api-client/manager/requirements.txt
  iot/api-client/mqtt_example/cloudiot_mqtt_example.py
  iot/api-client/mqtt_example/cloudiot_mqtt_example_test.py
  iot/api-client/mqtt_example/requirements.txt
Labels: cla: yes

#1982 Update nox package name
  AUTHORING_GUIDE.md
Labels: cla: yes

#1983 Moves Gateway demo to MQTT folder
  iot/api-client/mqtt_example/gateway_demo.py
Labels: cla: yes
