Repository GoogleCloudPlatform/python-docs-samples, pull requests merged in 2020-10, with the labels that each got.

#4785 Data cleaning region tags
  data-science-onramp/data-cleaning/clean.py
  data-science-onramp/data-cleaning/clean_test.py
Labels: automerge, cla: yes, samples

#4790 fix(iam): fix a broken test
  iam/api-client/custom_roles_test.py
Labels: automerge, cla: yes

#4788 Update service_accounts.py
  iam/api-client/service_accounts.py
Labels: cla: yes

#4796 Remove melaniedejong from Owners and Blunderbuss
  .github/CODEOWNERS
  .github/blunderbuss.yml
Labels: cla: yes

#4795 fix(jobs): longer max retry time, shorter delay
  jobs/v3/api_client/email_alert_search_sample_test.py
Labels: api: jobs, cla: yes, samples

#4791 Fix AI Platform online prediction tests
  ml_engine/online_prediction/predict.py
  ml_engine/online_prediction/predict_test.py
Labels: automerge, cla: yes, samples

#4815 chore: fixes flaky test
  video/cloud-client/analyze/video_detect_faces_beta_test.py
  video/cloud-client/analyze/video_detect_faces_gcs_beta_test.py
Labels: cla: yes

#4801 refactor: remove spanner samples
  spanner/cloud-client/README.rst
  spanner/cloud-client/README.rst.in
  spanner/cloud-client/backup_sample.py
  spanner/cloud-client/backup_sample_test.py
  spanner/cloud-client/batch_sample.py
  spanner/cloud-client/quickstart.py
  spanner/cloud-client/quickstart_test.py
  spanner/cloud-client/requirements-test.txt
  spanner/cloud-client/requirements.txt
  spanner/cloud-client/snippets.py
  spanner/cloud-client/snippets_test.py
Labels: api: spanner, cla: yes, samples

#4825 chore: remove monitoring samples
  monitoring/api/v3/alerts-client/README.md
  monitoring/api/v3/alerts-client/README.rst
  monitoring/api/v3/alerts-client/README.rst.in
  monitoring/api/v3/alerts-client/noxfile_config.py
  monitoring/api/v3/alerts-client/requirements-test.txt
  monitoring/api/v3/alerts-client/requirements.txt
  monitoring/api/v3/alerts-client/snippets.py
  monitoring/api/v3/alerts-client/snippets_test.py
  monitoring/api/v3/alerts-client/test_alert_policy.json
  monitoring/api/v3/alerts-client/test_notification_channel.json
  monitoring/api/v3/cloud-client/README.md
  monitoring/api/v3/cloud-client/README.rst
  monitoring/api/v3/cloud-client/README.rst.in
  monitoring/api/v3/cloud-client/noxfile_config.py
  monitoring/api/v3/cloud-client/quickstart.py
  monitoring/api/v3/cloud-client/quickstart_test.py
  monitoring/api/v3/cloud-client/requirements-test.txt
  monitoring/api/v3/cloud-client/requirements.txt
  monitoring/api/v3/cloud-client/snippets.py
  monitoring/api/v3/cloud-client/snippets_test.py
  monitoring/api/v3/uptime-check-client/README.md
  monitoring/api/v3/uptime-check-client/README.rst
  monitoring/api/v3/uptime-check-client/README.rst.in
  monitoring/api/v3/uptime-check-client/requirements-test.txt
  monitoring/api/v3/uptime-check-client/requirements.txt
  monitoring/api/v3/uptime-check-client/snippets.py
  monitoring/api/v3/uptime-check-client/snippets_test.py
Labels: cla: yes, samples

#4823 chore(functions/pubsub): use consistent param names
  functions/pubsub/main.py
  functions/pubsub/main_test.py
Labels: api: cloudfunctions, cla: yes, samples

#4820 samples: refactored samples to v2
  iot/api-client/end_to_end_example/cloudiot_pubsub_example_server_test.py
  iot/api-client/gcs_file_to_device/requirements.txt
  iot/api-client/http_example/cloudiot_http_example_test.py
  iot/api-client/http_example/requirements.txt
  iot/api-client/manager/manager.py
  iot/api-client/mqtt_example/fixtures.py
  iot/api-client/mqtt_example/gateway_demo.py
  iot/api-client/mqtt_example/requirements.txt
Labels: automerge, cla: yes, samples

#4836 healthcare API: remove v1beta1 DICOM/HL7v2 directories no longer being used
  healthcare/api-client/dicom/README.rst
  healthcare/api-client/dicom/README.rst.in
  healthcare/api-client/dicom/dicom_stores.py
  healthcare/api-client/dicom/dicom_stores_test.py
  healthcare/api-client/dicom/dicomweb.py
  healthcare/api-client/dicom/dicomweb_test.py
  healthcare/api-client/dicom/noxfile_config.py
  healthcare/api-client/dicom/requirements-test.txt
  healthcare/api-client/dicom/requirements.txt
  healthcare/api-client/dicom/resources/dicom_00000001_000.dcm
  healthcare/api-client/hl7v2/README.rst
  healthcare/api-client/hl7v2/README.rst.in
  healthcare/api-client/hl7v2/hl7v2_messages.py
  healthcare/api-client/hl7v2/hl7v2_messages_test.py
  healthcare/api-client/hl7v2/hl7v2_stores.py
  healthcare/api-client/hl7v2/hl7v2_stores_test.py
  healthcare/api-client/hl7v2/noxfile_config.py
  healthcare/api-client/hl7v2/requirements-test.txt
  healthcare/api-client/hl7v2/requirements.txt
  healthcare/api-client/hl7v2/resources/hl7-sample-ingest.json
Labels: cla: yes

#4831 Update Kubernetes Deployment for django tutorial
  kubernetes_engine/django_tutorial/polls.yaml
Labels: cla: yes, samples

#4841 healthcare API: remove v1beta1 datasets and FHIR directories/code no longer being used
  healthcare/api-client/datasets/README.rst
  healthcare/api-client/datasets/README.rst.in
  healthcare/api-client/datasets/datasets.py
  healthcare/api-client/datasets/datasets_test.py
  healthcare/api-client/datasets/noxfile_config.py
  healthcare/api-client/datasets/requirements-test.txt
  healthcare/api-client/datasets/requirements.txt
  healthcare/api-client/fhir/fhir_resources.py
  healthcare/api-client/fhir/fhir_stores.py
  healthcare/api-client/fhir/fhir_stores_test.py
  healthcare/api-client/fhir/noxfile_config.py
  healthcare/api-client/v1beta1/fhir/README.rst
  healthcare/api-client/v1beta1/fhir/README.rst.in
  healthcare/api-client/v1beta1/fhir/fhir_resources.py
  healthcare/api-client/v1beta1/fhir/fhir_resources_test.py
  healthcare/api-client/v1beta1/fhir/fhir_stores.py
  healthcare/api-client/v1beta1/fhir/fhir_stores_test.py
  healthcare/api-client/v1beta1/fhir/requirements-test.txt
  healthcare/api-client/v1beta1/fhir/requirements.txt
  healthcare/api-client/v1beta1/fhir/resources/Patient.json
  healthcare/api-client/v1beta1/fhir/resources/execute_bundle.json
Labels: cla: yes, samples

#4835 Adding e2e test for pubsub sample
  run/pubsub/e2e_test.py
  run/pubsub/e2e_test_setup.yaml
  run/pubsub/noxfile_config.py
  run/pubsub/requirements-test.txt
Labels: cla: yes, samples

#4789 chore: move talent samples to python-talent
  jobs/v4beta1/README.rst
  jobs/v4beta1/conftest.py
  jobs/v4beta1/job_search_autocomplete_job_title.py
  jobs/v4beta1/job_search_autocomplete_job_title_test.py
  jobs/v4beta1/job_search_batch_create_jobs.py
  jobs/v4beta1/job_search_batch_update_jobs.py
  jobs/v4beta1/job_search_commute_search.py
  jobs/v4beta1/job_search_commute_search_test.py
  jobs/v4beta1/job_search_create_client_event.py
  jobs/v4beta1/job_search_create_company.py
  jobs/v4beta1/job_search_create_company_test.py
  jobs/v4beta1/job_search_create_job.py
  jobs/v4beta1/job_search_create_job_custom_attributes.py
  jobs/v4beta1/job_search_create_job_custom_attributes_test.py
  jobs/v4beta1/job_search_create_job_test.py
  jobs/v4beta1/job_search_create_tenant.py
  jobs/v4beta1/job_search_create_tenant_test.py
  jobs/v4beta1/job_search_custom_ranking_search.py
  jobs/v4beta1/job_search_custom_ranking_search_test.py
  jobs/v4beta1/job_search_delete_company.py
  jobs/v4beta1/job_search_delete_company_test.py
  jobs/v4beta1/job_search_delete_job.py
  jobs/v4beta1/job_search_delete_job_test.py
  jobs/v4beta1/job_search_delete_tenant.py
  jobs/v4beta1/job_search_delete_tenant_test.py
  jobs/v4beta1/job_search_get_company.py
  jobs/v4beta1/job_search_get_company_test.py
  jobs/v4beta1/job_search_get_job.py
  jobs/v4beta1/job_search_get_job_test.py
  jobs/v4beta1/job_search_get_tenant.py
  jobs/v4beta1/job_search_get_tenant_test.py
  jobs/v4beta1/job_search_histogram_search.py
  jobs/v4beta1/job_search_histogram_search_test.py
  jobs/v4beta1/job_search_list_companies.py
  jobs/v4beta1/job_search_list_companies_test.py
  jobs/v4beta1/job_search_list_jobs.py
  jobs/v4beta1/job_search_list_jobs_test.py
  jobs/v4beta1/job_search_list_tenants.py
  jobs/v4beta1/job_search_list_tenants_test.py
  jobs/v4beta1/noxfile_config.py
  jobs/v4beta1/requirements-test.txt
  jobs/v4beta1/requirements.txt
Labels: automerge, cla: yes, samples

#4852 Adding e2e_test for Cloud Run image processing sample
  run/image-processing/e2e_test.py
  run/image-processing/e2e_test_setup.yaml
  run/image-processing/noxfile_config.py
  run/image-processing/test-images/zombie.jpg
Labels: cla: yes, samples

#4855 fix(jobs): bump the timeout and retry 2 times
  jobs/v3/api_client/email_alert_search_sample_test.py
Labels: api: jobs, cla: yes, samples

#4851 Remove samples for language API
  language/README.md
  language/api/README.rst
  language/api/README.rst.in
  language/api/analyze.py
  language/api/analyze_test.py
  language/api/requirements-test.txt
  language/api/requirements.txt
  language/classify_text/README.rst
  language/classify_text/README.rst.in
  language/classify_text/classify_text_tutorial.py
  language/classify_text/classify_text_tutorial_test.py
  language/classify_text/requirements-test.txt
  language/classify_text/requirements.txt
  language/classify_text/resources/query_text1.txt
  language/classify_text/resources/query_text2.txt
  language/classify_text/resources/query_text3.txt
  language/classify_text/resources/texts/android.txt
  language/classify_text/resources/texts/cat_in_the_hat.txt
  language/classify_text/resources/texts/cloud_computing.txt
  language/classify_text/resources/texts/eclipse.txt
  language/classify_text/resources/texts/eclipse_of_the_sun.txt
  language/classify_text/resources/texts/email.txt
  language/classify_text/resources/texts/gcp.txt
  language/classify_text/resources/texts/gmail.txt
  language/classify_text/resources/texts/google.txt
  language/classify_text/resources/texts/harry_potter.txt
  language/classify_text/resources/texts/matilda.txt
  language/classify_text/resources/texts/mobile_phone.txt
  language/classify_text/resources/texts/mr_fox.txt
  language/classify_text/resources/texts/wireless.txt
  language/cloud-client/.DS_Store
  language/cloud-client/v1/README.rst
  language/cloud-client/v1/README.rst.in
  language/cloud-client/v1/quickstart.py
  language/cloud-client/v1/quickstart_test.py
  language/cloud-client/v1/requirements-test.txt
  language/cloud-client/v1/requirements.txt
  language/cloud-client/v1/resources/text.txt
  language/cloud-client/v1/set_endpoint.py
  language/cloud-client/v1/set_endpoint_test.py
  language/generated-samples/v1/language_sentiment_text.py
  language/generated-samples/v1/language_sentiment_text_test.py
  language/generated-samples/v1/requirements-test.txt
  language/generated-samples/v1/requirements.txt
  language/sentiment/README.md
  language/sentiment/requirements-test.txt
  language/sentiment/requirements.txt
  language/sentiment/resources/mixed.txt
  language/sentiment/resources/neg.txt
  language/sentiment/resources/neutral.txt
  language/sentiment/resources/pos.txt
  language/sentiment/sentiment_analysis.py
  language/sentiment/sentiment_analysis_test.py
Labels: cla: yes, samples

#4826 Update poll.js
  appengine/standard/iap/js/poll.js
Labels: cla: yes, samples

#4888 chore(functions/http): make region tag spelling consistent
  functions/helloworld/main.py
Labels: api: cloudfunctions, cla: yes, samples

#4889 chore(functions): remove unused signed url sample
  functions/http/main.py
  functions/http/main_test.py
Labels: api: cloudfunctions, cla: yes, samples

#4893 dataflow: use pubsub subscription full path
  dataflow/flex-templates/streaming_beam/README.md
  dataflow/flex-templates/streaming_beam/metadata.json
Labels: api: dataflow, automerge, cla: yes, samples

#4887 chore(functions): delete unused region tag
  functions/tips/main.py
Labels: api: cloudfunctions, automerge, cla: yes, samples

#4884 Fix appengine standard endpoints region tags
  appengine/standard/endpoints-frameworks-v2/echo/main.py
  appengine/standard/endpoints-frameworks-v2/iata/main.py
  appengine/standard/endpoints-frameworks-v2/quickstart/main.py
  appengine/standard/endpoints/backend/main.py
  appengine/standard/endpoints/multiapi/main.py
Labels: automerge, cla: yes, samples

#4900 Add sync-repo-bot config
  .github/sync-repo-settings.yaml
Labels: cla: yes

#4902 chore(sync-repo-settings): disable admin enforced
  .github/sync-repo-settings.yaml
Labels: automerge, cla: yes

#4897 Update predict.py
  ml_engine/online_prediction/predict.py
Labels: cla: yes, samples

#4906 Fix incorrect parameter name
  functions/ocr/app/main.py
Labels: automerge, cla: yes, samples

#4899 dataflow: workaround for beam base image bug
  dataflow/flex-templates/streaming_beam/Dockerfile
  dataflow/flex-templates/streaming_beam/README.md
Labels: api: dataflow, cla: yes, samples

#4911 Add new updated SQL Server sample region tags.
  cloud-sql/sql-server/sqlalchemy/main.py
Labels: cla: yes, samples

#4876 chore: add logging team to codeowners
  .github/CODEOWNERS
  logging/cloud-client/README.rst
  logging/cloud-client/README.rst.in
Labels: api: clouderrorreporting, api: logging, automerge, cla: yes, lang: python, priority: p2, samples, type: process

#4914 Downgrade dependency for pg8000
  cloud-sql/postgres/sqlalchemy/requirements.txt
Labels: automerge, cla: yes, samples

#4916 Make predict test more lenient
  ml_engine/online_prediction/predict_test.py
Labels: cla: yes

#4898 chore(Dockerfile): support PyPI packages with C bindings
  .kokoro/docker/Dockerfile
Labels: cla: yes, samples

#4856 change pprint to print.
  storage/cloud-client/storage_get_bucket_metadata.py
Labels: cla: yes, samples

#4865 chore: Taskqueue migration - pull queues
  appengine/standard/migration/taskqueue/README.md
  appengine/standard/migration/taskqueue/pull-counter/README.md
  appengine/standard/migration/taskqueue/pull-counter/app.yaml
  appengine/standard/migration/taskqueue/pull-counter/app3.yaml
  appengine/standard/migration/taskqueue/pull-counter/appengine_config.py
  appengine/standard/migration/taskqueue/pull-counter/main.py
  appengine/standard/migration/taskqueue/pull-counter/main_test.py
  appengine/standard/migration/taskqueue/pull-counter/requirements-test.txt
  appengine/standard/migration/taskqueue/pull-counter/requirements.txt
  appengine/standard/migration/taskqueue/pull-counter/templates/counter.html
Labels: cla: yes, samples
