Repository GoogleCloudPlatform/python-docs-samples, pull requests merged in 2020-06, with the labels that each got.

#3919 [dlp] fix: mitigate flakiness
  dlp/conftest.py
  dlp/risk_test.py
Labels: cla: yes

#3845 Remove texttospeech samples
  texttospeech/cloud-client/README.rst
  texttospeech/cloud-client/README.rst.in
  texttospeech/cloud-client/audio_profile.py
  texttospeech/cloud-client/audio_profile_test.py
  texttospeech/cloud-client/list_voices.py
  texttospeech/cloud-client/list_voices_test.py
  texttospeech/cloud-client/quickstart.py
  texttospeech/cloud-client/requirements-test.txt
  texttospeech/cloud-client/requirements.txt
  texttospeech/cloud-client/resources/example.ssml
  texttospeech/cloud-client/resources/example.txt
  texttospeech/cloud-client/resources/hello.ssml
  texttospeech/cloud-client/resources/hello.txt
  texttospeech/cloud-client/ssml_addresses.py
  texttospeech/cloud-client/ssml_addresses_test.py
  texttospeech/cloud-client/synthesize_file.py
  texttospeech/cloud-client/synthesize_file_test.py
  texttospeech/cloud-client/synthesize_text.py
  texttospeech/cloud-client/synthesize_text_test.py
Labels: automerge, cla: yes

#3937 Using pythonunbuffered instead of flushing the sys.stdout
  run/hello-broken/Dockerfile
  run/hello-broken/main.py
  run/image-processing/Dockerfile
  run/image-processing/main.py
  run/logging-manual/Dockerfile
  run/logging-manual/main.py
  run/markdown-preview/editor/Dockerfile
  run/markdown-preview/renderer/Dockerfile
  run/pubsub/Dockerfile
  run/pubsub/main.py
  run/system-package/Dockerfile
  run/system-package/main.py
Labels: cla: yes

#3938 fix: make timeout an optional positional arg
  pubsub/cloud-client/subscriber.py
Labels: automerge, cla: yes

#3899 refactor Cloud SQL MySQL & Postgres samples to demonstrate both TCP and Unix socket connection patterns
  cloud-sql/mysql/sqlalchemy/README.md
  cloud-sql/mysql/sqlalchemy/app.flexible.yaml
  cloud-sql/mysql/sqlalchemy/app.standard.yaml
  cloud-sql/mysql/sqlalchemy/main.py
  cloud-sql/mysql/sqlalchemy/requirements.txt
  cloud-sql/postgres/sqlalchemy/README.md
  cloud-sql/postgres/sqlalchemy/app.flexible.yaml
  cloud-sql/postgres/sqlalchemy/app.standard.yaml
  cloud-sql/postgres/sqlalchemy/main.py
  cloud-sql/postgres/sqlalchemy/requirements.txt
Labels: cla: yes

#3935 Functions: clarify logging behavior
  functions/helloworld/main.py
Labels: automerge, cla: yes

#3936 [translate] fix hybrid glossaries tests
  translate/cloud-client/hybrid_glossaries/hybrid_tutorial.py
  translate/cloud-client/hybrid_glossaries/hybrid_tutorial_test.py
  translate/cloud-client/hybrid_glossaries/requirements.txt
  translate/cloud-client/hybrid_glossaries/resources/non_standard_format.txt
  translate/cloud-client/pytest.ini
Labels: automerge, cla: yes

#3925 [dlp] testing: fix Pub/Sub notifications
  dlp/README.rst
  dlp/README.rst.in
  dlp/conftest.py
  dlp/inspect_content.py
  dlp/inspect_content_test.py
  dlp/risk.py
  dlp/risk_test.py
  scripts/readme-gen/templates/README.tmpl.rst
Labels: cla: yes

#3922 Improve Spanner delete_data sample coverage
  spanner/cloud-client/snippets.py
Labels: api: spanner, cla: yes

#3951 Add larkee as codeowner of spanner
  .github/CODEOWNERS
Labels: automerge, cla: yes

#3953 Pub/Sub: replace name with id in samples
  pubsub/cloud-client/iam.py
  pubsub/cloud-client/iam_test.py
  pubsub/cloud-client/publisher.py
  pubsub/cloud-client/quickstart/pub.py
  pubsub/cloud-client/quickstart/sub.py
  pubsub/cloud-client/quickstart/sub_test.py
  pubsub/cloud-client/subscriber.py
Labels: cla: yes

#3962 update google-auth part 2
  auth/api-client/requirements.txt
  auth/end-user/web/requirements.txt
  bigquery_storage/to_dataframe/requirements.txt
  composer/rest/requirements.txt
  compute/api/requirements.txt
  compute/auth/requirements.txt
  compute/encryption/requirements.txt
  compute/oslogin/requirements.txt
Labels: cla: yes

#3961 update google-auth part 1
  appengine/standard/firebase/firenotes/backend/requirements.txt
  appengine/standard/firebase/firetactoe/requirements.txt
  appengine/standard/storage/api-client/requirements.txt
  appengine/standard_python3/building-an-app/building-an-app-3/requirements.txt
  appengine/standard_python3/building-an-app/building-an-app-4/requirements.txt
  appengine/standard_python3/pubsub/requirements.txt
  appengine/standard_python37/building-an-app/building-an-app-3/requirements.txt
  appengine/standard_python37/building-an-app/building-an-app-4/requirements.txt
  appengine/standard_python37/pubsub/requirements.txt
Labels: cla: yes

#3963 update google-auth part 3
  dataproc/requirements.txt
  endpoints/bookstore-grpc-transcoding/requirements.txt
  endpoints/bookstore-grpc/requirements.txt
  endpoints/getting-started/clients/service_to_service_non_default/requirements.txt
  endpoints/getting-started/requirements.txt
  functions/composer/requirements.txt
Labels: cla: yes

#3965 update google-auth part 4
  healthcare/api-client/datasets/requirements.txt
  healthcare/api-client/dicom/requirements.txt
  healthcare/api-client/fhir/requirements.txt
  healthcare/api-client/hl7v2/requirements.txt
  healthcare/api-client/v1/datasets/requirements.txt
  healthcare/api-client/v1/dicom/requirements.txt
  healthcare/api-client/v1/fhir/requirements.txt
  healthcare/api-client/v1/hl7v2/requirements.txt
Labels: cla: yes

#3966 update google-auth part 5
  iam/api-client/requirements.txt
  iap/requirements.txt
  iot/api-client/end_to_end_example/requirements.txt
  iot/api-client/gcs_file_to_device/requirements.txt
  iot/api-client/http_example/requirements.txt
  iot/api-client/manager/requirements.txt
  iot/api-client/mqtt_example/requirements.txt
Labels: cla: yes

#3967 final update for google-auth
  jobs/v3/api_client/requirements.txt
  kubernetes_engine/api-client/requirements.txt
  language/api/requirements.txt
  ml_engine/online_prediction/requirements.txt
  monitoring/api/v3/api-client/requirements.txt
  storage/api/requirements.txt
  storage/signed_urls/requirements.txt
  storage/transfer_service/requirements.txt
Labels: cla: yes

#3929 add example of creating AutoML Tables client with non-default endpoint ('new' sdk)
  tables/automl/automl_tables_set_endpoint.py
  tables/automl/endpoint_test.py
Labels: automerge, cla: yes

#3952 refactor Cloud SQL samples
  cloud-sql/mysql/sqlalchemy/README.md
  cloud-sql/mysql/sqlalchemy/app.flexible.yaml
  cloud-sql/mysql/sqlalchemy/app.standard.yaml
  cloud-sql/mysql/sqlalchemy/main.py
  cloud-sql/postgres/sqlalchemy/README.md
  cloud-sql/postgres/sqlalchemy/app.flexible.yaml
  cloud-sql/postgres/sqlalchemy/app.standard.yaml
  cloud-sql/postgres/sqlalchemy/main.py
  cloud-sql/sql-server/sqlalchemy/README.md
  cloud-sql/sql-server/sqlalchemy/app.yaml
  cloud-sql/sql-server/sqlalchemy/main.py
Labels: cla: yes

#3975 Change string format to f-strings
  firestore/cloud-client/snippets.py
Labels: cla: yes

#3964 Add text redaction sample using DLP
  dlp/README.rst
  dlp/deid.py
  dlp/deid_test.py
Labels: cla: yes

#3976 Add Datastore eventual consistency read example
  datastore/cloud-client/snippets.py
Labels: cla: yes

#3972 chore: add note about preference of stream() to get()
  firestore/cloud-client/snippets.py
Labels: cla: yes

#3973 [jobs] testing: use multiple projects
  jobs/v3/api_client/README.rst
  jobs/v3/api_client/README.rst.in
  jobs/v3/api_client/email_alert_search_sample_test.py
  jobs/v3/api_client/noxfile_config.py
Labels: cla: yes

#3956 Add code sample for string replacement based deidentification.
  dlp/deid.py
  dlp/deid_test.py
Labels: automerge, cla: yes

#3971 E2E tests for Cloud Run hello-broken and logging-manual samples
  run/hello-broken/e2e_test.py
  run/hello-broken/e2e_test_setup.yaml
  run/hello-broken/noxfile_config.py
  run/logging-manual/e2e_test.py
  run/logging-manual/e2e_test_setup.yaml
  run/logging-manual/noxfile_config.py
  run/logging-manual/requirements-test.txt
Labels: cla: yes

#4017 fix: changes positional to named pararameters in Video samples
  video/cloud-client/analyze/analyze.py
  video/cloud-client/labels/labels.py
  video/cloud-client/shotchange/shotchange.py
Labels: automerge, cla: yes

#3991 Add custom infoType snippets to DLP samples
  dlp/custom_infotype.py
  dlp/custom_infotype_test.py
Labels: cla: yes

#3977 Add Firestore list subcollections example
  firestore/cloud-client/snippets.py
  firestore/cloud-client/snippets_test.py
Labels: cla: yes

#3656 Samples for migrating from Python 2.7 runtime to Python 3.7
  appengine/standard/migration/incoming/README.md
  appengine/standard/migration/incoming/app.yaml
  appengine/standard/migration/incoming/appengine_config.py
  appengine/standard/migration/incoming/main.py
  appengine/standard/migration/incoming/main_test.py
  appengine/standard/migration/incoming/requirements-test.txt
  appengine/standard/migration/incoming/requirements.txt
  appengine/standard/migration/storage/README.md
  appengine/standard/migration/storage/app.yaml
  appengine/standard/migration/storage/app3.yaml
  appengine/standard/migration/storage/appengine_config.py
  appengine/standard/migration/storage/main.py
  appengine/standard/migration/storage/main_test.py
  appengine/standard/migration/storage/requirements-test.txt
  appengine/standard/migration/storage/requirements.txt
  appengine/standard/migration/urlfetch/async/README.md
  appengine/standard/migration/urlfetch/async/app.yaml
  appengine/standard/migration/urlfetch/async/app3.yaml
  appengine/standard/migration/urlfetch/async/appengine_config.py
  appengine/standard/migration/urlfetch/async/main.py
  appengine/standard/migration/urlfetch/async/main_test.py
  appengine/standard/migration/urlfetch/async/requirements-test.txt
  appengine/standard/migration/urlfetch/async/requirements.txt
  appengine/standard/migration/urlfetch/requests/README.md
  appengine/standard/migration/urlfetch/requests/app.yaml
  appengine/standard/migration/urlfetch/requests/app3.yaml
  appengine/standard/migration/urlfetch/requests/appengine_config.py
  appengine/standard/migration/urlfetch/requests/main.py
  appengine/standard/migration/urlfetch/requests/main_test.py
  appengine/standard/migration/urlfetch/requests/requirements-test.txt
  appengine/standard/migration/urlfetch/requests/requirements.txt
  appengine/standard_python37/migration/urlfetch/README.md
  appengine/standard_python37/migration/urlfetch/app.yaml
  appengine/standard_python37/migration/urlfetch/main.py
  appengine/standard_python37/migration/urlfetch/main_test.py
  appengine/standard_python37/migration/urlfetch/requirements-test.txt
  appengine/standard_python37/migration/urlfetch/requirements.txt
  appengine/standard_python37/migration/urlfetch/templates/index.html
Labels: cla: yes

#4028 [healthcare] testing: use fixture for fhir_store
  healthcare/api-client/fhir/fhir_stores_test.py
Labels: cla: yes

#4020 Rename DLP code samples from 'redact' to 'replace'
  dlp/README.rst
  dlp/deid.py
  dlp/deid_test.py
Labels: automerge, cla: yes

#4018 Add DLP sample for redacting all image text
  dlp/README.rst
  dlp/redact.py
  dlp/redact_test.py
Labels: automerge, cla: yes

#4035 Fix app yamls
  appengine/standard/i18n/app.yaml
  appengine/standard/multitenancy/app.yaml
  appengine/standard/ndb/overview/app.yaml
  appengine/standard/ndb/transactions/app.yaml
Labels: cla: yes

#4031 Add DLP sample code for inspecting with custom regex detector
  dlp/custom_infotype.py
  dlp/custom_infotype_test.py
Labels: automerge, cla: yes

#4050 remove whitelist replace with allowlist
  appengine/flexible/memcache/README.md
  translate/cloud-client/snippets.py
Labels: cla: yes

#3898 Move Firebase snippet to the body
  appengine/standard_python37/building-an-app/building-an-app-3/templates/index.html
  appengine/standard_python37/building-an-app/building-an-app-4/templates/index.html
Labels: automerge, cla: yes

#4037 Add code sample and tests for redaction
  dlp/deid.py
  dlp/deid_test.py
Labels: automerge, cla: yes

#4048 [storage] testing: use multiple projects
  storage/cloud-client/acl_test.py
  storage/cloud-client/hmac_samples_test.py
  storage/cloud-client/iam_test.py
  storage/cloud-client/noxfile_config.py
  storage/cloud-client/snippets_test.py
  storage/cloud-client/uniform_bucket_level_access_test.py
Labels: cla: yes

#4027 Pub/Sub: clean up redundant/wrong region tag
  pubsub/cloud-client/subscriber.py
Labels: cla: yes

#4063 Get response as string instead of bytes
  functions/security/main.py
  functions/security/main_test.py
Labels: cla: yes

#4059 Move composer code to composer folder
  composer/functions/README.md
  composer/functions/composer_storage_trigger.py
  composer/functions/composer_storage_trigger_test.py
  composer/functions/requirements-test.txt
  composer/functions/requirements.txt
Labels: automerge, cla: yes

#4067 Ndb migration sample
  appengine/standard/migration/ndb/overview/README.md
  appengine/standard/migration/ndb/overview/app.yaml
  appengine/standard/migration/ndb/overview/app3.yaml
  appengine/standard/migration/ndb/overview/appengine_config.py
  appengine/standard/migration/ndb/overview/favicon.ico
  appengine/standard/migration/ndb/overview/index.yaml
  appengine/standard/migration/ndb/overview/main.py
  appengine/standard/migration/ndb/overview/main_test.py
  appengine/standard/migration/ndb/overview/requirements-test.txt
  appengine/standard/migration/ndb/overview/requirements.txt
  appengine/standard/migration/ndb/overview/templates/index.html
  appengine/standard/ndb/overview/main.py
Labels: cla: yes

#4077 [appengine] pin rsa to 4.0
  appengine/standard/endpoints-frameworks-v2/echo/requirements.txt
  appengine/standard/endpoints-frameworks-v2/quickstart/requirements.txt
  appengine/standard/migration/ndb/overview/main_test.py
Labels: cla: yes

#3908 Remove KMS samples
  kms/README.rst
  kms/api-client/README.rst
  kms/api-client/README.rst.in
  kms/api-client/create_key_asymmetric_decrypt.py
  kms/api-client/create_key_asymmetric_sign.py
  kms/api-client/create_key_hsm.py
  kms/api-client/create_key_labels.py
  kms/api-client/create_key_ring.py
  kms/api-client/create_key_rotation_schedule.py
  kms/api-client/create_key_symmetric_encrypt_decrypt.py
  kms/api-client/create_key_version.py
  kms/api-client/decrypt_asymmetric.py
  kms/api-client/decrypt_symmetric.py
  kms/api-client/destroy_key_version.py
  kms/api-client/disable_key_version.py
  kms/api-client/enable_key_version.py
  kms/api-client/encrypt_asymmetric.py
  kms/api-client/encrypt_symmetric.py
  kms/api-client/get_key_labels.py
  kms/api-client/get_key_version_attestation.py
  kms/api-client/get_public_key.py
  kms/api-client/iam_add_member.py
  kms/api-client/iam_get_policy.py
  kms/api-client/iam_remove_member.py
  kms/api-client/quickstart.py
  kms/api-client/requirements-test.txt
  kms/api-client/requirements.txt
  kms/api-client/restore_key_version.py
  kms/api-client/sign_asymmetric.py
  kms/api-client/snippets_test.py
  kms/api-client/update_key_add_rotation.py
  kms/api-client/update_key_remove_labels.py
  kms/api-client/update_key_remove_rotation.py
  kms/api-client/update_key_set_primary.py
  kms/api-client/update_key_update_labels.py
  kms/api-client/verify_asymmetric_ec.py
  kms/api-client/verify_asymmetric_rsa.py
  kms/attestations/README.rst
  kms/attestations/README.rst.in
  kms/attestations/requirements-test.txt
  kms/attestations/requirements.txt
  kms/attestations/verify_attestation.py
  kms/attestations/verify_attestation_test.py
Labels: cla: yes

#4068 [jobs] testing: use multiple projects
  jobs/v4beta1/README.rst
  jobs/v4beta1/job_search_list_tenants_test.py
  jobs/v4beta1/noxfile_config.py
Labels: cla: yes

#4030 [btlr] testing: use NUM_TEST_WORKERS env var
  .kokoro/python3.6/common.cfg
  .kokoro/python3.7/common.cfg
  .kokoro/python3.8/common.cfg
  .kokoro/tests/run_tests.sh
Labels: cla: yes

#4081 Add DLP code sample and test for person_name detector with hotwords
  dlp/custom_infotype.py
  dlp/custom_infotype_test.py
Labels: automerge, cla: yes

#4069 Add a simplified inspect string example to DLP code samples
  dlp/inspect_content.py
  dlp/inspect_content_test.py
Labels: cla: yes

#4051 Add DLP sample code for reid w/ fpe using surrogate type and unwrapped security key
  dlp/deid.py
  dlp/deid_test.py
Labels: cla: yes

#4066 Create PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: cla: yes

#4012 add python snippets and tests for creating, listing, and deleting queues
  tasks/create_queue.py
  tasks/create_queue_test.py
  tasks/delete_queue.py
  tasks/delete_queue_test.py
  tasks/list_queues.py
  tasks/list_queues_test.py
Labels: cla: yes

#4064 [healthcare] testing: use multiple projects
  healthcare/api-client/datasets/README.rst
  healthcare/api-client/datasets/README.rst.in
  healthcare/api-client/datasets/noxfile_config.py
  healthcare/api-client/dicom/README.rst
  healthcare/api-client/dicom/README.rst.in
  healthcare/api-client/dicom/noxfile_config.py
  healthcare/api-client/fhir/README.rst
  healthcare/api-client/fhir/README.rst.in
  healthcare/api-client/fhir/noxfile_config.py
  healthcare/api-client/hl7v2/README.rst
  healthcare/api-client/hl7v2/README.rst.in
  healthcare/api-client/hl7v2/noxfile_config.py
  healthcare/api-client/v1/datasets/README.rst
  healthcare/api-client/v1/datasets/README.rst.in
  healthcare/api-client/v1/datasets/noxfile_config.py
  healthcare/api-client/v1/dicom/README.rst
  healthcare/api-client/v1/dicom/README.rst.in
  healthcare/api-client/v1/dicom/noxfile_config.py
  healthcare/api-client/v1/fhir/README.rst
  healthcare/api-client/v1/fhir/README.rst.in
  healthcare/api-client/v1/fhir/noxfile_config.py
  healthcare/api-client/v1/hl7v2/README.rst
  healthcare/api-client/v1/hl7v2/README.rst.in
  healthcare/api-client/v1/hl7v2/noxfile_config.py
Labels: cla: yes

#4071 Add DLP code sample and test for medical number custom detector with hotwords
  dlp/custom_infotype.py
  dlp/custom_infotype_test.py
Labels: automerge, cla: yes

#4011 [run] add Pub/Sub events sample
  run/events-pubsub/.dockerignore
  run/events-pubsub/Dockerfile
  run/events-pubsub/README.md
  run/events-pubsub/main.py
  run/events-pubsub/main_test.py
  run/events-pubsub/requirements-test.txt
  run/events-pubsub/requirements.txt
Labels: automerge, cla: yes

#4070 Pub/Sub: wrap subscriber in a with block and add comments
  pubsub/cloud-client/subscriber.py
Labels: automerge, cla: yes

#4078 [run] add sample code for gcs events
  run/events-gcs/Dockerfile
  run/events-gcs/README.md
  run/events-gcs/main.py
  run/events-gcs/main_test.py
  run/events-gcs/requirements-test.txt
  run/events-gcs/requirements.txt
Labels: cla: yes

#4055 feat: changes Media Translation mic sample to be state-aware
  media-translation/cloud-client/translate_from_mic.py
Labels: automerge, cla: yes

#4085 Add DLP code sample and test for de-id free text with surrogate
  dlp/deid.py
  dlp/deid_test.py
Labels: automerge, cla: yes

#4092 fix: changes a positional to named arg
  video/cloud-client/analyze/beta_snippets.py
Labels: automerge, cla: yes

#4086 Added tests for Django samples
  appengine/flexible/django_cloudsql/mysite/settings.py
  appengine/flexible/django_cloudsql/noxfile_config.py
  appengine/flexible/django_cloudsql/polls/test_polls.py
  appengine/flexible/django_cloudsql/requirements-test.txt
  appengine/standard/django/mysite/settings.py
  appengine/standard/django/polls/test_polls.py
  appengine/standard/django/pytest.ini
  appengine/standard/django/requirements-test.txt
  appengine/standard_python3/django/mysite/settings.py
  appengine/standard_python3/django/noxfile_config.py
  appengine/standard_python3/django/polls/test_polls.py
  appengine/standard_python3/django/polls/tests.py
  appengine/standard_python3/django/requirements-test.txt
  appengine/standard_python37/django/mysite/settings.py
  appengine/standard_python37/django/noxfile_config.py
  appengine/standard_python37/django/polls/test_polls.py
  appengine/standard_python37/django/polls/tests.py
  appengine/standard_python37/django/requirements-test.txt
Labels: cla: yes

#4094 [iam] testing: use uniqueId instead of email
  iam/api-client/service_accounts_test.py
Labels: cla: yes

#4096 [appengine] use noxfile_config.py instead of pytest.ini
  appengine/standard/django/noxfile_config.py
  appengine/standard/django/pytest.ini
  appengine/standard/noxfile-template.py
Labels: cla: yes

#4105 Updated gcs_to_bq method
  composer/workflows/bq_copy_across_locations.py
Labels: automerge, cla: yes

#4097 Clarify infinite retries example
  functions/tips/main.py
Labels: automerge, cla: yes

#4080 [asset] Add sample code for two new RPCs.
  asset/cloud-client/quickstart_searchalliampolicies.py
  asset/cloud-client/quickstart_searchalliampolicies_test.py
  asset/cloud-client/quickstart_searchallresources.py
  asset/cloud-client/quickstart_searchallresources_test.py
  asset/cloud-client/requirements.txt
Labels: cla: yes

#4116 Update Cloud Run sample owner
  .github/CODEOWNERS
Labels: automerge, cla: yes

#4107 fix: fixes run events gcs sample region tags
  run/events-gcs/Dockerfile
  run/events-gcs/main.py
Labels: cla: yes

#4123 testing: update the python versions in the Dockerfile
  .kokoro/docker/Dockerfile
  .kokoro/python3.8/periodic.cfg
Labels: cla: yes

#4114 healthcare API: add comment on update/patch FHIR resource
  healthcare/api-client/v1/fhir/fhir_resources.py
Labels: cla: yes

#4131 test(jobs): increase max test time to 300
  jobs/v3/api_client/email_alert_search_sample_test.py
Labels: cla: yes

#4065 [bigtable] update reads/filters region tags
  bigtable/metricscaler/metricscaler_test.py
  bigtable/snippets/filters/filter_snippets.py
  bigtable/snippets/reads/read_snippets.py
Labels: cla: yes

#4129 Use f-strings in the Authoring Guide
  AUTHORING_GUIDE.md
Labels: cla: yes

#4128 testing: use default service account
  .kokoro/tests/run_tests.sh
  .kokoro/trampoline_v2.sh
  scripts/decrypt-secrets.sh
Labels: cla: yes

#4152 [dlp] fix: add retry count to mitigate the flake
  dlp/risk_test.py
Labels: cla: yes

#4026 Trace python opentelemetry
  trace/trace-python-sample-opentelemetry/README.rst
  trace/trace-python-sample-opentelemetry/README.rst.in
  trace/trace-python-sample-opentelemetry/main.py
  trace/trace-python-sample-opentelemetry/main_test.py
  trace/trace-python-sample-opentelemetry/requirements-test.txt
  trace/trace-python-sample-opentelemetry/requirements.txt
Labels: cla: yes

#4079 update authoring guide
  AUTHORING_GUIDE.md
Labels: automerge, cla: yes

#4153 [monitoring] fix: mitigate flake
  monitoring/api/v3/uptime-check-client/requirements-test.txt
  monitoring/api/v3/uptime-check-client/snippets_test.py
Labels: cla: yes

#4156 testing: upgrade the base image to Ubuntu 18.04
  .kokoro/docker/Dockerfile
Labels: cla: yes

#4167 add a section for installing coreutils on MacOS
  AUTHORING_GUIDE.md
Labels: cla: yes

#4171 testing: reliablly fetch gpg keys
  .kokoro/docker/Dockerfile
  .kokoro/docker/fetch_gpg_keys.sh
  .kokoro/trampoline_v2.sh
  vision/automl/edge_container_predict/automl_vision_edge_container_predict_test.py
Labels: cla: yes

#4170 run: events-storage rename
  run/README.md
  run/events-storage/Dockerfile
  run/events-storage/README.md
  run/events-storage/main.py
  run/events-storage/main_test.py
  run/events-storage/requirements-test.txt
  run/events-storage/requirements.txt
Labels: cla: yes

#4183 docs(tasks): service_account_email parameter example
  tasks/create_http_task_with_token.py
Labels: cla: yes

#4181 [asset] fix: bump the timeout
  asset/cloud-client/quickstart_searchallresources_test.py
Labels: cla: yes

#4182 healthcare API: change FHIR Observation coding
  healthcare/api-client/v1/fhir/fhir_resources.py
Labels: automerge, cla: yes

#4188 [tables/automl] fix: update the csv file and the dataset name
  tables/automl/dataset_test.py
Labels: cla: yes

#4198 fix(spanner): use uuid for unique id
  spanner/cloud-client/backup_sample_test.py
  spanner/cloud-client/snippets_test.py
Labels: cla: yes

#4201 chore: changes boilerplate to LLC
  video/cloud-client/analyze/analyze.py
Labels: automerge, cla: yes

#4175 chore: remove PubSub cloud-client samples
  pubsub/cloud-client/README.rst
  pubsub/cloud-client/README.rst.in
  pubsub/cloud-client/iam.py
  pubsub/cloud-client/iam_test.py
  pubsub/cloud-client/publisher.py
  pubsub/cloud-client/publisher_test.py
  pubsub/cloud-client/quickstart/pub.py
  pubsub/cloud-client/quickstart/pub_test.py
  pubsub/cloud-client/quickstart/sub.py
  pubsub/cloud-client/quickstart/sub_test.py
  pubsub/cloud-client/requirements-test.txt
  pubsub/cloud-client/requirements.txt
  pubsub/cloud-client/subscriber.py
  pubsub/cloud-client/subscriber_test.py
Labels: cla: yes

#4187 Update functions billing example
  functions/billing/main.py
Labels: cla: yes

#4202 fix(monitoring): also retry upon DeadlineExceeded
  monitoring/api/v3/alerts-client/snippets_test.py
Labels: cla: yes

#4216 fix(functions): only check if there is a result
  functions/slack/main_test.py
Labels: cla: yes
