Repository GoogleCloudPlatform/python-docs-samples, pull requests merged in 2020-01, with the labels that each got.

#2667 fix: Improve Firestore tests by separating test runs, improving cleanup
  firestore/cloud-client/distributed_counters_test.py
  firestore/cloud-client/snippets.py
  firestore/cloud-client/snippets_test.py
Labels: cla: yes

#2679 automl: add translate ga samples
  automl/cloud-client/resources/input.txt
  automl/cloud-client/translate_create_dataset.py
  automl/cloud-client/translate_create_dataset_test.py
  automl/cloud-client/translate_create_model.py
  automl/cloud-client/translate_create_model_test.py
  automl/cloud-client/translate_predict.py
  automl/cloud-client/translate_predict_test.py
Labels: cla: yes

#2683 Add note in authoring guide about testing
  AUTHORING_GUIDE.md
Labels: cla: yes

#2669 fix: run lint and black on failing sample
  codelabs/functions/python_powered/main.py
Labels: cla: yes

#2671 fix: translate test
  translate/cloud-client/beta_snippets.py
  translate/cloud-client/beta_snippets_test.py
Labels: api: translate, cla: yes, testing, type: cleanup

#2686 Pub/Sub: remove `_ah` in AppEngine Python3 sample
  appengine/standard_python37/pubsub/README.md
  appengine/standard_python37/pubsub/main.py
  appengine/standard_python37/pubsub/main_test.py
Labels: cla: yes

#2690 fix continuous lint
  appengine/standard_python37/cloud_debugger/main.py
Labels: cla: yes

#2567 Have to specify flask library in app.yaml
  appengine/standard/pubsub/app.yaml
Labels: cla: yes

#2691 Revert appengine django dependency
  appengine/standard_python37/django/requirements.txt
Labels: cla: yes

#2694 catch potential error retrieving datastore results
  appengine/flexible/datastore/main.py
Labels: api: appengine, cla: yes

#2697 Update Mac setup guide
  MAC_SETUP.md
Labels: cla: yes

#2699 Bump secretmanager version
  secretmanager/api-client/requirements.txt
Labels: cla: yes

#2608 automl: add base dataset samples for automl ga
  automl/cloud-client/delete_dataset.py
  automl/cloud-client/delete_dataset_test.py
  automl/cloud-client/export_dataset.py
  automl/cloud-client/export_dataset_test.py
  automl/cloud-client/get_dataset.py
  automl/cloud-client/get_dataset_test.py
  automl/cloud-client/import_dataset.py
  automl/cloud-client/import_dataset_test.py
  automl/cloud-client/list_datasets.py
  automl/cloud-client/list_datasets_test.py
Labels: cla: yes

#2629 feat: dataproc quickstart sample added and create_cluster updated
  dataproc/create_cluster.py
  dataproc/create_cluster_test.py
  dataproc/quickstart/quickstart.py
  dataproc/quickstart/quickstart_test.py
Labels: cla: yes

#2701 Cleanup iam tests
  iam/api-client/access.py
  iam/api-client/access_test.py
  iam/api-client/custom_roles_test.py
Labels: cla: yes

#2692 Cleanup bigtable python examples
  bigtable/hello/main.py
  bigtable/hello/main_test.py
  bigtable/hello/requirements.txt
  bigtable/hello_happybase/main_test.py
  bigtable/instanceadmin/requirements.txt
  bigtable/metricscaler/metricscaler_test.py
  bigtable/metricscaler/requirements.txt
  bigtable/quickstart/main_test.py
  bigtable/quickstart/requirements.txt
  bigtable/quickstart_happybase/main.py
  bigtable/quickstart_happybase/main_test.py
  bigtable/snippets/writes/requirements.txt
  bigtable/snippets/writes/write_batch.py
  bigtable/snippets/writes/write_conditionally.py
  bigtable/snippets/writes/write_increment.py
  bigtable/snippets/writes/write_simple.py
  bigtable/snippets/writes/writes_test.py
  bigtable/tableadmin/requirements.txt
  bigtable/tableadmin/tableadmin_test.py
  testing/secrets.tar.enc
Labels: cla: yes

#2703 chore: update pytest version
  pytest.ini
  testing/requirements.txt
Labels: cla: yes

#2560 functions/http: add missing tests
  functions/http/main_test.py
Labels: cla: yes

#2705 fix: get bounds for blocks instead of pages
  vision/cloud-client/document_text/doctext.py
Labels: cla: yes

#2569 Add vision ocr set endpoint samples
  vision/cloud-client/detect/beta_snippets.py
  vision/cloud-client/detect/beta_snippets_test.py
  vision/cloud-client/detect/detect_test.py
  vision/cloud-client/detect/requirements.txt
  vision/cloud-client/detect/set_endpoint.py
  vision/cloud-client/detect/set_endpoint_test.py
Labels: cla: yes

#2709 Replaces empty return value with string
  iot/api-client/manager/manager.py
Labels: cla: yes

#2687 Add voice selection by name
  texttospeech/cloud-client/requirements.txt
  texttospeech/cloud-client/synthesize_text.py
Labels: cla: yes

#2714 Fix a small comment typo
  secretmanager/api-client/get_secret.py
Labels: cla: yes

#2717 Increase build timeout to 5 hours.
  .kokoro/python2.7/common.cfg
  .kokoro/python3.5/common.cfg
  .kokoro/python3.6/common.cfg
  .kokoro/python3.7/common.cfg
Labels: cla: yes

#2588 functions/slack: message verification - tokens -> signatures
  .kokoro/tests/run_tests.sh
  functions/slack/config.json
  functions/slack/main.py
  functions/slack/main_test.py
  functions/slack/requirements.txt
  testing/secrets.tar.enc
Labels: cla: yes

#2720 Minor polishing of authoring guide
  AUTHORING_GUIDE.md
Labels: cla: yes

#2676 automl: add natural language entity extraction ga samples
  automl/cloud-client/language_entity_extraction_create_dataset.py
  automl/cloud-client/language_entity_extraction_create_dataset_test.py
  automl/cloud-client/language_entity_extraction_create_model.py
  automl/cloud-client/language_entity_extraction_create_model_test.py
  automl/cloud-client/language_entity_extraction_predict.py
  automl/cloud-client/language_entity_extraction_predict_test.py
Labels: cla: yes

#2614 automl: add vision object detection samples for atuoml ga
  automl/cloud-client/resources/salad.jpg
  automl/cloud-client/vision_object_detection_create_dataset.py
  automl/cloud-client/vision_object_detection_create_dataset_test.py
  automl/cloud-client/vision_object_detection_create_model.py
  automl/cloud-client/vision_object_detection_create_model_test.py
  automl/cloud-client/vision_object_detection_deploy_model_node_count.py
  automl/cloud-client/vision_object_detection_deploy_model_node_count_test.py
  automl/cloud-client/vision_object_detection_predict.py
  automl/cloud-client/vision_object_detection_predict_test.py
Labels: cla: yes

#2700 Task Name in Creating HTTP Task with Token
  tasks/create_http_task_with_token.py
Labels: cla: yes

#2713 Use Python 3 in virtual environment
  iap/example_startup_script.sh
Labels: cla: yes

#2721 Delete spanner/cloud-client/bulk_load_csv.
  spanner/cloud-client/bulk_load_csv/README.rst
  spanner/cloud-client/bulk_load_csv/batch_import.py
  spanner/cloud-client/bulk_load_csv/batch_import_test.py
  spanner/cloud-client/bulk_load_csv/hnewscomments.csv
  spanner/cloud-client/bulk_load_csv/hnewsstories.csv
  spanner/cloud-client/bulk_load_csv/requirements.txt
  spanner/cloud-client/bulk_load_csv/schema.ddl
Labels: cla: yes

#2659 Update CODEOWNERS
  .github/CODEOWNERS
Labels: cla: yes

#2730 samples(storage): IAM conditions samples
  storage/cloud-client/iam_test.py
  storage/cloud-client/requirements.txt
  storage/cloud-client/storage_add_bucket_conditional_iam_binding.py
  storage/cloud-client/storage_add_bucket_iam_member.py
  storage/cloud-client/storage_remove_bucket_iam_member.py
  storage/cloud-client/storage_view_bucket_iam_members.py
Labels: cla: yes

#2725 vision: update samples to throw errors if one occurs
  vision/cloud-client/detect/beta_snippets.py
  vision/cloud-client/detect/detect.py
  vision/cloud-client/detect/detect_test.py
  vision/cloud-client/detect/set_endpoint.py
Labels: cla: yes

#2731 fix region tag typo
  translate/cloud-client/hybrid_glossaries/hybrid_tutorial.py
Labels: cla: yes

#2740 Fix bigtable tests
  testing/secrets.tar.enc
Labels: cla: yes

#2744 Add max-line-length to nox lint.
  noxfile-template.py
  noxfile.py
Labels: cla: yes

#2746 fix: changes fields printed in list glossary sample; some minor fixes
  translate/cloud-client/translate_v3_create_glossary.py
  translate/cloud-client/translate_v3_list_glossary.py
Labels: cla: yes

#2733 Update Dataproc Python Cloud Shell walkthrough tutorial
  dataproc/python-api-walkthrough.md
Labels: cla: yes

#2748 Adding environment port variable
  run/hello-broken/README.md
  run/image-processing/README.md
  run/logging-manual/README.md
  run/pubsub/README.md
  run/system-package/README.md
Labels: cla: yes

#2735 dialogflow: split up entity and entity type tests
  dialogflow/cloud-client/create_entity_test.py
  dialogflow/cloud-client/create_entity_type_test.py
  dialogflow/cloud-client/delete_entity_test.py
  dialogflow/cloud-client/delete_entity_type_test.py
  dialogflow/cloud-client/entity_management_test.py
  dialogflow/cloud-client/list_entities_test.py
  dialogflow/cloud-client/list_entity_types_test.py
Labels: cla: yes

#2743 vision: move published samples into master
  vision/cloud-client/detect/vision_async_batch_annotate_images.py
  vision/cloud-client/detect/vision_async_batch_annotate_images_test.py
  vision/cloud-client/detect/vision_batch_annotate_files.py
  vision/cloud-client/detect/vision_batch_annotate_files_gcs.py
  vision/cloud-client/detect/vision_batch_annotate_files_gcs_test.py
  vision/cloud-client/detect/vision_batch_annotate_files_test.py
Labels: cla: yes

#2734 fix: added cli functionality to dataproc quickstart example
  dataproc/quickstart/quickstart.py
  dataproc/quickstart/quickstart_test.py
Labels: cla: yes

#2747 speech: fixing flaky auto punctuation test
  speech/cloud-client/beta_snippets_test.py
  speech/cloud-client/transcribe_auto_punctuation_test.py
Labels: cla: yes

#2749 Add Secret Manager IAM samples
  secretmanager/api-client/README.rst
  secretmanager/api-client/README.rst.in
  secretmanager/api-client/iam_grant_access.py
  secretmanager/api-client/iam_revoke_access.py
  secretmanager/api-client/snippets_test.py
  testing/secrets.tar.enc
Labels: cla: yes

#2639 Cloud Healthcare API beta FHIR updates
  healthcare/api-client/fhir/README.rst.in
  healthcare/api-client/fhir/fhir_resources.py
  healthcare/api-client/fhir/fhir_resources_test.py
  healthcare/api-client/fhir/fhir_stores_test.py
  healthcare/api-client/fhir/resources/execute_bundle.json
Labels: cla: yes

#2755 video: add auto-generated Logo Recognition Samples
  video/cloud-client/analyze/README.rst
  video/cloud-client/analyze/analyze.py
  video/cloud-client/analyze/analyze_test.py
  video/cloud-client/analyze/beta_snippets.py
  video/cloud-client/analyze/beta_snippets_test.py
  video/cloud-client/analyze/resources/googlework_tiny.mp4
  video/cloud-client/analyze/video_detect_logo_beta.py
  video/cloud-client/analyze/video_detect_logo_beta_test.py
  video/cloud-client/analyze/video_detect_logo_gcs_beta.py
  video/cloud-client/analyze/video_detect_logo_gcs_beta_test.py
Labels: cla: yes

#2756 speech: canonical sample for speechcontext ga of classes
  speech/cloud-client/requirements.txt
  speech/cloud-client/transcribe_context_classes.py
  speech/cloud-client/transcribe_context_classes_test.py
Labels: cla: yes

#2754 automl: video beta move model samples from branch to master
  automl/beta/delete_model.py
  automl/beta/delete_model_test.py
  automl/beta/get_model.py
  automl/beta/get_model_evaluation.py
  automl/beta/get_model_evaluation_test.py
  automl/beta/get_model_test.py
  automl/beta/list_models.py
  automl/beta/list_models_test.py
Labels: cla: yes

#2759 Migrate published samples
  translate/cloud-client/translate_v3_translate_text.py
  translate/cloud-client/translate_v3_translate_text_test.py
Labels: cla: yes
