Repository GoogleCloudPlatform/python-docs-samples, pull requests merged in 2020-09, with the labels that each got.

#4603 chore: configure blunderbuss
  .github/CODEOWNERS
  .github/blunderbuss.yml
Labels: cla: yes, samples

#4613 fix(iap): add sleep to avoid test failures
  iap/iap_test.py
Labels: cla: yes

#4611 dataflow/flex-templates: adding reference to bug
  dataflow/flex-templates/streaming_beam/streaming_beam_test.py
Labels: api: dataflow, cla: yes, samples

#4615 feat(storage): Update storage_get_metadata.py to include custom_time
  storage/cloud-client/storage_get_metadata.py
Labels: api: storage, automerge, cla: yes, samples

#4607 Composer cloud build
  composer/workflows/cloud-build.yaml
  composer/workflows/requirements-composer.txt
  renovate.json
Labels: cla: yes, samples

#4414 Sample for Cloud Run service-to-service authentication
  auth/service-to-service/auth.py
  auth/service-to-service/auth_test.py
  auth/service-to-service/main.py
  auth/service-to-service/noxfile_config.py
  auth/service-to-service/requirements-test.txt
  auth/service-to-service/requirements.txt
Labels: cla: yes, samples

#4624 Remove tasks samples
  tasks/README.md
  tasks/create_http_task.py
  tasks/create_http_task_test.py
  tasks/create_http_task_with_token.py
  tasks/create_http_task_with_token_test.py
  tasks/create_queue.py
  tasks/create_queue_test.py
  tasks/delete_queue.py
  tasks/delete_queue_test.py
  tasks/list_queues.py
  tasks/list_queues_test.py
  tasks/requirements-test.txt
  tasks/requirements.txt
Labels: cla: yes, samples

#4620 fix: update relative path
  composer/workflows/cloud-build.yaml
Labels: cla: yes, samples

#4629 remove comment because composer doesn't like it
  composer/workflows/requirements-composer.txt
Labels: cla: yes

#4630 fix(run): add timestamp filter for faster test
  run/logging-manual/e2e_test.py
Labels: cla: yes

#4632 docs: add note about filtering for list methods
  AUTHORING_GUIDE.md
Labels: cla: yes

#4644 chore: blunderbuss update
  .github/blunderbuss.yml
Labels: cla: yes

#4655 Update python versions
  MAC_SETUP.md
Labels: cla: yes

#4548 fix: addresses broken Vision test in Translation hybrid tutorial
  translate/cloud-client/hybrid_glossaries/hybrid_tutorial_test.py
  translate/cloud-client/hybrid_glossaries/resources/non_standard_format.png
  translate/cloud-client/hybrid_glossaries/resources/non_standard_format.txt
Labels: cla: yes, samples

#4664 fix: use enums instead of str for task creation
  appengine/flexible/tasks/create_app_engine_queue_task.py
  appengine/flexible/tasks/snippets.py
Labels: automerge, cla: yes

#4427 feat: add GAE memorystore migration sample
  appengine/standard/migration/memorystore/.gcloudignore
  appengine/standard/migration/memorystore/README.md
  appengine/standard/migration/memorystore/app.yaml
  appengine/standard/migration/memorystore/app3.yaml
  appengine/standard/migration/memorystore/appengine_config.py
  appengine/standard/migration/memorystore/main.py
  appengine/standard/migration/memorystore/main_test.py
  appengine/standard/migration/memorystore/requirements-test.txt
  appengine/standard/migration/memorystore/requirements.txt
  appengine/standard/migration/memorystore/templates/index.html
  appengine/standard/migration/memorystore/templates/showdata.html
Labels: cla: yes, samples

#4489 feat(appengine): Pub/Sub sample for both Python 2.7 and 3
  appengine/standard_python3/pubsub/README.md
  appengine/standard_python3/pubsub/app.yaml
  appengine/standard_python3/pubsub/app27.yaml
  appengine/standard_python3/pubsub/appengine_config.py
Labels: cla: yes, samples

#4648 chore(functions/firebase): add guard against infinite loops
  functions/firebase/main.py
  functions/firebase/main_test.py
Labels: api: cloudfunctions, cla: yes, samples

#4617 chore: remove translate samples (moved)
  translate/cloud-client/README.rst
  translate/cloud-client/README.rst.in
  translate/cloud-client/beta_snippets.py
  translate/cloud-client/beta_snippets_test.py
  translate/cloud-client/hybrid_glossaries/README.rst
  translate/cloud-client/hybrid_glossaries/README.rst.in
  translate/cloud-client/hybrid_glossaries/hybrid_tutorial.py
  translate/cloud-client/hybrid_glossaries/hybrid_tutorial_test.py
  translate/cloud-client/hybrid_glossaries/requirements-test.txt
  translate/cloud-client/hybrid_glossaries/requirements.txt
  translate/cloud-client/hybrid_glossaries/resources/bistro_glossary.csv
  translate/cloud-client/hybrid_glossaries/resources/example.mp3
  translate/cloud-client/hybrid_glossaries/resources/example.png
  translate/cloud-client/hybrid_glossaries/resources/expected_standard_text.mp3
  translate/cloud-client/hybrid_glossaries/resources/standard_format.jpeg
  translate/cloud-client/hybrid_glossaries/resources/standard_format.txt
  translate/cloud-client/pytest.ini
  translate/cloud-client/quickstart.py
  translate/cloud-client/quickstart_test.py
  translate/cloud-client/requirements-test.txt
  translate/cloud-client/requirements.txt
  translate/cloud-client/snippets.py
  translate/cloud-client/snippets_test.py
  translate/cloud-client/translate_v3_batch_translate_text.py
  translate/cloud-client/translate_v3_batch_translate_text_test.py
  translate/cloud-client/translate_v3_batch_translate_text_with_glossary.py
  translate/cloud-client/translate_v3_batch_translate_text_with_glossary_test.py
  translate/cloud-client/translate_v3_create_glossary.py
  translate/cloud-client/translate_v3_create_glossary_test.py
  translate/cloud-client/translate_v3_delete_glossary.py
  translate/cloud-client/translate_v3_delete_glossary_test.py
  translate/cloud-client/translate_v3_detect_language.py
  translate/cloud-client/translate_v3_detect_language_test.py
  translate/cloud-client/translate_v3_get_glossary.py
  translate/cloud-client/translate_v3_get_glossary_test.py
  translate/cloud-client/translate_v3_get_supported_languages.py
  translate/cloud-client/translate_v3_get_supported_languages_test.py
  translate/cloud-client/translate_v3_get_supported_languages_with_target.py
  translate/cloud-client/translate_v3_get_supported_languages_with_target_test.py
  translate/cloud-client/translate_v3_list_glossary.py
  translate/cloud-client/translate_v3_list_glossary_test.py
  translate/cloud-client/translate_v3_translate_text.py
  translate/cloud-client/translate_v3_translate_text_test.py
  translate/cloud-client/translate_v3_translate_text_with_glossary.py
  translate/cloud-client/translate_v3_translate_text_with_glossary_test.py
  translate/cloud-client/translate_v3_translate_text_with_model.py
  translate/cloud-client/translate_v3_translate_text_with_model_test.py
Labels: cla: yes, samples

#4670 cleanup: update blunderbuss
  .github/blunderbuss.yml
Labels: cla: yes, samples

#4665 remove iot manager samples
  iot/api-client/manager/README.md
  iot/api-client/manager/README.rst
  iot/api-client/manager/README.rst.in
  iot/api-client/manager/manager.py
  iot/api-client/manager/manager_test.py
  iot/api-client/manager/requirements-test.txt
  iot/api-client/manager/requirements.txt
  iot/api-client/manager/resources/README.md
  iot/api-client/manager/resources/ec_public.pem
  iot/api-client/manager/resources/rsa_cert.pem
  iot/api-client/manager/resources/rsa_private.pem
Labels: cla: yes, samples

#4485 feat: add Dataproc-Composer tutorial
  composer/workflows/dataproc_workflow_template_instantiate_operator_tutorial.py
  composer/workflows/dataproc_workflow_template_instantiate_operator_tutorial_test.py
Labels: cla: yes, samples

#4658 dataflow/flex-templates: update commands to GA
  dataflow/flex-templates/streaming_beam/README.md
  dataflow/flex-templates/streaming_beam/metadata.json
Labels: api: dataflow, cla: yes, samples

#4692 dataflow/run_template: slightly increase max retry time in test
  dataflow/run_template/main_test.py
Labels: cla: yes

#4683 test: add manager for remaining tests
  iot/api-client/manager/manager.py
Labels: cla: yes, samples

#4667 chore: remove BigQuery Storage to_dataframe samples (moved)
  bigquery_storage/to_dataframe/README.rst
  bigquery_storage/to_dataframe/__init__.py
  bigquery_storage/to_dataframe/jupyter_test.py
  bigquery_storage/to_dataframe/main_test.py
  bigquery_storage/to_dataframe/requirements-test.txt
  bigquery_storage/to_dataframe/requirements.txt
Labels: cla: yes, samples

#4641 test(spanner): fix flaky restore_database() sample test
  spanner/cloud-client/backup_sample.py
  spanner/cloud-client/backup_sample_test.py
  spanner/cloud-client/requirements-test.txt
Labels: api: spanner, cla: yes, samples

#4702 fix(monitoring): retry in the test setup
  monitoring/api/v3/cloud-client/snippets_test.py
Labels: api: monitoring, automerge, cla: yes, samples

#4707 chore: also upload the Docker image in py36 and py37 builds
  .kokoro/python3.6/periodic.cfg
  .kokoro/python3.7/periodic.cfg
Labels: cla: yes

#4712 chore: remove secret manager samples (moved)
  secretmanager/README.md
  secretmanager/api-client/README.rst
  secretmanager/api-client/README.rst.in
  secretmanager/api-client/access_secret_version.py
  secretmanager/api-client/add_secret_version.py
  secretmanager/api-client/create_secret.py
  secretmanager/api-client/delete_secret.py
  secretmanager/api-client/destroy_secret_version.py
  secretmanager/api-client/disable_secret_version.py
  secretmanager/api-client/enable_secret_version.py
  secretmanager/api-client/get_secret.py
  secretmanager/api-client/get_secret_version.py
  secretmanager/api-client/iam_grant_access.py
  secretmanager/api-client/iam_revoke_access.py
  secretmanager/api-client/list_secret_versions.py
  secretmanager/api-client/list_secrets.py
  secretmanager/api-client/quickstart.py
  secretmanager/api-client/requirements-test.txt
  secretmanager/api-client/requirements.txt
  secretmanager/api-client/snippets_test.py
  secretmanager/api-client/update_secret.py
Labels: cla: yes

#4713 chore(functions): show client library init
  functions/pubsub/main.py
Labels: api: cloudfunctions, automerge, cla: yes, samples

#4711 feat: upgrade cloud run to ga
  cloud-sql/postgres/sqlalchemy/README.md
  run/README.md
  run/image-processing/README.md
  run/logging-manual/README.md
  run/pubsub/README.md
  run/system-package/README.md
Labels: automerge, cla: yes, samples

#4602 chore: remove bq data transfer samples (moved)
  bigquery/transfer/cloud-client/quickstart.py
  bigquery/transfer/cloud-client/quickstart_test.py
  bigquery/transfer/cloud-client/requirements-test.txt
  bigquery/transfer/cloud-client/requirements.txt
Labels: cla: yes, samples

#4643 feat(spanner): add samples for NUMERIC type
  spanner/cloud-client/snippets.py
  spanner/cloud-client/snippets_test.py
Labels: api: spanner, cla: yes, samples

#4706 Remove old quickstart
  iam/api-client/grantable_roles_test.py
  iam/api-client/quickstart.py
  iam/api-client/quickstart_test.py
  iam/api-client/quickstartv2.py
  iam/api-client/quickstartv2_test.py
Labels: automerge, cla: yes, samples

#4716 IAM: update quickstart comments
  iam/api-client/quickstart.py
Labels: api: iam, cla: yes, samples

#4647 chore: remove speech samples
  speech/README.rst
  speech/cloud-client/README.rst
  speech/cloud-client/README.rst.in
  speech/cloud-client/beta_snippets.py
  speech/cloud-client/beta_snippets_test.py
  speech/cloud-client/quickstart.py
  speech/cloud-client/quickstart_test.py
  speech/cloud-client/requirements-test.txt
  speech/cloud-client/requirements.txt
  speech/cloud-client/resources/Google_Gnome.wav
  speech/cloud-client/resources/audio.raw
  speech/cloud-client/resources/audio2.raw
  speech/cloud-client/resources/commercial_mono.wav
  speech/cloud-client/resources/multi.wav
  speech/cloud-client/resources/two_channel_16k.wav
  speech/cloud-client/transcribe.py
  speech/cloud-client/transcribe_async.py
  speech/cloud-client/transcribe_async_test.py
  speech/cloud-client/transcribe_auto_punctuation.py
  speech/cloud-client/transcribe_auto_punctuation_test.py
  speech/cloud-client/transcribe_context_classes.py
  speech/cloud-client/transcribe_context_classes_test.py
  speech/cloud-client/transcribe_enhanced_model.py
  speech/cloud-client/transcribe_enhanced_model_test.py
  speech/cloud-client/transcribe_model_selection.py
  speech/cloud-client/transcribe_model_selection_test.py
  speech/cloud-client/transcribe_multichannel.py
  speech/cloud-client/transcribe_multichannel_test.py
  speech/cloud-client/transcribe_onprem/README.rst
  speech/cloud-client/transcribe_onprem/transcribe_onprem.py
  speech/cloud-client/transcribe_streaming.py
  speech/cloud-client/transcribe_streaming_test.py
  speech/cloud-client/transcribe_test.py
  speech/cloud-client/transcribe_word_time_offsets.py
  speech/cloud-client/transcribe_word_time_offsets_test.py
  speech/microphone/README.rst
  speech/microphone/README.rst.in
  speech/microphone/requirements-test.txt
  speech/microphone/requirements.txt
  speech/microphone/resources/quit.raw
  speech/microphone/transcribe_streaming_infinite.py
  speech/microphone/transcribe_streaming_mic.py
  speech/microphone/transcribe_streaming_mic_test.py
Labels: cla: yes, samples

#4758 cleanup: replace sanity check with confidence check
  auth/end-user/web/main_test.py
  composer/workflows/bashoperator_python2_test.py
  composer/workflows/bq_copy_across_locations_test.py
  composer/workflows/bq_notify_test.py
  composer/workflows/connections_test.py
  composer/workflows/dataflowtemplateoperator_tutorial_test.py
  composer/workflows/dataproc_workflow_template_instantiate_operator_tutorial_test.py
  composer/workflows/hadoop_tutorial_test.py
  composer/workflows/kubernetes_pod_operator_test.py
  composer/workflows/pythonvirtualenvoperator_python2_test.py
  composer/workflows/quickstart_test.py
  composer/workflows/simple_test.py
  composer/workflows/trigger_response_dag_test.py
  composer/workflows/use_local_deps_test.py
Labels: cla: yes

#4599 refactor fixtures, add static resources
  memorystore/redis/cloud_run_deployment/e2e_test.py
Labels: automerge, cla: yes, samples

#4762 Eventarc Quickstart Brushup
  eventarc/audit-storage/Dockerfile
  eventarc/audit-storage/README.md
  eventarc/audit-storage/main.py
  eventarc/pubsub/Dockerfile
  eventarc/pubsub/main.py
Labels: automerge, cla: yes, samples

#4771 dataflow: update "Open in Cloud Shell" links
  dataflow/README.md
  dataflow/encryption-keys/README.md
  dataflow/flex-templates/streaming_beam/README.md
  dataflow/run_template/README.md
Labels: cla: yes
