Repository GoogleCloudPlatform/python-docs-samples, pull requests merged in 2020-04, with the labels that each got.

#3236 fix: add information on PKCS1v15
  storage/signed_urls/generate_signed_urls.py
Labels: cla: yes

#3248 Bump Django version to 3.0 and set PyMySQL version
  appengine/standard_python37/django/mysite/settings.py
  appengine/standard_python37/django/requirements.txt
Labels: automerge, cla: yes

#3042 automl: move video classification samples out of branch
  automl/beta/video_classification_create_dataset.py
  automl/beta/video_classification_create_dataset_test.py
  automl/beta/video_classification_create_model.py
  automl/beta/video_classification_create_model_test.py
Labels: automerge, cla: yes

#3267 [healthcare] fix: use uuid for resource names
  healthcare/api-client/fhir/fhir_resources_test.py
  healthcare/api-client/fhir/fhir_stores_test.py
Labels: cla: yes

#3253 [healthcare] fix: fix broken tests for healthcare API
  healthcare/api-client/hl7v2/hl7v2_messages.py
  healthcare/api-client/hl7v2/hl7v2_messages_test.py
  healthcare/api-client/hl7v2/hl7v2_stores_test.py
  healthcare/api-client/hl7v2/requirements-test.txt
Labels: automerge, cla: yes

#3272 Changing data labelling ownership to Steve
  .github/CODEOWNERS
Labels: automerge, cla: yes

#2728 re-write authoring guide, add links to other documentation
  AUTHORING_GUIDE.md
Labels: cla: yes

#3102 Adds example parameters
  iot/api-client/manager/manager.py
Labels: cla: yes

#3231 [storage] feat: add post policy sample
  storage/cloud-client/requirements.txt
  storage/cloud-client/snippets_test.py
  storage/cloud-client/storage_generate_signed_post_policy_v4.py
Labels: automerge, cla: yes

#3255 Remove oauth2client from IoT and Functions samples
  functions/billing/main.py
  functions/billing/requirements.txt
  functions/slack/requirements.txt
  iot/api-client/end_to_end_example/cloudiot_pubsub_example_server.py
  iot/api-client/end_to_end_example/requirements.txt
  iot/api-client/manager/requirements.txt
Labels: cla: yes

#3280 appengine/flexible/pubsub: init publisher client globally
  appengine/flexible/pubsub/main.py
Labels: cla: yes

#3288 [datalabeling] testing: mark some tests as flaky
  datalabeling/manage_dataset_test.py
  datalabeling/requirements-test.txt
Labels: cla: yes

#3285 [monitoring] fix: use retrying module in the fixture class
  monitoring/api/v3/alerts-client/requirements-test.txt
  monitoring/api/v3/alerts-client/snippets_test.py
Labels: cla: yes

#3287 [oslogin] fix: add retry around ssh test
  compute/oslogin/requirements-test.txt
  compute/oslogin/service_account_ssh_test.py
Labels: cla: yes

#3268 [kms] fix flaky test
  kms/api-client/requirements-test.txt
  kms/api-client/snippets_test.py
Labels: cla: yes

#3278 [jobs] testing: reduce test flakiness
  jobs/v3/api_client/auto_complete_sample.py
  jobs/v3/api_client/auto_complete_sample_test.py
  jobs/v3/api_client/commute_search_sample.py
  jobs/v3/api_client/commute_search_sample_test.py
  jobs/v3/api_client/custom_attribute_sample.py
  jobs/v3/api_client/custom_attribute_sample_test.py
  jobs/v3/api_client/email_alert_search_sample.py
  jobs/v3/api_client/email_alert_search_sample_test.py
  jobs/v3/api_client/featured_job_search_sample.py
  jobs/v3/api_client/featured_job_search_sample_test.py
  jobs/v3/api_client/general_search_sample.py
  jobs/v3/api_client/general_search_sample_test.py
  jobs/v3/api_client/histogram_sample.py
  jobs/v3/api_client/histogram_sample_test.py
  jobs/v3/api_client/location_search_sample.py
  jobs/v3/api_client/location_search_sample_test.py
  jobs/v3/api_client/requirements-test.txt
Labels: cla: yes

#3235 video: fix flaky beta tests
  video/cloud-client/analyze/analyze_test.py
  video/cloud-client/analyze/beta_snippets_test.py
  video/cloud-client/analyze/video_detect_logo_beta_test.py
  video/cloud-client/analyze/video_detect_logo_gcs_beta_test.py
Labels: cla: yes

#3293 [iam] fix: reduce flakiness
  iam/api-client/access_test.py
  iam/api-client/requirements-test.txt
Labels: cla: yes

#3295 [firestore] fix: mark 3 tests as flaky
  firestore/cloud-client/requirements-test.txt
  firestore/cloud-client/snippets_test.py
Labels: cla: yes

#3299 [iot] fix: mitigate flaky tests
  iot/api-client/manager/manager_test.py
Labels: cla: yes

#3297 [iot] fix: use uuid instead of time for resource name
  iot/api-client/gcs_file_to_device/gcs_send_to_device_test.py
Labels: cla: yes

#3277 Add GCF bearer token sample
  functions/security/main.py
  functions/security/main_test.py
Labels: automerge, cla: yes

#3312 GCF: Add Pub/Sub publisher sample
  functions/pubsub/main.py
  functions/pubsub/main_test.py
  functions/pubsub/requirements.txt
Labels: cla: yes

#3311 [monitoring] testing: mitigate 409 conflicts
  monitoring/api/v3/alerts-client/requirements-test.txt
  monitoring/api/v3/alerts-client/snippets_test.py
Labels: cla: yes, kokoro:force-run

#3097 fix: updated the app engine std pub/sub sample
  appengine/standard/pubsub/main.py
Labels: cla: yes

#3291 [iam] fix: reuse the same custom role for read/update tests
  iam/api-client/custom_roles_test.py
Labels: cla: yes

#2921 Added config for using Memorystore (Redis) with App Engine standard P…
  memorystore/redis/gae_standard_py2_deployment/app.yaml
  memorystore/redis/gae_standard_py2_deployment/appengine_config.py
  memorystore/redis/gae_standard_py2_deployment/requirements_py2.txt
Labels: automerge, cla: yes

#3303 add clarifying language to contributing.md
  CONTRIBUTING.md
Labels: automerge, cla: yes

#3338 add Takashi to blunderbuss
  .github/blunderbuss.yml
Labels: automerge, cla: yes

#3325 remove flaky from blog/
  blog/introduction_to_data_models_in_cloud_datastore/blog_test.py
  blog/introduction_to_data_models_in_cloud_datastore/requirements-test.txt
  blog/introduction_to_data_models_in_cloud_datastore/wiki_test.py
Labels: automerge, cla: yes

#3331 switch to regular flaky in jobs
  jobs/v3/api_client/quickstart_test.py
  jobs/v3/api_client/requirements-test.txt
Labels: cla: yes

#3326 switch to regular flaky in compute
  compute/api/create_instance_test.py
  compute/api/requirements-test.txt
Labels: automerge, cla: yes

#3324 GCF CI/CD: add cloudbuild.yaml
  functions/ci_cd/cloudbuild.yaml
Labels: automerge, cla: yes

#3334 switch to regular flaky in storage
  storage/api/customer_supplied_keys_test.py
  storage/api/requirements-test.txt
Labels: cla: yes

#3332 switch to regular flaky in ml_engine
  ml_engine/online_prediction/predict_test.py
  ml_engine/online_prediction/requirements-test.txt
Labels: cla: yes

#3329 switch to regular flaky in dns
  dns/api/main_test.py
  dns/api/requirements-test.txt
Labels: cla: yes

#3330 switch to regular flaky in iap
  iap/iap_test.py
  iap/requirements-test.txt
Labels: cla: yes

#3333 switch to regular flaky in monitoring
  monitoring/api/v3/api-client/custom_metric_test.py
  monitoring/api/v3/api-client/list_resources_test.py
Labels: cla: yes

#3327 switch to regular flaky in datastore
  datastore/cloud-client/snippets_test.py
  datastore/cloud-client/tasks_test.py
Labels: cla: yes

#3078 Remove Language sample unused region_tag comments
  language/classify_text/classify_text_tutorial.py
Labels: automerge, cla: yes

#3335 Update dependency google-cloud-pubsub to v1.4.2
  appengine/flexible/pubsub/requirements.txt
  appengine/standard_python37/pubsub/requirements.txt
Labels: cla: yes

#3399 update flask in iap
  iap/app_engine_app/requirements.txt
  iap/requirements.txt
Labels: cla: yes

#3396 update flask in datastore
  datastore/cloud-ndb/requirements.txt
Labels: automerge, cla: yes

#3398 update flask in functions
  functions/helloworld/requirements.txt
  functions/slack/requirements.txt
Labels: automerge, cla: yes

#3404 update flask in trace
  trace/cloud-trace-demo-app/app/requirements.txt
  trace/trace-python-sample/requirements.txt
Labels: automerge, cla: yes

#3400 update flask in memorystore
  memorystore/redis/requirements.txt
Labels: automerge, cla: yes

#3395 update flask in compute
  compute/managed-instances/demo/requirements.txt
  compute/xmpp_wikibot/requirements.txt
Labels: automerge, cla: yes

#3403 update flask in scheduler
  scheduler/requirements.txt
Labels: cla: yes

#3389 update to Flask 1.1.2 in appengine flex
  appengine/flexible/analytics/requirements.txt
  appengine/flexible/cloudsql/requirements.txt
  appengine/flexible/cloudsql_postgresql/requirements.txt
  appengine/flexible/datastore/requirements.txt
  appengine/flexible/disk/requirements.txt
  appengine/flexible/extending_runtime/requirements.txt
  appengine/flexible/hello_world/requirements.txt
  appengine/flexible/mailgun/requirements.txt
  appengine/flexible/mailjet/requirements.txt
  appengine/flexible/memcache/requirements.txt
  appengine/flexible/metadata/requirements.txt
  appengine/flexible/multiple_services/gateway-service/requirements.txt
  appengine/flexible/multiple_services/static-service/requirements.txt
  appengine/flexible/numpy/requirements.txt
  appengine/flexible/pubsub/requirements.txt
  appengine/flexible/redis/requirements.txt
  appengine/flexible/scipy/requirements.txt
  appengine/flexible/sendgrid/requirements.txt
  appengine/flexible/static_files/requirements.txt
  appengine/flexible/storage/requirements.txt
  appengine/flexible/tasks/requirements.txt
  appengine/flexible/twilio/requirements.txt
  appengine/flexible/websockets/requirements.txt
Labels: cla: yes

#3402 update flask in run
  run/hello-broken/requirements.txt
  run/image-processing/requirements.txt
  run/logging-manual/requirements.txt
  run/pubsub/requirements.txt
  run/system-package/requirements.txt
Labels: cla: yes

#3401 update flask in profiler
  profiler/appengine/flexible/requirements.txt
  profiler/appengine/standard_python37/requirements.txt
Labels: automerge, cla: yes

#3397 update flask in endpoints
  endpoints/getting-started/requirements.txt
Labels: automerge, cla: yes

#3394 update flask in codelabs
  codelabs/flex_and_vision/requirements.txt
Labels: automerge, cla: yes

#3391 update flask version in appengine standard 3.7
  appengine/standard_python37/bigquery/requirements.txt
  appengine/standard_python37/building-an-app/building-an-app-1/requirements.txt
  appengine/standard_python37/building-an-app/building-an-app-2/requirements.txt
  appengine/standard_python37/building-an-app/building-an-app-3/requirements.txt
  appengine/standard_python37/building-an-app/building-an-app-4/requirements.txt
  appengine/standard_python37/cloud_debugger/requirements.txt
  appengine/standard_python37/cloudsql/requirements.txt
  appengine/standard_python37/custom-server/requirements.txt
  appengine/standard_python37/hello_world/requirements.txt
  appengine/standard_python37/pubsub/requirements.txt
  appengine/standard_python37/redis/requirements.txt
  appengine/standard_python37/spanner/requirements.txt
  appengine/standard_python37/warmup/requirements.txt
Labels: automerge, cla: yes

#3393 update flask in cloud-sql
  cloud-sql/mysql/sqlalchemy/requirements.txt
  cloud-sql/postgres/sqlalchemy/requirements.txt
Labels: automerge, cla: yes

#3383 vision: increase timeout for tests
  vision/cloud-client/product_search/product_in_product_set_management.py
  vision/cloud-client/product_search/product_management.py
  vision/cloud-client/product_search/product_search_test.py
  vision/cloud-client/product_search/requirements-test.txt
Labels: automerge, cla: yes

#3390 appengine standard up flask version
  appengine/standard/analytics/requirements.txt
  appengine/standard/firebase/firenotes/backend/requirements.txt
  appengine/standard/firebase/firetactoe/requirements.txt
  appengine/standard/flask/tutorial/requirements.txt
  appengine/standard/iap/requirements.txt
  appengine/standard/mailjet/requirements.txt
  appengine/standard/ndb/transactions/requirements.txt
  appengine/standard/pubsub/requirements.txt
  appengine/standard/urlfetch/requests/requirements.txt
Labels: automerge, cla: yes

#3392 update flask in auth
  auth/end-user/web/requirements.txt
Labels: automerge, cla: yes

#3386 translate: make test generic
  translate/cloud-client/quickstart_test.py
Labels: automerge, cla: yes

#3284 fix: add mains to samples
  dataproc/create_cluster.py
  dataproc/create_cluster_test.py
  dataproc/instantiate_inline_workflow_template.py
  dataproc/quickstart/quickstart_test.py
Labels: automerge, cla: yes

#3135 Add sample for connecting to SQL Server with SQLAlchemy/pyodbc
  cloud-sql/sql-server/sqlalchemy/.gcloudignore
  cloud-sql/sql-server/sqlalchemy/.gitignore
  cloud-sql/sql-server/sqlalchemy/Dockerfile
  cloud-sql/sql-server/sqlalchemy/README.md
  cloud-sql/sql-server/sqlalchemy/app.yaml
  cloud-sql/sql-server/sqlalchemy/main.py
  cloud-sql/sql-server/sqlalchemy/requirements-test.txt
  cloud-sql/sql-server/sqlalchemy/requirements.txt
  cloud-sql/sql-server/sqlalchemy/templates/index.html
Labels: cla: yes

#3336 Update dependency google-cloud-pubsub to v1.4.2
  asset/cloud-client/requirements.txt
Labels: cla: yes

#3300 healthcare API: update v1beta1 datasets samples to v1
  healthcare/api-client/v1/datasets/README.rst
  healthcare/api-client/v1/datasets/README.rst.in
  healthcare/api-client/v1/datasets/datasets.py
  healthcare/api-client/v1/datasets/datasets_test.py
  healthcare/api-client/v1/datasets/requirements-test.txt
  healthcare/api-client/v1/datasets/requirements.txt
Labels: cla: yes

#3286 feat: adds 'single_utterance' to media translation sample
  media-translation/cloud-client/requirements-test.txt
  media-translation/cloud-client/translate_from_file.py
Labels: automerge, cla: yes

#3408 Make firestore get_check_exists method work as intended.
  firestore/cloud-client/snippets.py
Labels: automerge, cla: yes

#3413 testing: bump the timeout for periodic builds
  .kokoro/python3.6/periodic.cfg
  .kokoro/python3.7/periodic.cfg
  .kokoro/python3.8/periodic.cfg
Labels: cla: yes

#3385 video: use flaky on flaky timeouts
  video/cloud-client/analyze/analyze_test.py
  video/cloud-client/analyze/beta_snippets_test.py
  video/cloud-client/analyze/requirements-test.txt
Labels: cla: yes

#3114 vision: delete obsolete beta snippets for logo detection
  video/cloud-client/analyze/video_detect_logo_beta.py
  video/cloud-client/analyze/video_detect_logo_beta_test.py
  video/cloud-client/analyze/video_detect_logo_gcs_beta.py
  video/cloud-client/analyze/video_detect_logo_gcs_beta_test.py
Labels: automerge, cla: yes

#3145 first pass at v1beta2 analyze_form.py
  document/cloud-client/batch_parse_form_beta.py
  document/cloud-client/batch_parse_form_beta_test.py
  document/cloud-client/batch_parse_table_beta.py
  document/cloud-client/batch_parse_table_beta_test.py
  document/cloud-client/parse_form_beta.py
  document/cloud-client/parse_form_beta_test.py
  document/cloud-client/parse_table_beta.py
  document/cloud-client/parse_table_beta_test.py
  document/cloud-client/parse_with_model_beta.py
  document/cloud-client/parse_with_model_beta_test.py
  document/cloud-client/quickstart_beta.py
  document/cloud-client/quickstart_beta_test.py
  document/cloud-client/requirements-test.txt
  document/cloud-client/requirements.txt
  document/cloud-client/set_endpoint_beta.py
  document/cloud-client/set_endpoint_beta_test.py
Labels: automerge, cla: yes

#3388 healthcare API: update all HL7v2 v1beta1 samples to v1
  healthcare/api-client/v1/hl7v2/README.rst
  healthcare/api-client/v1/hl7v2/README.rst.in
  healthcare/api-client/v1/hl7v2/hl7v2_messages.py
  healthcare/api-client/v1/hl7v2/hl7v2_messages_test.py
  healthcare/api-client/v1/hl7v2/hl7v2_stores.py
  healthcare/api-client/v1/hl7v2/hl7v2_stores_test.py
  healthcare/api-client/v1/hl7v2/requirements-test.txt
  healthcare/api-client/v1/hl7v2/requirements.txt
  healthcare/api-client/v1/hl7v2/resources/hl7-sample-ingest.json
Labels: cla: yes

#3425 [iot] testing: re-raise the exception
  iot/api-client/manager/manager.py
  iot/api-client/manager/manager_test.py
Labels: cla: yes

#3420 [dlp] fix: fix periodic builds timeout
  dlp/inspect_content.py
  dlp/inspect_content_test.py
  dlp/jobs_test.py
  dlp/requirements-test.txt
  dlp/risk.py
  dlp/risk_test.py
Labels: cla: yes

#3427 Delete unused SQL samples
  functions/sql/mysql_sample.py
  functions/sql/mysql_test.py
  functions/sql/postgres_sample.py
  functions/sql/postgres_test.py
  functions/sql/requirements-test.txt
  functions/sql/requirements.txt
Labels: automerge, cla: yes

#3426 fix: address issues with concurrent BigQuery tests
  bigquery/cloud-client/authorized_view_tutorial.py
  bigquery/cloud-client/authorized_view_tutorial_test.py
  bigquery/cloud-client/natality_tutorial.py
  bigquery/cloud-client/natality_tutorial_test.py
  bigquery/cloud-client/quickstart.py
  bigquery/cloud-client/quickstart_test.py
Labels: cla: yes

#3264 Schedule datastore export
  datastore/schedule-export/README.md
  datastore/schedule-export/main.py
  datastore/schedule-export/requirements-test.txt
  datastore/schedule-export/requirements.txt
  datastore/schedule-export/schedule_export_test.py
Labels: cla: yes

#3428 [iot] fix: use fixtures for resource setup/teardown
  iot/api-client/mqtt_example/cloudiot_mqtt_example_test.py
  iot/api-client/mqtt_example/cloudiot_mqtt_image.py
  iot/api-client/mqtt_example/cloudiot_mqtt_image_test.py
  iot/api-client/mqtt_example/fixtures.py
  iot/api-client/mqtt_example/requirements-test.txt
Labels: cla: yes

#3434 [healthcare] fix: retry eventually consistent tests
  healthcare/api-client/v1/hl7v2/hl7v2_messages_test.py
  healthcare/api-client/v1/hl7v2/hl7v2_stores_test.py
  healthcare/api-client/v1/hl7v2/requirements-test.txt
Labels: cla: yes

#3447 [vision] fix: longer timeout
  vision/cloud-client/detect/detect.py
  vision/cloud-client/detect/detect_test.py
  vision/cloud-client/detect/requirements-test.txt
Labels: cla: yes

#3448 [datastore] fix: handle datastore eventual consistency
  datastore/cloud-ndb/flask_app_test.py
  datastore/cloud-ndb/quickstart_test.py
  datastore/cloud-ndb/requirements-test.txt
Labels: cla: yes

#3449 [compute] fix: always use a new uuid
  compute/api/create_instance_test.py
Labels: cla: yes

#3446 [video] testing: mark some tests witih flaky
  video/cloud-client/analyze/analyze_test.py
  video/cloud-client/analyze/beta_snippets_test.py
  video/cloud-client/analyze/video_detect_faces_beta_test.py
  video/cloud-client/analyze/video_detect_faces_gcs_beta_test.py
  video/cloud-client/analyze/video_detect_logo_gcs_test.py
  video/cloud-client/analyze/video_detect_logo_test.py
  video/cloud-client/analyze/video_detect_person_beta_test.py
  video/cloud-client/analyze/video_detect_person_gcs_beta_test.py
Labels: cla: yes

#3437 [firestore] fix: fix flaky tests
  firestore/cloud-client/snippets.py
Labels: cla: yes

#3407 add api_config_anthos.yaml
  endpoints/bookstore-grpc/api_config_anthos.yaml
Labels: cla: yes

#3458 fix: import from googleapiclient, not apiclient
  functions/slack/main.py
  functions/slack/main_test.py
  third_party/apache-airflow/plugins/gcs_plugin/hooks/gcs_hook.py
Labels: automerge, cla: yes

#3387 healthcare API: update all DICOM v1beta1 samples to v1
  healthcare/api-client/v1/dicom/README.rst
  healthcare/api-client/v1/dicom/README.rst.in
  healthcare/api-client/v1/dicom/dicom_stores.py
  healthcare/api-client/v1/dicom/dicom_stores_test.py
  healthcare/api-client/v1/dicom/dicomweb.py
  healthcare/api-client/v1/dicom/dicomweb_test.py
  healthcare/api-client/v1/dicom/requirements-test.txt
  healthcare/api-client/v1/dicom/requirements.txt
  healthcare/api-client/v1/dicom/resources/dicom_00000001_000.dcm
Labels: cla: yes

#3436 [container_registry] fix: fix broken test
  container_registry/container_analysis/samples_test.py
Labels: cla: yes

#3340 Update dependency google-cloud-pubsub to v1.4.2 in container and DLP
  container_registry/container_analysis/requirements.txt
  dlp/requirements.txt
Labels: cla: yes

#3342 Update dependency google-cloud-pubsub to v1.4.2 in functions and IoT
  functions/ocr/app/requirements.txt
  functions/pubsub/requirements.txt
  functions/tips/requirements.txt
  iot/api-client/end_to_end_example/requirements.txt
  iot/api-client/gcs_file_to_device/requirements.txt
  iot/api-client/http_example/requirements.txt
  iot/api-client/manager/requirements.txt
  iot/api-client/mqtt_example/requirements.txt
  iot/api-client/scripts/requirements.txt
Labels: cla: yes

#3443 [datalabeling] testing: wrap rpcs with backoff
  datalabeling/create_annotation_spec_set_test.py
  datalabeling/create_instruction.py
  datalabeling/create_instruction_test.py
  datalabeling/import_data_test.py
  datalabeling/label_image_test.py
  datalabeling/label_text_test.py
  datalabeling/label_video_test.py
  datalabeling/manage_dataset_test.py
  datalabeling/requirements-test.txt
  datalabeling/testing_lib.py
Labels: cla: yes

#3319 fix: use `crypto_key_path` instead of `crypto_key_path_path`
  kms/api-client/snippets.py
Labels: automerge, cla: yes

#3469 chore: remove gcp-devrel-py-tools from iam and datastore
  datastore/cloud-client/requirements-test.txt
  datastore/cloud-client/snippets_test.py
  datastore/cloud-client/tasks_test.py
  iam/api-client/requirements-test.txt
Labels: cla: yes

#3474 [appengine] chore: remove gcp-devrel-py-tools
  appengine/standard/analytics/requirements-test.txt
  appengine/standard/appengine_helper.py
  appengine/standard/blobstore/blobreader/requirements-test.txt
  appengine/standard/blobstore/gcs/requirements-test.txt
  appengine/standard/conftest.py
  appengine/standard/django/requirements-test.txt
  appengine/standard/download-appengine-sdk.py
  appengine/standard/endpoints-frameworks-v2/echo/requirements-test.txt
  appengine/standard/endpoints-frameworks-v2/iata/requirements-test.txt
  appengine/standard/endpoints-frameworks-v2/quickstart/requirements-test.txt
  appengine/standard/firebase/firenotes/backend/requirements-test.txt
  appengine/standard/flask/tutorial/requirements-test.txt
  appengine/standard/iap/requirements-test.txt
  appengine/standard/mailgun/requirements-test.txt
  appengine/standard/mailjet/requirements-test.txt
  appengine/standard/ndb/transactions/requirements-test.txt
  appengine/standard/noxfile-template.py
  appengine/standard/pubsub/requirements-test.txt
  appengine/standard/sendgrid/requirements-test.txt
  appengine/standard/storage/api-client/requirements-test.txt
  appengine/standard/storage/appengine-client/requirements-test.txt
  appengine/standard/urlfetch/requests/requirements-test.txt
Labels: cla: yes

#3476 [healthcare] chore: remove gcp-devrel-py-tools
  healthcare/api-client/hl7v2/hl7v2_messages_test.py
  healthcare/api-client/hl7v2/requirements-test.txt
Labels: cla: yes

#3470 chore: remove gcp-devrel-py-tools from iot and pubsub
  iot/api-client/mqtt_example/requirements-test.txt
  iot/api-client/mqtt_example/requirements.txt
  pubsub/cloud-client/publisher_test.py
  pubsub/cloud-client/requirements-test.txt
  pubsub/cloud-client/subscriber_test.py
Labels: cla: yes

#3478 [container analysis] effective severity
  container_registry/container_analysis/samples.py
  container_registry/container_analysis/samples_test.py
Labels: automerge, cla: yes

#3477 [logging] chore: remove gcp-devrel-py-tools
  logging/cloud-client/export_test.py
  logging/cloud-client/requirements-test.txt
  logging/cloud-client/snippets_test.py
Labels: cla: yes

#3384 healthcare API: update all FHIR v1beta1 samples to v1
  healthcare/api-client/v1/fhir/README.rst
  healthcare/api-client/v1/fhir/README.rst.in
  healthcare/api-client/v1/fhir/fhir_resources.py
  healthcare/api-client/v1/fhir/fhir_resources_test.py
  healthcare/api-client/v1/fhir/fhir_stores.py
  healthcare/api-client/v1/fhir/fhir_stores_test.py
  healthcare/api-client/v1/fhir/requirements-test.txt
  healthcare/api-client/v1/fhir/requirements.txt
  healthcare/api-client/v1/fhir/resources/Patient.json
  healthcare/api-client/v1/fhir/resources/execute_bundle.json
Labels: cla: yes

#3414 Correct path for the warmup call
  appengine/standard_python37/warmup/main_test.py
Labels: automerge, cla: yes

#3382 Update Data Catalog samples to V1
  datacatalog/cloud-client/lookup_entry.py
Labels: cla: yes

#3468 [spanner] fix: bump the timeout for instance creation
  spanner/cloud-client/backup_sample_test.py
Labels: cla: yes

#3289 Add progress messages and remove new line from response
  trace/cloud-trace-demo-app/README.md
  trace/cloud-trace-demo-app/app/app.py
  trace/cloud-trace-demo-app/app/demo-service-c.yaml.template
  trace/cloud-trace-demo-app/setup.sh
Labels: automerge, cla: yes

#3479 [kms] chore: remove gcp-devrel-py-tools
  kms/api-client/requirements-test.txt
  kms/api-client/snippets_test.py
Labels: cla: yes

#3475 [jobs] chore: remove gcp-devrel-py-tools
  jobs/v3/api_client/auto_complete_sample_test.py
  jobs/v3/api_client/commute_search_sample_test.py
  jobs/v3/api_client/custom_attribute_sample_test.py
  jobs/v3/api_client/email_alert_search_sample_test.py
  jobs/v3/api_client/featured_job_search_sample_test.py
  jobs/v3/api_client/general_search_sample_test.py
  jobs/v3/api_client/histogram_sample_test.py
  jobs/v3/api_client/location_search_sample_test.py
  jobs/v3/api_client/requirements-test.txt
Labels: cla: yes

#3467 Fix region tag in SQL Server Sample
  cloud-sql/sql-server/sqlalchemy/main.py
Labels: automerge, cla: yes

#3480 [monitoring] chore: remove gcp-devrel-py-tools
  monitoring/api/v3/api-client/custom_metric_test.py
  monitoring/api/v3/api-client/requirements-test.txt
  monitoring/api/v3/cloud-client/quickstart_test.py
  monitoring/api/v3/cloud-client/requirements-test.txt
  monitoring/api/v3/cloud-client/snippets_test.py
Labels: cla: yes

#3444 update iap to use google-auth for id_token
  iap/make_iap_request.py
  iap/requirements.txt
  iap/validate_jwt.py
Labels: cla: yes

#3484 [appengine] chore: remove gcp-devrel-py-tools
  appengine/standard/firebase/firetactoe/requirements-test.txt
Labels: automerge, cla: yes

#3493 [compute] fix: use unique disk name
  compute/encryption/generate_wrapped_rsa_key_test.py
Labels: cla: yes

#3249 dialogflow: remove unused samples + tests
  dialogflow/cloud-client/context_management.py
  dialogflow/cloud-client/context_management_test.py
  dialogflow/cloud-client/create_entity_test.py
  dialogflow/cloud-client/create_entity_type_test.py
  dialogflow/cloud-client/delete_document_test.py
  dialogflow/cloud-client/delete_entity_test.py
  dialogflow/cloud-client/delete_entity_type_test.py
  dialogflow/cloud-client/delete_knowledge_base_test.py
  dialogflow/cloud-client/detect_intent_with_model_selection.py
  dialogflow/cloud-client/detect_intent_with_model_selection_test.py
  dialogflow/cloud-client/document_management.py
  dialogflow/cloud-client/entity_management.py
  dialogflow/cloud-client/entity_type_management.py
  dialogflow/cloud-client/get_document_test.py
  dialogflow/cloud-client/get_knowledge_base_test.py
  dialogflow/cloud-client/knowledge_base_management.py
  dialogflow/cloud-client/list_documents_test.py
  dialogflow/cloud-client/list_entities_test.py
  dialogflow/cloud-client/list_entity_types_test.py
  dialogflow/cloud-client/list_knowledge_bases_test.py
  dialogflow/cloud-client/session_entity_type_management.py
  dialogflow/cloud-client/session_entity_type_management_test.py
Labels: cla: yes

#3481 use GRPC_SERVICE in endpoints/bookstore-grpc/api_config_anthos.yaml
  endpoints/bookstore-grpc/api_config_anthos.yaml
Labels: automerge, cla: yes

#3489 [codelabs] fix: use unique filename for photo upload
  codelabs/flex_and_vision/main_test.py
Labels: cla: yes

#3487 Revert "testing: bump the timeout for periodic builds"
  .kokoro/python3.6/periodic.cfg
  .kokoro/python3.7/periodic.cfg
  .kokoro/python3.8/periodic.cfg
Labels: cla: yes

#3423 remove samples/tests that aren't on devsite, incl. localized docs
  language/automl/automl_natural_language_dataset.py
  language/automl/automl_natural_language_model.py
  language/automl/automl_natural_language_predict.py
  language/automl/dataset_test.py
  language/automl/model_test.py
  language/automl/predict_test.py
Labels: cla: yes

#3492 [automl] fix: retry vision_object_detection_predict.predict
  automl/cloud-client/requirements-test.txt
  automl/cloud-client/vision_object_detection_predict_test.py
Labels: cla: yes

#3494 [bigtable] fix: wrap sample invocations with retries
  bigtable/snippets/writes/requirements-test.txt
  bigtable/snippets/writes/writes_test.py
  testing/test-env.tmpl.sh
Labels: cla: yes

#3343 Update dependency google-cloud-pubsub to v1.4.2 in Storage and Pub/Sub
  pubsub/cloud-client/requirements.txt
  storage/cloud-client/notification_polling_test.py
  storage/cloud-client/requirements.txt
Labels: cla: yes

#3495 [translate] fix: mark some tests as flaky
  translate/cloud-client/beta_snippets_test.py
  translate/cloud-client/requirements-test.txt
Labels: cla: yes

#3551 docs: Add few examples for uuid.
  AUTHORING_GUIDE.md
Labels: cla: yes

#3496 testing: replace @flaky with @pytest.mark.flaky
  blog/introduction_to_data_models_in_cloud_datastore/blog_test.py
  blog/introduction_to_data_models_in_cloud_datastore/wiki_test.py
  dns/api/main_test.py
  iap/iap_test.py
  jobs/v3/api_client/quickstart_test.py
  ml_engine/online_prediction/predict_test.py
  monitoring/api/v3/api-client/list_resources_test.py
  storage/api/customer_supplied_keys_test.py
  translate/cloud-client/translate_v3_batch_translate_text_test.py
  translate/cloud-client/translate_v3_batch_translate_text_with_glossary_test.py
  translate/cloud-client/translate_v3_create_glossary_test.py
  translate/cloud-client/translate_v3_delete_glossary_test.py
  vision/cloud-client/product_search/product_search_test.py
Labels: cla: yes

#3553 docs: add a note about infinite loops
  AUTHORING_GUIDE.md
Labels: cla: yes

#3488 [spanner] fix: set timeout for polling on operations
  spanner/cloud-client/backup_sample.py
  spanner/cloud-client/snippets.py
Labels: cla: yes

#3429 GCF: add multipart file-persistence note
  functions/http/main.py
Labels: automerge, cla: yes

#3562 docs: correct a wrong filename
  AUTHORING_GUIDE.md
Labels: cla: yes

#3563 [kms] fix: use unique ids for test
  kms/api-client/snippets_test.py
Labels: cla: yes

#3565 [iam] fix: use uuid4's first part for test
  iam/api-client/service_accounts_test.py
Labels: cla: yes

#3552 minor change so tutorial matches codelab
  composer/workflows/hadoop_tutorial.py
Labels: automerge, cla: yes

#3570 docs: add a section about retry
  AUTHORING_GUIDE.md
Labels: cla: yes

#3498 fix: use DELETE FROM for consistency
  spanner/cloud-client/snippets.py
Labels: api: spanner, cla: yes

#3564 functions/slack: use env vars + consistent var naming
  functions/slack/main.py
  functions/slack/main_test.py
  testing/secrets.tar.enc
Labels: cla: yes

#3569 Remove name attribute from the input
  storage/cloud-client/storage_generate_signed_post_policy_v4.py
Labels: automerge, cla: yes

#3568 [storage] fix: use unique blob name
  storage/cloud-client/encryption_test.py
Labels: automerge, cla: yes

#3379 Add example of mounting secret as a volume in Google Composer.
  composer/workflows/kubernetes_pod_operator.py
Labels: cla: yes

#3281 cdn: add sign_cookie example with tests
  .github/CODEOWNERS
  cdn/snippets.py
  cdn/snippets_test.py
Labels: cla: yes

#3655 [storage] fix: use a different bucket for requester_pays_test
  scripts/decrypt-secrets.sh
  scripts/encrypt-secrets.sh
  storage/cloud-client/README.md
  storage/cloud-client/requester_pays_test.py
  testing/secrets.tar.enc
  testing/test-env.tmpl.sh
Labels: cla: yes
