Repository GoogleCloudPlatform/python-docs-samples, pull requests merged in 2020-03, with the labels that each got.

#2914 Translate: migrate published v3 translate batch samples
  translate/automl/requirements.txt
  translate/automl/translate_v3_batch_translate_text_with_model.py
  translate/automl/translate_v3_batch_translate_text_with_model_test.py
  translate/cloud-client/translate_v3_batch_translate_text.py
  translate/cloud-client/translate_v3_batch_translate_text_test.py
  translate/cloud-client/translate_v3_batch_translate_text_with_glossary.py
  translate/cloud-client/translate_v3_batch_translate_text_with_glossary_test.py
Labels: automerge, cla: yes

#3022 remove python 3.5 config
  .kokoro/python3.5/common.cfg
  .kokoro/python3.5/continuous.cfg
  .kokoro/python3.5/periodic.cfg
  .kokoro/python3.5/presubmit.cfg
  AUTHORING_GUIDE.md
  noxfile-template.py
Labels: cla: yes

#3026 Pin django to a specific version
  appengine/standard/django/requirements.txt
Labels: cla: yes

#3025 splitting up #2651 part 1/3 - dataproc + endpoints
  dataproc/requirements.txt
  endpoints/bookstore-grpc-transcoding/requirements.txt
  endpoints/bookstore-grpc/requirements.txt
Labels: cla: yes

#3029 fix: Use unique resources for storage snippets.
  storage/cloud-client/acl_test.py
  storage/cloud-client/bucket_lock_test.py
  storage/cloud-client/snippets_test.py
Labels: cla: yes

#3024 make all run files py3 only
  noxfile-template.py
Labels: cla: yes

#3038 temporarily sub in cameron as codeowner
  .github/CODEOWNERS
Labels: cla: yes

#2835 fix: vision automl - delete unused files that have moved
  vision/automl/automl_vision_object_detection_deploy_model.py
  vision/automl/automl_vision_object_detection_deploy_node_count.py
  vision/automl/automl_vision_object_detection_test.py
  vision/automl/automl_vision_object_detection_undeploy_model.py
Labels: automerge, cla: yes

#3037 fix: Reuse HMAC key as we have a limit of 5
  storage/cloud-client/hmac_samples_test.py
Labels: cla: yes

#3039 fix: harden storage test fixtures
  storage/cloud-client/iam_test.py
  storage/cloud-client/uniform_bucket_level_access_test.py
Labels: cla: yes

#3027 splitting up #2651 part 3/3 - bigquery
  bigquery/datalab-migration/requirements.txt
Labels: cla: yes

#3051 Replace deprecated renovate command
  renovate.json
Labels: cla: yes

#3008 storage: Fix docs for signed URL generation
  storage/cloud-client/storage_generate_upload_signed_url_v4.py
Labels: cla: yes

#3057 automl: fix batch test due to error message change
  automl/cloud-client/batch_predict_test.py
Labels: cla: yes

#3062 updating owners for ML APIs / AutoML
  .github/CODEOWNERS
Labels: cla: yes

#3061 fix: wait up to 20 seconds for blob to appear
  video/cloud-client/analyze/beta_snippets_test.py
Labels: automerge, cla: yes

#3058 Fix dlp tests
  dlp/inspect_content.py
  dlp/inspect_content_test.py
  dlp/requirements.txt
Labels: automerge, cla: yes

#3043 automl: move video object tracking samples out of branch
  automl/beta/video_object_tracking_create_dataset.py
  automl/beta/video_object_tracking_create_dataset_test.py
  automl/beta/video_object_tracking_create_model.py
  automl/beta/video_object_tracking_create_model_test.py
Labels: automerge, cla: yes

#3068 Iot flaky tests
  iot/api-client/manager/manager_test.py
  iot/api-client/manager/requirements.txt
  iot/api-client/mqtt_example/cloudiot_mqtt_example_test.py
  iot/api-client/mqtt_example/cloudiot_mqtt_image_test.py
Labels: cla: yes, do not merge

#3067 fix: create fixture with random file name for test
  storage/api/crud_object_test.py
Labels: automerge, cla: yes

#3075 Remove unused region_tag comment.
  language/generated-samples/v1/language_sentiment_text.py
Labels: automerge, cla: yes

#3074 Remove Natural Language samples not included docs.
  language/cloud-client/v1/README.rst
  language/cloud-client/v1/README.rst.in
  language/cloud-client/v1/snippets.py
  language/cloud-client/v1/snippets_test.py
Labels: automerge, cla: yes

#3071 Clarifying comment for batch requests
  vision/cloud-client/detect/vision_async_batch_annotate_images.py
Labels: automerge, cla: yes

#3088 Update analyze.py
  video/cloud-client/analyze/analyze.py
Labels: cla: yes

#2750 automl: video beta - move beta samples out of branch and into master
  automl/beta/batch_predict.py
  automl/beta/batch_predict_test.py
  automl/beta/video_classification_create_dataset.py
  automl/beta/video_classification_create_dataset_test.py
  automl/beta/video_classification_create_model.py
  automl/beta/video_classification_create_model_test.py
Labels: automerge, cla: yes

#3090 vision: remove redundant flaky web test
  vision/cloud-client/web/web_detect_test.py
Labels: automerge, cla: yes

#3091 vision: fix flaky test
  vision/cloud-client/detect/detect_test.py
Labels: automerge, cla: yes

#3087 translate: fix tests
  translate/cloud-client/hybrid_glossaries/resources/example.mp3
  translate/cloud-client/translate_v3_batch_translate_text.py
  translate/cloud-client/translate_v3_batch_translate_text_test.py
  translate/cloud-client/translate_v3_batch_translate_text_with_glossary.py
  translate/cloud-client/translate_v3_batch_translate_text_with_glossary_test.py
  translate/cloud-client/translate_v3_create_glossary.py
  translate/cloud-client/translate_v3_create_glossary_test.py
  translate/cloud-client/translate_v3_delete_glossary.py
  translate/cloud-client/translate_v3_delete_glossary_test.py
Labels: automerge, cla: yes

#2707 bigtable: read and filter snippets
  bigtable/snippets/filters/filter_snippets.py
  bigtable/snippets/filters/filters_test.py
  bigtable/snippets/filters/requirements.txt
  bigtable/snippets/filters/snapshots/__init__.py
  bigtable/snippets/filters/snapshots/snap_filters_test.py
  bigtable/snippets/reads/read_snippets.py
  bigtable/snippets/reads/reads_test.py
  bigtable/snippets/reads/requirements.txt
  bigtable/snippets/reads/snapshots/__init__.py
  bigtable/snippets/reads/snapshots/snap_reads_test.py
Labels: cla: yes

#3045 automl: move samples to beta set
  automl/beta/get_model_evaluation.py
  automl/beta/get_operation_status.py
  automl/beta/get_operation_status_test.py
  automl/beta/import_dataset.py
  automl/beta/import_dataset_test.py
  automl/beta/list_datasets.py
  automl/beta/list_datasets_test.py
Labels: automerge, cla: yes

#3089 langauge: fix old automl tests
  language/automl/dataset_test.py
Labels: cla: yes

#3096 fix: update app engine standard mail sample to use the correct addres…
  appengine/standard/mail/attachment.py
  appengine/standard/mail/header.py
  appengine/standard/mail/send_mail.py
  appengine/standard/mail/send_message.py
  appengine/standard/mail/user_signup.py
Labels: cla: yes

#3065 SecretManager update v1beta1->v1
  secretmanager/api-client/access_secret_version.py
  secretmanager/api-client/add_secret_version.py
  secretmanager/api-client/create_secret.py
  secretmanager/api-client/delete_secret.py
  secretmanager/api-client/destroy_secret_version.py
  secretmanager/api-client/disable_secret_version.py
  secretmanager/api-client/enable_secret_version.py
  secretmanager/api-client/get_secret.py
  secretmanager/api-client/get_secret_version.py
  secretmanager/api-client/iam_grant_access.py
  secretmanager/api-client/iam_revoke_access.py
  secretmanager/api-client/list_secret_versions.py
  secretmanager/api-client/list_secrets.py
  secretmanager/api-client/quickstart.py
  secretmanager/api-client/requirements.txt
  secretmanager/api-client/snippets_test.py
  secretmanager/api-client/update_secret.py
Labels: automerge, cla: yes

#3109 Remove deprecated api samples
  jobs/v2/api_client/README.rst
  jobs/v2/api_client/README.rst.in
  jobs/v2/api_client/auto_complete_sample.py
  jobs/v2/api_client/auto_complete_sample_test.py
  jobs/v2/api_client/base_company_sample.py
  jobs/v2/api_client/base_company_sample_test.py
  jobs/v2/api_client/base_job_sample.py
  jobs/v2/api_client/base_job_sample_test.py
  jobs/v2/api_client/batch_operation_sample.py
  jobs/v2/api_client/batch_operation_sample_test.py
  jobs/v2/api_client/commute_search_sample.py
  jobs/v2/api_client/commute_search_sample_test.py
  jobs/v2/api_client/custom_attribute_sample.py
  jobs/v2/api_client/custom_attribute_sample_test.py
  jobs/v2/api_client/email_alert_search_sample.py
  jobs/v2/api_client/email_alert_search_sample_test.py
  jobs/v2/api_client/featured_job_search_sample.py
  jobs/v2/api_client/featured_job_search_sample_test.py
  jobs/v2/api_client/general_search_sample.py
  jobs/v2/api_client/general_search_sample_test.py
  jobs/v2/api_client/histogram_sample.py
  jobs/v2/api_client/histogram_sample_test.py
  jobs/v2/api_client/location_search_sample.py
  jobs/v2/api_client/location_search_sample_test.py
  jobs/v2/api_client/quickstart.py
  jobs/v2/api_client/quickstart_test.py
  jobs/v2/api_client/requirements.txt
Labels: cla: yes

#2753 automl: video beta samples move from branch to master
  automl/beta/delete_dataset.py
  automl/beta/delete_dataset_test.py
  automl/beta/import_dataset.py
  automl/beta/list_datasets.py
Labels: automerge, cla: yes

#3093 spanner: add query options versioning samples
  spanner/cloud-client/requirements.txt
  spanner/cloud-client/snippets.py
  spanner/cloud-client/snippets_test.py
Labels: api: spanner, cla: yes

#2918 datalabeling: ensure all tests use test endpoint
  datalabeling/create_instruction.py
  datalabeling/label_text.py
  datalabeling/label_text_test.py
  datalabeling/manage_dataset.py
Labels: automerge, cla: yes, status: investigating

#3044 automl: move samples into beta set
  automl/beta/batch_predict.py
  automl/beta/delete_dataset.py
  automl/beta/delete_dataset_test.py
Labels: cla: yes

#3107 feat: add remove conditional binding sample
  storage/cloud-client/iam_test.py
  storage/cloud-client/storage_remove_bucket_conditional_iam_binding.py
Labels: automerge, cla: yes

#3098 video: adding GA samples for logo detection
  video/cloud-client/analyze/analyze.py
  video/cloud-client/analyze/analyze_test.py
  video/cloud-client/analyze/beta_snippets.py
  video/cloud-client/analyze/beta_snippets_test.py
  video/cloud-client/analyze/requirements.txt
  video/cloud-client/analyze/video_detect_faces_beta.py
  video/cloud-client/analyze/video_detect_faces_gcs_beta.py
  video/cloud-client/analyze/video_detect_logo.py
  video/cloud-client/analyze/video_detect_logo_gcs.py
  video/cloud-client/analyze/video_detect_logo_gcs_test.py
  video/cloud-client/analyze/video_detect_logo_test.py
  video/cloud-client/analyze/video_detect_person_beta.py
  video/cloud-client/analyze/video_detect_person_gcs_beta.py
Labels: automerge, cla: yes

#3128 Correct book title by Neal Stephenson
  endpoints/bookstore-grpc-transcoding/bookstore_server.py
  endpoints/bookstore-grpc/bookstore_server.py
Labels: cla: yes

#3126 Bumped Django to resolve CVE-2020-7471
  kubernetes_engine/django_tutorial/requirements.txt
Labels: automerge, cla: yes

#3118 Pub/Sub: add SubscriberClient.close() to examples
  pubsub/cloud-client/iam.py
  pubsub/cloud-client/iam_test.py
  pubsub/cloud-client/quickstart/sub.py
  pubsub/cloud-client/quickstart/sub_test.py
  pubsub/cloud-client/requirements.txt
  pubsub/cloud-client/subscriber.py
  pubsub/cloud-client/subscriber_test.py
Labels: cla: yes

#3056 feat: added dataproc workflows samples
  dataproc/instantiate_inline_workflow_template.py
  dataproc/instantiate_inline_workflow_template_test.py
Labels: automerge, cla: yes

#3103 bigtable/metricscaler: Add Dockerfile
  bigtable/metricscaler/Dockerfile
Labels: cla: yes

#3137 Pub/Sub: update publish with batch settings sample
  pubsub/cloud-client/publisher.py
Labels: cla: yes

#3140 chore: update datalab dependency
  bigquery/datalab-migration/requirements.txt
Labels: cla: yes

#3143 renovate: Remove concurrent PR limit
  renovate.json
Labels: automerge, cla: yes

#3144 blunderbuss: Remove dmahugh
  .github/blunderbuss.yml
Labels: cla: yes

#3116 chore: only run 2.7 tests for GAE
  .kokoro/python2.7/common.cfg
  noxfile-template.py
  noxfile.py
Labels: automerge, cla: yes

#3199 fix whitespace error that snuck in
  noxfile-template.py
Labels: cla: yes

#3048 dataflow/flex-templates: Add Pub/Sub to BigQuery sample
  dataflow/flex-templates/streaming_beam/Dockerfile
  dataflow/flex-templates/streaming_beam/README.md
  dataflow/flex-templates/streaming_beam/metadata.json
  dataflow/flex-templates/streaming_beam/requirements.txt
  dataflow/flex-templates/streaming_beam/streaming_beam.py
  dataflow/flex-templates/streaming_beam/streaming_beam_test.py
Labels: cla: yes

#3101 spanner: Add Cloud Spanner Backup samples
  spanner/cloud-client/backup_sample.py
  spanner/cloud-client/backup_sample_test.py
Labels: api: spanner, cla: yes

#3117 feat: adds media translation samples
  media-translation/cloud-client/README.rst
  media-translation/cloud-client/README.rst.in
  media-translation/cloud-client/requirements.txt
  media-translation/cloud-client/resources/audio.raw
  media-translation/cloud-client/translate_from_file.py
  media-translation/cloud-client/translate_from_file_test.py
  media-translation/cloud-client/translate_from_mic.py
Labels: automerge, cla: yes

#3229 Prevent "[CRITICAL] WORKER TIMEOUT" error message
  run/hello-broken/Dockerfile
  run/image-processing/Dockerfile
  run/logging-manual/Dockerfile
  run/pubsub/Dockerfile
  run/system-package/Dockerfile
Labels: cla: yes
