Repository GoogleCloudPlatform/python-docs-samples, pull requests merged in 2020-12, with the labels that each got.

#5013 Add patch call
  storage/cloud-client/storage_set_metadata.py
Labels: cla: yes, samples

#4993 Add DAG for airflow metadb cleanup for Composer.
  composer/workflows/airflow_db_cleanup.py
  composer/workflows/airflow_db_cleanup_test.py
Labels: cla: yes, samples

#5028 add region tags
  composer/workflows/airflow_db_cleanup.py
Labels: cla: yes, samples

#4869 Add new django tutorial
  .github/CODEOWNERS
  noxfile-template.py
  run/README.md
  run/django/.gcloudignore
  run/django/Dockerfile
  run/django/README.md
  run/django/cloudmigrate.yaml
  run/django/e2e_test.py
  run/django/manage.py
  run/django/mysite/__init__.py
  run/django/mysite/asgi.py
  run/django/mysite/migrations/0001_createsuperuser.py
  run/django/mysite/migrations/__init__.py
  run/django/mysite/settings.py
  run/django/mysite/urls.py
  run/django/mysite/wsgi.py
  run/django/noxfile_config.py
  run/django/polls/__init__.py
  run/django/polls/admin.py
  run/django/polls/apps.py
  run/django/polls/models.py
  run/django/polls/test_polls.py
  run/django/polls/urls.py
  run/django/polls/views.py
  run/django/requirements-test.txt
  run/django/requirements.txt
Labels: cla: yes, samples

#5030 Fix region tags for run/django
  run/django/cloudmigrate.yaml
  run/django/mysite/migrations/0001_createsuperuser.py
  run/django/mysite/settings.py
Labels: cla: yes, samples

#5017 Add Rafal to composer codeowners
  .github/CODEOWNERS
Labels: cla: yes, samples

#4979 new tutorial: deployment previews
  run/deployment-previews/Dockerfile
  run/deployment-previews/README.md
  run/deployment-previews/check_status.py
  run/deployment-previews/cloudbuild-configurations/README.md
  run/deployment-previews/cloudbuild-configurations/cloudbuild-cleanup.yaml
  run/deployment-previews/cloudbuild-configurations/cloudbuild-preview.yaml
  run/deployment-previews/cloudbuild-configurations/cloudbuild.yaml
  run/deployment-previews/noxfile_config.py
  run/deployment-previews/requirements-test.txt
  run/deployment-previews/requirements.txt
  run/deployment-previews/test_app.py
Labels: automerge, cla: yes, samples

#5047 chore(functions): support env variables in integration tests
  functions/helloworld/sample_http_test_integration.py
Labels: api: cloudfunctions, cla: yes, samples

#5041 remove third_party folder
  .github/CODEOWNERS
  composer/workflows/bq_copy_across_locations.py
  composer/workflows/bq_copy_across_locations_test.py
  third_party/apache-airflow/LICENSE
  third_party/apache-airflow/README.md
  third_party/apache-airflow/plugins/__init__.py
  third_party/apache-airflow/plugins/gcs_plugin/__init__.py
  third_party/apache-airflow/plugins/gcs_plugin/hooks/__init__.py
  third_party/apache-airflow/plugins/gcs_plugin/hooks/gcs_hook.py
  third_party/apache-airflow/plugins/gcs_plugin/operators/__init__.py
  third_party/apache-airflow/plugins/gcs_plugin/operators/gcs_to_gcs.py
Labels: automerge, cla: yes, samples

#5048 chore(functions/ci_cd): fix Cloud Build not running pytest
  functions/ci_cd/cloudbuild.yaml
Labels: api: cloudfunctions, cla: yes, samples

#5050 update region tag guidance
  AUTHORING_GUIDE.md
Labels: automerge, cla: yes, samples

#5052 fix: add a comment to draw attention to using get_blob, not blob
  storage/cloud-client/storage_download_file.py
  storage/cloud-client/storage_get_metadata.py
Labels: cla: yes, samples

#5056 chore(functions): remove BASE_URL env var
  functions/helloworld/sample_http_test_integration.py
Labels: api: cloudfunctions, cla: yes, samples

#5054 docs: explain how to use noxfile_config and add secrets
  AUTHORING_GUIDE.md
  noxfile_config.py
Labels: cla: yes, samples

#4937 Taskqueue push queues migration samples
  appengine/standard/migration/taskqueue/counter/README.md
  appengine/standard/migration/taskqueue/counter/app.yaml
  appengine/standard/migration/taskqueue/counter/app3.yaml
  appengine/standard/migration/taskqueue/counter/appengine_config.py
  appengine/standard/migration/taskqueue/counter/main-test.py
  appengine/standard/migration/taskqueue/counter/main.py
  appengine/standard/migration/taskqueue/counter/requirements-test.txt
  appengine/standard/migration/taskqueue/counter/requirements.txt
  appengine/standard/migration/taskqueue/counter/templates/counter.html
Labels: automerge, cla: yes, samples

#5064 fix(storage): Update comment, prefix should include delimiter
  storage/cloud-client/storage_list_files_with_prefix.py
Labels: api: storage, cla: yes, samples

#5059 chore: added an explanation on automl project envs
  testing/test-env.tmpl.sh
Labels: automerge, cla: yes, samples

#5073 Don't skip test_app any more
  appengine/standard/migration/ndb/overview/main_test.py
Labels: cla: yes, samples

#5075 chore(functions): use consistent env var names
  functions/helloworld/sample_pubsub_test_system.py
Labels: api: cloudfunctions, automerge, cla: yes, samples

#5053 refactor cloud run tests for container reg cleanup
  run/hello-broken/e2e_test.py
  run/hello-broken/e2e_test_setup.yaml
  run/hello-broken/main.py
  run/hello-broken/noxfile_config.py
  run/helloworld/e2e_test.py
  run/helloworld/e2e_test_setup.yaml
  run/helloworld/main.py
  run/helloworld/noxfile_config.py
  run/image-processing/e2e_test.py
  run/image-processing/e2e_test_setup.yaml
  run/image-processing/image_test.py
  run/image-processing/main.py
  run/image-processing/main_test.py
  run/image-processing/noxfile_config.py
  run/image-processing/requirements-test.txt
  run/logging-manual/e2e_test.py
  run/logging-manual/e2e_test_setup.yaml
  run/logging-manual/main.py
  run/logging-manual/main_test.py
  run/logging-manual/noxfile_config.py
  run/markdown-preview/e2e_test.py
  run/markdown-preview/e2e_test_setup.yaml
  run/markdown-preview/noxfile_config.py
  run/pubsub/e2e_test.py
  run/pubsub/e2e_test_setup.yaml
  run/pubsub/main.py
  run/pubsub/main_test.py
  run/pubsub/noxfile_config.py
  run/pubsub/requirements-test.txt
  run/system-package/e2e_test.py
  run/system-package/e2e_test_setup.yaml
  run/system-package/noxfile_config.py
Labels: automerge, cla: yes, samples

#5157 Pub/Sub: add region to command to run Dataflow job
  pubsub/streaming-analytics/README.md
Labels: automerge, cla: yes, samples

#5153 Correct tutorial URL in README
  run/deployment-previews/README.md
Labels: automerge, cla: yes, samples

#5071 Update Appengine samples to python39
  appengine/standard_python3/bigquery/app.yaml
  appengine/standard_python3/bigquery/main.py
  appengine/standard_python3/building-an-app/building-an-app-1/app.yaml
  appengine/standard_python3/building-an-app/building-an-app-1/main.py
  appengine/standard_python3/building-an-app/building-an-app-1/static/script.js
  appengine/standard_python3/building-an-app/building-an-app-2/app.yaml
  appengine/standard_python3/building-an-app/building-an-app-2/main.py
  appengine/standard_python3/building-an-app/building-an-app-2/static/script.js
  appengine/standard_python3/building-an-app/building-an-app-2/templates/index.html
  appengine/standard_python3/building-an-app/building-an-app-3/app.yaml
  appengine/standard_python3/building-an-app/building-an-app-3/main.py
  appengine/standard_python3/building-an-app/building-an-app-3/static/script.js
  appengine/standard_python3/building-an-app/building-an-app-3/templates/index.html
  appengine/standard_python3/building-an-app/building-an-app-4/app.yaml
  appengine/standard_python3/building-an-app/building-an-app-4/main.py
  appengine/standard_python3/building-an-app/building-an-app-4/static/script.js
  appengine/standard_python3/building-an-app/building-an-app-4/templates/index.html
  appengine/standard_python3/cloud_debugger/app.yaml
  appengine/standard_python3/cloud_debugger/main.py
  appengine/standard_python3/cloudsql/app.yaml
  appengine/standard_python3/cloudsql/main_mysql.py
  appengine/standard_python3/cloudsql/main_mysql_pooling.py
  appengine/standard_python3/cloudsql/main_postgres.py
  appengine/standard_python3/cloudsql/main_postgres_pooling.py
  appengine/standard_python3/custom-server/app.yaml
  appengine/standard_python3/django/app.yaml
  appengine/standard_python3/hello_world/app.yaml
  appengine/standard_python3/hello_world/main.py
  appengine/standard_python3/migration/urlfetch/app.yaml
  appengine/standard_python3/pubsub/README.md
  appengine/standard_python3/pubsub/app.yaml
  appengine/standard_python3/redis/app.yaml
  appengine/standard_python3/spanner/app.yaml
  appengine/standard_python3/spanner/main.py
  appengine/standard_python3/warmup/app.yaml
  appengine/standard_python3/warmup/main.py
Labels: cla: yes, samples

#4944 feat(samples): added new region tag
  firestore/cloud-async-client/distributed_counters.py
  firestore/cloud-async-client/snippets.py
  firestore/cloud-client/distributed_counters.py
  firestore/cloud-client/snippets.py
Labels: automerge, cla: yes, samples

#5066 Remove dialogflow samples
  .github/CODEOWNERS
  dialogflow/cloud-client/README.rst
  dialogflow/cloud-client/create_document_test.py
  dialogflow/cloud-client/create_knowledge_base_test.py
  dialogflow/cloud-client/detect_intent_audio.py
  dialogflow/cloud-client/detect_intent_audio_test.py
  dialogflow/cloud-client/detect_intent_knowledge.py
  dialogflow/cloud-client/detect_intent_knowledge_test.py
  dialogflow/cloud-client/detect_intent_stream.py
  dialogflow/cloud-client/detect_intent_stream_test.py
  dialogflow/cloud-client/detect_intent_texts.py
  dialogflow/cloud-client/detect_intent_texts_test.py
  dialogflow/cloud-client/detect_intent_with_sentiment_analysis.py
  dialogflow/cloud-client/detect_intent_with_sentiment_analysis_test.py
  dialogflow/cloud-client/detect_intent_with_texttospeech_response.py
  dialogflow/cloud-client/detect_intent_with_texttospeech_response_test.py
  dialogflow/cloud-client/document_management.py
  dialogflow/cloud-client/intent_management.py
  dialogflow/cloud-client/intent_management_test.py
  dialogflow/cloud-client/knowledge_base_management.py
  dialogflow/cloud-client/requirements-test.txt
  dialogflow/cloud-client/requirements.txt
  dialogflow/cloud-client/resources/230pm.wav
  dialogflow/cloud-client/resources/RoomReservation.zip
  dialogflow/cloud-client/resources/book_a_room.wav
  dialogflow/cloud-client/resources/half_an_hour.wav
  dialogflow/cloud-client/resources/mountain_view.wav
  dialogflow/cloud-client/resources/today.wav
  dialogflow/cloud-client/resources/two_people.wav
Labels: cla: yes, samples

#5179 dataflow: simplify enabled APIs list
  dataflow/README.md
Labels: api: dataflow, cla: yes, samples
