Repository GoogleCloudPlatform/python-docs-samples, pull requests merged in 2020-11, with the labels that each got.

#4941 add details about type hinting to authoring guide
  AUTHORING_GUIDE.md
Labels: cla: yes

#4938 docs: readme formatting
  README.md
Labels: cla: yes

#4936 [Cloud Run] Add variable backoff for E2E test
  run/logging-manual/e2e_test.py
Labels: automerge, cla: yes

#4951 Update Cloud Run Region tags
  run/hello-broken/Dockerfile
  run/hello-broken/main.py
  run/helloworld/Dockerfile
  run/helloworld/main.py
  run/image-processing/Dockerfile
  run/image-processing/image.py
  run/image-processing/main.py
  run/logging-manual/main.py
  run/markdown-preview/editor/main.py
  run/markdown-preview/editor/render.py
  run/markdown-preview/editor/templates/index.html
  run/pubsub/Dockerfile
  run/pubsub/main.py
  run/system-package/Dockerfile
  run/system-package/main.py
Labels: cla: yes

#4928 Remove outdated SQL Server sample region tags.
  cloud-sql/sql-server/sqlalchemy/main.py
Labels: cla: yes

#4950 chore(logging): config logging and error reporting apis
  .github/blunderbuss.yml
Labels: api: logging, automerge, cla: yes

#4961 Add missed region tags
  functions/tips/main.py
Labels: automerge, cla: yes

#4955 update region tag for sample browser
  composer/workflows/unit_testing_test.py
Labels: automerge, cla: yes

#4858 feat: Target new Datastore Client after microgenerator migration
  datastore/cloud-client/admin.py
  datastore/cloud-client/quickstart.py
  datastore/cloud-client/quickstart_test.py
  datastore/cloud-client/requirements.txt
  datastore/cloud-client/snippets.py
  datastore/cloud-client/snippets_test.py
  datastore/cloud-client/tasks.py
  datastore/cloud-client/tasks_test.py
  firestore/cloud-async-client/requirements.txt
Labels: cla: yes, samples

#4977 Added tests to Cloud SQL quickstarts
  .gitignore
  .kokoro/tests/run_tests.sh
  cloud-sql/mysql/sqlalchemy/connection_test.py
  cloud-sql/mysql/sqlalchemy/main.py
  cloud-sql/mysql/sqlalchemy/noxfile.py
  cloud-sql/postgres/sqlalchemy/connection_test.py
  cloud-sql/postgres/sqlalchemy/main.py
  cloud-sql/postgres/sqlalchemy/noxfile.py
  cloud-sql/sql-server/sqlalchemy/connection_test.py
  cloud-sql/sql-server/sqlalchemy/main.py
  cloud-sql/sql-server/sqlalchemy/noxfile.py
  testing/test-env.tmpl.sh
Labels: cla: yes

#4986 Ignore updates to cattrs
  composer/workflows/requirements.txt
  renovate.json
Labels: cla: yes, samples

#5001 Fix argument validation (iot/api-client/mqtt_example)
  iot/api-client/mqtt_example/cloudiot_mqtt_example.py
Labels: cla: yes, samples

#5003 chore (run/logging): Use actual product names
  run/logging-manual/main.py
Labels: api: run, cla: yes, samples

#4997 Add UUIDs to test template names and test bucket names
  media/transcoder/job_template_test.py
  media/transcoder/job_test.py
  media/transcoder/requirements-test.txt
Labels: cla: yes, samples
