Repository GoogleCloudPlatform/python-docs-samples, pull requests merged in 2020-02, with the labels that each got.

#2763 Fix: Reuse same Spanner database in Cloud Function
  functions/spanner/main.py
Labels: api: functions, api: spanner, cla: yes

#2716 Cloud trace demo app
  trace/cloud-trace-demo-app/README.md
  trace/cloud-trace-demo-app/app/Dockerfile
  trace/cloud-trace-demo-app/app/app.py
  trace/cloud-trace-demo-app/app/app_test.py
  trace/cloud-trace-demo-app/app/demo-service-a.yaml
  trace/cloud-trace-demo-app/app/demo-service-b.yaml.template
  trace/cloud-trace-demo-app/app/demo-service-c.yaml.template
  trace/cloud-trace-demo-app/app/requirements.txt
  trace/cloud-trace-demo-app/example.png
  trace/cloud-trace-demo-app/setup.sh
  trace/trace-python-sample/README.rst
  trace/trace-python-sample/README.rst.in
  trace/trace-python-sample/main.py
  trace/trace-python-sample/main_test.py
  trace/trace-python-sample/requirements.txt
Labels: cla: yes

#2745 translate v3 snippets
  translate/cloud-client/translate_v3_create_glossary.py
  translate/cloud-client/translate_v3_create_glossary_test.py
  translate/cloud-client/translate_v3_delete_glossary.py
  translate/cloud-client/translate_v3_delete_glossary_test.py
  translate/cloud-client/translate_v3_get_glossary.py
  translate/cloud-client/translate_v3_get_glossary_test.py
  translate/cloud-client/translate_v3_translate_text.py
  translate/cloud-client/translate_v3_translate_text_with_glossary.py
  translate/cloud-client/translate_v3_translate_text_with_glossary_test.py
Labels: cla: yes

#2768 Translate: migrate published samples
  translate/cloud-client/translate_v3_detect_language.py
  translate/cloud-client/translate_v3_detect_language_test.py
  translate/cloud-client/translate_v3_get_supported_languages.py
  translate/cloud-client/translate_v3_get_supported_languages_test.py
Labels: cla: yes

#2769 Translate: migrate published glossaries samples
  translate/cloud-client/translate_v3_list_glossary.py
  translate/cloud-client/translate_v3_list_glossary_test.py
Labels: cla: yes

#2771 Add GAE billing limit sample
  functions/billing/main.py
Labels: cla: yes

#2773 Updated commands for Cloud Run
  cloud-sql/mysql/sqlalchemy/README.md
Labels: cla: yes

#2774 Add GAE billing tests + fix region tags
  .kokoro/tests/run_tests.sh
  functions/billing/main.py
  functions/billing/main_test.py
Labels: cla: yes

#2764 endpoints: Modify gRPC bookstore to support gRPC on Cloud Run
  endpoints/README.md
  endpoints/bookstore-grpc/Dockerfile
  endpoints/bookstore-grpc/bookstore_client.py
  endpoints/bookstore-grpc/bookstore_server.py
  endpoints/roots.pem
Labels: cla: yes

#2779 update image in kpo sample
  composer/workflows/kubernetes_pod_operator.py
  composer/workflows/requirements.txt
Labels: cla: yes

#2780 Adds check for missing gateway ID on gateway commands
  iot/api-client/mqtt_example/cloudiot_mqtt_example.py
  iot/api-client/mqtt_example/cloudiot_mqtt_example_test.py
Labels: cla: yes

#2775 .kokoro: publish test log to Build Cop Bot
  .kokoro/tests/run_tests.sh
Labels: cla: yes

#2621 fix: correct dataset name, use env var for project
  dlp/deid.py
  dlp/deid_test.py
  dlp/inspect_content.py
  dlp/inspect_content_test.py
  dlp/jobs.py
  dlp/jobs_test.py
  dlp/metadata.py
  dlp/quickstart.py
  dlp/redact.py
  dlp/redact_test.py
  dlp/risk.py
  dlp/risk_test.py
  dlp/templates.py
  dlp/templates_test.py
  dlp/triggers.py
  dlp/triggers_test.py
Labels: api: dlp, cla: yes

#2787 Minor edits to GAE billing sample
  functions/billing/main.py
  functions/billing/requirements.txt
Labels: cla: yes

#2796 Update Firebase UI Web version and host
  appengine/standard_python37/building-an-app/building-an-app-3/templates/index.html
Labels: cla: yes

#2844 Fix incorrect data submission
  functions/composer/composer_storage_trigger.py
Labels: cla: yes

#2711 fix: Update MAC_SETUP to describe using builtin venv
  MAC_SETUP.md
Labels: cla: yes

#2853 Remove param to reduce latency (per docs)
  dlp/inspect_content_test.py
Labels: cla: yes

#2829 dataflow: wait for jobs to be cancellable in tests for run_template.
  dataflow/run_template/main_test.py
Labels: cla: yes

#2920 fix: address bigquery/bqml test failures
  bigquery/bqml/data_scientist_tutorial_test.py
  bigquery/bqml/ncaa_tutorial_test.py
  bigquery/bqml/requirements.txt
  bigquery/bqml/resources/feature_input_query.sql
  bigquery/bqml/resources/training_data_query.sql
Labels: cla: yes

#2917 Minor fix of readme
  trace/cloud-trace-demo-app/README.md
  trace/cloud-trace-demo-app/setup.sh
Labels: cla: yes

#2847 fix authoring guide bug
  AUTHORING_GUIDE.md
Labels: cla: yes

#2935 .kokoro: use buildcop.sh script to publish logs
  .kokoro/tests/run_tests.sh
Labels: cla: yes

#2919 video: adding face detection and person detection samples for beta
  video/cloud-client/analyze/requirements.txt
  video/cloud-client/analyze/video_detect_faces_beta.py
  video/cloud-client/analyze/video_detect_faces_beta_test.py
  video/cloud-client/analyze/video_detect_faces_gcs_beta.py
  video/cloud-client/analyze/video_detect_faces_gcs_beta_test.py
  video/cloud-client/analyze/video_detect_person_beta.py
  video/cloud-client/analyze/video_detect_person_beta_test.py
  video/cloud-client/analyze/video_detect_person_gcs_beta.py
  video/cloud-client/analyze/video_detect_person_gcs_beta_test.py
Labels: cla: yes

#2937 translate: increase timeout
  translate/cloud-client/beta_snippets.py
Labels: cla: yes

#2855 Add sample queries for optimizing-indexes docs
  datastore/cloud-client/snippets.py
  datastore/cloud-client/snippets_test.py
Labels: cla: yes

#2957 .kokoro/testing: use buildcop binary to publish logs
  .kokoro/tests/run_tests.sh
Labels: cla: yes

#2912 Update NDB version to 1.0.1
  datastore/cloud-ndb/requirements.txt
Labels: cla: yes

#2960 Pub/Sub: remove publish concurrency control sample
  pubsub/cloud-client/README.rst
  pubsub/cloud-client/publisher.py
  pubsub/cloud-client/publisher_test.py
Labels: cla: yes

#2988 vision: fix flaky test
  vision/cloud-client/detect/detect_test.py
Labels: cla: yes

#2990 Simplify opencensus quickstart tests.
  opencensus/metrics_quickstart.py
  opencensus/metrics_quickstart_test.py
Labels: automerge, cla: yes

#2915 vision: fix flaky tests to be more generic in the results
  vision/cloud-client/web/web_detect_test.py
Labels: cla: yes

#2936 dialogflow: make flaky test more generic
  dialogflow/cloud-client/context_management_test.py
  dialogflow/cloud-client/create_document_test.py
  dialogflow/cloud-client/create_entity_test.py
  dialogflow/cloud-client/create_entity_type_test.py
  dialogflow/cloud-client/create_knowledge_base_test.py
  dialogflow/cloud-client/delete_document_test.py
  dialogflow/cloud-client/delete_entity_test.py
  dialogflow/cloud-client/delete_entity_type_test.py
  dialogflow/cloud-client/delete_knowledge_base_test.py
  dialogflow/cloud-client/detect_intent_audio_test.py
  dialogflow/cloud-client/detect_intent_knowledge_test.py
  dialogflow/cloud-client/detect_intent_stream_test.py
  dialogflow/cloud-client/detect_intent_texts_test.py
  dialogflow/cloud-client/detect_intent_with_model_selection_test.py
  dialogflow/cloud-client/detect_intent_with_sentiment_analysis_test.py
  dialogflow/cloud-client/detect_intent_with_texttospeech_response_test.py
  dialogflow/cloud-client/get_knowledge_base_test.py
  dialogflow/cloud-client/intent_management_test.py
  dialogflow/cloud-client/list_entities_test.py
  dialogflow/cloud-client/list_entity_types_test.py
  dialogflow/cloud-client/list_knowledge_bases_test.py
  dialogflow/cloud-client/session_entity_type_management_test.py
Labels: cla: yes

#2986 Pub/Sub: remove unreferenced samples
  pubsub/cloud-client/README.rst
  pubsub/cloud-client/quickstart.py
  pubsub/cloud-client/quickstart_test.py
Labels: automerge, cla: yes

#2995 fix: monitoring tests
  monitoring/api/v3/cloud-client/quickstart_test.py
  monitoring/api/v3/cloud-client/snippets.py
  monitoring/api/v3/cloud-client/snippets_test.py
Labels: automerge, cla: yes

#2996 Passing flaky hints to prevent buildcop failures
  iot/api-client/mqtt_example/cloudiot_mqtt_example_test.py
  iot/api-client/mqtt_example/cloudiot_mqtt_image_test.py
Labels: cla: yes

#2997 Fixes #2765 by adding a value for user agent
  appengine/flexible/analytics/main.py
  appengine/flexible/analytics/requirements.txt
Labels: cla: yes

#3001 fix: dataproc quickstart test to properly clean up gcs bucket during teardown
  dataproc/quickstart/quickstart_test.py
Labels: cla: yes

#2628 Speech sample cleanup
  speech/microphone/requirements.txt
  speech/microphone/transcribe_streaming_indefinite.py
  speech/microphone/transcribe_streaming_infinite.py
Labels: automerge, cla: yes
