Repository GoogleCloudPlatform/python-docs-samples, pull requests merged in 2020-05, with the labels that each got.

#3572 translate: fix glossary leak issue
  translate/cloud-client/requirements-test.txt
  translate/cloud-client/translate_v3_batch_translate_text_test.py
  translate/cloud-client/translate_v3_batch_translate_text_with_glossary_test.py
  translate/cloud-client/translate_v3_create_glossary_test.py
  translate/cloud-client/translate_v3_detect_language.py
  translate/cloud-client/translate_v3_detect_language_test.py
  translate/cloud-client/translate_v3_get_glossary_test.py
  translate/cloud-client/translate_v3_get_supported_languages.py
  translate/cloud-client/translate_v3_get_supported_languages_test.py
  translate/cloud-client/translate_v3_list_glossary.py
  translate/cloud-client/translate_v3_list_glossary_test.py
  translate/cloud-client/translate_v3_translate_text.py
  translate/cloud-client/translate_v3_translate_text_test.py
  translate/cloud-client/translate_v3_translate_text_with_glossary_test.py
Labels: cla: yes

#3547 Markdown tutorial
  run/markdown-preview/README.md
  run/markdown-preview/e2e_test.py
  run/markdown-preview/e2e_test_setup.yaml
  run/markdown-preview/editor/Dockerfile
  run/markdown-preview/editor/main.py
  run/markdown-preview/editor/main_test.py
  run/markdown-preview/editor/render.py
  run/markdown-preview/editor/requirements-test.txt
  run/markdown-preview/editor/requirements.txt
  run/markdown-preview/editor/templates/index.html
  run/markdown-preview/editor/templates/markdown.md
  run/markdown-preview/noxfile.py
  run/markdown-preview/renderer/Dockerfile
  run/markdown-preview/renderer/main.py
  run/markdown-preview/renderer/main_test.py
  run/markdown-preview/renderer/requirements-test.txt
  run/markdown-preview/renderer/requirements.txt
  run/markdown-preview/requirements-test.txt
  run/markdown-preview/requirements.txt
Labels: cla: yes

#3119 bigtable: Handle dev instances and use storage utilization in metric scaler
  bigtable/metricscaler/metricscaler.py
  bigtable/metricscaler/metricscaler_test.py
Labels: cla: yes

#3262 Add kms/attestations/ directory with sample script to verify attestations
  kms/attestations/README.rst.in
  kms/attestations/requirements-test.txt
  kms/attestations/requirements.txt
  kms/attestations/verify_attestation.py
  kms/attestations/verify_attestation_test.py
Labels: cla: yes

#3665 run: Dockerfile COPY to ./
  run/hello-broken/Dockerfile
  run/logging-manual/Dockerfile
  run/markdown-preview/editor/Dockerfile
  run/markdown-preview/renderer/Dockerfile
  run/system-package/Dockerfile
Labels: cla: yes

#3667 fix: bump ipython version to address compilation issues with py3.8
  bigquery/datalab-migration/requirements.txt
Labels: cla: yes

#3578 docs(storage): add samples for lifer cycle and versioning
  storage/cloud-client/snippets_test.py
  storage/cloud-client/storage_disable_bucket_lifecycle_management.py
  storage/cloud-client/storage_disable_versioning.py
  storage/cloud-client/storage_enable_bucket_lifecycle_management.py
  storage/cloud-client/storage_enable_versioning.py
  storage/cloud-client/storage_set_metadata.py
Labels: cla: yes

#3685 [dlp] fix: increase the number of retries for some tests
  dlp/risk_test.py
Labels: cla: yes

#3684 [vision] fix: add timeout for LRO result and mark it as flaky
  vision/cloud-client/detect/vision_async_batch_annotate_images.py
  vision/cloud-client/detect/vision_async_batch_annotate_images_test.py
Labels: cla: yes

#3679 testing: disable py-3.8 build for some tests
  appengine/flexible/memcache/noxfile.py
  dataflow/encryption-keys/noxfile.py
  dataflow/flex-templates/streaming_beam/noxfile.py
  ml_engine/online_prediction/noxfile.py
  pubsub/streaming-analytics/noxfile.py
Labels: cla: yes

#3686 Refactor README.md file to divide the folder into 2 sections:
  notebooks/README.md
  notebooks/samples/README.md
  notebooks/samples/requirements-test.txt
  notebooks/samples/requirements.txt
Labels: automerge, cla: yes

#3688 chore: pin new Cloud Spanner release
  spanner/cloud-client/requirements.txt
Labels: api: spanner, cla: yes

#3671 [dialogflow] fix: marking a test with flaky
  dialogflow/cloud-client/create_document_test.py
  dialogflow/cloud-client/document_management.py
  dialogflow/cloud-client/requirements-test.txt
Labels: cla: yes

#2948 remove misleading raise_for_status
  endpoints/getting-started/clients/google-jwt-client.py
Labels: automerge, cla: yes

#3695 functions/slack: config file -> env vars
  functions/ocr/app/config.json
  functions/ocr/app/main.py
Labels: automerge, cla: yes

#3689 chore: add build badges to README
  README.md
Labels: cla: yes

#3696 Adding SoDa teams for easier triage
  .github/CODEOWNERS
Labels: automerge, cla: yes

#3691 Update logging example to retrieve the default handler
  logging/cloud-client/README.rst
  logging/cloud-client/handler.py
Labels: automerge, cla: yes

#3693 automl: remove vision samples no longer on cgc
  vision/automl/automl_vision_dataset.py
  vision/automl/automl_vision_model.py
  vision/automl/automl_vision_predict.py
  vision/automl/dataset_test.py
  vision/automl/model_test.py
  vision/automl/predict_test.py
Labels: cla: yes

#3698 [container_registry] fix: bump the pubsub timeout
  container_registry/container_analysis/samples_test.py
Labels: cla: yes

#3697 [monitoring] fix: use backoff for writing the value
  monitoring/api/v3/api-client/custom_metric_test.py
Labels: cla: yes

#3709 [vision] fix: mark a test as flaky
  vision/cloud-client/web/requirements-test.txt
  vision/cloud-client/web/web_detect_test.py
Labels: cla: yes

#3708 Add example command for docs
  iot/api-client/manager/manager.py
Labels: cla: yes

#3716 chore: remove unused oauth2client in healthcare
  healthcare/api-client/v1/fhir/requirements.txt
Labels: cla: yes

#3720 Retry HttpErrors for test_patch_hl7v2_message
  healthcare/api-client/v1/hl7v2/hl7v2_messages_test.py
Labels: cla: yes

#3719 [healthcare] fix: retry flaky API calls
  healthcare/api-client/fhir/fhir_resources.py
  healthcare/api-client/fhir/fhir_resources_test.py
  healthcare/api-client/fhir/fhir_stores.py
  healthcare/api-client/fhir/requirements-test.txt
Labels: cla: yes

#3726 fix: update google-auth version for issue #3712
  iap/requirements.txt
Labels: cla: yes

#3727 testing: remove I100 and I201 from the ignore list
  noxfile-template.py
Labels: cla: yes

#3735 remove unused samples
  auth/http-client/requirements-test.txt
  auth/http-client/requirements.txt
  auth/http-client/snippets.py
  auth/http-client/snippets_test.py
Labels: cla: yes

#3736 chore: some lint fixes
  appengine/flexible/pubsub/main.py
  appengine/flexible/scipy/main.py
  appengine/flexible/tasks/snippets_test.py
  appengine/standard_python37/cloud_debugger/main.py
Labels: cla: yes

#3737 chore: some lint fixes
  appengine/standard_python37/pubsub/main.py
  appengine/standard_python37/pubsub/main_test.py
  automl/beta/set_endpoint_test.py
  bigquery/bqml/data_scientist_tutorial_test.py
Labels: cla: yes

#3738 chore: some lint fixes
  bigquery/datalab-migration/samples_test.py
  bigtable/hello_happybase/main.py
  bigtable/metricscaler/metricscaler_test.py
  bigtable/quickstart/main_test.py
Labels: cla: yes

#3739 chore: some lint fixes
  bigtable/quickstart_happybase/main_test.py
  bigtable/snippets/filters/filter_snippets.py
  bigtable/snippets/filters/filters_test.py
  bigtable/snippets/reads/reads_test.py
  bigtable/snippets/writes/write_simple.py
  bigtable/snippets/writes/writes_test.py
Labels: cla: yes

#3740 chore: some lint fixes
  bigtable/quickstart_happybase/main_test.py
  cloud-sql/sql-server/sqlalchemy/main.py
  composer/workflows/conftest.py
  composer/workflows/kubernetes_pod_operator.py
  compute/managed-instances/demo/app.py
  compute/metadata/detect_legacy_usage.py
  compute/metadata/detect_legacy_usage_test.py
Labels: cla: yes

#3743 chore: some lint fixes
  compute/oslogin/service_account_ssh.py
  compute/oslogin/service_account_ssh_test.py
  dataflow/run_template/main_test.py
  dataproc/create_cluster_test.py
  dataproc/quickstart/quickstart_test.py
  dataproc/single_job_workflow.py
  dataproc/submit_job_to_cluster.py
  datastore/cloud-ndb/flask_app_test.py
  dialogflow/cloud-client/create_knowledge_base_test.py
Labels: cla: yes

#3744 chore: some lint fixes
  dlp/inspect_content.py
  dlp/quickstart.py
  dlp/risk_test.py
  document/cloud-client/batch_parse_form_beta.py
  document/cloud-client/batch_parse_form_beta_test.py
  document/cloud-client/batch_parse_table_beta.py
  document/cloud-client/batch_parse_table_beta_test.py
  document/cloud-client/parse_form_beta_test.py
  document/cloud-client/parse_table_beta_test.py
  document/cloud-client/parse_with_model_beta_test.py
  document/cloud-client/quickstart_beta_test.py
  document/cloud-client/set_endpoint_beta_test.py
  endpoints/bookstore-grpc/bookstore_server.py
  healthcare/api-client/datasets/datasets.py
  healthcare/api-client/dicom/dicom_stores.py
  healthcare/api-client/dicom/dicom_stores_test.py
  healthcare/api-client/dicom/dicomweb.py
  healthcare/api-client/dicom/dicomweb_test.py
Labels: cla: yes

#3746 chore: some lint fixes
  healthcare/api-client/fhir/fhir_resources.py
  healthcare/api-client/fhir/fhir_resources_test.py
  healthcare/api-client/fhir/fhir_stores.py
  healthcare/api-client/fhir/fhir_stores_test.py
  healthcare/api-client/hl7v2/hl7v2_messages.py
  healthcare/api-client/hl7v2/hl7v2_messages_test.py
  healthcare/api-client/hl7v2/hl7v2_stores.py
  healthcare/api-client/hl7v2/hl7v2_stores_test.py
  healthcare/api-client/v1/datasets/datasets_test.py
  healthcare/api-client/v1/dicom/dicom_stores_test.py
  healthcare/api-client/v1/dicom/dicomweb_test.py
  healthcare/api-client/v1/fhir/fhir_resources.py
  healthcare/api-client/v1/fhir/fhir_resources_test.py
  healthcare/api-client/v1/fhir/fhir_stores_test.py
  healthcare/api-client/v1/hl7v2/hl7v2_messages.py
  healthcare/api-client/v1/hl7v2/hl7v2_messages_test.py
  healthcare/api-client/v1/hl7v2/hl7v2_stores_test.py
Labels: cla: yes

#3747 chore: some lint fixes
  iam/api-client/access_test.py
  iam/api-client/custom_roles_test.py
  iot/api-client/codelabs/gateway.py
  iot/api-client/end_to_end_example/cloudiot_pubsub_example_server.py
  iot/api-client/gcs_file_to_device/gcs_send_to_device_test.py
  iot/api-client/http_example/cloudiot_http_example_test.py
  iot/api-client/manager/manager_test.py
  iot/api-client/mqtt_example/cloudiot_mqtt_example_test.py
  iot/api-client/mqtt_example/cloudiot_mqtt_image.py
  iot/api-client/mqtt_example/cloudiot_mqtt_image_test.py
  iot/api-client/mqtt_example/fixtures.py
  iot/api-client/mqtt_example/gateway_demo.py
Labels: cla: yes

#3748 chore: some lint fixes
  jobs/v3/api_client/auto_complete_sample_test.py
  jobs/v3/api_client/base_company_sample_test.py
  jobs/v3/api_client/base_job_sample_test.py
  jobs/v3/api_client/batch_operation_sample_test.py
  jobs/v3/api_client/commute_search_sample_test.py
  jobs/v3/api_client/custom_attribute_sample_test.py
  jobs/v3/api_client/email_alert_search_sample_test.py
  jobs/v3/api_client/featured_job_search_sample_test.py
  jobs/v3/api_client/general_search_sample_test.py
  jobs/v3/api_client/histogram_sample_test.py
  jobs/v3/api_client/location_search_sample_test.py
  jobs/v3/api_client/quickstart_test.py
  kms/api-client/snippets_test.py
  monitoring/api/v3/api-client/custom_metric_test.py
  monitoring/api/v3/cloud-client/snippets_test.py
  pubsub/cloud-client/quickstart/pub_test.py
  pubsub/cloud-client/quickstart/sub_test.py
  run/hello-broken/main.py
  run/hello-broken/main_test.py
Labels: cla: yes

#3749 chore: some lint fixes
  run/image-processing/main.py
  run/image-processing/main_test.py
  run/logging-manual/main.py
  run/logging-manual/main_test.py
  run/markdown-preview/editor/main.py
  run/markdown-preview/editor/main_test.py
  run/markdown-preview/noxfile.py
  run/markdown-preview/renderer/main.py
  run/markdown-preview/renderer/main_test.py
  run/pubsub/main.py
  run/system-package/main.py
  run/system-package/main_test.py
  secretmanager/api-client/snippets_test.py
  spanner/cloud-client/backup_sample_test.py
Labels: cla: yes

#3750 chore: some lint fixes
  speech/microphone/transcribe_streaming_infinite.py
  storage/api/crud_object_test.py
  storage/cloud-client/acl_test.py
  storage/cloud-client/bucket_lock_test.py
  storage/cloud-client/encryption_test.py
  storage/cloud-client/hmac_samples_test.py
  storage/cloud-client/iam_test.py
  storage/cloud-client/requester_pays_test.py
  storage/cloud-client/snippets_test.py
  storage/cloud-client/storage_add_bucket_label.py
  storage/cloud-client/storage_download_encrypted_file.py
  storage/cloud-client/storage_generate_signed_post_policy_v4.py
  storage/cloud-client/storage_generate_signed_url_v2.py
  storage/cloud-client/storage_generate_signed_url_v4.py
  storage/cloud-client/storage_generate_upload_signed_url_v4.py
  storage/cloud-client/storage_get_bucket_labels.py
  storage/cloud-client/storage_get_bucket_metadata.py
  storage/cloud-client/storage_remove_bucket_label.py
  storage/cloud-client/storage_rotate_encryption_key.py
  storage/cloud-client/storage_upload_encrypted_file.py
  storage/cloud-client/uniform_bucket_level_access_test.py
  storage/signed_urls/generate_signed_urls.py
  tables/automl/dataset_test.py
  tables/automl/model_test.py
  tables/automl/predict_test.py
  texttospeech/cloud-client/ssml_addresses.py
  texttospeech/cloud-client/ssml_addresses_test.py
  trace/cloud-trace-demo-app/app/app.py
  trace/cloud-trace-demo-app/app/app_test.py
  trace/trace-python-sample/main_test.py
Labels: cla: yes

#3752 chore: apply noxfile changes for flake8 import order
  appengine/flexible/memcache/noxfile.py
  dataflow/encryption-keys/noxfile.py
  dataflow/flex-templates/streaming_beam/noxfile.py
  dataflow/flex-templates/streaming_beam/streaming_beam_test.py
  ml_engine/online_prediction/noxfile.py
  pubsub/streaming-analytics/PubSubToGCS.py
  pubsub/streaming-analytics/PubSubToGCS_test.py
  pubsub/streaming-analytics/noxfile.py
Labels: cla: yes

#3751 chore: some lint fixes
  translate/automl/translate_v3_batch_translate_text_with_model_test.py
  translate/cloud-client/beta_snippets_test.py
  translate/cloud-client/hybrid_glossaries/hybrid_tutorial.py
  translate/cloud-client/hybrid_glossaries/hybrid_tutorial_tests.py
  translate/cloud-client/translate_v3_batch_translate_text_test.py
  translate/cloud-client/translate_v3_batch_translate_text_with_glossary_test.py
  translate/cloud-client/translate_v3_create_glossary_test.py
  translate/cloud-client/translate_v3_detect_language_test.py
  translate/cloud-client/translate_v3_get_glossary_test.py
  translate/cloud-client/translate_v3_get_supported_languages_test.py
  translate/cloud-client/translate_v3_get_supported_languages_with_target_test.py
  translate/cloud-client/translate_v3_list_glossary_test.py
  translate/cloud-client/translate_v3_translate_text_test.py
  translate/cloud-client/translate_v3_translate_text_with_glossary_test.py
  translate/cloud-client/translate_v3_translate_text_with_model_test.py
  video/cloud-client/analyze/beta_snippets_test.py
  video/cloud-client/analyze/video_detect_faces_beta.py
  video/cloud-client/analyze/video_detect_person_beta.py
  vision/automl/edge_container_predict/automl_vision_edge_container_predict.py
  vision/automl/edge_container_predict/automl_vision_edge_container_predict_test.py
  vision/cloud-client/detect/detect.py
  vision/cloud-client/detect/detect_test.py
  vision/cloud-client/detect/vision_batch_annotate_files.py
  vision/cloud-client/product_search/import_product_sets_test.py
Labels: automerge, cla: yes

#3571 automl: tables code sample clean-up
  tables/automl/automl_tables_dataset.py
  tables/automl/dataset_test.py
Labels: cla: yes

#3486 [bigtable] Cloud function example
  functions/bigtable/main.py
  functions/bigtable/main_test.py
  functions/bigtable/requirements-test.txt
  functions/bigtable/requirements.txt
Labels: cla: yes

#3718 Remove oauth2client from AppEngine Standard Firebase
  appengine/standard/firebase/firetactoe/firetactoe.py
  appengine/standard/firebase/firetactoe/firetactoe_test.py
  appengine/standard/firebase/firetactoe/requirements-test.txt
  appengine/standard/firebase/firetactoe/requirements.txt
  appengine/standard/firebase/firetactoe/rest_api.py
Labels: automerge, cla: yes

#3745 Add request_method to create example.
  monitoring/api/v3/uptime-check-client/snippets.py
Labels: cla: yes

#3707 [datalabeling] fix: clean up old datasets before the test
  datalabeling/create_annotation_spec_set.py
  datalabeling/export_data.py
  datalabeling/import_data.py
  datalabeling/label_image.py
  datalabeling/label_text.py
  datalabeling/label_text_test.py
  datalabeling/label_video.py
  datalabeling/manage_dataset.py
  datalabeling/manage_dataset_test.py
  datalabeling/testing_lib.py
Labels: automerge, cla: yes

#3758 [healthcare] fix: create/delete the Pub/Sub topic
  healthcare/api-client/dicom/dicom_stores_test.py
  healthcare/api-client/dicom/requirements.txt
  healthcare/api-client/v1/dicom/dicom_stores_test.py
  healthcare/api-client/v1/dicom/requirements.txt
Labels: automerge, cla: yes

#3764 [vision] testing: retry upon errors
  vision/cloud-client/detect/detect_test.py
  vision/cloud-client/detect/requirements-test.txt
Labels: cla: yes

#3731 fix make_iap_request
  functions/composer/composer_storage_trigger.py
Labels: automerge, cla: yes

#3761 [vision] testing: re-enable test_async_detect_document
  vision/cloud-client/detect/detect_test.py
  vision/cloud-client/detect/resources/cloud-samples-data/vision/document/custom_0773375000_title_only.pdf
Labels: automerge, cla: yes

#3687 docs(storage): add samples
  storage/cloud-client/encryption_test.py
  storage/cloud-client/iam_test.py
  storage/cloud-client/snippets_test.py
  storage/cloud-client/storage_bucket_delete_default_kms_key.py
  storage/cloud-client/storage_compose_file.py
  storage/cloud-client/storage_create_bucket_class_location.py
  storage/cloud-client/storage_define_bucket_website_configuration.py
  storage/cloud-client/storage_download_public_file.py
  storage/cloud-client/storage_get_service_account.py
  storage/cloud-client/storage_object_csek_to_cmek.py
  storage/cloud-client/storage_object_get_kms_key.py
  storage/cloud-client/storage_set_bucket_public_iam.py
Labels: cla: yes

#3765 [container-registry] fix: mark a flaky test
  container_registry/container_analysis/samples_test.py
Labels: cla: yes

#3700 testing: multi project noxfile-template.py
  .kokoro/python2.7/common.cfg
  .kokoro/python3.6/common.cfg
  .kokoro/python3.7/common.cfg
  .kokoro/python3.8/common.cfg
  .kokoro/tests/run_tests.sh
  monitoring/api/v3/alerts-client/noxfile_config.py
  noxfile-template.py
  noxfile_config.py
Labels: cla: yes, testing

#3762 [datalabeling] testing: retry upon ServerError
  datalabeling/create_annotation_spec_set_test.py
  datalabeling/create_instruction_test.py
  datalabeling/import_data_test.py
  datalabeling/label_image_test.py
  datalabeling/label_text_test.py
  datalabeling/label_video_test.py
  datalabeling/manage_dataset_test.py
Labels: cla: yes

#3767 cleanup: remove stale code block
  .kokoro/tests/run_tests.sh
Labels: cla: yes

#3705 Add main function to attestation verification script
  kms/attestations/verify_attestation.py
Labels: cla: yes

#3768 [appengine] testing: relax datastore test
  appengine/flexible/datastore/main_test.py
Labels: automerge, cla: yes

#3770 [media-translation] docs: hide cloud shell button for mic sample
  media-translation/cloud-client/README.rst
  media-translation/cloud-client/README.rst.in
  scripts/readme-gen/templates/README.tmpl.rst
Labels: cla: yes

#3771 [monitoring] testing: start using build specific projects
  .kokoro/python3.6/common.cfg
  .kokoro/python3.7/common.cfg
  .kokoro/python3.8/common.cfg
  monitoring/api/v3/alerts-client/README.rst
  monitoring/api/v3/alerts-client/README.rst.in
  scripts/readme-gen/templates/README.tmpl.rst
Labels: automerge, cla: yes

#3772 [iam] testing: use multiple projects
  iam/api-client/README.md
  iam/api-client/noxfile_config.py
Labels: cla: yes

#3811 Remove grant from codeowners
  .github/CODEOWNERS
Labels: cla: yes

#3808 functions: fix slack + pubsub tests
  .kokoro/tests/run_tests.sh
  functions/pubsub/main.py
  functions/pubsub/main_test.py
  functions/slack/main_test.py
  functions/slack/noxfile_config.py
  testing/secrets.tar.enc
Labels: cla: yes

#3817 update google-auth to 1.15.0 part 4
  healthcare/api-client/datasets/requirements.txt
  healthcare/api-client/dicom/requirements.txt
  healthcare/api-client/fhir/requirements.txt
  healthcare/api-client/hl7v2/requirements.txt
  healthcare/api-client/v1/datasets/requirements.txt
  healthcare/api-client/v1/dicom/requirements.txt
  healthcare/api-client/v1/fhir/requirements.txt
  healthcare/api-client/v1/hl7v2/requirements.txt
Labels: cla: yes

#3814 update google-auth to 1.15.0 part 1
  appengine/standard/firebase/firenotes/backend/requirements.txt
  appengine/standard/firebase/firetactoe/requirements.txt
  appengine/standard/storage/api-client/requirements.txt
  appengine/standard_python3/building-an-app/building-an-app-3/requirements.txt
  appengine/standard_python3/building-an-app/building-an-app-4/requirements.txt
  appengine/standard_python3/pubsub/requirements.txt
  appengine/standard_python37/building-an-app/building-an-app-3/requirements.txt
  appengine/standard_python37/building-an-app/building-an-app-4/requirements.txt
  appengine/standard_python37/pubsub/requirements.txt
Labels: cla: yes

#3815 update google-auth to 1.15.0 part 2
  auth/api-client/requirements.txt
  auth/end-user/web/requirements.txt
  bigquery_storage/to_dataframe/requirements.txt
  composer/rest/requirements.txt
  compute/api/requirements.txt
  compute/auth/requirements.txt
  compute/encryption/requirements.txt
  compute/oslogin/requirements.txt
Labels: cla: yes

#3816 update google-auth to 1.15.0 part 3
  dataproc/requirements.txt
  endpoints/bookstore-grpc-transcoding/requirements.txt
  endpoints/bookstore-grpc/requirements.txt
  endpoints/getting-started/clients/service_to_service_non_default/requirements.txt
  endpoints/getting-started/requirements.txt
  functions/composer/requirements.txt
Labels: cla: yes

#3818 update google-auth to 1.15.0 part 5
  iam/api-client/requirements.txt
  iap/requirements.txt
  iot/api-client/end_to_end_example/requirements.txt
  iot/api-client/gcs_file_to_device/requirements.txt
  iot/api-client/http_example/requirements.txt
  iot/api-client/manager/requirements.txt
  iot/api-client/mqtt_example/requirements.txt
Labels: automerge, cla: yes

#3819 update google-auth to 1.15.0 final part
  jobs/v3/api_client/requirements.txt
  kubernetes_engine/api-client/requirements.txt
  language/api/requirements.txt
  ml_engine/online_prediction/requirements.txt
  monitoring/api/v3/api-client/requirements.txt
  storage/api/requirements.txt
  storage/signed_urls/requirements.txt
  storage/transfer_service/requirements.txt
Labels: cla: yes

#3824 update google-api-python-client to 1.8.3 part 2
  dataflow/run_template/requirements.txt
  datastore/schedule-export/requirements.txt
  endpoints/getting-started/clients/service_to_service_non_default/requirements.txt
  functions/billing/requirements.txt
  functions/slack/requirements.txt
Labels: cla: yes

#3825 update google-api-python-client to 1.8.3 part 3
  healthcare/api-client/datasets/requirements.txt
  healthcare/api-client/dicom/requirements.txt
  healthcare/api-client/fhir/requirements.txt
  healthcare/api-client/hl7v2/requirements.txt
  healthcare/api-client/v1/datasets/requirements.txt
  healthcare/api-client/v1/dicom/requirements.txt
  healthcare/api-client/v1/fhir/requirements.txt
  healthcare/api-client/v1/hl7v2/requirements.txt
Labels: cla: yes

#3827 update google-api-python-client to 1.8.3 final part
  jobs/v3/api_client/requirements.txt
  kubernetes_engine/api-client/requirements.txt
  language/api/requirements.txt
  ml_engine/online_prediction/requirements.txt
  monitoring/api/v3/api-client/requirements.txt
  notebooks/samples/requirements.txt
  storage/api/requirements.txt
  storage/transfer_service/requirements.txt
Labels: cla: yes

#3826 update google-api-python-client to 1.8.3 part 4
  iam/api-client/requirements.txt
  iot/api-client/end_to_end_example/requirements.txt
  iot/api-client/gcs_file_to_device/requirements.txt
  iot/api-client/http_example/requirements.txt
  iot/api-client/manager/requirements.txt
  iot/api-client/mqtt_example/requirements.txt
Labels: cla: yes

#3823 update google-api-python-client to 1.8.3 part 1
  appengine/standard/pubsub/requirements.txt
  appengine/standard/storage/api-client/requirements.txt
  appengine/standard_python3/pubsub/requirements.txt
  appengine/standard_python37/pubsub/requirements.txt
  auth/api-client/requirements.txt
  auth/end-user/web/requirements.txt
  compute/api/requirements.txt
  compute/auth/requirements.txt
  compute/encryption/requirements.txt
  compute/oslogin/requirements.txt
Labels: cla: yes

#2893 convert cancel to fixture
  dataflow/run_template/main_test.py
  dataflow/run_template/requirements-test.txt
Labels: cla: yes, needs review

#3829 remove nnegrey from CODEOWNERS
  .github/CODEOWNERS
Labels: cla: yes

#3776 Add testing Dockerfile and Cloud Build configuration
  .kokoro/docker/Dockerfile
  .kokoro/docker/cloudbuild.yaml
Labels: cla: yes

#3833 Add 'INSTALL_LIBRARY_FROM_SOURCE' to noxfile-template
  noxfile-template.py
Labels: automerge, cla: yes

#3839 [vision] fix: move the Docker image
  vision/automl/edge_container_predict/Dockerfile
  vision/automl/edge_container_predict/README.md
  vision/automl/edge_container_predict/automl_vision_edge_container_predict_test.py
Labels: cla: yes

#3794 docs(storage): add samples for file archive generation and cors configuration
  storage/cloud-client/snippets_test.py
  storage/cloud-client/storage_change_default_storage_class.py
  storage/cloud-client/storage_change_file_storage_class.py
  storage/cloud-client/storage_copy_file_archived_generation.py
  storage/cloud-client/storage_cors_configuration.py
  storage/cloud-client/storage_delete_file_archived_generation.py
  storage/cloud-client/storage_list_file_archived_generations.py
  storage/cloud-client/storage_remove_cors_configuration.py
Labels: automerge, cla: yes

#3836 chore: add a comment about Ubuntu LTS versions
  .kokoro/docker/Dockerfile
Labels: automerge, cla: yes

#3822 testing: set and use REPORT_TO_BUILD_COP_BOT
  .kokoro/python2.7/periodic.cfg
  .kokoro/python3.6/periodic.cfg
  .kokoro/python3.7/periodic.cfg
  .kokoro/python3.8/periodic.cfg
  .kokoro/tests/run_tests.sh
Labels: automerge, cla: yes, testing

#3834 Update docker image used for tests
  .kokoro/python2.7/common.cfg
  .kokoro/python3.6/common.cfg
  .kokoro/python3.7/common.cfg
  .kokoro/python3.8/common.cfg
Labels: automerge, cla: yes

#3847 GCF cloudbuild.yaml: clarify "dir" parameter
  functions/ci_cd/cloudbuild.yaml
Labels: automerge, cla: yes

#3290 feat: add dataflow-composer tutorial code samples
  composer/workflows/dataflowtemplateoperator_create_dataset_and_table_helper.py
  composer/workflows/dataflowtemplateoperator_create_dataset_and_table_test.py
  composer/workflows/dataflowtemplateoperator_tutorial.py
  composer/workflows/dataflowtemplateoperator_tutorial_test.py
Labels: automerge, cla: yes

#3273 Talent v4beta1 samples [Restoring deleted branch samples]
  jobs/v4beta1/conftest.py
  jobs/v4beta1/job_search_autocomplete_job_title.py
  jobs/v4beta1/job_search_autocomplete_job_title_test.py
  jobs/v4beta1/job_search_batch_create_jobs.py
  jobs/v4beta1/job_search_batch_update_jobs.py
  jobs/v4beta1/job_search_commute_search.py
  jobs/v4beta1/job_search_commute_search_test.py
  jobs/v4beta1/job_search_create_client_event.py
  jobs/v4beta1/job_search_create_company.py
  jobs/v4beta1/job_search_create_company_test.py
  jobs/v4beta1/job_search_create_job.py
  jobs/v4beta1/job_search_create_job_custom_attributes.py
  jobs/v4beta1/job_search_create_job_custom_attributes_test.py
  jobs/v4beta1/job_search_create_job_test.py
  jobs/v4beta1/job_search_create_tenant.py
  jobs/v4beta1/job_search_create_tenant_test.py
  jobs/v4beta1/job_search_custom_ranking_search.py
  jobs/v4beta1/job_search_custom_ranking_search_test.py
  jobs/v4beta1/job_search_delete_company.py
  jobs/v4beta1/job_search_delete_company_test.py
  jobs/v4beta1/job_search_delete_job.py
  jobs/v4beta1/job_search_delete_job_test.py
  jobs/v4beta1/job_search_delete_tenant.py
  jobs/v4beta1/job_search_delete_tenant_test.py
  jobs/v4beta1/job_search_get_company.py
  jobs/v4beta1/job_search_get_company_test.py
  jobs/v4beta1/job_search_get_job.py
  jobs/v4beta1/job_search_get_job_test.py
  jobs/v4beta1/job_search_get_tenant.py
  jobs/v4beta1/job_search_get_tenant_test.py
  jobs/v4beta1/job_search_histogram_search.py
  jobs/v4beta1/job_search_histogram_search_test.py
  jobs/v4beta1/job_search_list_companies.py
  jobs/v4beta1/job_search_list_companies_test.py
  jobs/v4beta1/job_search_list_jobs.py
  jobs/v4beta1/job_search_list_jobs_test.py
  jobs/v4beta1/job_search_list_tenants.py
  jobs/v4beta1/job_search_list_tenants_test.py
  jobs/v4beta1/requirements-test.txt
  jobs/v4beta1/requirements.txt
Labels: cla: yes

#3859 [docker] upgrade gcloud version to 293.0.0
  .kokoro/docker/Dockerfile
Labels: cla: yes

#3857 [kokoro] testing: use secrets manager
  .kokoro/lint/common.cfg
  .kokoro/tests/run_tests.sh
  scripts/decrypt-secrets.sh
  scripts/encrypt-secrets.sh
  testing/secrets.tar.enc
Labels: cla: yes

#3866 testing: fix encrypt-secrets.sh
  scripts/encrypt-secrets.sh
Labels: cla: yes

#3877 testing: various cleanups
  appengine/flexible/scipy/assets/resized_google_logo.jpg
  appengine/flexible/scipy/fixtures/assets/resized_google_logo.jpg
  appengine/flexible/scipy/main.py
  appengine/flexible/scipy/main_test.py
  bigtable/snippets/reads/snapshots/snap_reads_test.py
  iap/iap_test.py
  iot/api-client/gcs_file_to_device/gcs_example_mqtt_device_test.py
  iot/api-client/mqtt_example/cloudiot_mqtt_image_test.py
  logging/cloud-client/snippets_test.py
  texttospeech/cloud-client/.gitignore
  vision/automl/edge_container_predict/automl_vision_edge_container_predict_test.py
Labels: cla: yes

#3879 testing: various cleanups
  .kokoro/tests/run_tests.sh
  scripts/decrypt-secrets.sh
  scripts/encrypt-secrets.sh
Labels: cla: yes

#3883 [bigquery] opt in to use the build specific projects
  bigquery/cloud-client/README.rst
  bigquery/cloud-client/README.rst.in
  bigquery/cloud-client/noxfile_config.py
Labels: cla: yes

#3900 [monitoring] fix: use the same random value for retry
  monitoring/api/v3/api-client/custom_metric_test.py
Labels: cla: yes

#3860 testing: migrate to trampoline_v2
  .kokoro/docker/Dockerfile
  .kokoro/lint/common.cfg
  .kokoro/lint/continuous.cfg
  .kokoro/lint/periodic.cfg
  .kokoro/lint/presubmit.cfg
  .kokoro/python2.7/common.cfg
  .kokoro/python2.7/continuous.cfg
  .kokoro/python2.7/periodic.cfg
  .kokoro/python2.7/presubmit.cfg
  .kokoro/python3.6/common.cfg
  .kokoro/python3.6/continuous.cfg
  .kokoro/python3.6/periodic.cfg
  .kokoro/python3.6/presubmit.cfg
  .kokoro/python3.7/common.cfg
  .kokoro/python3.7/continuous.cfg
  .kokoro/python3.7/periodic.cfg
  .kokoro/python3.7/presubmit.cfg
  .kokoro/python3.8/common.cfg
  .kokoro/python3.8/continuous.cfg
  .kokoro/python3.8/periodic.cfg
  .kokoro/python3.8/presubmit.cfg
  .kokoro/tests/run_tests.sh
  .kokoro/trampoline_v2.sh
  .trampolinerc
  .trampolinerc_tmpl
  scripts/decrypt-secrets.sh
  scripts/run_tests_local.sh
Labels: cla: yes

#3904 samples: add Pub/Sub dead letter queue samples
  pubsub/cloud-client/README.rst
  pubsub/cloud-client/publisher.py
  pubsub/cloud-client/subscriber.py
  pubsub/cloud-client/subscriber_test.py
Labels: cla: yes

#3918 docs: add info on how to run tests with the new script
  AUTHORING_GUIDE.md
Labels: cla: yes

#3916 testing: diff against the common commit on the master
  .kokoro/tests/run_tests.sh
Labels: cla: yes
