Repository GoogleCloudPlatform/python-docs-samples, pull requests merged in 2021-06, with the labels that each got.

#6055 ignore composer constraints file
  renovate.json
Labels: cla: yes, samples

#6059 chore: update snippet-bot config
  .github/snippet-bot.yml
Labels: cla: yes, samples

#6058 chore: update sync-repo-settings config
  .github/sync-repo-settings.yaml
Labels: cla: yes, samples

#6065 chore(.github): update storage blunderbus config
  .github/blunderbuss.yml
Labels: automerge, cla: yes, samples

#5893 docs(firestore): clean-up region tagging
  firestore/cloud-async-client/distributed_counters.py
  firestore/cloud-async-client/snippets.py
  firestore/cloud-client/distributed_counters.py
  firestore/cloud-client/snippets.py
Labels: api: firestore, cla: yes, samples

#6079 trace: Update OpenTelemetry library versions
  trace/cloud-trace-demo-app-opentelemetry/app/app.py
  trace/cloud-trace-demo-app-opentelemetry/app/requirements.txt
  trace/trace-python-sample-opentelemetry/main.py
  trace/trace-python-sample-opentelemetry/main_test.py
  trace/trace-python-sample-opentelemetry/requirements.txt
Labels: api: cloudtrace, cla: yes, samples

#6074 test(storage): fix S3 SDK tests
  storage/s3-sdk/list_gcs_buckets_test.py
  storage/s3-sdk/list_gcs_objects_test.py
  storage/s3-sdk/noxfile_config.py
  storage/s3-sdk/requirements-test.txt
  storage/s3-sdk/s3_sdk_test.py
  testing/test-env.tmpl.sh
Labels: api: storage, automerge, cla: yes, samples

#5784 django secrets and samples rework
  appengine/flexible/django_cloudsql/README.md
  appengine/flexible/django_cloudsql/app.yaml
  appengine/flexible/django_cloudsql/mysite/settings.py
  appengine/flexible/django_cloudsql/mysite/urls.py
  appengine/flexible/django_cloudsql/polls/urls.py
  appengine/flexible/django_cloudsql/requirements.txt
  appengine/standard_python3/django/.gcloudignore
  appengine/standard_python3/django/README.md
  appengine/standard_python3/django/app.yaml
  appengine/standard_python3/django/mysite/settings.py
  appengine/standard_python3/django/mysite/urls.py
  appengine/standard_python3/django/mysite/wsgi.py
  appengine/standard_python3/django/noxfile_config.py
  appengine/standard_python3/django/polls/templates/polls/detail.html
  appengine/standard_python3/django/polls/templates/polls/index.html
  appengine/standard_python3/django/polls/templates/polls/results.html
  appengine/standard_python3/django/polls/test_polls.py
  appengine/standard_python3/django/requirements.txt
  kubernetes_engine/django_tutorial/mysite/settings.py
  run/django/README.md
  run/django/cloudmigrate.yaml
  run/django/mysite/settings.py
  run/django/mysite/wsgi.py
Labels: cla: yes, samples, snippet-bot:no-prefix-req

#6060 move maintenance guide internally
  composer/dag_test_utils/MAINTAINING.md
Labels: cla: yes, samples

#5692 dataflow: update Dockerfile and modularize tests
  dataflow/__init__.py
  dataflow/conftest.py
  dataflow/flex-templates/__init__.py
  dataflow/flex-templates/streaming_beam/.dockerignore
  dataflow/flex-templates/streaming_beam/.gcloudignore
  dataflow/flex-templates/streaming_beam/Dockerfile
  dataflow/flex-templates/streaming_beam/__init__.py
  dataflow/flex-templates/streaming_beam/e2e_test.py
  dataflow/flex-templates/streaming_beam/noxfile.py
  dataflow/flex-templates/streaming_beam/noxfile_config.py
  dataflow/flex-templates/streaming_beam/requirements-test.txt
  dataflow/flex-templates/streaming_beam/streaming_beam.py
  dataflow/flex-templates/streaming_beam/streaming_beam_test.py
  dataflow/run_template/main_test.py
Labels: api: dataflow, cla: yes, samples

#6092 chore(deps): pin functions-framework version
  functions/helloworld/requirements.txt
Labels: cla: yes, priority: p2, samples, type: bug

#6097 (minor) Correct comment format for licence on templates
  appengine/standard_python3/django/polls/templates/polls/detail.html
  appengine/standard_python3/django/polls/templates/polls/index.html
  appengine/standard_python3/django/polls/templates/polls/results.html
Labels: automerge, cla: yes, samples

#5896 add airflow 1 samples to legacy samples
  composer/airflow_1_samples/README.md
  composer/airflow_1_samples/__init__.py
  composer/airflow_1_samples/airflow_db_cleanup.py
  composer/airflow_1_samples/airflow_db_cleanup_test.py
  composer/airflow_1_samples/bq_copy_across_locations.py
  composer/airflow_1_samples/bq_copy_across_locations_test.py
  composer/airflow_1_samples/bq_copy_eu_to_us_sample.csv
  composer/airflow_1_samples/bq_notify.py
  composer/airflow_1_samples/bq_notify_test.py
  composer/airflow_1_samples/clear_file_system_caches_dag.py
  composer/airflow_1_samples/clear_file_system_caches_dag_test.py
  composer/airflow_1_samples/conftest.py
  composer/airflow_1_samples/connections.py
  composer/airflow_1_samples/connections_test.py
  composer/airflow_1_samples/constraints.txt
  composer/airflow_1_samples/dataflowtemplateoperator_tutorial.py
  composer/airflow_1_samples/dataflowtemplateoperator_tutorial_test.py
  composer/airflow_1_samples/dataproc_workflow_template_instantiate_operator_tutorial.py
  composer/airflow_1_samples/dataproc_workflow_template_instantiate_operator_tutorial_test.py
  composer/airflow_1_samples/dependencies/__init__.py
  composer/airflow_1_samples/dependencies/coin_module.py
  composer/airflow_1_samples/hadoop_tutorial.py
  composer/airflow_1_samples/hadoop_tutorial_test.py
  composer/airflow_1_samples/kubernetes_pod_operator.py
  composer/airflow_1_samples/kubernetes_pod_operator_test.py
  composer/airflow_1_samples/localreqs.txt
  composer/airflow_1_samples/noxfile_config.py
  composer/airflow_1_samples/quickstart.py
  composer/airflow_1_samples/quickstart_test.py
  composer/airflow_1_samples/requirements-test.txt
  composer/airflow_1_samples/requirements.txt
  composer/airflow_1_samples/simple.py
  composer/airflow_1_samples/simple_test.py
  composer/airflow_1_samples/trigger_response_dag.py
  composer/airflow_1_samples/trigger_response_dag_test.py
  composer/airflow_1_samples/unit_testing_cycle.py
  composer/airflow_1_samples/unit_testing_test.py
  composer/airflow_1_samples/unit_testing_variables.py
  composer/airflow_1_samples/use_local_deps.py
  composer/airflow_1_samples/use_local_deps_test.py
Labels: cla: yes, samples

#5869 Airflow db transfer script 1.10.14/15->2.0.1+
  composer/tools/composer_db_transfer.md
  composer/tools/composer_db_transfer.py
Labels: api: composer, automerge, cla: yes, samples

#6111 test(storage): fix S3 SDK tests (again)
  storage/s3-sdk/s3_sdk_test.py
Labels: api: storage, cla: yes, samples

#6087 Add retries to Run service requests
  run/idp-sql/test/e2e_test.py
  run/logging-manual/e2e_test.py
Labels: automerge, cla: yes, samples

#5884 feat: VM Indentity samples added.
  compute/metadata/requirements.txt
  compute/metadata/vm_identity.py
  compute/metadata/vm_identity_test.py
Labels: cla: yes, samples

#6115 move inline code samples to github
  composer/airflow_1_samples/grouping.py
  composer/airflow_1_samples/grouping_test.py
  composer/airflow_1_samples/relationship_child.py
  composer/airflow_1_samples/relationship_child_test.py
  composer/airflow_1_samples/relationship_parent.py
  composer/airflow_1_samples/relationship_parent_test.py
  composer/workflows/grouping.py
  composer/workflows/grouping_test.py
  composer/workflows/relationship_child.py
  composer/workflows/relationship_child_test.py
  composer/workflows/relationship_parent.py
  composer/workflows/relationship_parent_test.py
  composer/workflows/taskgroup.py
  composer/workflows/taskgroup_test.py
Labels: cla: yes, samples

#6155 chore: Cleaning up the vm identity sample.
  compute/metadata/vm_identity.py
  compute/metadata/vm_identity_test.py
Labels: cla: yes, samples

#5686 Data orchestration blog sample
  composer/blog/gcp-tech-blog/data-orchestration-with-composer/README.md
  composer/blog/gcp-tech-blog/data-orchestration-with-composer/__init__.py
  composer/blog/gcp-tech-blog/data-orchestration-with-composer/conftest.py
  composer/blog/gcp-tech-blog/data-orchestration-with-composer/constraints.txt
  composer/blog/gcp-tech-blog/data-orchestration-with-composer/dags/__init__.py
  composer/blog/gcp-tech-blog/data-orchestration-with-composer/dags/data_orchestration_blog_sample_dag.py
  composer/blog/gcp-tech-blog/data-orchestration-with-composer/dags/data_orchestration_blog_sample_dag_test.py
  composer/blog/gcp-tech-blog/data-orchestration-with-composer/noxfile_config.py
  composer/blog/gcp-tech-blog/data-orchestration-with-composer/requirements-test.txt
  composer/blog/gcp-tech-blog/data-orchestration-with-composer/requirements.txt
Labels: cla: yes, samples

#6163 chore(healthcare): increased timeout to reduce flakiness
  healthcare/api-client/v1/fhir/fhir_resources_test.py
  healthcare/api-client/v1/fhir/fhir_stores_test.py
  healthcare/api-client/v1beta1/fhir/fhir_resources_test.py
  healthcare/api-client/v1beta1/fhir/fhir_stores_test.py
Labels: api: healthcare, cla: yes, samples

#6167 fix: Update todo variables
  appengine/flexible/tasks/create_app_engine_queue_task.py
Labels: cla: yes, samples

#6162 chore: Updating list of documents
  compute/metadata/README.md
Labels: cla: yes, samples

#6122 Chc cleanup hl7v2
  healthcare/api-client/v1/hl7v2/README.rst
  healthcare/api-client/v1/hl7v2/hl7v2_messages.py
  healthcare/api-client/v1/hl7v2/hl7v2_messages_test.py
  healthcare/api-client/v1/hl7v2/hl7v2_stores.py
  healthcare/api-client/v1/hl7v2/hl7v2_stores_test.py
Labels: cla: yes, samples

#6168 Add m-strzelczyk@ as codeowner for compute
  .github/CODEOWNERS
  .github/blunderbuss.yml
Labels: cla: yes, samples

#5888 healthcare API: DICOM v1 formatting fixes and cleanup
  healthcare/api-client/v1/dicom/README.rst
  healthcare/api-client/v1/dicom/dicom_stores.py
  healthcare/api-client/v1/dicom/dicom_stores_test.py
  healthcare/api-client/v1/dicom/dicomweb.py
  healthcare/api-client/v1/dicom/dicomweb_test.py
Labels: cla: yes, samples

#6169 fix: Compute VM Identity issue #6156
  compute/metadata/vm_identity.py
  compute/metadata/vm_identity_test.py
Labels: cla: yes, samples

#6164 samples: removes Media Translation samples from repo
  media-translation/cloud-client/README.rst
  media-translation/cloud-client/README.rst.in
  media-translation/cloud-client/requirements-test.txt
  media-translation/cloud-client/requirements.txt
  media-translation/cloud-client/resources/audio.raw
  media-translation/cloud-client/translate_from_file.py
  media-translation/cloud-client/translate_from_file_test.py
  media-translation/cloud-client/translate_from_mic.py
Labels: cla: yes, samples

#6181 Update composer readme
  composer/tools/README.md
Labels: cla: yes, samples

#6184 ignore composer blog constraints
  renovate.json
Labels: cla: yes, samples

#6198 remove package pattern throwing a warning
  renovate.json
Labels: automerge, cla: yes, samples

#6227 Update renovate.json
  renovate.json
Labels: cla: yes, samples

#6250 ppai/image-classification: fix dependency conflicts
  people-and-planet-ai/image-classification/README.ipynb
  people-and-planet-ai/image-classification/requirements.txt
Labels: cla: yes, samples

#6247 feat: add retry to test
  run/idp-sql/test/e2e_test.py
Labels: automerge, cla: yes, samples

#4971 public access prevention samples & tests
  storage/cloud-client/conftest.py
  storage/cloud-client/public_access_prevention_test.py
  storage/cloud-client/requirements.txt
  storage/cloud-client/storage_get_bucket_metadata.py
  storage/cloud-client/storage_get_public_access_prevention.py
  storage/cloud-client/storage_set_public_access_prevention_enforced.py
  storage/cloud-client/storage_set_public_access_prevention_unspecified.py
  storage/cloud-client/uniform_bucket_level_access_test.py
Labels: cla: yes, samples
