Repository GoogleCloudPlatform/python-docs-samples, pull requests merged in 2021-05, with the labels that each got.

#5741 fix(docs): corrects typos in project documentation
  appengine/standard/i18n/README.md
  cloud-sql/mysql/client-side-encryption/README.md
  cloud-sql/mysql/sqlalchemy/README.md
  cloud-sql/postgres/client-side-encryption/README.md
  cloud-sql/postgres/sqlalchemy/README.md
  notebooks/rendered/bigquery-basics.md
  run/image-processing/README.md
Labels: automerge, cla: yes, samples

#5790 Update gcloud version
  .kokoro/docker/Dockerfile
  run/image-processing/e2e_test.py
  run/pubsub/e2e_test.py
Labels: cla: yes, samples

#5789 chore: add alwaysCreateStatusCheck config for snippet-bot
  .github/snippet-bot.yml
Labels: cla: yes, samples

#5806 add pip version override for virtualenv in nox
  noxfile-template.py
  noxfile_config.py
Labels: cla: yes, samples

#5837 chore: add snippet-bot's checks to the protection rule
  .github/sync-repo-settings.yaml
Labels: cla: yes, samples

#5848 prepare utils for pypi distribution
  composer/dag_test_utils/README.md
  composer/dag_test_utils/pyproject.toml
  composer/dag_test_utils/setup.py
Labels: api: composer, cla: yes, samples

#5738 healthcare API: FHIR v1 formatting fixes and cleanup
  healthcare/api-client/v1/fhir/README.rst
  healthcare/api-client/v1/fhir/fhir_resources.py
  healthcare/api-client/v1/fhir/fhir_resources_test.py
  healthcare/api-client/v1/fhir/fhir_stores.py
  healthcare/api-client/v1/fhir/fhir_stores_test.py
Labels: cla: yes, samples

#5860 Change composer requirements to point to released package
  composer/blog/gcp-tech-blog/unit-test-dags-cloud-build/requirements-test.txt
  composer/workflows/requirements-test.txt
Labels: api: composer, cla: yes, samples

#5862 docs: describe event and context in Pub/Sub example
  functions/helloworld/main.py
  functions/helloworld/sample_pubsub_test.py
Labels: cla: yes, samples

#5760 Add retry sample to STS
  storage/transfer_service/get_transfer_job_with_retries.py
  storage/transfer_service/sts_snippets_test.py
Labels: automerge, cla: yes, samples

#5868 chore: tmatsuo out
  .github/blunderbuss.yml
Labels: cla: yes, samples

#5770 fix(data-science-onramp): Change file names, remove extra dependencies for model training
  data-science-onramp/ai-platform/modules/setup.py
  data-science-onramp/ai-platform/modules/trainer/sklearn_model/task.py
  data-science-onramp/ai-platform/modules/trainer/tfkeras_model/task.py
  data-science-onramp/ai-platform/noxfile_config.py
  data-science-onramp/ai-platform/sklearn_test.py
  data-science-onramp/ai-platform/tfkeras_test.py
  data-science-onramp/data-ingestion/ingestion.py
  data-science-onramp/data-ingestion/ingestion.sh
  data-science-onramp/data-ingestion/ingestion_test.py
  data-science-onramp/data-processing/README.md
  data-science-onramp/data-processing/noxfile_config.py
  data-science-onramp/data-processing/process.py
  data-science-onramp/data-processing/process_test.py
  data-science-onramp/data-processing/requirements-test.txt
  data-science-onramp/data-processing/requirements.txt
  data-science-onramp/data-processing/testing_data/raw_data.csv
Labels: cla: yes, samples

#5855 chore: convert the header-checker-lint.yml to yaml
  .github/header-checker-lint.yml
Labels: automerge, cla: yes, samples

#5834 Fix deprecation warning for sqlalchemy 1.4
  cloud-sql/postgres/sqlalchemy/main.py
Labels: cla: yes, samples

#5874 chore(deps): update Renovate to ignore patches
  renovate.json
Labels: cla: yes, samples

#5876 fix deprecation warnings and update documentation in SQL samples
  cloud-sql/mysql/client-side-encryption/snippets/cloud_sql_connection_pool.py
  cloud-sql/mysql/sqlalchemy/README.md
  cloud-sql/mysql/sqlalchemy/main.py
  cloud-sql/postgres/client-side-encryption/snippets/cloud_sql_connection_pool.py
  cloud-sql/postgres/sqlalchemy/README.md
  cloud-sql/sql-server/sqlalchemy/main.py
  run/idp-sql/database.py
Labels: cla: yes, samples

#5872 docs: update AUTHORING_GUIDE
  AUTHORING_GUIDE.md
Labels: automerge, cla: yes, samples

#5865 Update dag test utils for Airflow 2.0
  composer/dag_test_utils/CHANGELOG.md
  composer/dag_test_utils/MAINTAINING.md
  composer/dag_test_utils/README.md
  composer/dag_test_utils/internal_unit_testing.py
  composer/dag_test_utils/setup.py
  composer/workflows/requirements-test.txt
Labels: cla: yes, samples

#5891 Update CODEOWNERS and Blunderbuss for SoDa
  .github/CODEOWNERS
  .github/blunderbuss.yml
Labels: cla: yes, samples
