Repository GoogleCloudPlatform/python-docs-samples, pull requests merged in 2021-01, with the labels that each got.

#5193 Adding "replace_microseconds" parameter to API
  composer/functions/composer_storage_trigger.py
Labels: cla: yes, samples

#5199 Add git dependency to Dataflow Flex template Dockerfile
  dataflow/flex-templates/streaming_beam/Dockerfile
Labels: automerge, cla: yes, samples

#5212 Fix typo in Dockerfile
  run/deployment-previews/Dockerfile
  run/deployment-previews/check_status.py
Labels: cla: yes, samples

#5217 Strip spaces and newlines from secret
  run/deployment-previews/check_status.py
Labels: automerge, cla: yes, samples

#5067 dataflow: add GPU sample
  dataflow/gpu-workers/.dockerignore
  dataflow/gpu-workers/.gcloudignore
  dataflow/gpu-workers/Dockerfile
  dataflow/gpu-workers/README.md
  dataflow/gpu-workers/e2e_test.py
  dataflow/gpu-workers/landsat_view.py
  dataflow/gpu-workers/noxfile_config.py
  dataflow/gpu-workers/requirements-test.txt
  dataflow/gpu-workers/requirements.txt
Labels: api: dataflow, cla: yes, samples

#5221 Add feature engineering notebook
  data-science-onramp/feature-engineering/feature_engineering.ipynb
Labels: automerge, cla: yes, samples

#5188 docs: fix simple typo, tempaltes -> templates
  appengine/standard/i18n/README.md
Labels: automerge, cla: yes, samples

#5215 docs: fix link with public domain
  dataflow/flex-templates/streaming_beam/README.md
Labels: cla: yes, samples

#5228 chore: remove docai v1beta samples
  document/README.rst
  document/cloud-client/batch_parse_form_beta.py
  document/cloud-client/batch_parse_form_beta_test.py
  document/cloud-client/batch_parse_table_beta.py
  document/cloud-client/batch_parse_table_beta_test.py
  document/cloud-client/parse_form_beta.py
  document/cloud-client/parse_form_beta_test.py
  document/cloud-client/parse_table_beta.py
  document/cloud-client/parse_table_beta_test.py
  document/cloud-client/parse_with_model_beta.py
  document/cloud-client/parse_with_model_beta_test.py
  document/cloud-client/quickstart_beta.py
  document/cloud-client/quickstart_beta_test.py
  document/cloud-client/requirements-test.txt
  document/cloud-client/requirements.txt
  document/cloud-client/set_endpoint_beta.py
  document/cloud-client/set_endpoint_beta_test.py
Labels: automerge, cla: yes, samples

#5237 fix(healthcare): add more retries for mitigating flakes
  healthcare/api-client/v1/datasets/datasets_test.py
  healthcare/api-client/v1beta1/fhir/fhir_resources_test.py
Labels: api: healthcare, cla: yes, samples

#5227 add header checker config
  .github/header-checker-lint.yml
Labels: cla: yes, samples

#5192 chore(appengine): add support for application/json
  appengine/flexible/tasks/create_app_engine_queue_task.py
Labels: api: appengine, cla: yes, samples

#5254 chore(GAE flex): rm unused SQL samples
  appengine/flexible/cloudsql/README.md
  appengine/flexible/cloudsql/app.yaml
  appengine/flexible/cloudsql/create_tables.py
  appengine/flexible/cloudsql/main.py
  appengine/flexible/cloudsql/main_test.py
  appengine/flexible/cloudsql/requirements-test.txt
  appengine/flexible/cloudsql/requirements.txt
  appengine/flexible/cloudsql_postgresql/app.yaml
  appengine/flexible/cloudsql_postgresql/create_tables.py
  appengine/flexible/cloudsql_postgresql/main.py
  appengine/flexible/cloudsql_postgresql/main_test.py
  appengine/flexible/cloudsql_postgresql/requirements-test.txt
  appengine/flexible/cloudsql_postgresql/requirements.txt
Labels: cla: yes, samples

#5263 Add iot team as code owner
  .github/CODEOWNERS
Labels: cla: yes, samples

#5271 chore(GAE flex): rm unused memcache sample
  appengine/flexible/memcache/README.md
  appengine/flexible/memcache/app.yaml
  appengine/flexible/memcache/main.py
  appengine/flexible/memcache/main_test.py
  appengine/flexible/memcache/noxfile.py
  appengine/flexible/memcache/requirements-test.txt
  appengine/flexible/memcache/requirements.txt
Labels: automerge, cla: yes, samples

#5273 chore(GAE): remove unused redis sample
  appengine/flexible/redis/app.yaml
  appengine/flexible/redis/main.py
  appengine/flexible/redis/main_test.py
  appengine/flexible/redis/requirements-test.txt
  appengine/flexible/redis/requirements.txt
Labels: automerge, cla: yes, samples

#5267 fix(trace): resolve pip conflicts
  trace/cloud-trace-demo-app-opentelemetry/app/noxfile_config.py
  trace/cloud-trace-demo-app-opentelemetry/app/requirements.txt
  trace/cloud-trace-demo-app/app/noxfile_config.py
  trace/cloud-trace-demo-app/app/requirements.txt
  trace/trace-python-sample-opentelemetry/noxfile_config.py
  trace/trace-python-sample-opentelemetry/requirements.txt
Labels: api: cloudtrace, cla: yes, samples

#5261 Increase verbosity for debugging Django timeouts
  run/django/cloudmigrate.yaml
Labels: cla: yes, samples

#5285 fix(healthcare): retry flaky test
  healthcare/api-client/v1/dicom/dicom_stores_test.py
Labels: api: healthcare, cla: yes, samples

#5286 fix: update index.html
  appengine/standard_python3/pubsub/templates/index.html
Labels: cla: yes, samples

#5302 fix(healthcare): retry flaky test
  healthcare/api-client/v1beta1/fhir/fhir_stores_test.py
Labels: api: healthcare, cla: yes, samples

#5305 fix(run): Clarify the source of GOOGLE_CLOUD_PROJECT var
  run/logging-manual/main.py
Labels: api: run, cla: yes, samples

#5301 fix(django): correct default secret name
  run/django/cloudmigrate.yaml
Labels: automerge, cla: yes, samples

#5304 build: migrate to flakybot
  .kokoro/tests/run_single_test.sh
  .kokoro/tests/run_tests_orig.sh
  .kokoro/trampoline_v2.sh
Labels: cla: yes, samples
