Repository GoogleCloudPlatform/python-docs-samples, pull requests merged in 2021-08, with the labels that each got.

#6505 chore: Remove deprecated region tag
  appengine/flexible/django_cloudsql/mysite/settings.py
  kubernetes_engine/django_tutorial/mysite/settings.py
  run/django/mysite/settings.py
Labels: cla: yes, samples

#5736 Remove unnecessary order_by field in a query
  firestore/cloud-client/snippets.py
Labels: automerge, cla: yes, samples

#6438 chore: Handle AutoGKE in composer_db_transfer.py
  composer/tools/composer_db_transfer.py
Labels: cla: yes, samples

#6509 Add back timestamp protobuf
  appengine/flexible/tasks/create_app_engine_queue_task.py
Labels: cla: yes, samples

#6503 ppai/image-classification: use new model
  people-and-planet-ai/image-classification/e2e_test.py
Labels: cla: yes, samples

#6528 ppai/image-classification: use new model
  people-and-planet-ai/image-classification/e2e_test.py
Labels: cla: yes, samples

#6529 fix(storage): update service account email for acl tests
  storage/cloud-client/acl_test.py
Labels: cla: yes, api: storage, samples

#6530 New sample for Functions v2
  functions/v2/pubsub/main.py
  functions/v2/pubsub/main_test.py
  functions/v2/pubsub/requirements-test.txt
  functions/v2/pubsub/requirements.txt
Labels: cla: yes, api: cloudfunctions, samples

#6527 Load empty db with AF 1.10.14 schema instead of running an init job
  composer/tools/composer_db_transfer.py
Labels: cla: yes, automerge, samples

#6532 fix(samples): fix column name in DagModel of Airflow workflow to clean up database
  composer/workflows/airflow_db_cleanup.py
  composer/workflows/constraints.txt
  composer/workflows/requirements.txt
Labels: cla: yes, automerge, samples

#6540 chore: update Dataproc codeowners
  .github/CODEOWNERS
Labels: cla: yes, samples

#6547 chore: update CODEOWNERS
  .github/CODEOWNERS
  .github/blunderbuss.yml
Labels: cla: yes, automerge, samples, api: auth

#6553 docs(storage): update description in storage_download_file
  storage/cloud-client/storage_download_file.py
Labels: cla: yes, api: storage, samples

#6542 feat: add downscoping with Credential Access Boundaries samples
  auth/downscoping/README.md
  auth/downscoping/requirements-test.txt
  auth/downscoping/requirements.txt
  auth/downscoping/snippets.py
  auth/downscoping/snippets_test.py
Labels: cla: yes, samples

#6511 chore: fix output formatting of HL7v2 notificationConfigs
  healthcare/api-client/v1/hl7v2/README.rst
  healthcare/api-client/v1/hl7v2/hl7v2_stores.py
Labels: cla: yes, automerge, samples

#6552 Add dependency to HTML
  appengine/standard_python3/building-an-app/building-an-app-3/templates/index.html
Labels: cla: yes, automerge, samples

#6545 more codeowner/blunderbuss updates
  .github/CODEOWNERS
  .github/blunderbuss.yml
Labels: cla: yes, automerge, samples

#6534 Update example to apps/v1
  endpoints/kubernetes/grpc-bookstore.yaml
Labels: cla: yes, automerge, samples

#6556 add info about Dataflow region availability
  composer/airflow_1_samples/dataproc_workflow_template_instantiate_operator_tutorial.py
  composer/workflows/dataflowtemplateoperator_tutorial.py
Labels: cla: yes, automerge, samples

#6560 Use requirements.txt instead of hard-coded install
  run/helloworld/Dockerfile
Labels: cla: yes, automerge, samples

#6561 feat: update Transcoder API samples to v1
  media/transcoder/create_job_from_ad_hoc.py
  media/transcoder/create_job_from_preset.py
  media/transcoder/create_job_from_template.py
  media/transcoder/create_job_template.py
  media/transcoder/create_job_with_animated_overlay.py
  media/transcoder/create_job_with_periodic_images_spritesheet.py
  media/transcoder/create_job_with_set_number_images_spritesheet.py
  media/transcoder/create_job_with_static_overlay.py
  media/transcoder/delete_job.py
  media/transcoder/delete_job_template.py
  media/transcoder/get_job.py
  media/transcoder/get_job_state.py
  media/transcoder/get_job_template.py
  media/transcoder/job_template_test.py
  media/transcoder/list_job_templates.py
  media/transcoder/list_jobs.py
Labels: cla: yes, automerge, samples

#6554 Add storage move_blob sample and fix confusion with rename
  storage/cloud-client/snippets_test.py
  storage/cloud-client/storage_move_file.py
  storage/cloud-client/storage_rename_file.py
Labels: cla: yes, samples

#6563 chore(dataflow): remove old gpu-workers sample
  dataflow/gpu-workers/.dockerignore
  dataflow/gpu-workers/.gcloudignore
  dataflow/gpu-workers/Dockerfile
  dataflow/gpu-workers/README.md
  dataflow/gpu-workers/cloudbuild.yaml
  dataflow/gpu-workers/e2e_test.py
  dataflow/gpu-workers/landsat_view.py
  dataflow/gpu-workers/noxfile_config.py
  dataflow/gpu-workers/requirements-test.txt
  dataflow/gpu-workers/requirements.txt
Labels: cla: yes, automerge, api: dataflow, samples

#4885 fix(samples): v1 and v1beta1 region tags collide
  healthcare/api-client/v1beta1/fhir/fhir_resources.py
  healthcare/api-client/v1beta1/fhir/fhir_stores.py
Labels: cla: yes, automerge, samples

#6581 docs: require timezone aware datetimes
  AUTHORING_GUIDE.md
Labels: cla: yes, automerge, samples

#6591 chore: Review the language fixes.
  storage/cloud-client/storage_add_bucket_iam_member.py
  storage/cloud-client/storage_create_hmac_key.py
  workflows/cloud-client/main.py
Labels: cla: yes, samples

#6634 clarify samples noxfile instructions
  AUTHORING_GUIDE.md
Labels: cla: yes, samples
