Repository GoogleCloudPlatform/python-docs-samples, pull requests merged in 2021-12, with the labels that each got.

#7167 test: update Kokoro to use main branch
  .kokoro/lint/presubmit.cfg
  .kokoro/python2.7/presubmit.cfg
  .kokoro/python3.10/presubmit.cfg
  .kokoro/python3.6/presubmit.cfg
  .kokoro/python3.7/presubmit.cfg
  .kokoro/python3.8/presubmit.cfg
  .kokoro/python3.9/presubmit.cfg
  .kokoro/tests/run_tests.sh
  .kokoro/tests/run_tests_diff_main.sh
  .kokoro/tests/run_tests_orig.sh
Labels: cla: yes, samples

#7180 ppai/timeseries-classification: use check_call instead of run
  people-and-planet-ai/timeseries-classification/e2e_test.py
Labels: cla: yes, samples

#7159 Fix flaky tests by running slow deletion as a background task
  auth/service-to-service/auth_test.py
  memorystore/redis/cloud_run_deployment/e2e_test.py
  run/filesystem/e2e_test.py
  run/hello-broken/e2e_test.py
  run/helloworld/e2e_test.py
  run/image-processing/e2e_test.py
  run/logging-manual/e2e_test.py
  run/markdown-preview/e2e_test.py
  run/pubsub/e2e_test.py
  run/system-package/e2e_test.py
Labels: cla: yes, samples

#7186 fix: Remove invalid --async flag from functions command
  auth/service-to-service/auth_test.py
Labels: cla: yes, samples

#7189 Bump numpy/scipy in appengine/flexible
  appengine/flexible/numpy/requirements.txt
  appengine/flexible/scipy/requirements.txt
Labels: cla: yes, samples

#7188 chore: clean up data cleaning residue
  data-science-onramp/data-processing/README.md
  data-science-onramp/data-processing/process.py
Labels: cla: yes, samples

#7190 Upgrade pandas in BQ samples lagging in python 3.10
  bigquery/bqml/requirements.txt
  bigquery/pandas-gbq-migration/requirements.txt
Labels: cla: yes, samples

#7194 fix(functions/v2/storage): fix incorrect region tag
  functions/v2/storage/main.py
Labels: cla: yes, api: cloudfunctions, samples

#7193 refactor: update http sample
  functions/helloworld/main.py
Labels: cla: yes, automerge, samples

#7198 dataflow: simplify authentication instructions
  dataflow/README.md
Labels: cla: yes, api: dataflow, samples

#7219 chore: add comment to cloudsql unix socket sample
  cloud-sql/postgres/sqlalchemy/main.py
Labels: samples

#7091 feat: Add samples for STS GAPIC client
  .github/CODEOWNERS
  .kokoro/tests/run_tests.sh
  storage/transfer_service/README.md
  storage/transfer_service/README.rst.in
  storage/transfer_service/requirements-test.txt
  storage/transfer_service/sts_snippets_test.py
  storagetransfer/README.rst
  storagetransfer/README.rst.in
  storagetransfer/aws_request.py
  storagetransfer/aws_request_apiary.py
  storagetransfer/aws_request_test.py
  storagetransfer/check_latest_transfer_operation.py
  storagetransfer/check_latest_transfer_operation_apiary.py
  storagetransfer/check_latest_transfer_operation_test.py
  storagetransfer/conftest.py
  storagetransfer/create_client.py
  storagetransfer/create_client_apiary.py
  storagetransfer/create_client_test.py
  storagetransfer/get_transfer_job_with_retries.py
  storagetransfer/get_transfer_job_with_retries_apiary.py
  storagetransfer/get_transfer_job_with_retries_test.py
  storagetransfer/nearline_request.py
  storagetransfer/nearline_request_apiary.py
  storagetransfer/nearline_request_test.py
  storagetransfer/noxfile_config.py
  storagetransfer/quickstart.py
  storagetransfer/requirements-test.txt
  storagetransfer/requirements.txt
  storagetransfer/transfer_check.py
  storagetransfer/transfer_check_apiary.py
  storagetransfer/transfer_check_test.py
Labels: cla: yes, samples

#7217 feat(functions/v2): add GCE + CAL sample
  functions/v2/label_gce_instance/main.py
  functions/v2/label_gce_instance/main_test.py
  functions/v2/label_gce_instance/requirements-test.txt
  functions/v2/label_gce_instance/requirements.txt
Labels: api: cloudfunctions, samples

#7222 exempt some samples from python 3.10 tests
  appengine/standard_python3/cloud_debugger/noxfile_config.py
  cloud-sql/mysql/client-side-encryption/noxfile_config.py
  cloud-sql/postgres/client-side-encryption/noxfile_config.py
  cloud-sql/sql-server/client-side-encryption/noxfile_config.py
Labels: samples

#7239 chore(functions/label_gce_instance): update GCE library
  functions/v2/label_gce_instance/main.py
  functions/v2/label_gce_instance/requirements.txt
Labels: api: cloudfunctions, samples

#7259 exempt constraint file
  renovate.json
Labels: samples

#7218 feat: Prevent overriding the value from config
  run/django/mysite/settings.py
Labels: automerge, samples

#7301 Cleanup cluster if error during creation
  data-science-onramp/data-ingestion/ingestion.py
  data-science-onramp/data-ingestion/ingestion_test.py
  data-science-onramp/data-processing/process.py
  data-science-onramp/data-processing/process_test.py
Labels: samples
