Repository GoogleCloudPlatform/python-docs-samples, pull requests merged in 2021-11, with the labels that each got.

#6935 docs: clarify default preset
  media/transcoder/create_job_from_preset.py
Labels: cla: yes, automerge, samples

#7034 group dataflow dependency updates
  dataflow/gpu-examples/pytorch-minimal/Dockerfile
  dataflow/gpu-examples/pytorch-minimal/requirements.txt
  dataflow/gpu-examples/tensorflow-landsat/Dockerfile
  dataflow/gpu-examples/tensorflow-landsat/requirements.txt
  dataflow/gpu-examples/tensorflow-minimal/Dockerfile
  dataflow/gpu-examples/tensorflow-minimal/requirements.txt
Labels: cla: yes, samples

#7023 samples: fix flaky test teardown in servicedirectory
  servicedirectory/snippets_test.py
Labels: cla: yes, automerge, samples

#7015 Update Cloud SQL sample apps with Kubernetes Engine yaml files.
  cloud-sql/mysql/sqlalchemy/deployment.yaml
  cloud-sql/mysql/sqlalchemy/service-account.yaml
  cloud-sql/mysql/sqlalchemy/service.yaml
  cloud-sql/postgres/sqlalchemy/deployment.yaml
  cloud-sql/postgres/sqlalchemy/service-account.yaml
  cloud-sql/postgres/sqlalchemy/service.yaml
Labels: cla: yes, samples

#7040 Fix link to external Django tutorial
  appengine/standard/django/README.md
Labels: cla: yes, automerge, samples

#7057 add constraint on WTForms
  composer/airflow_1_samples/constraints.txt
  composer/airflow_1_samples/noxfile_config.py
  composer/blog/gcp-tech-blog/unit-test-dags-cloud-build/constraints.txt
Labels: cla: yes, automerge, samples

#7058 Update Cloud Run logging test
  run/logging-manual/e2e_test.py
Labels: cla: yes, automerge, samples

#6927 Add a sample for triggering DAGs in Composer 2 using Airflow REST API
  composer/rest/composer2/composer2_airflow_rest_api.py
  composer/rest/composer2/composer2_airflow_rest_api_test.py
  composer/rest/composer2/requirements-test.txt
  composer/rest/composer2/requirements.txt
Labels: cla: yes, automerge, samples

#7077 fix: 3.10 build - Remove noxfiles, add noxfile_configs where needed
  cloud-sql/mysql/sqlalchemy/noxfile.py
  cloud-sql/postgres/sqlalchemy/noxfile.py
  ml_engine/online_prediction/noxfile.py
  ml_engine/online_prediction/noxfile_config.py
  pubsub/streaming-analytics/noxfile.py
  pubsub/streaming-analytics/noxfile_config.py
  run/markdown-preview/editor/noxfile.py
  run/markdown-preview/renderer/noxfile.py
Labels: cla: yes, automerge, samples

#6964 build: use latest pip (21.3.1)
  .kokoro/docker/Dockerfile
Labels: cla: yes, samples

#6587 Use timezone aware datetimes
  AUTHORING_GUIDE.md
  appengine/flexible/datastore/main.py
  appengine/flexible/tasks/create_app_engine_queue_task.py
  appengine/standard/mail/user_signup.py
  appengine/standard_python3/building-an-app/building-an-app-2/main.py
  appengine/standard_python3/building-an-app/building-an-app-3/main.py
  appengine/standard_python3/building-an-app/building-an-app-4/main.py
  appengine/standard_python3/pubsub/main_test.py
  blog/introduction_to_data_models_in_cloud_datastore/blog.py
  blog/introduction_to_data_models_in_cloud_datastore/wiki.py
  cloud-sql/mysql/client-side-encryption/snippets/encrypt_and_insert_data.py
  cloud-sql/mysql/sqlalchemy/main.py
  cloud-sql/postgres/client-side-encryption/snippets/encrypt_and_insert_data.py
  cloud-sql/postgres/sqlalchemy/main.py
  cloud-sql/sql-server/client-side-encryption/snippets/encrypt_and_insert_data.py
  cloud-sql/sql-server/sqlalchemy/main.py
  composer/airflow_1_samples/bq_copy_across_locations.py
  composer/airflow_1_samples/hadoop_tutorial.py
  composer/airflow_1_samples/kubernetes_pod_operator.py
  composer/airflow_1_samples/quickstart.py
  composer/airflow_1_samples/unit_testing_cycle.py
  composer/airflow_1_samples/unit_testing_variables.py
  composer/workflows/bq_copy_across_locations.py
  composer/workflows/hadoop_tutorial.py
  composer/workflows/kubernetes_pod_operator.py
  composer/workflows/quickstart.py
  composer/workflows/unit_testing_cycle.py
  composer/workflows/unit_testing_variables.py
  datastore/cloud-client/snippets.py
  datastore/cloud-client/tasks.py
  firestore/cloud-async-client/snippets.py
  firestore/cloud-client/snippets.py
  functions/helloworld/sample_storage_test_integration.py
  iot/api-client/codelabs/gateway.py
  iot/api-client/end_to_end_example/cloudiot_pubsub_example_mqtt_device.py
  iot/api-client/gcs_file_to_device/gcs_example_mqtt_device.py
  iot/api-client/http_example/cloudiot_http_example.py
  iot/api-client/mqtt_example/cloudiot_mqtt_example.py
  iot/api-client/mqtt_example/gateway_demo.py
  monitoring/api/v3/api-client/custom_metric.py
  monitoring/api/v3/api-client/list_resources.py
  run/idp-sql/main.py
  storage/signed_urls/generate_signed_urls.py
Labels: cla: yes, samples

#7089 fix: composer db upgrade script readme
  composer/tools/composer_db_transfer.md
Labels: cla: yes, samples

#7098 docs(samples): fix the header format
  iam/api-client/workload_identity_federation.py
Labels: cla: yes, samples

#7095 remove more rogue noxfiles
  cloud-sql/sql-server/sqlalchemy/noxfile.py
  dataflow/encryption-keys/noxfile.py
  dataflow/encryption-keys/noxfile_config.py
  eventarc/noxfile.py
Labels: cla: yes, automerge, samples

#7041 Update CONTRIBUTING and AUTHORING_GUIDE with submission and review guidelines
  .github/CODEOWNERS
  AUTHORING_GUIDE.md
  CONTRIBUTING.md
Labels: cla: yes, automerge, samples

#7143 fix: add testing for functions/v2/storage
  functions/v2/storage/main.py
  functions/v2/storage/main_test.py
  functions/v2/storage/requirements-test.txt
  functions/v2/storage/requirements.txt
Labels: cla: yes, priority: p2, samples

#7140 Using check_call to expose underlying error messages
  memorystore/redis/cloud_run_deployment/e2e_test.py
  run/django/test/e2e_test.py
  run/filesystem/e2e_test.py
  run/hello-broken/e2e_test.py
  run/helloworld/e2e_test.py
  run/idp-sql/test/e2e_test.py
  run/image-processing/e2e_test.py
  run/logging-manual/e2e_test.py
  run/markdown-preview/e2e_test.py
  run/pubsub/e2e_test.py
  run/system-package/e2e_test.py
Labels: cla: yes, samples

#7139 Fix `tempLocation` Dataflow parameter in Airflow example
  composer/airflow_1_samples/dataflowtemplateoperator_tutorial.py
  composer/workflows/dataflowtemplateoperator_tutorial.py
Labels: cla: yes, samples

#7151 Add region tags for the Composer 2 Airflow REST API example
  composer/rest/composer2/composer2_airflow_rest_api.py
Labels: cla: yes, samples

#7154 chore: update reference of master branch to main for other repositories
  .kokoro/tests/run_single_test.sh
  .kokoro/tests/run_tests_orig.sh
  AUTHORING_GUIDE.md
  asset/README.rst
  automl/README.rst
  bigquery/cloud-client/README.rst
  bigquery_storage/to_dataframe/README.rst
  cloud-sql/mysql/client-side-encryption/README.md
  cloud-sql/postgres/client-side-encryption/README.md
  cloud-sql/sql-server/client-side-encryption/README.md
  container_registry/container_analysis/README.md
  datacatalog/cloud-client/README.rst
  datalabeling/README.md
  dataproc/README.md
  dialogflow/cloud-client/README.rst
  dlp/README.md
  document/README.rst
  error_reporting/README.md
  iot/api-client/manager/README.md
  jobs/v4beta1/README.rst
  kms/README.rst
  language/README.md
  logging/cloud-client/README.rst
  monitoring/api/v3/alerts-client/README.md
  monitoring/api/v3/cloud-client/README.md
  monitoring/api/v3/uptime-check-client/README.md
  pubsub/cloud-client/README.rst
  scheduler/README.md
  secretmanager/README.md
  speech/README.rst
  tables/README.rst
  tasks/README.md
  texttospeech/cloud-client/README.rst
  translate/automl/README.rst
  translate/cloud-client/README.rst
  video/cloud-client/README.rst
  vision/cloud-client/README.md
Labels: cla: yes, samples

#7155 Rename clear file system dag
  composer/workflows/clear_file_system_caches_dag_composer_v1.py
  composer/workflows/clear_file_system_caches_dag_composer_v1_test.py
Labels: cla: yes, automerge, samples

#7157 feat(functions/v2): Add generic audit logging sample
  functions/v2/audit_log/main.py
  functions/v2/audit_log/main_test.py
  functions/v2/audit_log/requirements-test.txt
  functions/v2/audit_log/requirements.txt
Labels: cla: yes, samples

#7164 refactor: Update deployment preview to support built-in secrets, discovery API
  run/deployment-previews/Dockerfile
  run/deployment-previews/check_status.py
  run/deployment-previews/cloudbuild-configurations/cloudbuild-cleanup.yaml
  run/deployment-previews/cloudbuild-configurations/cloudbuild-preview.yaml
  run/deployment-previews/requirements.txt
  run/deployment-previews/test_app.py
Labels: cla: yes, automerge, samples

#7162 Private Service Connect integration
  composer/tools/composer_db_transfer.py
Labels: cla: yes, samples

#7121 refactor: update gcs sample
  functions/v2/storage/main.py
  functions/v2/storage/requirements.txt
Labels: cla: yes, samples

#7176 cleanup: Removing outdated wikibot sample
  compute/xmpp_wikibot/README.md
  compute/xmpp_wikibot/requirements-test.txt
  compute/xmpp_wikibot/requirements.txt
  compute/xmpp_wikibot/wikibot.py
Labels: cla: yes, samples

#7120 refactor: update pubsub sample
  functions/v2/pubsub/main.py
  functions/v2/pubsub/requirements.txt
Labels: cla: yes, automerge, samples

#7172 (fix) correct marshalling error in cloud build yaml
  run/deployment-previews/cloudbuild-configurations/cloudbuild-preview.yaml
Labels: cla: yes, automerge, samples

#7171 chore: register pubsublite CODEOWNERS and blunderbuss config
  .github/CODEOWNERS
  .github/blunderbuss.yml
Labels: cla: yes, automerge, samples
