Repository GoogleCloudPlatform/python-docs-samples, pull requests merged in 2021-03, with the labels that each got.

#5426 fix(datastore): longer LRO timeout
  datastore/cloud-client/admin.py
  datastore/cloud-client/admin_test.py
  datastore/cloud-client/snippets.py
  datastore/cloud-client/snippets_test.py
  datastore/cloud-client/tasks.py
  datastore/cloud-client/tasks_test.py
Labels: api: datastore, cla: yes, samples

#5437 fix(cloud-sql): dump cloud sql log file upon failure
  cloud-sql/mysql/sqlalchemy/connection_test.py
Labels: cla: yes, samples

#5438 fix(codelabs): retry GatewayTimeout
  codelabs/flex_and_vision/main_test.py
  codelabs/flex_and_vision/requirements-test.txt
Labels: cla: yes, samples

#5440 fix(data-science-onramp): fixing tests and adding a region tag
  data-science-onramp/ai-platform/modules/setup.py
  data-science-onramp/ai-platform/modules/trainer/sklearn_model/task.py
  data-science-onramp/ai-platform/modules/trainer/tfkeras_model/task.py
  data-science-onramp/ai-platform/sklearn_test.py
  data-science-onramp/ai-platform/tfkeras_test.py
Labels: cla: yes, samples

#5451 fix(healthcare): bump backoff timeouts to 240
  healthcare/api-client/v1/fhir/fhir_resources_test.py
  healthcare/api-client/v1/fhir/fhir_stores_test.py
  healthcare/api-client/v1beta1/fhir/fhir_resources_test.py
  healthcare/api-client/v1beta1/fhir/fhir_stores_test.py
Labels: api: healthcare, automerge, cla: yes, samples

#5278 (storage) add sample for check latest transfer operation in transfer …
  storage/transfer_service/check_latest_transfer_operation.py
  storage/transfer_service/sts_snippets_test.py
Labels: cla: yes, samples

#5465 testing: upgrade the test docker image to ubuntu 20.04
  .kokoro/docker/Dockerfile
Labels: cla: yes, samples

#5360 Add `blogs` folder for blog post code
  composer/blog/README.md
  composer/blog/__init__.py
  composer/blog/gcp-tech-blog/README.md
  composer/blog/gcp-tech-blog/__init__.py
  composer/blog/gcp-tech-blog/unit-test-dags-cloud-build/Dockerfile
  composer/blog/gcp-tech-blog/unit-test-dags-cloud-build/__init__.py
  composer/blog/gcp-tech-blog/unit-test-dags-cloud-build/dags/__init__.py
  composer/blog/gcp-tech-blog/unit-test-dags-cloud-build/dags/example_dag.py
  composer/blog/gcp-tech-blog/unit-test-dags-cloud-build/dags/example_dag_test.py
  composer/blog/gcp-tech-blog/unit-test-dags-cloud-build/renovate.json
  composer/blog/gcp-tech-blog/unit-test-dags-cloud-build/requirements-composer.txt
  composer/blog/gcp-tech-blog/unit-test-dags-cloud-build/requirements-test.txt
  composer/blog/gcp-tech-blog/unit-test-dags-cloud-build/requirements.txt
  composer/blog/gcp-tech-blog/unit-test-dags-cloud-build/test-dags.cloudbuild.yaml
  composer/blog/gcp-tech-blog/unit-test-dags-cloud-build/update-composer.cloudbuild.yaml
Labels: cla: yes, samples

#5492 fixed inconsistency of dotenv in run/django project
  run/django/mysite/settings.py
Labels: automerge, cla: yes, samples

#5468 adding prediction data and fixing training columns used
  data-science-onramp/ai-platform/modules/trainer/utils.py
  data-science-onramp/ai-platform/predict.json
Labels: cla: yes, samples

#5496 fix(datastore): properly retry the test
  datastore/cloud-client/admin_test.py
Labels: api: datastore, cla: yes, samples

#5498 chore: delete eventarc anthos files
  eventarc/audit-storage/anthos.md
  eventarc/pubsub/anthos.md
Labels: automerge, cla: yes, samples

#5469 Fix sample config file
  composer/blog/gcp-tech-blog/unit-test-dags-cloud-build/update-composer.cloudbuild.yaml
Labels: cla: yes, samples

#5499 fix: broken composer tests
  composer/blog/gcp-tech-blog/unit-test-dags-cloud-build/dags/example_dag_test.py
  composer/blog/noxfile_config.py
  composer/conftest.py
  composer/workflows/airflow_db_cleanup_test.py
  composer/workflows/bq_copy_across_locations_test.py
  composer/workflows/bq_notify_test.py
  composer/workflows/dataflowtemplateoperator_tutorial_test.py
  composer/workflows/dataproc_workflow_template_instantiate_operator_tutorial_test.py
  composer/workflows/hadoop_tutorial_test.py
  composer/workflows/quickstart_test.py
  composer/workflows/unit_testing_test.py
Labels: api: composer, cla: yes, samples

#5512 chore(composer): readme-only changes
  composer/blog/README.md
  composer/blog/gcp-tech-blog/unit-test-dags-cloud-build/README.md
Labels: api: composer, cla: yes, samples

#5530 Explicitly pin SQLAlchemy for composer samples
  composer/blog/gcp-tech-blog/unit-test-dags-cloud-build/requirements.txt
  composer/workflows/requirements.txt
Labels: cla: yes, samples

#5515 fix(composer): use separate airflow db file per session
  composer/blog/gcp-tech-blog/unit-test-dags-cloud-build/dags/example_dag_test.py
  composer/blog/gcp-tech-blog/unit-test-dags-cloud-build/noxfile_config.py
  composer/conftest.py
  composer/workflows/noxfile_config.py
  composer/workflows/quickstart_test.py
Labels: api: composer, cla: yes, samples

#5533 fix(datascienceonramp): revert workaround
  data-science-onramp/data-cleaning/clean_test.py
  data-science-onramp/data-ingestion/setup_test.py
Labels: automerge, cla: yes, samples

#5527 docs: add region tag for sigterm handler
  run/idp-sql/main.py
Labels: automerge, cla: yes, samples

#5357 Dataflow gpu
  dataflow/gpu-workers/.dockerignore
  dataflow/gpu-workers/.gcloudignore
  dataflow/gpu-workers/e2e_test.py
  dataflow/gpu-workers/landsat_view.py
Labels: automerge, cla: yes, samples

#5548 chore(functions): remove RTDB path params
  functions/firebase/main.py
  functions/firebase/main_test.py
Labels: api: cloudfunctions, cla: yes, samples

#5547 Pub/Sub: enable parallel writes to GCS in Pub/Sub Dataflow example
  pubsub/streaming-analytics/PubSubToGCS.py
  pubsub/streaming-analytics/PubSubToGCS_test.py
  pubsub/streaming-analytics/README.md
Labels: cla: yes, samples

#5543 fix(datastore): properly retry a flaky test
  datastore/cloud-client/admin_test.py
  datastore/cloud-client/snippets_test.py
Labels: api: datastore, automerge, cla: yes, samples

#5560 docs: update eventarc docs
  eventarc/README.md
  eventarc/audit-storage/README.md
  eventarc/pubsub/README.md
Labels: automerge, cla: yes, samples

#5561 chore(eventarc): update region tags
  eventarc/audit-storage/Dockerfile
  eventarc/audit-storage/main.py
Labels: api: eventarc, automerge, cla: yes, samples

#5541 Add two custom flags to allow custom root CA path and hostname override in endpoints bookstore_client.py
  endpoints/bookstore-grpc/bookstore_client.py
Labels: automerge, cla: yes, samples

#5577 feat: add environment variables for dialogflow samples.
  testing/test-env.tmpl.sh
Labels: cla: yes, samples

#5554 chore: add bazel to testing Dockerfile
  .kokoro/docker/Dockerfile
Labels: cla: yes, samples

#5590 fix(jobs): add more retries
  jobs/v3/api_client/general_search_sample_test.py
  jobs/v3/api_client/histogram_sample_test.py
Labels: api: jobs, cla: yes, samples

#5592 fix(healthcare): retry sample invocations
  healthcare/api-client/v1/fhir/fhir_stores_test.py
Labels: api: healthcare, cla: yes, samples

#5536 docs: added type hints and comments to Datastore samples
  datastore/cloud-client/snippets.py
  datastore/cloud-client/tasks.py
Labels: cla: yes, samples
