Repository GoogleCloudPlatform/python-docs-samples, pull requests merged in 2021-02, with the labels that each got.

#5266 feat(AST parser): use v2 parser architecture
  .kokoro/docker/Dockerfile
  .kokoro/tests/run_single_test.sh
  .kokoro/tests/run_tests.sh
Labels: cla: yes, samples

#5306 fix(healthcare): retry flaky test
  healthcare/api-client/v1/hl7v2/hl7v2_stores_test.py
Labels: api: healthcare, cla: yes, samples

#5326 fix: use temporary ubuntu image from gcr.io
  .kokoro/docker/Dockerfile
Labels: cla: yes, samples

#5322 Add Rachael the DA as a Composer codeowner
  .github/CODEOWNERS
Labels: cla: yes, samples

#5325 fix(storage): list all versions
  storage/cloud-client/storage_list_file_archived_generations.py
Labels: api: storage, automerge, cla: yes, samples

#5330 fix: use cached image from mirror.gcr.io
  .kokoro/docker/Dockerfile
Labels: cla: yes, samples

#5332 Use Python 3.9 for run/django
  run/django/Dockerfile
Labels: cla: yes, samples

#5329 docs: address sample feedback issues
  storage/cloud-client/snippets_test.py
  storage/cloud-client/storage_change_file_storage_class.py
  storage/cloud-client/storage_compose_file.py
Labels: automerge, cla: yes, samples

#5324 feat(functions): link to Flask integration explainer
  functions/helloworld/main.py
Labels: api: cloudfunctions, automerge, cla: yes, samples

#5343 testing(data-science-onramp): add debug output
  data-science-onramp/data-cleaning/clean.py
  data-science-onramp/data-cleaning/clean_test.py
Labels: automerge, cla: yes, samples

#5348 docs(eventarc): update ReadMes
  eventarc/audit-storage/README.md
  eventarc/pubsub/README.md
Labels: automerge, cla: yes, samples

#5340 fix(django): retry-based e2e testing
  run/django/.gcloudignore
  run/django/e2e_test.py
  run/django/mysite/migrations/0001_createsuperuser.py
  run/django/mysite/settings.py
  run/django/polls/test_polls.py
  run/django/test/e2e_test.py
  run/django/test/e2e_test_cleanup.yaml
  run/django/test/e2e_test_setup.yaml
  run/django/test/retry.sh
Labels: cla: yes, samples

#5358 Update header-checker config
  .github/header-checker-lint.yml
Labels: automerge, cla: yes, samples

#5320 Fix name of updated field
  appengine/flexible/tasks/create_app_engine_queue_task.py
Labels: cla: yes, samples

#5366 chore: deleted migrated samples
  vision/automl/automl_vision_model.py
  vision/automl/edge_container_predict/Dockerfile
  vision/automl/edge_container_predict/README.md
  vision/automl/edge_container_predict/automl_vision_edge_container_predict.py
  vision/automl/edge_container_predict/automl_vision_edge_container_predict_test.py
  vision/automl/edge_container_predict/cloudbuild.yaml
  vision/automl/edge_container_predict/test.jpg
  vision/automl/model_test.py
  vision/automl/requirements-test.txt
  vision/automl/requirements.txt
  vision/automl/resources/test.png
Labels: cla: yes, samples

#5373 fix: update eventarc storage name
  eventarc/audit-storage/main.py
  eventarc/audit-storage/main_test.py
Labels: automerge, cla: yes, samples

#5375 feat(run): Add timeout comment to Dockerfiles
  run/django/Dockerfile
  run/hello-broken/Dockerfile
  run/helloworld/Dockerfile
  run/image-processing/Dockerfile
  run/logging-manual/Dockerfile
  run/markdown-preview/editor/Dockerfile
  run/markdown-preview/renderer/Dockerfile
  run/pubsub/Dockerfile
  run/system-package/Dockerfile
Labels: api: run, automerge, cla: yes, samples

#5364 add wildcard to __init__.py
  .github/header-checker-lint.yml
Labels: cla: yes, samples

#5368 fix(django): cleanup storage bucket
  run/django/test/e2e_test.py
  run/django/test/e2e_test_cleanup.yaml
  run/django/test/retry.sh
Labels: automerge, cla: yes, samples

#5387 testing: use our own docker cache temporarily
  .kokoro/docker/Dockerfile
Labels: cla: yes, samples

#5389 add holidays dataset and readme about it
  data-science-onramp/data-ingestion/README.md
  data-science-onramp/data-ingestion/holidays.csv
Labels: automerge, cla: yes, samples

#5384 Edit code format typo
  cloud-sql/postgres/sqlalchemy/README.md
Labels: automerge, cla: yes, samples

#5396 Remove unused code in Markdown sample
  run/markdown-preview/editor/main.py
  run/markdown-preview/editor/main_test.py
  run/markdown-preview/editor/render.py
Labels: cla: yes, samples

#4498 feat(ai-platform): add an AI platform sample
  data-science-onramp/ai-platform/__init__.py
  data-science-onramp/ai-platform/modules/setup.py
  data-science-onramp/ai-platform/modules/trainer/__init__.py
  data-science-onramp/ai-platform/modules/trainer/sklearn_model/__init__.py
  data-science-onramp/ai-platform/modules/trainer/sklearn_model/model.py
  data-science-onramp/ai-platform/modules/trainer/sklearn_model/task.py
  data-science-onramp/ai-platform/modules/trainer/tfkeras_model/__init__.py
  data-science-onramp/ai-platform/modules/trainer/tfkeras_model/model.py
  data-science-onramp/ai-platform/modules/trainer/tfkeras_model/task.py
  data-science-onramp/ai-platform/modules/trainer/utils.py
  data-science-onramp/ai-platform/noxfile_config.py
  data-science-onramp/ai-platform/requirements-test.txt
  data-science-onramp/ai-platform/requirements.txt
  data-science-onramp/ai-platform/sklearn_test.py
  data-science-onramp/ai-platform/tfkeras_test.py
  data-science-onramp/ai-platform/train.csv
Labels: automerge, cla: yes, kokoro:force-run, samples

#5405 update feature engineering to use new holidays dataset
  data-science-onramp/feature-engineering/README.md
  data-science-onramp/feature-engineering/feature_engineering.ipynb
Labels: cla: yes, samples

#5403 fix(media): increase max retries
  media/transcoder/job_test.py
  media/transcoder/requirements-test.txt
Labels: api: mediatranslation, cla: yes, samples

#5407 add missing region tags
  data-science-onramp/data-ingestion/setup.py
Labels: cla: yes, samples

#5315 feat: python version of idp-sql tutorial
  run/README.md
  run/idp-sql/Dockerfile
  run/idp-sql/README.md
  run/idp-sql/app.json
  run/idp-sql/credentials.py
  run/idp-sql/database.py
  run/idp-sql/main.py
  run/idp-sql/middleware.py
  run/idp-sql/noxfile_config.py
  run/idp-sql/postcreate.sh
  run/idp-sql/postgres-secrets.json
  run/idp-sql/requirements-test.txt
  run/idp-sql/requirements.txt
  run/idp-sql/setup.sh
  run/idp-sql/static/config.js
  run/idp-sql/static/firebase.js
  run/idp-sql/templates/index.html
  run/idp-sql/test/e2e_test.py
  run/idp-sql/test/e2e_test_cleanup.yaml
  run/idp-sql/test/e2e_test_setup.yaml
  run/idp-sql/test/retry.sh
  testing/test-env.tmpl.sh
Labels: cla: yes, samples

#5413 dataflow: use us-central1-f for gpu test
  dataflow/gpu-workers/e2e_test.py
Labels: api: dataflow, cla: yes, samples

#5292 fix: use pytds driver in SQL Server sample
  cloud-sql/sql-server/sqlalchemy/Dockerfile
  cloud-sql/sql-server/sqlalchemy/README.md
  cloud-sql/sql-server/sqlalchemy/connection_test.py
  cloud-sql/sql-server/sqlalchemy/main.py
  cloud-sql/sql-server/sqlalchemy/requirements.txt
Labels: cla: yes, samples

#5419 fix(appengine): pin rsa to 4.5
  appengine/standard/endpoints-frameworks-v2/iata/requirements.txt
Labels: api: appengine, cla: yes, samples

#5344 chore(monitoring): add opencensus samples
  .github/CODEOWNERS
  monitoring/opencensus/README.md
  monitoring/opencensus/main.py
  monitoring/opencensus/main_test.py
  monitoring/opencensus/requirements-test.txt
  monitoring/opencensus/requirements.txt
Labels: cla: yes, samples

#5420 workaround for pyspark connector breaking change
  data-science-onramp/data-cleaning/clean_test.py
  data-science-onramp/data-ingestion/setup_test.py
Labels: cla: yes, samples

#5427 fix(header-checker): also allow Google, Inc
  .github/header-checker-lint.yml
Labels: cla: yes, samples
