Repository GoogleCloudPlatform/python-docs-samples, pull requests merged in 2022-01, with the labels that each got.

#7214 refactor: update remaining http samples to use declarative func signature
  functions/helloworld/main.py
  functions/v2/audit_log/main.py
  functions/v2/audit_log/requirements.txt
  functions/v2/pubsub/main.py
  functions/v2/storage/main.py
Labels: automerge, samples

#7316 Revert "chore: reference python-samples-reviewers "
  .github/CODEOWNERS
  AUTHORING_GUIDE.md
Labels: samples

#7314 add note about using finally
  AUTHORING_GUIDE.md
Labels: samples

#7312 Update script to be copy/pasteable
  run/filesystem/gcsfuse_run.sh
  run/filesystem/run.sh
Labels: automerge, samples

#7204 dataflow/gpu: add dataflow prime gpu hints
  dataflow/gpu-examples/tensorflow-landsat-prime/.gcloudignore
  dataflow/gpu-examples/tensorflow-landsat-prime/Dockerfile
  dataflow/gpu-examples/tensorflow-landsat-prime/README.md
  dataflow/gpu-examples/tensorflow-landsat-prime/build.yaml
  dataflow/gpu-examples/tensorflow-landsat-prime/e2e_test.py
  dataflow/gpu-examples/tensorflow-landsat-prime/main.py
  dataflow/gpu-examples/tensorflow-landsat-prime/noxfile_config.py
  dataflow/gpu-examples/tensorflow-landsat-prime/requirements-test.txt
  dataflow/gpu-examples/tensorflow-landsat-prime/requirements.txt
  dataflow/gpu-examples/tensorflow-landsat-prime/run.yaml
Labels: api: dataflow, samples

#7187 Fix overlap in sql db creation in E2E tests
  run/django/test/e2e_test_cleanup.yaml
  run/django/test/e2e_test_setup.yaml
  run/django/test/retry.sh
  run/idp-sql/test/e2e_test_cleanup.yaml
  run/idp-sql/test/e2e_test_setup.yaml
  run/idp-sql/test/retry.sh
Labels: cla: yes, automerge, samples

#7342 Noxfile check for tests
  noxfile-template.py
Labels: automerge, samples

#7357 chore(deps): update pytest to 6.2.5 and add note for Python2 pins
  appengine/standard/analytics/requirements-test.txt
  appengine/standard/blobstore/blobreader/requirements-test.txt
  appengine/standard/blobstore/gcs/requirements-test.txt
  appengine/standard/django/requirements-test.txt
  appengine/standard/endpoints-frameworks-v2/echo/requirements-test.txt
  appengine/standard/endpoints-frameworks-v2/iata/requirements-test.txt
  appengine/standard/endpoints-frameworks-v2/quickstart/requirements-test.txt
  appengine/standard/firebase/firenotes/backend/requirements-test.txt
  appengine/standard/firebase/firetactoe/requirements-test.txt
  appengine/standard/flask/tutorial/requirements-test.txt
  appengine/standard/iap/requirements-test.txt
  appengine/standard/mailgun/requirements-test.txt
  appengine/standard/mailjet/requirements-test.txt
  appengine/standard/migration/incoming/requirements-test.txt
  appengine/standard/migration/memorystore/requirements-test.txt
  appengine/standard/migration/ndb/overview/requirements-test.txt
  appengine/standard/migration/ndb/redis_cache/requirements-test.txt
  appengine/standard/migration/storage/requirements-test.txt
  appengine/standard/migration/taskqueue/counter/requirements-test.txt
  appengine/standard/migration/taskqueue/pull-counter/requirements-test.txt
  appengine/standard/migration/urlfetch/async/requirements-test.txt
  appengine/standard/migration/urlfetch/requests/requirements-test.txt
  appengine/standard/ndb/transactions/requirements-test.txt
  appengine/standard/pubsub/requirements-test.txt
  appengine/standard/sendgrid/requirements-test.txt
  appengine/standard/storage/api-client/requirements-test.txt
  appengine/standard/storage/appengine-client/requirements-test.txt
  appengine/standard/urlfetch/requests/requirements-test.txt
  functions/imagemagick/requirements-dev.txt
  run/hello-broken/requirements.txt
  run/image-processing/requirements.txt
  run/logging-manual/requirements.txt
  run/pubsub/requirements.txt
Labels: samples

#7354 remove irrelevant comment
  composer/airflow_1_samples/gke_operator.py
  composer/workflows/gke_operator.py
Labels: samples

#6648 chore(functions/logging): exclude trace code from sample
  run/logging-manual/e2e_test.py
  run/logging-manual/main.py
  run/logging-manual/main_test.py
Labels: cla: yes, api: cloudfunctions, samples

#7197 feat: add code sample and test for concatenating two input videos
  media/testdata/ChromeCast.mp4
  media/testdata/overlay.jpg
  media/transcoder/create_job_with_concatenated_inputs.py
  media/transcoder/job_test.py
Labels: cla: yes, samples

#7379 Add SQL Server to Cloud SQL Cloud Run quickstart.
  cloud-sql/sql-server/sqlalchemy/Dockerfile
  cloud-sql/sql-server/sqlalchemy/certs/.gitkeep
  cloud-sql/sql-server/sqlalchemy/main.py
  cloud-sql/sql-server/sqlalchemy/requirements.txt
Labels: samples

#7387 fix: assert true if a test job is running but is stuck
  media/transcoder/job_test.py
Labels: samples

#7327 pubsublite: rewrite test to use ephemeral Dataproc cluster
  pubsublite/spark-connector/spark_streaming_from_pubsublite_example.py
  pubsublite/spark-connector/spark_streaming_test.py
  pubsublite/spark-connector/spark_streaming_to_pubsublite_example.py
Labels: samples, api: pubsublite

#7394 chore: remove Transcoder samples
  media/README.rst
  media/transcoder/README.md
  media/transcoder/create_job_from_ad_hoc.py
  media/transcoder/create_job_from_preset.py
  media/transcoder/create_job_from_template.py
  media/transcoder/create_job_template.py
  media/transcoder/create_job_with_animated_overlay.py
  media/transcoder/create_job_with_concatenated_inputs.py
  media/transcoder/create_job_with_periodic_images_spritesheet.py
  media/transcoder/create_job_with_set_number_images_spritesheet.py
  media/transcoder/create_job_with_static_overlay.py
  media/transcoder/delete_job.py
  media/transcoder/delete_job_template.py
  media/transcoder/get_job.py
  media/transcoder/get_job_state.py
  media/transcoder/get_job_template.py
  media/transcoder/job_template_test.py
  media/transcoder/job_test.py
  media/transcoder/list_job_templates.py
  media/transcoder/list_jobs.py
  media/transcoder/requirements-test.txt
  media/transcoder/requirements.txt
  testing/test-env.tmpl.sh
Labels: samples

#7400 Drop 3.6 from datalab migration
  bigquery/datalab-migration/noxfile_config.py
  bigquery/datalab-migration/requirements.txt
Labels: samples

#7291 Added sample for geospatial classification
  people-and-planet-ai/README.md
  people-and-planet-ai/geospatial-classification/README.ipynb
  people-and-planet-ai/geospatial-classification/README.md
  people-and-planet-ai/geospatial-classification/constraints.txt
  people-and-planet-ai/geospatial-classification/e2e_test.py
  people-and-planet-ai/geospatial-classification/img/inputs.png
  people-and-planet-ai/geospatial-classification/img/padding.png
  people-and-planet-ai/geospatial-classification/img/sparse_labels.png
  people-and-planet-ai/geospatial-classification/img/training.png
  people-and-planet-ai/geospatial-classification/labeled_geospatial_data.csv
  people-and-planet-ai/geospatial-classification/noxfile_config.py
  people-and-planet-ai/geospatial-classification/requirements-test.txt
  people-and-planet-ai/geospatial-classification/requirements.txt
  people-and-planet-ai/geospatial-classification/serving_app/Dockerfile
  people-and-planet-ai/geospatial-classification/serving_app/main.py
  people-and-planet-ai/geospatial-classification/serving_app/predict.py
  people-and-planet-ai/geospatial-classification/serving_app/requirements.txt
  people-and-planet-ai/geospatial-classification/task.py
Labels: samples

#7406 doc: Update env variable mentioned in Authoring Guide
  AUTHORING_GUIDE.md
Labels: samples

#7405 feat(pubsublite): attributes field in sink example
  pubsublite/spark-connector/spark_streaming_to_pubsublite_example.py
Labels: samples, api: pubsublite

#7408 remove numpy version for 3.6
  people-and-planet-ai/geospatial-classification/requirements.txt
Labels: automerge, samples

#7353 Remove redundant config
  pubsublite/spark-connector/spark_streaming_to_pubsublite_example.py
Labels: samples

#7231 docs: Change Python client examples from sample_task to sampleTask
  datastore/cloud-client/snippets.py
  datastore/cloud-client/snippets_test.py
Labels: samples
