Repository GoogleCloudPlatform/python-docs-samples, pull requests merged in 2022-05, with the labels that each got.

#7831 feat(cloudsql/postgres): update to v2 samples
  cloud-sql/postgres/sqlalchemy/Dockerfile
  cloud-sql/postgres/sqlalchemy/README.md
  cloud-sql/postgres/sqlalchemy/app.flexible.yaml
  cloud-sql/postgres/sqlalchemy/app.py
  cloud-sql/postgres/sqlalchemy/app.standard.yaml
  cloud-sql/postgres/sqlalchemy/connect_connector.py
  cloud-sql/postgres/sqlalchemy/connect_tcp.py
  cloud-sql/postgres/sqlalchemy/connect_unix.py
  cloud-sql/postgres/sqlalchemy/connection_test.py
  cloud-sql/postgres/sqlalchemy/deployment.yaml
  cloud-sql/postgres/sqlalchemy/main.py
  cloud-sql/postgres/sqlalchemy/requirements.txt
  cloud-sql/postgres/sqlalchemy/templates/index.html
  testing/test-env.tmpl.sh
Labels: api: cloudsql, samples

#7838 chore(appengine/flexible): downgrade Flask version for Python < 3.7
  appengine/flexible/analytics/requirements.txt
  appengine/flexible/datastore/requirements.txt
  appengine/flexible/disk/requirements.txt
  appengine/flexible/extending_runtime/requirements.txt
  appengine/flexible/hello_world/requirements.txt
  appengine/flexible/metadata/requirements.txt
  appengine/flexible/multiple_services/gateway-service/requirements.txt
  appengine/flexible/multiple_services/static-service/requirements.txt
  appengine/flexible/numpy/requirements.txt
  appengine/flexible/pubsub/requirements.txt
  appengine/flexible/scipy/requirements.txt
  appengine/flexible/static_files/requirements.txt
  appengine/flexible/tasks/requirements.txt
  appengine/flexible/twilio/requirements.txt
Labels: api: appengine, samples

#7849 fix: update Jobs region
  run/jobs/e2e_test.py
  run/jobs/e2e_test_cleanup.yaml
  run/jobs/e2e_test_setup.yaml
Labels: automerge, samples

#7862 Fix OS environ variable
  appengine/flexible/multiple_services/gateway-service/services_config.py
Labels: samples

#7856 feat(cloudsql/mysql): update mysql to v2 samples
  cloud-sql/mysql/sqlalchemy/Dockerfile
  cloud-sql/mysql/sqlalchemy/README.md
  cloud-sql/mysql/sqlalchemy/app.flexible.yaml
  cloud-sql/mysql/sqlalchemy/app.py
  cloud-sql/mysql/sqlalchemy/app.standard.yaml
  cloud-sql/mysql/sqlalchemy/connect_connector.py
  cloud-sql/mysql/sqlalchemy/connect_tcp.py
  cloud-sql/mysql/sqlalchemy/connect_unix.py
  cloud-sql/mysql/sqlalchemy/connection_test.py
  cloud-sql/mysql/sqlalchemy/deployment.yaml
  cloud-sql/mysql/sqlalchemy/main.py
  cloud-sql/mysql/sqlalchemy/requirements.txt
  cloud-sql/mysql/sqlalchemy/templates/index.html
  testing/test-env.tmpl.sh
Labels: api: cloudsql, samples

#7874 chore: update CODEOWNERS to all files under directory
  .github/CODEOWNERS
Labels: automerge, samples

#7746 feat(functions/v2): add HTTP Structured Logging sample
  functions/v2/http_logging/main.py
  functions/v2/http_logging/main_test.py
  functions/v2/http_logging/requirements-test.txt
  functions/v2/http_logging/requirements.txt
Labels: api: cloudfunctions, samples

#7873 Updating Django sample for Google App Engine Flexible Environment
  appengine/flexible/hello_world_django/README.md
Labels: samples

#7886 docs: add Google Cloud Samples browser link to readme template
  README.md
Labels: samples

#7880 feat(functions/v2): add imagemagick sample
  functions/v2/imagemagick/README.md
  functions/v2/imagemagick/main.py
  functions/v2/imagemagick/main_test.py
  functions/v2/imagemagick/requirements-test.txt
  functions/v2/imagemagick/requirements.txt
  functions/v2/imagemagick/zombie.jpg
Labels: api: cloudfunctions, samples

#7889 feat(functions/slack): add GCF v2 decorators
  functions/slack/main.py
  functions/slack/requirements.txt
Labels: api: cloudfunctions, samples

#7877 Added DAG file for Airflow Summit 2022
  composer/2022_airflow_summit/README.md
  composer/2022_airflow_summit/parallel_work.py
  composer/2022_airflow_summit/parallel_work_test.py
  composer/2022_airflow_summit/requirements-test.txt
  composer/2022_airflow_summit/requirements.txt
  composer/README.md
Labels: samples

#7847 Fix airflow_db_cleanup script for Airflow 2
  composer/workflows/airflow_db_cleanup.py
Labels: automerge, samples

#7903 Added DAG file for Airflow Summit 2022
  composer/2022_airflow_summit/README.md
  composer/2022_airflow_summit/retries.py
  composer/2022_airflow_summit/retries_test.py
Labels: automerge, samples

#7885 Improve Error Handling for Pause/Unpause DAG script
  composer/tools/composer_dags.py
Labels: samples

#7901 Update main for Python 3. Use .items() instead of .iteritems()
  datastore/cloud-client/snippets.py
Labels: samples

#7921 docs: update variable comment
  composer/workflows/dataproc_batch_operators.py
Labels: samples

#7923 Update MAC_SETUP.md
  MAC_SETUP.md
Labels: samples

#7934 pubsublite: lifecycle config during cluster creation
  pubsublite/spark-connector/spark_streaming_test.py
Labels: samples, api: pubsublite

#7748 healthcare API: add AttributeDefinition CRUD samples+tests
  healthcare/api-client/v1/consent/README.rst
  healthcare/api-client/v1/consent/README.rst.in
  healthcare/api-client/v1/consent/attribute_definitions.py
  healthcare/api-client/v1/consent/attribute_definitions_test.py
Labels: samples

#7954 Manually fix formatting issue in README
  healthcare/api-client/v1/consent/README.rst
Labels: samples

#7964 Added DAG file for Airflow Summit 2022
  composer/2022_airflow_summit/README.md
  composer/2022_airflow_summit/bigquery_permissions.py
  composer/2022_airflow_summit/bigquery_permissions_test.py
Labels: automerge, samples

#7974 Update renovate.json
  renovate.json
Labels: samples

#8010 fix broken build: Revert constraints changes
  composer/2022_airflow_summit/constraints.txt
Labels: samples
