Repository GoogleCloudPlatform/python-docs-samples, pull requests merged in 2022-06, with the labels that each got.

#8023 fix: update post so retries are actually performed
  functions/helloworld/sample_http_test_integration.py
Labels: samples

#8025 feat(cloudsql/sql-server): update SQL Server to v2 samples
  cloud-sql/sql-server/sqlalchemy/Dockerfile
  cloud-sql/sql-server/sqlalchemy/README.md
  cloud-sql/sql-server/sqlalchemy/app.flexible.yaml
  cloud-sql/sql-server/sqlalchemy/app.py
  cloud-sql/sql-server/sqlalchemy/app.standard.yaml
  cloud-sql/sql-server/sqlalchemy/connect_connector.py
  cloud-sql/sql-server/sqlalchemy/connect_tcp.py
  cloud-sql/sql-server/sqlalchemy/connection_test.py
  cloud-sql/sql-server/sqlalchemy/deployment.yaml
  cloud-sql/sql-server/sqlalchemy/main.py
  cloud-sql/sql-server/sqlalchemy/requirements.txt
  cloud-sql/sql-server/sqlalchemy/templates/index.html
Labels: api: cloudsql, samples

#7781 chore: update authoring guide with nox testing note
  AUTHORING_GUIDE.md
Labels: samples

#8037 chore: address codeql
  composer/rest/get_client_id_test.py
Labels: samples

#8038 chore: add blunderbuss for label 'api: people-and-planet-ai'
  .github/blunderbuss.yml
Labels: automerge, samples

#8054 add backoff to fix flaky test
  composer/2022_airflow_summit/data_analytics_process_test.py
  composer/2022_airflow_summit/requirements-test.txt
Labels: automerge, samples

#8066 docs(composer): clarify optional parameter
  composer/airflow_1_samples/kubernetes_pod_operator.py
  composer/workflows/kubernetes_pod_operator.py
Labels: samples

#8031 Address django/python version compatibility
  appengine/flexible/django_cloudsql/requirements.txt
  appengine/flexible/hello_world_django/requirements.txt
  appengine/standard_python3/django/requirements.txt
  kubernetes_engine/django_tutorial/requirements.txt
  run/django/requirements.txt
Labels: samples

#8067 chore(functions): Update import location
  functions/v2/http_logging/main.py
Labels: api: cloudfunctions, samples

#8081 fix: upgrade dataproc image version for spark connector
  pubsublite/spark-connector/README.md
  pubsublite/spark-connector/spark_streaming_test.py
Labels: samples

#8075 chore(run/idp-sql): Fix cloud run button
  run/idp-sql/app.json
Labels: api: run, samples

#8098 test: retry ServiceUnavailable
  storagetransfer/aws_request_test.py
Labels: samples

#8100 (healthcare API):update v1beta1 samples to use R4 store to fix flakiness
  healthcare/api-client/v1beta1/fhir/fhir_resources.py
  healthcare/api-client/v1beta1/fhir/fhir_stores.py
Labels: samples

#8082 chore: Update gcloud to 389.0.0
  .kokoro/docker/Dockerfile
Labels: samples

#8064 feat: add unique hash to commit status context
  run/deployment-previews/check_status.py
Labels: automerge, api: run, samples

#8091 feat(storagetransfer): Add POSIX & Manifest Samples
  storagetransfer/conftest.py
  storagetransfer/manifest_request.py
  storagetransfer/manifest_request_test.py
  storagetransfer/posix_download.py
  storagetransfer/posix_download_test.py
  storagetransfer/posix_request.py
  storagetransfer/posix_request_test.py
  storagetransfer/posix_to_posix_request.py
  storagetransfer/posix_to_posix_request_test.py
Labels: api: storagetransfer, samples

#8060 New sample: receiving authenticated requests
  run/service-auth/Procfile
  run/service-auth/app.py
  run/service-auth/noxfile_config.py
  run/service-auth/receive.py
  run/service-auth/receive_test.py
  run/service-auth/requirements-test.txt
  run/service-auth/requirements.txt
Labels: samples

#8116 feat(run/jobs): make tests more robust
  run/jobs/main_test.py
Labels: api: run, samples

#8112 chore: update google-cloud-datastore to 2.7.1
  appengine/flexible/datastore/requirements.txt
  appengine/standard/migration/taskqueue/counter/requirements.txt
  appengine/standard/migration/taskqueue/pull-counter/requirements.txt
  appengine/standard_python3/building-an-app/building-an-app-2/requirements.txt
  appengine/standard_python3/building-an-app/building-an-app-3/requirements.txt
  appengine/standard_python3/building-an-app/building-an-app-4/requirements.txt
  blog/introduction_to_data_models_in_cloud_datastore/requirements.txt
  codelabs/flex_and_vision/requirements.txt
  datastore/cloud-client/requirements.txt
Labels: samples

#8129 dataflow/gpu: use compatible nvidia image
  dataflow/gpu-examples/tensorflow-minimal/Dockerfile
  dataflow/gpu-examples/tensorflow-minimal/requirements.txt
Labels: api: dataflow, samples

#8130 pubsublite: limit tests in python 3.8
  pubsublite/spark-connector/noxfile_config.py
Labels: samples, api: pubsublite

#8089 fix broken link, refactor to remove conditional and add error checking
  composer/cicd_sample/README.md
  composer/cicd_sample/utils/add_dags_to_composer.py
  composer/cicd_sample/utils/add_dags_to_composer_test.py
Labels: samples

#8135 Updated Dockerfile from using Python 3.6 to 3.10
  .kokoro/docker/Dockerfile
Labels: samples

#8145 fix(appengine): hardcoded PORT -> env var
  appengine/standard_python3/custom-server/app.yaml
Labels: api: appengine, samples
