Repository GoogleCloudPlatform/python-docs-samples, pull requests merged in 2022-07, with the labels that each got.

#8151 chore(docker): Update Dockerfile to install pip for every Python3 version
  .kokoro/docker/Dockerfile
Labels: samples

#8149 Update Dataflow Flex Template README
  dataflow/flex-templates/streaming_beam/README.md
Labels: samples

#8148 sample: rename DAG ID of data_analytics_dag.py
  composer/2022_airflow_summit/data_analytics_dag.py
  composer/2022_airflow_summit/noxfile_config.py
Labels: samples

#8169 test: retry service unavailable posix_request_test, posix_to_posix_re…
  storagetransfer/posix_request_test.py
  storagetransfer/posix_to_posix_request_test.py
Labels: samples

#7801 fix(appengine/static-service): fix non-extension'ed file handling
  appengine/flexible/multiple_services/static-service/main.py
Labels: automerge, api: appengine, samples

#8170 docs(samples): DAG codes for transferring files from Azure to GCS tutorial
  composer/workflows/azureblobstoretogcsoperator_tutorial.py
  composer/workflows/azureblobstoretogcsoperator_tutorial_test.py
  composer/workflows/requirements.txt
Labels: samples

#8198 Add region tags
  composer/2022_airflow_summit/data_analytics_dag.py
  composer/2022_airflow_summit/data_analytics_process.py
Labels: samples

#8203 fix: update pyodbc dependency to fix sqlalchemy test
  cloud-sql/sql-server/sqlalchemy/requirements.txt
Labels: samples

#7370 Fixing issue 7277
  compute/oslogin/service_account_ssh.py
Labels: samples

#8204 chore: remove 3.6 status from the README
  README.md
Labels: samples

#8199 chore: add link to Google Cloud Samples Style Guide
  AUTHORING_GUIDE.md
Labels: samples

#8215 dataflow/ubuntu-container: use LTS ubuntu version
  dataflow/custom-containers/ubuntu/Dockerfile
  dataflow/custom-containers/ubuntu/requirements.txt
Labels: api: dataflow, samples

#8218 add region tags for aws + azure tutorials
  composer/workflows/azureblobstoretogcsoperator_tutorial.py
  composer/workflows/s3togcsoperator_tutorial.py
Labels: automerge, samples

#8217 test: retry ServiceUnavailable posix_download_test
  storagetransfer/posix_download_test.py
Labels: samples

#8216 Fix: add region tags
  appengine/standard_python3/bundled-services/blobstore/django/main.py
  appengine/standard_python3/bundled-services/blobstore/flask/main.py
  appengine/standard_python3/bundled-services/blobstore/wsgi/main.py
  appengine/standard_python3/bundled-services/deferred/django/main.py
  appengine/standard_python3/bundled-services/deferred/flask/main.py
  appengine/standard_python3/bundled-services/deferred/wsgi/main.py
  appengine/standard_python3/bundled-services/mail/django/main.py
  appengine/standard_python3/bundled-services/mail/flask/main.py
  appengine/standard_python3/bundled-services/mail/wsgi/main.py
Labels: samples

#8220 Fix SQL creation conflict
  run/django/e2e_test_setup.yaml
  run/idp-sql/e2e_test_setup.yaml
Labels: samples
