Repository GoogleCloudPlatform/python-docs-samples, pull requests merged in 2022-04, with the labels that each got.

#7591 chore: update README with py3.9 and 3.10 test status
  README.md
Labels: automerge, samples

#7751 Fix: Change variable name for consistency
  auth/service-to-service/auth.py
Labels: samples

#7754 Fix: Make test var name match code
  auth/service-to-service/auth_test.py
Labels: samples

#7738 chore(functions/storage): clarify comments
  functions/helloworld/main.py
Labels: api: cloudfunctions, samples

#7625 Dataproc Serverless workflows
  composer/workflows/dataproc_batch_operators.py
  composer/workflows/dataproc_batch_operators_test.py
Labels: automerge, samples

#7793 chore(functions/helloworld): update product names
  functions/helloworld/main.py
Labels: api: cloudfunctions, samples

#7777 fix: e2e test errors
  run/filesystem/cloudbuild.yaml
  run/filesystem/retry.sh
  run/jobs/Procfile
  run/jobs/e2e_test.py
  run/jobs/e2e_test_setup.yaml
  run/jobs/main.py
Labels: samples

#7795 chore(auth): document Cloud Run URL structure
  auth/service-to-service/auth.py
Labels: samples

#7789 fix: type linting issue
  run/deployment-previews/test_app.py
Labels: samples

#7788 ppai: fix lint errors
  people-and-planet-ai/image-classification/e2e_test.py
  people-and-planet-ai/image-classification/requirements.txt
  people-and-planet-ai/image-classification/train_model.py
  people-and-planet-ai/timeseries-classification/create_datasets.py
  people-and-planet-ai/timeseries-classification/trainer.py
Labels: samples

#7753 chore: Update Airflow 2 GKE sample to use regional clusters
  composer/workflows/gke_operator.py
Labels: samples

#7779 Reassert idp-sql and django tests
  run/django/e2e_test.py
  run/django/e2e_test_cleanup.yaml
  run/django/e2e_test_setup.yaml
  run/django/retry.sh
  run/idp-sql/README.md
  run/idp-sql/e2e_test.py
  run/idp-sql/e2e_test_cleanup.yaml
  run/idp-sql/e2e_test_setup.yaml
  run/idp-sql/middleware.py
  run/idp-sql/retry.sh
Labels: automerge, samples

#6582 docs: add guidelines around imports and initializing GAPIC objects
  AUTHORING_GUIDE.md
Labels: cla: yes, samples

#7796 chore: remove Bu Sun from auth codeowners
  .github/CODEOWNERS
Labels: samples

#7817 fix(run/jobs): Fix flaky test
  run/jobs/e2e_test_setup.yaml
Labels: api: run, samples

#7823 dataflow (fix): pin in to ubuntu:impish
  dataflow/custom-containers/ubuntu/Dockerfile
Labels: samples

#7841 Add note about installation on Apple Silicon
  MAC_SETUP.md
Labels: automerge, samples
