Repository GoogleCloudPlatform/python-docs-samples, pull requests merged in 2022-02, with the labels that each got.

#7383 Composer DAGs Pause/Unpause Script
  composer/tools/composer_dags.md
  composer/tools/composer_dags.py
Labels: samples

#7412 Add django CSRF setting
  appengine/standard_python3/django/app.yaml
  appengine/standard_python3/django/mysite/settings.py
  run/django/mysite/settings.py
Labels: automerge, samples

#7323 dataflow: improve waiting functions
  dataflow/conftest.py
  dataflow/flex-templates/streaming_beam/e2e_test.py
  dataflow/flex-templates/streaming_beam/metadata.json
  dataflow/flex-templates/streaming_beam/requirements.txt
Labels: automerge, api: dataflow, samples

#7439 Fix b/203682194
  composer/airflow_1_samples/quickstart.py
  composer/workflows/quickstart.py
Labels: samples

#7414 Update Cloud SQL for SQL Server sample app w/ Kubernetes Engine
  cloud-sql/sql-server/sqlalchemy/Dockerfile
  cloud-sql/sql-server/sqlalchemy/deployment.yaml
  cloud-sql/sql-server/sqlalchemy/main.py
  cloud-sql/sql-server/sqlalchemy/service-account.yaml
  cloud-sql/sql-server/sqlalchemy/service.yaml
Labels: samples

#7440 test: fix flaky healthcare samples
  healthcare/api-client/v1/fhir/fhir_resources_test.py
  healthcare/api-client/v1/fhir/fhir_stores_test.py
  healthcare/api-client/v1beta1/fhir/fhir_resources_test.py
  healthcare/api-client/v1beta1/fhir/fhir_stores_test.py
Labels: automerge, samples

#7415 docs(workload-identity-samples): replaced project_id with project_number
  iam/api-client/workload_identity_federation.py
Labels: samples

#7420 test: fix flaky dataflow/gpu/landsat-prime test
  dataflow/gpu-examples/tensorflow-landsat-prime/e2e_test.py
  dataflow/gpu-examples/tensorflow-landsat-prime/main.py
Labels: automerge, api: dataflow, samples

#7446 fix: remove redundant Airflow variable
  composer/airflow_1_samples/dataflowtemplateoperator_tutorial.py
  composer/airflow_1_samples/dataflowtemplateoperator_tutorial_test.py
Labels: automerge, samples

#7441 Replace outdated README with current one. Update `tools` readme
  composer/README.md
  composer/tools/README.md
  composer/workflows/README.rst
  composer/workflows/README.rst.in
Labels: samples

#7447 feat(iam): use Application Default Credentials (ADC) in IAM quickstart
  iam/api-client/quickstart.py
  iam/api-client/quickstart_test.py
Labels: api: iam, samples

#7411 dataflow: add custom container minimal sample
  dataflow/custom-containers/README.md
  dataflow/custom-containers/minimal/Dockerfile
  dataflow/custom-containers/minimal/e2e_test.py
  dataflow/custom-containers/minimal/main.py
  dataflow/custom-containers/minimal/noxfile_config.py
  dataflow/custom-containers/minimal/requirements-test.txt
  dataflow/custom-containers/minimal/requirements.txt
Labels: automerge, api: dataflow, samples

#7445 dataflow: add ubuntu custom container sample
  dataflow/custom-containers/ubuntu/Dockerfile
  dataflow/custom-containers/ubuntu/e2e_test.py
  dataflow/custom-containers/ubuntu/main.py
  dataflow/custom-containers/ubuntu/noxfile_config.py
  dataflow/custom-containers/ubuntu/requirements-test.txt
  dataflow/custom-containers/ubuntu/requirements.txt
Labels: api: dataflow, samples

#7464 fix: update GCS method
  composer/cicd_sample/utils/add_dags_to_composer.py
Labels: samples

#7470 Make Python PubSub sample match other language ones
  functions/v2/pubsub/main.py
  functions/v2/pubsub/main_test.py
Labels: samples

#7463 chore(compute): Changing the default zone for compute api tests
  compute/api/create_instance_test.py
Labels: automerge, api: compute, samples

#7443 dataflow tests: simplify wait function + fix landsat prime flaky test
  dataflow/conftest.py
  dataflow/gpu-examples/tensorflow-landsat-prime/e2e_test.py
  dataflow/gpu-examples/tensorflow-landsat-prime/main.py
Labels: samples

#7483 chore(deps): pin markupsafe version
  composer/airflow_1_samples/requirements.txt
  trace/cloud-trace-demo-app-opentelemetry/app/requirements.txt
  trace/cloud-trace-demo-app/app/requirements.txt
Labels: samples

#7311 fix link typo in run-filesystem sub-readme
  run/filesystem/README.md
Labels: samples

#7343 dataflow/tensorflow-landsat: remove conflicting flag
  dataflow/gpu-examples/tensorflow-landsat/run.yaml
Labels: automerge, api: dataflow, samples

#7393 docs(iam-samples): extract json_key_file from privateKeyData
  iam/api-client/service_account_keys.py
Labels: samples

#7494 Update BigQuery basics.ipynb
  notebooks/tutorials/bigquery/BigQuery basics.ipynb
Labels: samples

#7473 fix: b/219021576
  composer/airflow_1_samples/constraints.txt
  composer/airflow_1_samples/hadoop_tutorial.py
  composer/airflow_1_samples/requirements.txt
  composer/workflows/hadoop_tutorial.py
Labels: automerge, samples

#7488 chore: remove silvolu from blunderbuss/codeowners
  .github/CODEOWNERS
  .github/blunderbuss.yml
Labels: samples

#7508 remove noxfile_config from directory with no .py files
  notebooks/noxfile_config.py
Labels: samples

#7317 Use python-samples-reviewers GH team
  .github/CODEOWNERS
  AUTHORING_GUIDE.md
Labels: samples

#7409 ci: do not run 3.6 tests by default
  appengine/standard_python3/bigquery/noxfile_config.py
  appengine/standard_python3/cloud_debugger/noxfile_config.py
  bigquery/bqml/noxfile_config.py
  bigquery/pandas-gbq-migration/noxfile_config.py
  data-science-onramp/data-ingestion/noxfile_config.py
  data-science-onramp/data-processing/noxfile_config.py
  dataflow/encryption-keys/noxfile_config.py
  ml_engine/online_prediction/noxfile_config.py
  noxfile-template.py
  noxfile_config.py
  pubsub/streaming-analytics/noxfile_config.py
Labels: samples

#7501 fix: wait for healthcare dataset creation using operations client
  healthcare/api-client/v1/fhir/fhir_resources_test.py
  healthcare/api-client/v1/fhir/fhir_stores_test.py
  healthcare/api-client/v1/fhir/noxfile_config.py
  healthcare/api-client/v1beta1/fhir/fhir_resources_test.py
  healthcare/api-client/v1beta1/fhir/fhir_stores_test.py
Labels: samples
