Repository GoogleCloudPlatform/python-docs-samples, pull requests merged in 2022-08, with the labels that each got.

#8227 Fix: Datastore client: Mark test as flaky
  datastore/cloud-client/admin_test.py
Labels: samples

#8208 fix(oslogin): Fixing a flaky issue with OSLogin SSH tests
  compute/oslogin/service_account_ssh.py
  compute/oslogin/service_account_ssh_test.py
Labels: api: oslogin, samples

#8221 Fix: Retry CLI launch if needed
  appengine/standard_python3/bundled-services/blobstore/django/main_test.py
  appengine/standard_python3/bundled-services/blobstore/django/requirements-test.txt
  appengine/standard_python3/bundled-services/blobstore/flask/main_test.py
  appengine/standard_python3/bundled-services/blobstore/flask/requirements-test.txt
  appengine/standard_python3/bundled-services/blobstore/wsgi/main_test.py
  appengine/standard_python3/bundled-services/blobstore/wsgi/requirements-test.txt
  appengine/standard_python3/bundled-services/deferred/django/main_test.py
  appengine/standard_python3/bundled-services/deferred/django/requirements-test.txt
  appengine/standard_python3/bundled-services/deferred/flask/main_test.py
  appengine/standard_python3/bundled-services/deferred/flask/requirements-test.txt
  appengine/standard_python3/bundled-services/deferred/wsgi/main_test.py
  appengine/standard_python3/bundled-services/deferred/wsgi/requirements-test.txt
  appengine/standard_python3/bundled-services/mail/django/main_test.py
  appengine/standard_python3/bundled-services/mail/django/requirements-test.txt
  appengine/standard_python3/bundled-services/mail/flask/main_test.py
  appengine/standard_python3/bundled-services/mail/flask/requirements-test.txt
  appengine/standard_python3/bundled-services/mail/wsgi/main_test.py
  appengine/standard_python3/bundled-services/mail/wsgi/requirements-test.txt
Labels: samples

#8238 Fix: replace pytest.yield_fixture with pytest.fixture
  appengine/standard/appengine_helper.py
  datastore/cloud-client/snippets_test.py
  datastore/cloud-client/tasks_test.py
  dns/api/main_test.py
Labels: automerge, samples

#8244 chore(samples): Updating debian version from 9 to 11
  compute/api/create_instance.py
  memorystore/redis/gce_deployment/deploy.sh
Labels: samples

#8233 Fix: Datastore samples: `exclude_from_indexes` expects a tuple, not a…
  datastore/cloud-client/snippets.py
  datastore/cloud-client/tasks.py
Labels: automerge, samples

#8250 chore(cloudsql): add consistent region tags
  cloud-sql/mysql/sqlalchemy/connect_tcp.py
  cloud-sql/postgres/sqlalchemy/connect_tcp.py
  cloud-sql/sql-server/sqlalchemy/connect_tcp.py
Labels: api: cloudsql, samples

#8248 chore: Remove datastore schedule export
  datastore/schedule-export/README.md
  datastore/schedule-export/main.py
  datastore/schedule-export/requirements-test.txt
  datastore/schedule-export/requirements.txt
  datastore/schedule-export/schedule_export_test.py
Labels: samples

#8251 docs: Add the firestore_setup_client_create_with_project_id region tag
  firestore/cloud-client/snippets.py
Labels: samples

#8257 fix: use backoff exception to gracefully exit and fail
  compute/oslogin/requirements-test.txt
  compute/oslogin/service_account_ssh_test.py
Labels: samples

#8262 fix: add fixture for dataproc batch and better test cleanup
  composer/2022_airflow_summit/data_analytics_process_test.py
  composer/2022_airflow_summit/noxfile_config.py
Labels: samples

#8267 samples(healthcare API): add samples and tests for v1 FHIR profiles
  healthcare/api-client/v1/fhir/README.rst
  healthcare/api-client/v1/fhir/fhir_resources.py
  healthcare/api-client/v1/fhir/fhir_resources_test.py
  healthcare/api-client/v1/fhir/resources/CodeSystemExample.json
  healthcare/api-client/v1/fhir/resources/ImplementationGuideExample.json
  healthcare/api-client/v1/fhir/resources/StructureDefinitionExample.json
  healthcare/api-client/v1/fhir/resources/StructureDefinitionProfileUrlExample.json
Labels: samples

#8283 Fix: Sanitize text response
  appengine/flexible/tasks/main.py
  appengine/flexible/tasks/templates/index.html
Labels: samples

#8282 fix(pubsublite): ignore python 3.10
  pubsublite/spark-connector/noxfile_config.py
Labels: samples, api: pubsublite

#8285 explicitly add google providers dependency
  composer/2022_airflow_summit/requirements.txt
Labels: samples

#8286 Fix: wait time and exception checks
  appengine/standard_python3/bundled-services/blobstore/django/main.py
  appengine/standard_python3/bundled-services/blobstore/flask/main.py
  appengine/standard_python3/bundled-services/deferred/flask/main.py
  appengine/standard_python3/bundled-services/mail/django/main.py
  appengine/standard_python3/bundled-services/mail/django/main_test.py
  appengine/standard_python3/bundled-services/mail/flask/main.py
  appengine/standard_python3/bundled-services/mail/flask/main_test.py
  appengine/standard_python3/bundled-services/mail/wsgi/main.py
  appengine/standard_python3/bundled-services/mail/wsgi/main_test.py
Labels: samples

#8287 Extend test retry period
  run/idp-sql/e2e_test.py
Labels: samples

#8288 fix: longer waits to reduce flaky
  appengine/standard_python3/bundled-services/deferred/django/main.py
  appengine/standard_python3/bundled-services/deferred/django/main_test.py
  appengine/standard_python3/bundled-services/deferred/flask/main.py
  appengine/standard_python3/bundled-services/deferred/flask/main_test.py
  appengine/standard_python3/bundled-services/deferred/wsgi/main.py
  appengine/standard_python3/bundled-services/deferred/wsgi/main_test.py
Labels: samples

#7894 Example Airflow DAG that sends an email message through SendGrid
  composer/workflows/email_operator_sendgrid.py
  composer/workflows/email_operator_sendgrid_test.py
Labels: samples

#8296 Update header checker
  .github/header-checker-lint.yml
Labels: samples

#8291 dataflow: extensible template with javascript udf
  dataflow/conftest.py
  dataflow/extensible-templates/dataflow_udf_transform.js
  dataflow/extensible-templates/e2e_test.py
  dataflow/extensible-templates/noxfile_config.py
  dataflow/extensible-templates/requirements-test.txt
  dataflow/extensible-templates/requirements.txt
Labels: api: dataflow, samples

#8302 dataflow: update apache-beam version
  dataflow/flex-templates/streaming_beam/requirements.txt
Labels: samples

#8303 dataflow: replace job name underscores with hyphens
  dataflow/run_template/main_test.py
Labels: api: dataflow, samples
