Repository GoogleCloudPlatform/python-docs-samples, pull requests merged in 2023-01, with the labels that each got.

#8850 I found a typo on the CONTRIBUTING document
  CONTRIBUTING.md
Labels: samples

#8844 Fix/8843
  vision/snippets/face_detection/faces.py
Labels: samples

#8845 Deprecation notice for composer_db_transfer.py
  composer/tools/composer_db_transfer.md
  composer/tools/composer_db_transfer.py
Labels: samples

#8856 update GH owners for composer to include teamsync team
  .github/CODEOWNERS
Labels: automerge, samples

#8840 chore(functions/concepts-after-timeout): Update sample signature using functions framework
  functions/concepts-after-timeout/main.py
  functions/concepts-after-timeout/requirements.txt
Labels: api: cloudfunctions, samples

#8838 chore(functions/tips-lazy-globals): Update sample signature using functions framework
  functions/tips-lazy-globals/main.py
  functions/tips-lazy-globals/requirements.txt
Labels: api: cloudfunctions, samples

#8839 chore(functions/tips-scopes): Update sample signature using functions framework
  functions/tips-scopes/main.py
  functions/tips-scopes/requirements.txt
Labels: api: cloudfunctions, samples

#8842 Adding KubernetesPodOperator example for Composer 2
  composer/workflows/kubernetes_pod_operator_c2.py
  composer/workflows/kubernetes_pod_operator_c2_test.py
Labels: samples

#8866 Remove arbitrary equals - not supported by MEND renovate
  appengine/flexible/scipy/requirements.txt
  appengine/standard/firebase/firenotes/backend/requirements.txt
  appengine/standard/migration/taskqueue/counter/requirements.txt
  appengine/standard/migration/taskqueue/pull-counter/requirements.txt
  bigquery/datalab-migration/requirements.txt
  compute/oslogin/requirements-test.txt
  iot/api-client/gcs_file_to_device/requirements.txt
  language/snippets/classify_text/requirements.txt
Labels: automerge, samples

#8463 Fix issue in env var substitution
  run/deployment-previews/cloudbuild-configurations/cloudbuild-preview.yaml
Labels: samples

#8833 Updates to `run/image-processing/e2e_test.py`
  run/image-processing/cloudbuild.yaml
  run/image-processing/e2e_test.py
Labels: samples

#8861 feat: add python 3.11.1 to the samples image
  .kokoro/docker/Dockerfile
Labels: samples

#8872 feat: add python 3.11 testing
  .kokoro/docker/Dockerfile
  .kokoro/python3.11/common.cfg
  .kokoro/python3.11/continuous.cfg
  .kokoro/python3.11/periodic.cfg
  .kokoro/python3.11/presubmit.cfg
  MAC_SETUP.md
  README.md
  appengine/flexible/django_cloudsql/requirements.txt
  appengine/flexible/scipy/noxfile_config.py
  appengine/flexible/scipy/requirements.txt
  appengine/standard/noxfile-template.py
  appengine/standard_python3/bigquery/noxfile_config.py
  appengine/standard_python3/cloud_debugger/noxfile_config.py
  appengine/standard_python3/cloudsql/requirements.txt
  appengine/standard_python3/django/requirements.txt
  bigquery/bqml/noxfile_config.py
  bigquery/datalab-migration/noxfile_config.py
  bigquery/pandas-gbq-migration/noxfile_config.py
  cloud-sql/mysql/client-side-encryption/noxfile_config.py
  cloud-sql/postgres/client-side-encryption/noxfile_config.py
  cloud-sql/sql-server/client-side-encryption/noxfile_config.py
  composer/2022_airflow_summit/constraints.txt
  composer/2022_airflow_summit/noxfile_config.py
  composer/airflow_1_samples/noxfile_config.py
  composer/blog/gcp-tech-blog/data-orchestration-with-composer/constraints.txt
  composer/blog/gcp-tech-blog/data-orchestration-with-composer/noxfile_config.py
  composer/blog/gcp-tech-blog/unit-test-dags-cloud-build/noxfile_config.py
  composer/cicd_sample/constraints.txt
  composer/cicd_sample/noxfile_config.py
  composer/cicd_sample/utils/noxfile_config.py
  composer/workflows/constraints.txt
  composer/workflows/noxfile_config.py
  data-science-onramp/data-ingestion/noxfile_config.py
  data-science-onramp/data-processing/noxfile_config.py
  dataflow/custom-containers/miniconda/noxfile_config.py
  dataflow/custom-containers/minimal/noxfile_config.py
  dataflow/custom-containers/ubuntu/noxfile_config.py
  dataflow/encryption-keys/noxfile_config.py
  dataflow/extensible-templates/noxfile_config.py
  dataflow/flex-templates/streaming_beam/noxfile_config.py
  dataflow/gpu-examples/pytorch-minimal/noxfile_config.py
  dataflow/gpu-examples/tensorflow-landsat-prime/noxfile_config.py
  dataflow/gpu-examples/tensorflow-landsat/noxfile_config.py
  dataflow/gpu-examples/tensorflow-minimal/noxfile_config.py
  kubernetes_engine/django_tutorial/requirements.txt
  ml_engine/online_prediction/noxfile_config.py
  noxfile-template.py
  people-and-planet-ai/geospatial-classification/noxfile_config.py
  people-and-planet-ai/image-classification/noxfile_config.py
  people-and-planet-ai/land-cover-classification/noxfile_config.py
  people-and-planet-ai/timeseries-classification/noxfile_config.py
  pubsub/streaming-analytics/noxfile_config.py
  pubsublite/spark-connector/noxfile_config.py
  run/django/requirements.txt
Labels: samples

#8851 Airflow db cleanup dag update
  composer/airflow_1_samples/airflow_db_cleanup.py
  composer/workflows/airflow_db_cleanup.py
Labels: samples

#8967 docs: Fix Retail README headers
  retail/interactive-tutorials/README.md
Labels: samples

#8882 chore(GAE Python3): add HTTP retries to flaky test
  appengine/standard_python3/bundled-services/blobstore/django/main_test.py
  appengine/standard_python3/bundled-services/blobstore/flask/main_test.py
  appengine/standard_python3/bundled-services/blobstore/wsgi/main_test.py
  appengine/standard_python3/bundled-services/deferred/django/main_test.py
  appengine/standard_python3/bundled-services/deferred/flask/main_test.py
  appengine/standard_python3/bundled-services/deferred/wsgi/main_test.py
  appengine/standard_python3/bundled-services/mail/django/main_test.py
  appengine/standard_python3/bundled-services/mail/flask/main_test.py
  appengine/standard_python3/bundled-services/mail/wsgi/main_test.py
Labels: samples

#8884 chore(functions/v2): Update sample signatures using functions framework
  functions/http/main.py
  functions/http/requirements.txt
Labels: api: cloudfunctions, samples

#8971 Revert "chore(deps): update dependency apache-airflow-providers-cncf-kubernetes to v5.1.0"
  composer/workflows/requirements.txt
Labels: samples

#8973 chore(ci): add mappings from directories to services
  .github/auto-label.yaml
Labels: samples

#8974 chore: Update Retail sample ownership
  .github/CODEOWNERS
Labels: samples

#8860 Composer tutorial: add function and dag
  composer/functions/pubsub_publisher.py
  composer/functions/pubsub_publisher_test.py
  composer/functions/requirements.txt
  composer/workflows/pubsub_trigger_response_dag.py
  composer/workflows/pubsub_trigger_response_dag_test.py
Labels: automerge, samples

#8800 docs(samples): Created Initial Enterprise Knowledge Graph Sample
  .github/CODEOWNERS
  .github/blunderbuss.yml
  enterpriseknowledgegraph/entity_reconciliation/cancel_entity_reconciliation_job_sample.py
  enterpriseknowledgegraph/entity_reconciliation/cancel_entity_reconciliation_job_sample_test.py
  enterpriseknowledgegraph/entity_reconciliation/create_entity_reconciliation_job_sample.py
  enterpriseknowledgegraph/entity_reconciliation/create_entity_reconciliation_job_sample_test.py
  enterpriseknowledgegraph/entity_reconciliation/delete_entity_reconciliation_job_sample.py
  enterpriseknowledgegraph/entity_reconciliation/delete_entity_reconciliation_job_sample_test.py
  enterpriseknowledgegraph/entity_reconciliation/get_entity_reconciliation_job_sample.py
  enterpriseknowledgegraph/entity_reconciliation/get_entity_reconciliation_job_sample_test.py
  enterpriseknowledgegraph/entity_reconciliation/list_entity_reconciliation_jobs_sample.py
  enterpriseknowledgegraph/entity_reconciliation/list_entity_reconciliation_jobs_sample_test.py
  enterpriseknowledgegraph/entity_reconciliation/requirements-test.txt
  enterpriseknowledgegraph/entity_reconciliation/requirements.txt
  enterpriseknowledgegraph/search/lookup_public_kg_sample.py
  enterpriseknowledgegraph/search/lookup_public_kg_sample_test.py
  enterpriseknowledgegraph/search/lookup_sample.py
  enterpriseknowledgegraph/search/lookup_sample_test.py
  enterpriseknowledgegraph/search/requirements-test.txt
  enterpriseknowledgegraph/search/requirements.txt
  enterpriseknowledgegraph/search/search_public_kg_sample.py
  enterpriseknowledgegraph/search/search_public_kg_sample_test.py
  enterpriseknowledgegraph/search/search_sample.py
  enterpriseknowledgegraph/search/search_sample_test.py
Labels: samples

#8995 Revert "feat: add python 3.11 testing"
  .kokoro/docker/Dockerfile
  .kokoro/python3.11/common.cfg
  .kokoro/python3.11/continuous.cfg
  .kokoro/python3.11/periodic.cfg
  .kokoro/python3.11/presubmit.cfg
  MAC_SETUP.md
  README.md
  appengine/flexible/django_cloudsql/requirements.txt
  appengine/flexible/scipy/noxfile_config.py
  appengine/flexible/scipy/requirements.txt
  appengine/standard/noxfile-template.py
  appengine/standard_python3/bigquery/noxfile_config.py
  appengine/standard_python3/cloud_debugger/noxfile_config.py
  appengine/standard_python3/cloudsql/requirements.txt
  appengine/standard_python3/django/requirements.txt
  bigquery/bqml/noxfile_config.py
  bigquery/datalab-migration/noxfile_config.py
  bigquery/pandas-gbq-migration/noxfile_config.py
  cloud-sql/mysql/client-side-encryption/noxfile_config.py
  cloud-sql/postgres/client-side-encryption/noxfile_config.py
  cloud-sql/sql-server/client-side-encryption/noxfile_config.py
  composer/2022_airflow_summit/constraints.txt
  composer/2022_airflow_summit/noxfile_config.py
  composer/airflow_1_samples/noxfile_config.py
  composer/blog/gcp-tech-blog/data-orchestration-with-composer/constraints.txt
  composer/blog/gcp-tech-blog/data-orchestration-with-composer/noxfile_config.py
  composer/blog/gcp-tech-blog/unit-test-dags-cloud-build/noxfile_config.py
  composer/cicd_sample/constraints.txt
  composer/cicd_sample/noxfile_config.py
  composer/cicd_sample/utils/noxfile_config.py
  composer/workflows/constraints.txt
  composer/workflows/noxfile_config.py
  data-science-onramp/data-ingestion/noxfile_config.py
  data-science-onramp/data-processing/noxfile_config.py
  dataflow/custom-containers/miniconda/noxfile_config.py
  dataflow/custom-containers/minimal/noxfile_config.py
  dataflow/custom-containers/ubuntu/noxfile_config.py
  dataflow/encryption-keys/noxfile_config.py
  dataflow/extensible-templates/noxfile_config.py
  dataflow/flex-templates/streaming_beam/noxfile_config.py
  dataflow/gpu-examples/pytorch-minimal/noxfile_config.py
  dataflow/gpu-examples/tensorflow-landsat-prime/noxfile_config.py
  dataflow/gpu-examples/tensorflow-landsat/noxfile_config.py
  dataflow/gpu-examples/tensorflow-minimal/noxfile_config.py
  kubernetes_engine/django_tutorial/requirements.txt
  ml_engine/online_prediction/noxfile_config.py
  noxfile-template.py
  people-and-planet-ai/geospatial-classification/noxfile_config.py
  people-and-planet-ai/image-classification/noxfile_config.py
  people-and-planet-ai/land-cover-classification/noxfile_config.py
  people-and-planet-ai/timeseries-classification/noxfile_config.py
  pubsub/streaming-analytics/noxfile_config.py
  pubsublite/spark-connector/noxfile_config.py
  run/django/requirements.txt
Labels: api: composer, samples

#9003 ci: remove 3.11 from Dockerfile
  .kokoro/docker/Dockerfile
Labels: samples

#8985 chore(functions/tips-gcp-apis):update sample to use functions framework declarative signature
  functions/tips-gcp-apis/main.py
  functions/tips-gcp-apis/requirements.txt
Labels: api: cloudfunctions, samples

#8876 docs(samples): Document AI - Added Test & Evaluation Samples for `v1beta3` 2.3.0
  documentai/snippets/evaluate_processor_version_sample.py
  documentai/snippets/evaluate_processor_version_sample_test.py
  documentai/snippets/get_evaluation_sample.py
  documentai/snippets/get_evaluation_sample_test.py
  documentai/snippets/list_evaluations_sample.py
  documentai/snippets/list_evaluations_sample_test.py
  documentai/snippets/noxfile_config.py
  documentai/snippets/train_processor_version_sample.py
  documentai/snippets/train_processor_version_sample_test.py
Labels: automerge, samples

#8969 docs(samples): Document AI Warehouse - Created Quickstart Sample Code
  .github/CODEOWNERS
  .github/blunderbuss.yml
  contentwarehouse/AUTHORING_GUIDE.md
  contentwarehouse/CONTRIBUTING.md
  contentwarehouse/__init__.py
  contentwarehouse/snippets/__init__.py
  contentwarehouse/snippets/noxfile_config.py
  contentwarehouse/snippets/quickstart_sample.py
  contentwarehouse/snippets/quickstart_sample_test.py
  contentwarehouse/snippets/requirements-test.txt
  contentwarehouse/snippets/requirements.txt
  contentwarehouse/snippets/search_documents_sample.py
  contentwarehouse/snippets/search_documents_sample_test.py
  contentwarehouse/snippets/test_utilities.py
Labels: automerge, samples

#8983 fix(retail): updates tutorial for new location
  retail/interactive-tutorials/README.md
  retail/interactive-tutorials/events/conftest.py
  retail/interactive-tutorials/product/conftest.py
  retail/interactive-tutorials/product/setup_product/products_create_gcs_bucket.py
  retail/interactive-tutorials/user_import_data_to_catalog.sh
Labels: automerge, samples, api: retail

#9022 fix: Providing better error message for accounts without keys
  compute/oslogin/physical_security_key_ssh.py
Labels: api: compute, samples

#8996 chore(contact-center-insights): migrate code from googleapis/python-contact-center-insights
  contact-center-insights/snippets/create_analysis.py
  contact-center-insights/snippets/create_conversation.py
  contact-center-insights/snippets/create_conversation_with_ttl.py
  contact-center-insights/snippets/create_issue_model.py
  contact-center-insights/snippets/create_phrase_matcher_all_of.py
  contact-center-insights/snippets/create_phrase_matcher_any_of.py
  contact-center-insights/snippets/enable_pubsub_notifications.py
  contact-center-insights/snippets/export_to_bigquery.py
  contact-center-insights/snippets/get_operation.py
  contact-center-insights/snippets/noxfile_config.py
  contact-center-insights/snippets/requirements-test.txt
  contact-center-insights/snippets/requirements.txt
  contact-center-insights/snippets/set_project_ttl.py
  contact-center-insights/snippets/test_create_analysis.py
  contact-center-insights/snippets/test_create_conversation.py
  contact-center-insights/snippets/test_create_conversation_with_ttl.py
  contact-center-insights/snippets/test_create_issue_model.py
  contact-center-insights/snippets/test_create_phrase_matcher_all_of.py
  contact-center-insights/snippets/test_create_phrase_matcher_any_of.py
  contact-center-insights/snippets/test_enable_pubsub_notifications.py
  contact-center-insights/snippets/test_export_to_bigquery.py
  contact-center-insights/snippets/test_get_operation.py
  contact-center-insights/snippets/test_set_project_ttl.py
Labels: samples, api: contactcenterinsights

#8823 Update api_key_test.py for flaky test
  auth/api-client/api_key_test.py
  auth/api-client/requirements-test.txt
Labels: automerge, samples

#9043 Change default port from 8000 to 8080.
  recaptchaenterprise/samples/demosite/docker-compose.yaml
Labels: samples

#8874 test: add retries to dataproc tests
  dataproc/snippets/create_cluster_test.py
  dataproc/snippets/instantiate_inline_workflow_template_test.py
  dataproc/snippets/submit_job_test.py
  dataproc/snippets/update_cluster_test.py
Labels: samples

#9046 Revert "migrate code from googleapis/python-security-private-ca"
  privateca/snippets/activate_subordinate_ca.py
  privateca/snippets/conftest.py
  privateca/snippets/create_ca_pool.py
  privateca/snippets/create_certificate.py
  privateca/snippets/create_certificate_authority.py
  privateca/snippets/create_certificate_csr.py
  privateca/snippets/create_certificate_template.py
  privateca/snippets/create_subordinate_ca.py
  privateca/snippets/delete_ca_pool.py
  privateca/snippets/delete_certificate_authority.py
  privateca/snippets/delete_certificate_template.py
  privateca/snippets/disable_certificate_authority.py
  privateca/snippets/enable_certificate_authority.py
  privateca/snippets/filter_certificates.py
  privateca/snippets/list_ca_pools.py
  privateca/snippets/list_certificate_authorities.py
  privateca/snippets/list_certificate_templates.py
  privateca/snippets/list_certificates.py
  privateca/snippets/monitor_certificate_authority.py
  privateca/snippets/noxfile_config.py
  privateca/snippets/requirements-test.txt
  privateca/snippets/requirements.txt
  privateca/snippets/revoke_certificate.py
  privateca/snippets/test_ca_pools.py
  privateca/snippets/test_certificate_authorities.py
  privateca/snippets/test_certificates.py
  privateca/snippets/test_crud_certificate_templates.py
  privateca/snippets/test_subordinate_ca.py
  privateca/snippets/undelete_certificate_authority.py
  privateca/snippets/update_ca_pool_issuance_policy.py
  privateca/snippets/update_certificate_authority.py
  privateca/snippets/update_certificate_template.py
Labels: automerge, samples

#8497 feat: migrate code from googleapis/python-iam
  .github/CODEOWNERS
  .github/blunderbuss.yml
  iam/cloud-client/AUTHORING_GUIDE.md
  iam/cloud-client/CONTRIBUTING.md
  iam/cloud-client/snippets/__init__.py
  iam/cloud-client/snippets/conftest.py
  iam/cloud-client/snippets/create_deny_policy.py
  iam/cloud-client/snippets/delete_deny_policy.py
  iam/cloud-client/snippets/get_deny_policy.py
  iam/cloud-client/snippets/list_deny_policies.py
  iam/cloud-client/snippets/noxfile_config.py
  iam/cloud-client/snippets/requirements-test.txt
  iam/cloud-client/snippets/requirements.txt
  iam/cloud-client/snippets/test_deny_policies.py
  iam/cloud-client/snippets/update_deny_policy.py
Labels: samples

#8968 chore(samples): remove flaky test conditions
  retail/interactive-tutorials/search/search_with_query_expansion_spec_test.py
Labels: samples

#9024 More updates to run/image-processing/e2e_test.py
  run/image-processing/cloudbuild.yaml
  run/image-processing/e2e_test.py
Labels: api: run, samples

#8979 fix: remove unused assignment
  monitoring/snippets/v3/cloud-client/snippets.py
Labels: samples

#9052 fix: wait longer for incoming mail
  appengine/standard_python3/bundled-services/mail/wsgi/main_test.py
Labels: api: appengine, samples

#8984 Update vertex datascienceonramp
  data-science-onramp/vertex-ai/requirements.txt
Labels: samples

#9068 Demosite app recaptcha
  recaptchaenterprise/samples/demosite/app/main.py
  recaptchaenterprise/samples/demosite/app/static/browserconfig.xml
  recaptchaenterprise/samples/demosite/app/static/images/bot-color-unoptimized.svg
  recaptchaenterprise/samples/demosite/app/static/images/castle-unoptimized.svg
  recaptchaenterprise/samples/demosite/app/static/images/celebrate-unoptimized.svg
  recaptchaenterprise/samples/demosite/app/static/images/icons/favicon-120px.png
  recaptchaenterprise/samples/demosite/app/static/images/icons/favicon-128px.png
  recaptchaenterprise/samples/demosite/app/static/images/icons/favicon-144px.png
  recaptchaenterprise/samples/demosite/app/static/images/icons/favicon-150px.png
  recaptchaenterprise/samples/demosite/app/static/images/icons/favicon-152px.png
  recaptchaenterprise/samples/demosite/app/static/images/icons/favicon-16px.png
  recaptchaenterprise/samples/demosite/app/static/images/icons/favicon-180px.png
  recaptchaenterprise/samples/demosite/app/static/images/icons/favicon-192px.png
  recaptchaenterprise/samples/demosite/app/static/images/icons/favicon-196px.png
  recaptchaenterprise/samples/demosite/app/static/images/icons/favicon-310px.png
  recaptchaenterprise/samples/demosite/app/static/images/icons/favicon-32px.png
  recaptchaenterprise/samples/demosite/app/static/images/icons/favicon-512px.png
  recaptchaenterprise/samples/demosite/app/static/images/icons/favicon-64px.png
  recaptchaenterprise/samples/demosite/app/static/images/icons/favicon-70px.png
  recaptchaenterprise/samples/demosite/app/static/images/icons/favicon-96px.png
  recaptchaenterprise/samples/demosite/app/static/images/icons/favicon.ico
  recaptchaenterprise/samples/demosite/app/static/images/icons/favicon.svg
  recaptchaenterprise/samples/demosite/app/static/images/item-bike-unoptimized.svg
  recaptchaenterprise/samples/demosite/app/static/images/item-crosswalk-unoptimized.svg
  recaptchaenterprise/samples/demosite/app/static/images/magnifier-unoptimized.svg
  recaptchaenterprise/samples/demosite/app/static/images/mugshot-unoptimized.svg
  recaptchaenterprise/samples/demosite/app/static/images/shadow-arrow-unoptimized.svg
  recaptchaenterprise/samples/demosite/app/static/images/shadow-blob-unoptimized.svg
  recaptchaenterprise/samples/demosite/app/static/images/shadow-creeper-unoptimized.svg
  recaptchaenterprise/samples/demosite/app/static/images/shadow-flame-unoptimized.svg
  recaptchaenterprise/samples/demosite/app/static/images/shadow-ghost-unoptimized.svg
  recaptchaenterprise/samples/demosite/app/static/images/shadow-skull-unoptimized.svg
  recaptchaenterprise/samples/demosite/app/static/images/shield-unoptimized.svg
  recaptchaenterprise/samples/demosite/app/static/images/stop-unoptimized.svg
  recaptchaenterprise/samples/demosite/app/static/images/warning-unoptimized.svg
  recaptchaenterprise/samples/demosite/app/static/manifest.webmanifest
  recaptchaenterprise/samples/demosite/app/static/scripts/component.js
  recaptchaenterprise/samples/demosite/app/static/scripts/global.js
  recaptchaenterprise/samples/demosite/app/templates/comment.html
  recaptchaenterprise/samples/demosite/app/templates/game.html
  recaptchaenterprise/samples/demosite/app/templates/home.html
  recaptchaenterprise/samples/demosite/app/templates/login.html
  recaptchaenterprise/samples/demosite/app/templates/signup.html
  recaptchaenterprise/samples/demosite/app/templates/store.html
  recaptchaenterprise/samples/demosite/app/urls.py
Labels: samples
