Repository GoogleCloudPlatform/python-docs-samples, pull requests merged in 2023-12, with the labels that each got.

#10986 fix: practice-folder CODEOWNERS
  .github/CODEOWNERS
Labels: samples

#10987 fix: Update hello.py timestamp message
  practice-folder/beginner-sample/hello.py
  practice-folder/beginner-sample/hello_test.py
Labels: samples

#10985 chore: add create indexes section to notebook
  cloud-sql/postgres/pgvector/notebooks/pgvector_gen_ai_demo.ipynb
Labels: api: cloudsql, samples

#10991 chore(docs): update import log README
  logging/import-logs/README.md
Labels: automerge, samples

#11004 fix: correct deprecated Django functionality, update Django deps
  appengine/standard_python3/bundled-services/mail/django/main.py
  appengine/standard_python3/bundled-services/mail/django/requirements.txt
Labels: api: appengine, samples

#10998 chores(deps): update to Django 5, where supported by Python
  appengine/flexible/django_cloudsql/README.md
  appengine/flexible/django_cloudsql/mysite/settings.py
  appengine/flexible/django_cloudsql/requirements.txt
  appengine/flexible/hello_world_django/project_name/settings.py
  appengine/flexible/hello_world_django/project_name/urls.py
  appengine/flexible/hello_world_django/project_name/wsgi.py
  appengine/flexible/hello_world_django/requirements.txt
  appengine/flexible_python37_and_earlier/django_cloudsql/README.md
  appengine/flexible_python37_and_earlier/django_cloudsql/mysite/settings.py
  appengine/flexible_python37_and_earlier/django_cloudsql/requirements.txt
  appengine/flexible_python37_and_earlier/hello_world_django/project_name/settings.py
  appengine/flexible_python37_and_earlier/hello_world_django/project_name/urls.py
  appengine/flexible_python37_and_earlier/hello_world_django/project_name/wsgi.py
  appengine/flexible_python37_and_earlier/hello_world_django/requirements.txt
  appengine/standard/django/README.md
  appengine/standard/django/mysite/settings.py
  appengine/standard/django/mysite/wsgi.py
  appengine/standard_python3/bundled-services/blobstore/django/requirements.txt
  appengine/standard_python3/bundled-services/deferred/django/requirements.txt
  appengine/standard_python3/cloudsql/requirements.txt
  appengine/standard_python3/django/README.md
  appengine/standard_python3/django/mysite/settings.py
  appengine/standard_python3/django/requirements.txt
  kubernetes_engine/django_tutorial/README.md
  kubernetes_engine/django_tutorial/mysite/settings.py
  kubernetes_engine/django_tutorial/requirements.txt
  run/django/README.md
  run/django/mysite/asgi.py
  run/django/mysite/settings.py
  run/django/requirements.txt
Labels: api: appengine, api: run, api: container, samples

#11005 fix: import log to destination project
  logging/import-logs/README.md
  logging/import-logs/main.py
  logging/import-logs/main_test.py
Labels: samples

#10956 fix(firestore): Add await to the example
  firestore/cloud-async-client/snippets.py
  firestore/cloud-async-client/snippets_test.py
Labels: api: firestore, samples

#10997 fix: Fixing functions/billing tests
  functions/billing/main_test.py
Labels: api: cloudfunctions, samples

#11015 feat(generative-ai): Add function calling example for multimodal snippet
  generative_ai/function_calling.py
Labels: samples

#11016 feat(generative-ai): Add code samples for Gemini models
  generative_ai/gemini_chat_example.py
  generative_ai/gemini_count_token_example.py
  generative_ai/gemini_guide_example.py
  generative_ai/gemini_multi_image_example.py
  generative_ai/gemini_safety_config_example.py
  generative_ai/gemini_single_turn_video_example.py
  generative_ai/requirements.txt
  generative_ai/test_gemini_examples.py
Labels: samples

#10994 feat: intermediate codelab
  practice-folder/intermediate-sample/main.py
  practice-folder/intermediate-sample/main_test.py
  practice-folder/intermediate-sample/requirements-test.txt
  practice-folder/intermediate-sample/requirements.txt
Labels: samples

#11032 Add DAGs to inspect moved tables after airflow upgrade
  composer/workflows/airflow_moved_tables.py
  composer/workflows/airflow_moved_tables_test.py
  composer/workflows/requirements.txt
Labels: api: composer, samples

#11045 chore(generative_ai): update the order of items
  generative_ai/gemini_guide_example.py
  generative_ai/gemini_multi_image_example.py
  generative_ai/gemini_safety_config_example.py
  generative_ai/gemini_single_turn_video_example.py
Labels: samples
