Repository GoogleCloudPlatform/python-docs-samples, pull requests merged in 2023-11, with the labels that each got.

#10773 chore(flakybot): Changing default flaky issue priority to p2
  .github/flakybot.yaml
Labels: samples

#10905 fix(dlp): Included imports inside the region tag for dlp samples
  dlp/snippets/Deidentify/deidentify_cloud_storage.py
  dlp/snippets/Deidentify/deidentify_date_shift.py
  dlp/snippets/Deidentify/deidentify_deterministic.py
  dlp/snippets/Deidentify/deidentify_dictionary_replacement.py
  dlp/snippets/Deidentify/deidentify_exception_list.py
  dlp/snippets/Deidentify/deidentify_fpe.py
  dlp/snippets/Deidentify/deidentify_free_text_with_fpe_using_surrogate.py
  dlp/snippets/Deidentify/deidentify_masking.py
  dlp/snippets/Deidentify/deidentify_redact.py
  dlp/snippets/Deidentify/deidentify_replace.py
  dlp/snippets/Deidentify/deidentify_replace_infotype.py
  dlp/snippets/Deidentify/deidentify_simple_word_list.py
  dlp/snippets/Deidentify/deidentify_table_bucketing.py
  dlp/snippets/Deidentify/deidentify_table_condition_infotypes.py
  dlp/snippets/Deidentify/deidentify_table_condition_masking.py
  dlp/snippets/Deidentify/deidentify_table_fpe.py
  dlp/snippets/Deidentify/deidentify_table_infotypes.py
  dlp/snippets/Deidentify/deidentify_table_primitive_bucketing.py
  dlp/snippets/Deidentify/deidentify_table_row_suppress.py
  dlp/snippets/Deidentify/deidentify_table_with_crypto_hash.py
  dlp/snippets/Deidentify/deidentify_table_with_multiple_crypto_hash.py
  dlp/snippets/Deidentify/deidentify_time_extract.py
  dlp/snippets/Deidentify/reidentify_deterministic.py
  dlp/snippets/Deidentify/reidentify_fpe.py
  dlp/snippets/Deidentify/reidentify_free_text_with_fpe_using_surrogate.py
  dlp/snippets/Deidentify/reidentify_table_fpe.py
  dlp/snippets/Deidentify/reidentify_text_fpe.py
Labels: api: dlp, samples

#10904 Pin MySQL sample to Python 3.11
  cloud-sql/mysql/sqlalchemy/Dockerfile
Labels: api: cloudsql, samples

#10908 docs: remove datalab migration doc
  bigquery/datalab-migration/README.md
  bigquery/datalab-migration/noxfile_config.py
  bigquery/datalab-migration/requirements-test.txt
  bigquery/datalab-migration/requirements.txt
  bigquery/datalab-migration/samples_test.py
Labels: api: bigquery, samples

#10912 feat: add codelabs practice folder
  practice-folder/beginner-sample/hello.py
  practice-folder/beginner-sample/hello_test.py
  practice-folder/beginner-sample/requirements-test.txt
  practice-folder/beginner-sample/requirements.txt
  practice-folder/noxfile_config.py
Labels: samples

#10932 fix flaky test, fix authoring guide typo
  AUTHORING_GUIDE.md
  automl/tables/automl_tables_dataset.py
  automl/tables/dataset_test.py
Labels: api: automl, samples

#10914 feat: Add Auto Approve bot config
  .github/auto-approve.yml
Labels: samples

#10917 feat: Makefile for consistent python testing interface
  Makefile
Labels: samples

#10923 Add code snippet for auto-detect language feature.
  speech/snippets/transcribe_chirp_auto_detect_language.py
  speech/snippets/transcribe_chirp_auto_detect_language_test.py
Labels: api: speech, samples

#10934 fix(recaptcha): Fixing Flask+Werkzeug versioning problem
  recaptcha_enterprise/snippets/requirements-test.txt
Labels: api: recaptchaenterprise, samples

#10930 feat: Adding Python 3.12 to our test image
  .kokoro/docker/Dockerfile
  .kokoro/docker/fetch_gpg_keys.sh
Labels: samples

#10935 Restore Dockerfile
  run/helloworld/Dockerfile
Labels: api: run, samples

#10918 docs(samples): Add flex template "getting started" sample
  dataflow/flex-templates/getting_started/README.md
  dataflow/flex-templates/getting_started/getting_started.py
  dataflow/flex-templates/getting_started/metadata.json
  dataflow/flex-templates/getting_started/requirements.txt
Labels: samples

#10747 Update pub/sub - appengine push request sample
  appengine/standard_python3/pubsub/main.py
  appengine/standard_python3/pubsub/main_test.py
Labels: api: pubsub, samples

#10944 fix(generative_ai): update testcase
  generative_ai/code_completion_test_function_test.py
Labels: samples

#10952 fix: update import logs sample README.md
  logging/import-logs/README.md
Labels: samples

#10966 fix: correct last updated message
  practice-folder/beginner-sample/hello.py
  practice-folder/beginner-sample/hello_test.py
Labels: samples

#10974 fix: assign practice-folder CODEOWNER
  .github/CODEOWNERS
Labels: samples

#10980 fix: correct last updated message
  practice-folder/beginner-sample/hello.py
  practice-folder/beginner-sample/hello_test.py
Labels: samples
