Repository GoogleCloudPlatform/python-docs-samples, pull requests merged in 2024-05, with the labels that each got.

#11589 samples(vertex-ai): Add missing parameter for RAG Upload File
  generative_ai/rag.py
  generative_ai/rag_test.py
  generative_ai/requirements.txt
Labels: samples, api: vertex-ai

#11613 samples(documentai, discoveryengine): Add Samples for Vertex AI Search Standalone RAG APIs
  discoveryengine/requirements.txt
  discoveryengine/standalone_apis_sample.py
  discoveryengine/standalone_apis_sample_test.py
  documentai/snippets/handle_response_sample_test.py
  documentai/snippets/handle_response_sample_v1beta3.py
  documentai/snippets/requirements.txt
Labels: samples, api: documentai, api: discoveryengine

#11611 chore: update docs and region tags
  generative_ai/anthropic_claude_3_streaming.py
  generative_ai/anthropic_claude_3_unary.py
  generative_ai/code_chat.py
  generative_ai/code_completion_function.py
  generative_ai/code_completion_test_function.py
  generative_ai/grounding.py
  generative_ai/ideation.py
  generative_ai/list_tuned_code_generation_models.py
  generative_ai/list_tuned_models.py
  generative_ai/multimodal_embedding_image.py
  generative_ai/multimodal_embedding_image_video_text.py
  generative_ai/multimodal_embedding_video.py
  generative_ai/sentiment_analysis.py
  generative_ai/streaming_chat.py
  generative_ai/streaming_code.py
  generative_ai/streaming_codechat.py
  generative_ai/streaming_text.py
  generative_ai/summarization.py
  generative_ai/tune_code_generation_model.py
  generative_ai/tuning.py
Labels: samples

#11614 refactor(generative-ai): Remove redundant TODOs
  generative_ai/gemini_guide_example.py
Labels: samples

#11618 Use tune_model method on TextEmbeddingModel class.
  generative_ai/embedding_model_tuning.py
  generative_ai/embedding_model_tuning_test.py
  generative_ai/requirements.txt
Labels: samples

#11619 refactor(generative_ai): update gemini sample to use specific location and add developer TODOs
  generative_ai/gemini_chat_example.py
  generative_ai/gemini_count_token_example.py
  generative_ai/gemini_grounding_example.py
  generative_ai/gemini_guide_example.py
  generative_ai/gemini_multi_image_example.py
  generative_ai/gemini_pro_basic_example.py
  generative_ai/gemini_pro_config_example.py
  generative_ai/gemini_safety_config_example.py
  generative_ai/gemini_single_turn_video_example.py
  generative_ai/test_gemini_examples.py
Labels: samples

#11713 fix(generative-ai): Update count tokens sample
  generative_ai/embedding_model_tuning_test.py
  generative_ai/gemini_count_token_example.py
  generative_ai/test_gemini_examples.py
Labels: samples

#11718 style(generative_ai): Update AI samples to have script style format
  generative_ai/README.md
  generative_ai/code_generation_function.py
  generative_ai/code_generation_unittest.py
  generative_ai/distillation.py
  generative_ai/extraction.py
  generative_ai/function_calling.py
  generative_ai/function_calling_chat.py
  generative_ai/tune_code_generation_model.py
  generative_ai/tuning.py
Labels: samples

#11717 fix(iam.deny): Skipping test if we don't have permission to run it.
  iam/cloud-client/snippets/conftest.py
Labels: api: iam, samples

#11722 chore(fixit): remove redundant region tags
  run/helloworld/main.py
  run/pubsub/main.py
Labels: api: run, samples

#11723 feat: override the 003 model code sample to 004 models.
  generative_ai/embedding.py
  generative_ai/embedding_test.py
Labels: samples

#11602 feat: service account manipulations samples
  iam/cloud-client/snippets/service_account_get_policy.py
  iam/cloud-client/snippets/service_account_rename.py
  iam/cloud-client/snippets/service_account_set_policy.py
  iam/cloud-client/snippets/test_service_account.py
Labels: api: iam, samples

#11724 Add samples for the Tuning API reference doc
  generative_ai/gemini_tuning.py
  generative_ai/gemini_tuning_test.py
Labels: samples

#11737 fix: indent error
  generative_ai/gemini_video_audio.py
Labels: samples

#11728 Add samples for the Extensions API reference doc
  generative_ai/gemini_extensions.py
  generative_ai/gemini_extensions_test.py
Labels: samples

#11738 samples(generative_ai): Create Reasoning engine samples
  generative_ai/gemini_reasoning_engine.py
  generative_ai/gemini_reasoning_engine_test.py
  generative_ai/requirements-test.txt
  generative_ai/requirements.txt
Labels: samples, aiplatform

#11740 feat: update text-only input sample to use a generic review
  generative_ai/gemini_text_input_example.py
Labels: samples

#11739 samples(documentai): Add missing region tag around imports
  documentai/snippets/handle_response_sample_v1beta3.py
Labels: samples, api: documentai

#11746 samples(generative_ai): Add Rapid Evaluation Python Samples
  generative_ai/gemini_rapid_evaluation.py
  generative_ai/gemini_rapid_evaluation_test.py
  generative_ai/requirements.txt
Labels: samples

#11748 samples(generative_ai): Update Rapid Eval Sample to use Vertex AI SDK
  generative_ai/gemini_rapid_evaluation.py
  generative_ai/gemini_rapid_evaluation_test.py
Labels: kokoro:force-run, samples

#11747 functions: delete functions/ci_cd directory
  functions/ci_cd/cloudbuild.yaml
Labels: api: cloudfunctions, samples

#11749 deprecate: move deployment-previews to devrel-demos
  run/deployment-previews/Dockerfile
  run/deployment-previews/README.md
  run/deployment-previews/check_status.py
  run/deployment-previews/cloudbuild-configurations/README.md
  run/deployment-previews/cloudbuild-configurations/cloudbuild-cleanup.yaml
  run/deployment-previews/cloudbuild-configurations/cloudbuild-preview.yaml
  run/deployment-previews/cloudbuild-configurations/cloudbuild.yaml
  run/deployment-previews/images/deployment-previews-deployed-service.png
  run/deployment-previews/images/deployment-previews-github-completed-check.png
  run/deployment-previews/images/deployment-previews-github-edit-file-2.png
  run/deployment-previews/images/deployment-previews-github-pending-check.png
  run/deployment-previews/images/deployment-previews-preview-service.png
  run/deployment-previews/images/deployment-previews-revisions-four.png
  run/deployment-previews/images/deployment-previews-revisions-one.png
  run/deployment-previews/images/deployment-previews-revisions-three.png
  run/deployment-previews/images/deployment-previews-revisions-two.png
  run/deployment-previews/images/deployment-previews-updated-service.png
  run/deployment-previews/noxfile_config.py
  run/deployment-previews/requirements-test.txt
  run/deployment-previews/requirements.txt
  run/deployment-previews/test_app.py
Labels: api: run, samples

#11721 docs(bigquery-connection): supply a manual connection_id to assist with cleanup
  bigquery-connection/snippets/create_mysql_connection.py
  bigquery-connection/snippets/create_mysql_connection_test.py
Labels: samples

#11755 chore(cloudrun): Cleanup deprecated sample Cloud Run Filesystem
  run/filesystem/Dockerfile
  run/filesystem/README.md
  run/filesystem/cloudbuild.yaml
  run/filesystem/e2e_test.py
  run/filesystem/gcsfuse.Dockerfile
  run/filesystem/gcsfuse_run.sh
  run/filesystem/main.py
  run/filesystem/main_test.py
  run/filesystem/requirements-test.txt
  run/filesystem/requirements.txt
  run/filesystem/retry.sh
  run/filesystem/run.sh
Labels: api: run, samples

#11745 Standardize the location parameter
  generative_ai/gemini_tuning.py
  generative_ai/gemini_tuning_test.py
  generative_ai/inference/inference_api_test.py
  generative_ai/inference/non_stream_multimodality_basic.py
  generative_ai/inference/non_stream_text_basic.py
  generative_ai/inference/stream_multimodality_basic.py
  generative_ai/inference/stream_text_basic.py
  generative_ai/multimodal_embedding_image.py
  generative_ai/multimodal_embedding_image_test.py
  generative_ai/multimodal_embedding_image_video_text.py
  generative_ai/multimodal_embedding_image_video_text_test.py
  generative_ai/multimodal_embedding_video.py
  generative_ai/multimodal_embedding_video_test.py
Labels: kokoro:run, samples

#11753 fix: leverage single pre-created role in tests
  iam/cloud-client/snippets/conftest.py
Labels: api: iam, samples

#11626 [Fix] Adding retries for flaky tests
  iam/cloud-client/snippets/get_policy.py
  iam/cloud-client/snippets/modify_policy_add_member.py
  iam/cloud-client/snippets/modify_policy_remove_member.py
  iam/cloud-client/snippets/requirements-test.txt
  iam/cloud-client/snippets/set_policy.py
  iam/cloud-client/snippets/test_project_policies.py
  iam/cloud-client/snippets/test_service_account_key.py
Labels: api: iam, samples

#11756 feat: refactor text-only Gemini prompt
  generative_ai/gemini_text_input_example.py
Labels: samples

#11763 fix: remove unused region tags
  eventarc/generic/Dockerfile
  eventarc/pubsub/Dockerfile
Labels: samples, api: eventarc

#11768 feat: Gemini 1.5 Flash updates
  generative_ai/function_calling.py
  generative_ai/gemini_all_modalities.py
  generative_ai/gemini_audio.py
  generative_ai/gemini_pdf_example.py
  generative_ai/gemini_system_instruction.py
  generative_ai/gemini_video_audio.py
Labels: samples

#11770 feat(generative_ai): update gemini model to use flash model
  generative_ai/function_calling.py
  generative_ai/gemini_all_modalities.py
  generative_ai/gemini_audio.py
  generative_ai/gemini_count_token_example.py
  generative_ai/gemini_pdf_example.py
  generative_ai/gemini_system_instruction.py
  generative_ai/gemini_tuning_test.py
  generative_ai/gemini_video_audio.py
  generative_ai/inference/inference_api_test.py
Labels: samples

#11772 docs(generative_ai): clearing comments
  generative_ai/function_calling.py
  generative_ai/gemini_all_modalities.py
  generative_ai/gemini_audio.py
  generative_ai/gemini_count_token_example.py
  generative_ai/gemini_pdf_example.py
  generative_ai/gemini_system_instruction.py
  generative_ai/gemini_video_audio.py
Labels: samples

#11773 feat: Update embedding tuning sample to use new preview parameters.
  generative_ai/embedding_model_tuning.py
  generative_ai/requirements.txt
Labels: samples

#11607 [snipets][compute_ip_address_unassign_static_address]
  compute/client_library/ingredients/instances/ip_address/unassign_static_ip_from_existing_vm.py
  compute/client_library/recipes/instances/ip_address/unassign_static_ip_address_from_existing_vm.py
  compute/client_library/snippets/instances/ip_address/unassign_static_ip_address_from_existing_vm.py
  compute/client_library/snippets/tests/test_ip_address.py
Labels: api: compute, samples

#11598 [snipets][compute_ip_address_assign_static_existing_vm]
  compute/client_library/ingredients/instances/ip_address/assign_static_ip_to_existing_vm.py
  compute/client_library/recipes/instances/ip_address/assign_static_ip_to_existing_vm.py
  compute/client_library/snippets/instances/ip_address/assign_static_ip_to_existing_vm.py
  compute/client_library/snippets/tests/test_ip_address.py
Labels: api: compute, samples

#11610 Samples/compute ip address assign static external new vm
  compute/client_library/ingredients/instances/ip_address/assign_static_external_ip_to_new_vm.py
  compute/client_library/recipes/instances/ip_address/assign_static_external_ip_to_new_vm.py
  compute/client_library/snippets/instances/ip_address/assign_static_external_ip_to_new_vm.py
  compute/client_library/snippets/tests/test_ip_address.py
Labels: api: compute, samples

#11405 Add script for usage in IAP public documentation on how to authentica…
  iap/README.md
  iap/generate_self_signed_jwt.py
  iap/requirements.txt
Labels: api: iap, samples, automerge: exact

#11779 fix: closeSend example for python
  dialogflow/detect_intent_stream.py
Labels: api: dialogflow, samples

#11617 [snipets][compute_ip_address_promote_ephemeral]
  compute/client_library/ingredients/instances/ip_address/promote_ephemeral_ip.py
  compute/client_library/recipes/instances/ip_address/promote_ephemeral_ip.py
  compute/client_library/snippets/instances/ip_address/promote_ephemeral_ip.py
  compute/client_library/snippets/tests/test_ip_address.py
Labels: api: compute, samples

#11781 Feat: Memcached samples
  memorystore/memcache/noxfile_config.py
  memorystore/memcache/quickstart.py
  memorystore/memcache/quickstart_test.py
  memorystore/memcache/requirement-test.txt
  memorystore/memcache/requirement.txt
Labels: samples, api: memorystore

#11784 fix: spelling and update comment test_gemini_examples.py
  generative_ai/embedding_model_tuning.py
  generative_ai/test_gemini_examples.py
Labels: samples

#11782 Use Alphabet 10k sample dataset.
  generative_ai/embedding_model_tuning.py
Labels: samples

#11790 fix(generative-ai): temperature is not defined in the sample
  generative_ai/summarization.py
  generative_ai/summarization_test.py
Labels: samples

#11754 samples(generative_ai): Update RAG Samples to include `RagResource`
  generative_ai/rag.py
  generative_ai/rag_test.py
Labels: samples

#11780 cleanup(IAM): Removing Apiary code samples.
  iam/api-client/access.py
  iam/api-client/access_test.py
  iam/api-client/custom_roles.py
  iam/api-client/custom_roles_test.py
  iam/api-client/quickstart.py
  iam/api-client/quickstart_test.py
  iam/api-client/service_account_keys.py
  iam/api-client/service_accounts.py
  iam/api-client/service_accounts_test.py
  iam/cloud-client/snippets/iam_check_permissions.py
  iam/cloud-client/snippets/iam_modify_policy_add_role.py
  iam/cloud-client/snippets/query_testable_permissions.py
  iam/cloud-client/snippets/test_test_permissions.py
Labels: api: iam, samples

#11795 feat(generative-ai): Update Gemini model versions
  generative_ai/gemini_multi_image_example.py
  generative_ai/gemini_pro_basic_example.py
  generative_ai/gemini_single_turn_video_example.py
Labels: samples

#11799 style(cdn): update snippets.py code format.
  cdn/snippets.py
  cdn/snippets_test.py
Labels: samples

#11792 fix: added additional configurations with description
  container/snippets/create_cluster.py
  container/snippets/create_cluster_test.py
Labels: api: container, samples

#11807 Add tool use sample for Claude model
  generative_ai/anthropic_claude_3_tool_use.py
  generative_ai/anthropic_claude_3_tool_use_test.py
Labels: samples

#11810 Refactor the chat completions API samples
  generative_ai/chat_completions/chat_completions_test.py
  generative_ai/chat_completions/non_streaming_image.py
  generative_ai/chat_completions/non_streaming_text.py
  generative_ai/chat_completions/noxfile_config.py
  generative_ai/chat_completions/streaming_image.py
  generative_ai/chat_completions/streaming_text.py
Labels: samples
