Repository GoogleCloudPlatform/python-docs-samples, pull requests merged in 2024-02, with the labels that each got.

#11164 fixed the issue with transcribed text exits after one word
  speech/microphone/noxfile_config.py
  speech/microphone/transcribe_streaming_mic.py
Labels: api: speech, samples

#11166 fix: compute template test issue
  compute/client_library/ingredients/instances/create_instance.py
  compute/client_library/snippets/tests/test_templates.py
Labels: api: compute, samples

#11147 docs(samples): Fix Pub/Sub snippet for Dataflow runner
  dataflow/snippets/tests/test_write_pubsub.py
  dataflow/snippets/write_pubsub.py
Labels: samples

#11170 docs(samples): Set the assessment.event.expected_action when sending a CreateAssessm…
  recaptcha_enterprise/demosite/app/backend/create_recaptcha_assessment.py
  recaptcha_enterprise/demosite/app/urls.py
Labels: api: recaptchaenterprise, samples, asset: flagship

#11156 feat: add code samples for distillation
  generative_ai/distillation.py
  generative_ai/distillation_test.py
Labels: samples

#11197 feat(soft-delete-cost-analysis): Script to identify buckets with relative increase in cost on enabling the soft-delete.
  storage/cost-analysis/README.md
  storage/cost-analysis/storage_soft_delete_relative_cost_analyzer.py
Labels: api: storage, samples

#11205 feat: update gemini samples imports
  generative_ai/function_calling.py
  generative_ai/gemini_chat_example.py
  generative_ai/gemini_count_token_example.py
  generative_ai/gemini_guide_example.py
  generative_ai/gemini_multi_image_example.py
  generative_ai/gemini_pro_basic_example.py
  generative_ai/gemini_pro_config_example.py
  generative_ai/gemini_safety_config_example.py
  generative_ai/gemini_single_turn_video_example.py
  generative_ai/requirements.txt
  generative_ai/test_gemini_examples.py
Labels: samples

#11202 fix(monitoring): Fixing flaky tests
  monitoring/snippets/v3/cloud-client/snippets_test.py
Labels: api: monitoring, samples

#11222 docs(samples): Updating readme for soft delete cost analyzer script
  storage/cost-analysis/README.md
  storage/cost-analysis/storage_soft_delete_relative_cost_analyzer.py
Labels: api: storage, samples

#11224 fix: distillation unit test fix
  generative_ai/distillation.py
  generative_ai/distillation_test.py
Labels: samples

#11210 feat: add imagen edit image sample
  generative_ai/imagen/edit_image_mask_free.py
  generative_ai/imagen/edit_image_mask_free_test.py
  generative_ai/imagen/test_resources/cat.png
  generative_ai/imagen/test_resources/dog.png
  generative_ai/requirements.txt
Labels: samples

#11229 fix(generative-ai): update text-bison stable version to 002
  generative_ai/classify_news_items.py
  generative_ai/evaluate_model.py
  generative_ai/extraction.py
  generative_ai/ideation.py
  generative_ai/list_tuned_models.py
  generative_ai/sentiment_analysis.py
  generative_ai/summarization.py
  generative_ai/tuning.py
Labels: samples

#10267 feat(Imagen): Add python sdk samples for Multimodal Embeddings
  generative_ai/multimodal_embedding_image.py
  generative_ai/multimodal_embedding_image_test.py
  generative_ai/multimodal_embedding_image_video_text.py
  generative_ai/multimodal_embedding_image_video_text_test.py
  generative_ai/multimodal_embedding_video.py
  generative_ai/multimodal_embedding_video_test.py
  generative_ai/requirements.txt
Labels: samples

#11245 fix(sample) - Update soft_delete_window(seconds) from int to float in the soft delete relative cost analyzer.
  storage/cost-analysis/README.md
  storage/cost-analysis/storage_soft_delete_relative_cost_analyzer.py
Labels: api: storage, samples

#10506 remove unnecessary "break" from for loop
  asset/snippets/quickstart_searchallresources.py
Labels: kokoro:run, samples, api: asset

#11259 bug fix: fix the function call for Gen AI samples
  generative_ai/chat.py
  generative_ai/classify_news_items.py
  generative_ai/classify_news_items_test.py
  generative_ai/code_chat.py
  generative_ai/code_completion_function.py
  generative_ai/code_completion_test_function.py
  generative_ai/code_generation_function.py
  generative_ai/distillation.py
  generative_ai/embedding.py
  generative_ai/evaluate_model.py
  generative_ai/evaluate_model_test.py
  generative_ai/extraction.py
  generative_ai/extraction_test.py
  generative_ai/ideation.py
  generative_ai/ideation_test.py
  generative_ai/list_tuned_code_generation_models.py
  generative_ai/list_tuned_models.py
  generative_ai/sentiment_analysis.py
  generative_ai/streaming_chat.py
  generative_ai/streaming_code.py
  generative_ai/streaming_codechat.py
  generative_ai/streaming_text.py
  generative_ai/summarization.py
  generative_ai/tune_code_generation_model.py
  generative_ai/tuning.py
Labels: samples

#11204 fix(firestore): failed recursive delete in snippet
  firestore/cloud-client/snippets.py
Labels: api: firestore, samples

#10938 feat(Makefile): use make to run kokoro tests
  .kokoro/tests/run_single_test.sh
  Makefile
Labels: samples

#11247 feat: add imagen samples: generate image from prompt, get captions, g…
  generative_ai/imagen/generate_image.py
  generative_ai/imagen/generate_image_test.py
  generative_ai/imagen/get_short_form_image_captions.py
  generative_ai/imagen/get_short_form_image_captions_test.py
  generative_ai/imagen/get_short_form_image_responses.py
  generative_ai/imagen/get_short_form_image_responses_test.py
Labels: samples

#11257 Add code sample for `generative-ai/function-calling-chat` that uses the chat modality
  generative_ai/function_calling.py
  generative_ai/function_calling_chat.py
  generative_ai/function_calling_chat_test.py
Labels: samples

#11246 feat: Add Vertex AI Grounding samples
  generative_ai/gemini_grounding_example.py
  generative_ai/grounding.py
  generative_ai/grounding_test.py
  generative_ai/test_gemini_examples.py
Labels: samples
