Repository GoogleCloudPlatform/python-docs-samples, pull requests merged in 2024-03, with the labels that each got.

#11274 samples(discoveryengine): Add Model Prompt Spec and Model Spec to `search_sample()`
  discoveryengine/requirements-test.txt
  discoveryengine/requirements.txt
  discoveryengine/search_sample.py
Labels: samples, api: discoveryengine

#11275 feat: add edit image with mask sample and test
  generative_ai/imagen/edit_image_mask.py
  generative_ai/imagen/edit_image_mask_test.py
  generative_ai/imagen/test_resources/dog_book.png
  generative_ai/imagen/test_resources/dog_newspaper.png
  generative_ai/imagen/test_resources/dog_newspaper_mask.png
Labels: samples

#11288 fix(discoveryengine): Update Search Sample to use Engine/App ID
  discoveryengine/requirements.txt
  discoveryengine/search_sample.py
  discoveryengine/search_sample_test.py
Labels: samples, api: discoveryengine

#11299 chore(deps): update google-cloud-recaptcha-enterprise client to 1.18.1
  recaptcha_enterprise/demosite/app/requirements.txt
Labels: api: recaptchaenterprise, samples, asset: flagship

#11116 fix: update the last_updated string
  practice-folder/beginner-sample/hello.py
  practice-folder/beginner-sample/hello_test.py
Labels: samples

#11293 Add code sample on how to use Claude 3
  generative_ai/anthropic_claude_3_streaming.py
  generative_ai/anthropic_claude_3_streaming_test.py
  generative_ai/anthropic_claude_3_unary.py
  generative_ai/anthropic_claude_3_unary_test.py
  generative_ai/requirements.txt
Labels: samples

#11313 fix: skip failing Gemini grounding test due to allowlist restrictions
  generative_ai/test_gemini_examples.py
Labels: samples

#11290 chore: update embedding sample to be more developer friendly
  generative_ai/embedding.py
Labels: samples

#11316 fix: dimension parameter not supported
  generative_ai/multimodal_embedding_image.py
Labels: samples

#11266 [Gemini function calling] Fix type annotation for function output in `generative-ai/function-calling` example
  generative_ai/function_calling.py
Labels: samples

#11324 Update `generative-ai/function-calling` code sample to remove role from FunctionResponse
  generative_ai/function_calling.py
Labels: samples

#11300 fix disk list.py
  compute/client_library/ingredients/disks/list.py
  compute/client_library/snippets/disks/list.py
Labels: automerge, api: compute, samples

#11318 Update comments: config_file must be specified explicitly
  composer/workflows/kubernetes_pod_operator_c2.py
Labels: api: composer, samples

#11252 Add an example for building a flex template for a python pipeline with extra dependencies and a custom container.
  dataflow/conftest.py
  dataflow/flex-templates/pipeline_with_dependencies/Dockerfile
  dataflow/flex-templates/pipeline_with_dependencies/README.md
  dataflow/flex-templates/pipeline_with_dependencies/e2e_test.py
  dataflow/flex-templates/pipeline_with_dependencies/main.py
  dataflow/flex-templates/pipeline_with_dependencies/metadata.json
  dataflow/flex-templates/pipeline_with_dependencies/my_package/__init__.py
  dataflow/flex-templates/pipeline_with_dependencies/my_package/launcher.py
  dataflow/flex-templates/pipeline_with_dependencies/my_package/my_pipeline.py
  dataflow/flex-templates/pipeline_with_dependencies/my_package/my_transforms.py
  dataflow/flex-templates/pipeline_with_dependencies/my_package/utils/__init__.py
  dataflow/flex-templates/pipeline_with_dependencies/my_package/utils/figlet.py
  dataflow/flex-templates/pipeline_with_dependencies/noxfile_config.py
  dataflow/flex-templates/pipeline_with_dependencies/requirements-test.txt
  dataflow/flex-templates/pipeline_with_dependencies/requirements.txt
  dataflow/flex-templates/pipeline_with_dependencies/setup.py
  renovate.json
Labels: samples

#11358 build: Add setuptools to Dockerfile
  .kokoro/docker/Dockerfile
Labels: samples

#11361 refactor: change the region tags for Gemini samples
  generative_ai/function_calling.py
  generative_ai/function_calling_chat.py
  generative_ai/gemini_chat_example.py
  generative_ai/gemini_count_token_example.py
  generative_ai/gemini_grounding_example.py
  generative_ai/gemini_guide_example.py
  generative_ai/gemini_multi_image_example.py
  generative_ai/gemini_pro_basic_example.py
  generative_ai/gemini_pro_config_example.py
  generative_ai/gemini_safety_config_example.py
  generative_ai/gemini_single_turn_video_example.py
Labels: samples

#11363 fix: update comment to reflect the required argument
  run/jobs/main.py
Labels: api: run, samples

#11362 Don't pass the --setup_file option when a package is already installed in the custom image.
  dataflow/flex-templates/pipeline_with_dependencies/Dockerfile
Labels: samples
