Repository GoogleCloudPlatform/python-docs-samples, pull requests merged in 2024-04, with the labels that each got.

#11368 feat: Text-Embedding Model Tuning demo.
  generative_ai/embedding_model_tuning.py
  generative_ai/embedding_model_tuning_test.py
Labels: samples

#11387 Fix flaky test_gemini_examples.py
  generative_ai/test_gemini_examples.py
Labels: samples

#11380 feat: add edit product image editing sample and test for Imagen 2
  generative_ai/imagen/edit_image_product_image.py
  generative_ai/imagen/edit_image_product_image_test.py
  generative_ai/imagen/test_resources/cat.png
  generative_ai/imagen/test_resources/dog.png
  generative_ai/imagen/test_resources/dog_book.png
  generative_ai/imagen/test_resources/dog_newspaper.png
  generative_ai/imagen/test_resources/dog_newspaper_mask.png
  generative_ai/imagen/test_resources/pillow.png
  generative_ai/imagen/test_resources/pillow_on_beach.png
  generative_ai/requirements.txt
Labels: samples

#11390 feat: Add Gemini PDF Sample & Add Type for `GenerationConfig`
  generative_ai/embedding_model_tuning.py
  generative_ai/embedding_model_tuning_test.py
  generative_ai/function_calling.py
  generative_ai/gemini_pdf_example.py
  generative_ai/gemini_pro_config_example.py
  generative_ai/gemini_safety_config_example.py
  generative_ai/test_gemini_examples.py
Labels: samples, api: vertex-ai

#11406 chore: remove 3.12 tests from python 3.7 samples
  appengine/flexible_python37_and_earlier/analytics/noxfile_config.py
  appengine/flexible_python37_and_earlier/datastore/noxfile_config.py
  appengine/flexible_python37_and_earlier/disk/noxfile_config.py
  appengine/flexible_python37_and_earlier/django_cloudsql/noxfile_config.py
  appengine/flexible_python37_and_earlier/extending_runtime/noxfile_config.py
  appengine/flexible_python37_and_earlier/hello_world/noxfile_config.py
  appengine/flexible_python37_and_earlier/hello_world_django/noxfile_config.py
  appengine/flexible_python37_and_earlier/metadata/noxfile_config.py
  appengine/flexible_python37_and_earlier/multiple_services/noxfile_config.py
  appengine/flexible_python37_and_earlier/numpy/noxfile_config.py
  appengine/flexible_python37_and_earlier/pubsub/noxfile_config.py
  appengine/flexible_python37_and_earlier/scipy/noxfile_config.py
  appengine/flexible_python37_and_earlier/static_files/noxfile_config.py
  appengine/flexible_python37_and_earlier/storage/noxfile_config.py
  appengine/flexible_python37_and_earlier/tasks/noxfile_config.py
  appengine/flexible_python37_and_earlier/twilio/noxfile_config.py
  appengine/flexible_python37_and_earlier/websockets/noxfile_config.py
  profiler/appengine/standard_python37/noxfile_config.py
Labels: api: appengine, api: cloudprofiler, samples

#11391 feat: add storagecontrol quickstart sample
  .github/CODEOWNERS
  .github/blunderbuss.yml
  storagecontrol/conftest.py
  storagecontrol/noxfile_config.py
  storagecontrol/quickstart.py
  storagecontrol/quickstart_test.py
  storagecontrol/requirements-test.txt
  storagecontrol/requirements.txt
Labels: samples

#11411 feat: update generate image sample to 006
  generative_ai/imagen/generate_image.py
Labels: samples

#11410 fix: remove unneeded number of images parameter from edit product ima…
  generative_ai/imagen/edit_image_product_image.py
Labels: samples

#11412 feat: update region tags for existing Imagen samples
  generative_ai/imagen/edit_image_mask.py
  generative_ai/imagen/edit_image_mask_free.py
  generative_ai/imagen/get_short_form_image_captions.py
  generative_ai/imagen/get_short_form_image_responses.py
Labels: samples

#11429 feat: Add Gemini 1.5 Pro code samples
  generative_ai/gemini_all_modalities.py
  generative_ai/gemini_audio.py
  generative_ai/gemini_system_instruction.py
  generative_ai/gemini_video_audio.py
  generative_ai/requirements.txt
  generative_ai/test_gemini_examples.py
Labels: samples

#11426 fix: Tidy up text embedding model tuning demo.
  generative_ai/embedding_model_tuning.py
Labels: samples

#11435 refactor: Update Gemini PDF example
  generative_ai/gemini_pdf_example.py
  generative_ai/test_gemini_examples.py
Labels: samples

#11428 nitpick: Update documentation and naming in read_table_list function
  composer/workflows/bq_copy_across_locations.py
Labels: api: composer, samples

#11430 fix(generative-ai): Making test more accepting for AI answer.
  generative_ai/test_gemini_examples.py
Labels: automerge, samples

#11459 tests: Skip Document AI Warehouse Tests due to deprecation/failures
  contentwarehouse/snippets/create_folder_link_document_sample_test.py
  contentwarehouse/snippets/create_get_delete_document_schema_test.py
  contentwarehouse/snippets/create_get_update_delete_document_test.py
  contentwarehouse/snippets/create_rule_set_sample_test.py
  contentwarehouse/snippets/fetch_acl_sample_test.py
  contentwarehouse/snippets/list_document_schema_test.py
  contentwarehouse/snippets/noxfile_config.py
  contentwarehouse/snippets/quickstart_sample_test.py
  contentwarehouse/snippets/search_documents_sample_test.py
  contentwarehouse/snippets/set_acl_sample_test.py
  contentwarehouse/snippets/update_document_schema_sample_test.py
Labels: samples, api: contentwarehouse

#11436 Add separate sample for grounding with web and vertex search.
  generative_ai/gemini_grounding_example.py
  generative_ai/test_gemini_examples.py
Labels: samples

#11535 chore: Change Dependabot to group dependencies
  .github/dependabot.yml
Labels: samples

#11534 Update Dockerfile to fix Python 3.12 tests
  .kokoro/docker/Dockerfile
  vision/snippets/detect/detect_test.py
Labels: samples

#11540 feat: update Imagen 2 samples for usability
  generative_ai/imagen/generate_image.py
  generative_ai/imagen/generate_image_test.py
Labels: samples

#11451 issue-10628 fix
  speech/microphone/README.rst
  speech/snippets/README.rst
Labels: api: speech, samples

#11542 chore: update cloud-sql/sqlserver deps
  cloud-sql/sql-server/sqlalchemy/requirements-test.txt
  cloud-sql/sql-server/sqlalchemy/requirements.txt
Labels: api: cloudsql, samples

#11547 fix: Pin Gemini Function Calling code samples to `gemini-1.0-pro-001`
  generative_ai/function_calling.py
  generative_ai/function_calling_chat.py
  generative_ai/imagen/generate_image.py
Labels: samples

#11543 feat: update Imagen 2 samples for usability
  generative_ai/imagen/edit_image_inpainting_insert_mask.py
  generative_ai/imagen/edit_image_inpainting_insert_mask_mode.py
  generative_ai/imagen/edit_image_inpainting_insert_mask_mode_test.py
  generative_ai/imagen/edit_image_inpainting_insert_mask_test.py
  generative_ai/imagen/edit_image_inpainting_remove_mask.py
  generative_ai/imagen/edit_image_inpainting_remove_mask_mode.py
  generative_ai/imagen/edit_image_inpainting_remove_mask_mode_test.py
  generative_ai/imagen/edit_image_inpainting_remove_mask_test.py
  generative_ai/imagen/edit_image_mask.py
  generative_ai/imagen/edit_image_mask_free.py
  generative_ai/imagen/edit_image_mask_free_test.py
  generative_ai/imagen/edit_image_mask_test.py
  generative_ai/imagen/edit_image_outpainting_mask.py
  generative_ai/imagen/edit_image_outpainting_mask_test.py
  generative_ai/imagen/edit_image_product_image.py
  generative_ai/imagen/edit_image_product_image_test.py
  generative_ai/imagen/get_short_form_image_captions.py
  generative_ai/imagen/get_short_form_image_captions_test.py
  generative_ai/imagen/get_short_form_image_responses.py
  generative_ai/imagen/get_short_form_image_responses_test.py
  generative_ai/requirements.txt
Labels: samples

#11460 Add Samples for Vertex AI RAG
  generative_ai/imagen/edit_image_inpainting_insert_mask.py
  generative_ai/imagen/edit_image_inpainting_insert_mask_mode.py
  generative_ai/imagen/edit_image_inpainting_remove_mask.py
  generative_ai/imagen/edit_image_inpainting_remove_mask_mode.py
  generative_ai/imagen/edit_image_mask.py
  generative_ai/imagen/edit_image_mask_free.py
  generative_ai/imagen/edit_image_outpainting_mask.py
  generative_ai/imagen/edit_image_product_image.py
  generative_ai/imagen/get_short_form_image_captions.py
  generative_ai/imagen/get_short_form_image_responses.py
  generative_ai/rag.py
  generative_ai/rag_test.py
  generative_ai/requirements-test.txt
  generative_ai/requirements.txt
Labels: samples, api: vertex-ai

#11544 Snipets/compute_ip_address_get_vm_address
  compute/client_library/ingredients/instances/ip_address/get_vm_address.py
  compute/client_library/recipes/instances/ip_address/get_vm_address.py
  compute/client_library/snippets/instances/ip_address/get_vm_address.py
  compute/client_library/snippets/tests/test_ip_address.py
Labels: api: compute, samples

#11454 [Issue 9129 fix] Improve integration tests
  functions/helloworld/sample_http_test_integration.py
Labels: api: cloudfunctions, samples

#11452 [issue-9643 fix] added ttl to secrets tests and samples
  secretmanager/snippets/create_secret.py
  secretmanager/snippets/create_secret_with_user_managed_replication.py
  secretmanager/snippets/snippets_test.py
Labels: api: secretmanager, samples

#11409 Update requirements.txt to include google cloud iam
  iap/requirements.txt
Labels: api: iap, samples

#11440 Outdated bash operator import on Composer 2 Docs #11433
  composer/workflows/clear_file_system_caches_dag_composer_v1.py
  composer/workflows/trigger_response_dag.py
Labels: kokoro:run, api: composer, samples

#11579 feat: gemini code samples updates
  generative_ai/README.md
  generative_ai/function_calling.py
  generative_ai/function_calling_chat.py
  generative_ai/gemini_all_modalities.py
  generative_ai/gemini_audio.py
  generative_ai/gemini_chat_example.py
  generative_ai/gemini_count_token_example.py
  generative_ai/gemini_grounding_example.py
  generative_ai/gemini_guide_example.py
  generative_ai/gemini_multi_image_example.py
  generative_ai/gemini_pdf_example.py
  generative_ai/gemini_pro_basic_example.py
  generative_ai/gemini_pro_config_example.py
  generative_ai/gemini_safety_config_example.py
  generative_ai/gemini_single_turn_video_example.py
  generative_ai/gemini_system_instruction.py
  generative_ai/gemini_video_audio.py
  generative_ai/rag.py
Labels: samples

#11581 [snipets][compute_ip_address_get_static_address]
  compute/client_library/ingredients/instances/ip_address/get_static_ip_address.py
  compute/client_library/recipes/instances/ip_address/get_static_ip_address.py
  compute/client_library/snippets/instances/ip_address/get_static_ip_address.py
  compute/client_library/snippets/tests/test_ip_address.py
Labels: api: compute, samples

#11582 [snipets][compute_ip_address_list_static_external]
  compute/client_library/ingredients/instances/ip_address/list_static_ip_addresses.py
  compute/client_library/recipes/instances/ip_address/list_static_ip_addresses.py
  compute/client_library/snippets/instances/ip_address/list_static_ip_addresses.py
  compute/client_library/snippets/tests/test_ip_address.py
Labels: api: compute, samples

#11422 fix: moving imports inside functions
  dialogflow/participant_management.py
  dialogflow/requirements.txt
Labels: api: dialogflow, samples

#11588 refactor(generative-ai): Update the classification sample to the new style
  generative_ai/classify_news_items.py
  generative_ai/classify_news_items_test.py
Labels: samples

#11587 refactor(generative-ai): Update chat sample to the new style
  generative_ai/chat.py
  generative_ai/chat_test.py
Labels: samples

#11586 [snipets][compute_ip_address_release_static_address]
  compute/client_library/ingredients/instances/ip_address/release_external_ip_address.py
  compute/client_library/recipes/instances/ip_address/release_external_ip_address.py
  compute/client_library/snippets/instances/ip_address/release_external_ip_address.py
  compute/client_library/snippets/tests/test_ip_address.py
Labels: api: compute, samples

#11448 version bump for aiplatform_sdk_list_tuned_code_generation_models fix
  generative_ai/list_tuned_code_generation_models.py
Labels: samples

#11592 Update gemini_pdf_example.py
  generative_ai/gemini_pdf_example.py
  generative_ai/test_gemini_examples.py
Labels: samples

#11593 refactor(generative-ai): Update code tuning sample to the new style
  generative_ai/tune_code_generation_model.py
  generative_ai/tune_code_generation_model_test.py
Labels: samples

#11594 refactor(generative-ai): Update text model tuning sample to the new style
  generative_ai/tuning.py
  generative_ai/tuning_test.py
Labels: samples

#11453 [Issue 9129 fix] Prepare cloud function creation code sample
  functions/v2/deploy-function/deploy_function.py
  functions/v2/deploy-function/requirements-test.txt
  functions/v2/deploy-function/requirements.txt
  functions/v2/deploy-function/test_deploy_function.py
Labels: api: cloudfunctions, samples

#11567 feat: project iam policy snippet
  iam/cloud-client/snippets/get_policy.py
  iam/cloud-client/snippets/modify_policy_add_member.py
  iam/cloud-client/snippets/modify_policy_remove_member.py
  iam/cloud-client/snippets/query_testable_permissions.py
  iam/cloud-client/snippets/requirements.txt
  iam/cloud-client/snippets/set_policy.py
  iam/cloud-client/snippets/test_project_policies.py
Labels: api: iam, samples

#11424 feat: write sample for creating key for service account
  iam/cloud-client/snippets/create_key.py
  iam/cloud-client/snippets/delete_key.py
  iam/cloud-client/snippets/list_keys.py
  iam/cloud-client/snippets/test_service_account_key.py
Labels: api: iam, samples

#11600 feat: add image watermark verification sample and test
  generative_ai/imagen/test_resources/dog_newspaper.png
  generative_ai/imagen/verify_image_watermark.py
  generative_ai/imagen/verify_image_watermark_test.py
Labels: samples

#11604 fix: Spelling error `available`
  documentai/snippets/handle_response_sample.py
Labels: samples, api: documentai

#11284 Add gemma-on-dataflow streaming example
  dataflow/gemma/Dockerfile
  dataflow/gemma/README.md
  dataflow/gemma/custom_model_gemma.py
  dataflow/gemma/e2e_test.py
  dataflow/gemma/noxfile_config.py
  dataflow/gemma/requirements-test.txt
  dataflow/gemma/requirements.txt
  renovate.json
Labels: samples

#11595 docs: Add in-depth script details & formula breakdown to Storage Cost Analysis README
  storage/cost-analysis/README.md
  storage/cost-analysis/storage_soft_delete_relative_cost_analyzer.py
Labels: api: storage, samples
