Repository GoogleCloudPlatform/python-docs-samples, pull requests merged in 2024-10, with the labels that each got.

#12635 refactor(generative-ai): Cleaning samples - Group A (Controlled Generation, Embeddings, Extensions, Function Calling)
  generative_ai/chat_completions/chat_completions_function_calling_basic.py
  generative_ai/chat_completions/chat_completions_function_calling_config.py
  generative_ai/chat_completions/chat_completions_test.py
  generative_ai/controlled_generation/response_mime_type.py
  generative_ai/controlled_generation/response_schema.py
  generative_ai/embedding.py
  generative_ai/embedding_batch.py
  generative_ai/embedding_batch_test.py
  generative_ai/embedding_model_tuning.py
  generative_ai/embedding_model_tuning_test.py
  generative_ai/embedding_preview.py
  generative_ai/embedding_test.py
  generative_ai/function_calling.py
  generative_ai/function_calling/chat_function_calling_config.py
  generative_ai/function_calling_chat.py
  generative_ai/function_calling_chat_test.py
  generative_ai/function_calling_test.py
  generative_ai/gemini_extensions.py
  generative_ai/gemini_extensions_test.py
  generative_ai/multimodal_embedding_image.py
  generative_ai/multimodal_embedding_image_test.py
  generative_ai/multimodal_embedding_image_video_text.py
  generative_ai/multimodal_embedding_image_video_text_test.py
  generative_ai/multimodal_embedding_video.py
  generative_ai/multimodal_embedding_video_test.py
Labels: samples

#12643 refactor: (GenAI) Reorganized Audio Samples (Group C)
  generative_ai/test_gemini_examples.py
  generative_ai/understand_audio/summarization_example.py
  generative_ai/understand_audio/transcription_example.py
  generative_ai/understand_audio/understand_audio_test.py
Labels: samples

#12612 refactor: (GenAI) Reorganized Rag Samples (Group С)
  generative_ai/rag/create_corpus_example.py
  generative_ai/rag/delete_corpus_example.py
  generative_ai/rag/delete_file_example.py
  generative_ai/rag/generate_content_example.py
  generative_ai/rag/get_corpus_example.py
  generative_ai/rag/get_file_example.py
  generative_ai/rag/import_files_async_example.py
  generative_ai/rag/import_files_example.py
  generative_ai/rag/list_corpora_example.py
  generative_ai/rag/list_files_example.py
  generative_ai/rag/quickstart_example.py
  generative_ai/rag/retrieval_query_example.py
  generative_ai/rag/test_rag.py
  generative_ai/rag/upload_file_example.py
Labels: samples

#12653 Remove templated config_file path, fix parameter comments
  composer/workflows/kubernetes_pod_operator_c2.py
Labels: api: composer, samples

#12639 fix(iam): add a print for visibility
  iam/cloud-client/snippets/get_policy.py
  iam/cloud-client/snippets/test_service_account.py
Labels: api: iam, samples

#12642 feat(tts): add streaming synthesis sample
  texttospeech/snippets/requirements.txt
  texttospeech/snippets/streaming_tts_quickstart.py
  texttospeech/snippets/streaming_tts_quickstart_test.py
Labels: api: texttospeech, samples

#12631 feat: (Gen AI): Add a sample for updating context cache with an expiration date
  generative_ai/context_caching/test_context_caching.py
  generative_ai/context_caching/update_context_cache.py
Labels: needs review, samples

#12608 feat (Gen AI): Add new sample for Evaluation - Pairwise summarization metric
  generative_ai/evaluation/pairwise_summarization_quality.py
  generative_ai/evaluation/test_evaluation.py
Labels: samples

#12663 Lint changes PR
  securitycenter/snippets_v2/mute_findings_v2.py
  securitycenter/snippets_v2/mute_findings_v2_test.py
  securitycenter/snippets_v2/noxfile_config.py
  securitycenter/snippets_v2/requirements.txt
  securitycenter/snippets_v2/snippets_bigquery_export_v2.py
  securitycenter/snippets_v2/snippets_bigquery_export_v2_test.py
  securitycenter/snippets_v2/snippets_findings_v2.py
  securitycenter/snippets_v2/snippets_findings_v2_test.py
  securitycenter/snippets_v2/snippets_mute_config_v2.py
  securitycenter/snippets_v2/snippets_mute_config_v2_test.py
  securitycenter/snippets_v2/snippets_notification_configs_v2.py
  securitycenter/snippets_v2/snippets_notification_v2_test.py
  securitycenter/snippets_v2/snippets_security_marks_v2.py
  securitycenter/snippets_v2/snippets_security_marks_v2_test.py
Labels: api: securitycenter, samples

#12670 fix: Update `discoveryengine.GcsSource` `data_schema` with more options.
  discoveryengine/import_documents_sample.py
Labels: samples, api: discoveryengine

#12667 feat(Gen-AI): Updates for the for list_context_caches sample
  generative_ai/context_caching/list_content_caches.py
  generative_ai/context_caching/test_context_caching.py
Labels: needs review, samples

#12668 feat: Create Compute reservation create from VM Sample
  compute/client_library/ingredients/compute_reservation/create_compute_reservation_from_vm.py
  compute/client_library/recipes/compute_reservations/create_compute_reservation_from_vm.py
  compute/client_library/snippets/compute_reservations/create_compute_reservation_from_vm.py
  compute/client_library/snippets/tests/test_compute_reservation.py
Labels: api: compute, samples

#12674 chore(codeowners): Update CODEOWNERS for recaptcha/ folder
  .github/CODEOWNERS
Labels: samples

#12676 fix: typo in sample file name
  generative_ai/context_caching/list_context_caches.py
  generative_ai/context_caching/test_context_caching.py
Labels: samples

#12644 refactor: (GenAI) Reorganized Video Samples (Group C)
  generative_ai/test_gemini_examples.py
  generative_ai/understand_video/audio_video_example.py
  generative_ai/understand_video/single_turn_video_example.py
  generative_ai/understand_video/understand_video_test.py
Labels: samples

#12682 feat(generative_ai): minor code update to extensions list sample
  generative_ai/extensions/extensions_test.py
  generative_ai/extensions/list_example.py
Labels: samples

#12609 feat: add v2 API config for bulk mute finding to the existing mute config Python client library or samples
  securitycenter/snippets_v2/mute_findings_v2.py
  securitycenter/snippets_v2/mute_findings_v2_test.py
Labels: api: securitycenter, samples

#12679 fix(generative_ai): fix typos in function calling sample
  generative_ai/context_caching/list_context_caches.py
  generative_ai/embeddings/batch_example.py
  generative_ai/embeddings/generate_embeddings_with_lower_dimension.py
  generative_ai/evaluation/get_rouge_score.py
  generative_ai/evaluation/pairwise_summarization_quality.py
  generative_ai/function_calling/advanced_example.py
  generative_ai/function_calling/basic_example.py
  generative_ai/function_calling/chat_example.py
  generative_ai/function_calling/parallel_function_calling_example.py
Labels: needs review, samples

#12683 chore(generative-ai): update gemini model version in count token examples
  generative_ai/embeddings/generate_embeddings_with_lower_dimension.py
  generative_ai/embeddings/test_embeddings.py
  generative_ai/requirements.txt
  generative_ai/token_count/api_example.py
  generative_ai/token_count/local_sdk_example.py
  generative_ai/token_count/multimodal_token_count_example.py
  generative_ai/token_count/simple_example.py
  generative_ai/token_count/test_token_count_examples.py
Labels: samples

#12685 fix(gae): remove stale code
  appengine/standard/angular/README.md
  appengine/standard/angular/app.yaml
  appengine/standard/angular/app/css/app.css
  appengine/standard/angular/app/index.html
  appengine/standard/angular/app/js/app.js
  appengine/standard/angular/app/partials/insert.html
  appengine/standard/angular/app/partials/main.html
  appengine/standard/angular/app/partials/update.html
  appengine/standard/angular/main.py
  appengine/standard/angular/model.py
  appengine/standard/angular/scripts/deploy.sh
  appengine/standard/angular/scripts/run.sh
Labels: api: appengine, samples

#12064 samples(discoveryengine): Add Grounded Generation API Samples
  discoveryengine/requirements-test.txt
  discoveryengine/requirements.txt
  discoveryengine/site_search_engine_sample.py
  discoveryengine/site_search_engine_sample_test.py
  discoveryengine/standalone_apis_sample.py
  discoveryengine/standalone_apis_sample_test.py
Labels: samples, api: discoveryengine

#12694 Remove an extraneous command from README.md
  dataflow/flex-templates/pipeline_with_dependencies/README.md
Labels: samples

#12680 refactor (generative-ai): Cleaning old samples - Group C
  generative_ai/count_token/count_token_example.py
  generative_ai/count_token/count_token_example_test.py
  generative_ai/gemini_audio.py
  generative_ai/gemini_count_token_example.py
  generative_ai/gemini_reasoning_engine.py
  generative_ai/gemini_reasoning_engine_test.py
  generative_ai/gemini_safety_config_example.py
  generative_ai/gemini_single_turn_video_example.py
  generative_ai/gemini_system_instruction.py
  generative_ai/gemini_video_audio.py
  generative_ai/rag.py
  generative_ai/rag_test.py
  generative_ai/test_gemini_examples.py
Labels: samples

#12690 feat: TPU *Create / *get / *create_with_script / *delete Samples
  .github/CODEOWNERS
  .github/blunderbuss.yml
  tpu/create_tpu.py
  tpu/create_tpu_with_script.py
  tpu/delete_tpu.py
  tpu/get_tpu.py
  tpu/noxfile_config.py
  tpu/requirements-test.txt
  tpu/requirements.txt
  tpu/test_tpu.py
Labels: api: compute, samples, api: tpu

#12699 refactor (generative-ai): Cleaning old samples - Group D (Text Generations)
  generative_ai/chat.py
  generative_ai/chat_test.py
  generative_ai/code_chat.py
  generative_ai/code_chat_test.py
  generative_ai/code_completion_function.py
  generative_ai/code_completion_function_test.py
  generative_ai/code_generation_function.py
  generative_ai/code_generation_function_test.py
  generative_ai/gemini_all_modalities.py
  generative_ai/gemini_chat_example.py
  generative_ai/gemini_guide_example.py
  generative_ai/gemini_multi_image_example.py
  generative_ai/gemini_pdf_example.py
  generative_ai/gemini_pro_basic_example.py
  generative_ai/gemini_pro_config_example.py
  generative_ai/gemini_text_input_example.py
  generative_ai/ideation.py
  generative_ai/ideation_test.py
  generative_ai/inference/inference_api_test.py
  generative_ai/streaming_text.py
  generative_ai/streaming_text_test.py
  generative_ai/test_gemini_examples.py
Labels: samples

#12703 ci(generative-ai): Add noxfile_config.py to all subdirectories for `generative_ai` to only run affected directory tests
  generative_ai/batch_predict/noxfile_config.py
  generative_ai/chat_completions/noxfile_config.py
  generative_ai/context_caching/noxfile_config.py
  generative_ai/controlled_generation/noxfile_config.py
  generative_ai/embeddings/noxfile_config.py
  generative_ai/evaluation/noxfile_config.py
  generative_ai/extensions/noxfile_config.py
  generative_ai/function_calling/noxfile_config.py
  generative_ai/function_calling/parallel_function_calling_example.py
  generative_ai/grounding/noxfile_config.py
  generative_ai/image/noxfile_config.py
  generative_ai/image_generation/noxfile_config.py
  generative_ai/inference/noxfile_config.py
  generative_ai/model_garden/noxfile_config.py
  generative_ai/model_tuning/noxfile_config.py
  generative_ai/openai/noxfile_config.py
  generative_ai/prompts/noxfile_config.py
  generative_ai/rag/noxfile_config.py
  generative_ai/reasoning_engine/noxfile_config.py
  generative_ai/safety/noxfile_config.py
  generative_ai/system_instructions/noxfile_config.py
  generative_ai/text_generation/noxfile_config.py
  generative_ai/token_count/noxfile_config.py
  generative_ai/understand_audio/noxfile_config.py
  generative_ai/understand_docs/noxfile_config.py
  generative_ai/understand_video/noxfile_config.py
  generative_ai/video/noxfile_config.py
Labels: samples

#12704 fix: Accepting time-zone aware expiration datetime only to prevent hard-to debug issues with invalid signatures
  cdn/snippets.py
  cdn/snippets_test.py
Labels: samples

#12678 feat : Create compute shared reservation Sample
  compute/client_library/ingredients/compute_reservation/create_compute_shared_reservation.py
  compute/client_library/recipes/compute_reservations/create_compute_shared_reservation.py
  compute/client_library/snippets/compute_reservations/create_compute_shared_reservation.py
  compute/client_library/snippets/tests/test_compute_reservation.py
Labels: api: compute, samples

#12702 feat: New Samples for TPU: Start, Stop, List
  .github/auto-label.yaml
  tpu/list_tpu.py
  tpu/start_tpu.py
  tpu/stop_tpu.py
  tpu/test_tpu.py
Labels: samples

#12710 feat(generative-ai): update claude_3_streaming_example.py
  generative_ai/model_garden/claude_3_streaming_example.py
  generative_ai/model_garden/test_model_garden_examples.py
Labels: needs review, samples

#12689 feat:add samples for annotations, SM
  secretmanager/snippets/create_secret_with_annotations.py
  secretmanager/snippets/edit_secret_annotations.py
  secretmanager/snippets/regional_samples/create_regional_secret_with_annotations.py
  secretmanager/snippets/regional_samples/edit_regional_secret_annotations.py
  secretmanager/snippets/regional_samples/snippets_test.py
  secretmanager/snippets/regional_samples/view_regional_secret_annotations.py
  secretmanager/snippets/snippets_test.py
  secretmanager/snippets/view_secret_annotations.py
Labels: api: secretmanager, samples

#12723 feat(generative-ai): Update to gemini_batch_predict gcs specific
  generative_ai/batch_predict/gemini_batch_predict_gcs.py
  generative_ai/batch_predict/test_batch_predict_examples.py
Labels: samples

#12720 docs: Generative ai docs
  generative_ai/README.md
  generative_ai/template_folder/advanced_example.py
  generative_ai/template_folder/noxfile_config.py
  generative_ai/template_folder/requirements-test.txt
  generative_ai/template_folder/requirements.txt
  generative_ai/template_folder/simple_example.py
  generative_ai/template_folder/test_template_folder_examples.py
Labels: samples

#12726 fix incorrect import used in v2 code samples
  securitycenter/snippets_v2/snippets_findings_v2.py
Labels: api: securitycenter, samples

#12737 fix: activate service account needed for tests
  .kokoro/tests/run_tests.sh
Labels: samples

#12736 feat: from vertexai.batch_prediction import BatchPredictionJob
  generative_ai/batch_predict/gemini_batch_predict_gcs.py
  generative_ai/batch_predict/requirements.txt
Labels: samples

#12732 feat: Compute regional template Samples - Create, Get, Delete
  compute/client_library/ingredients/instance-templates/compute_regional_template/create_compute_regional_template.py
  compute/client_library/ingredients/instance-templates/compute_regional_template/delete_compute_regional_template.py
  compute/client_library/ingredients/instance-templates/compute_regional_template/get_compute_regional_template.py
  compute/client_library/recipes/instance_templates/compute_regional_template/create_compute_regional_template.py
  compute/client_library/recipes/instance_templates/compute_regional_template/delete_compute_regional_template.py
  compute/client_library/recipes/instance_templates/compute_regional_template/get_compute_regional_template.py
  compute/client_library/snippets/instance_templates/compute_regional_template/__init__.py
  compute/client_library/snippets/instance_templates/compute_regional_template/create_compute_regional_template.py
  compute/client_library/snippets/instance_templates/compute_regional_template/delete_compute_regional_template.py
  compute/client_library/snippets/instance_templates/compute_regional_template/get_compute_regional_template.py
  compute/client_library/snippets/tests/test_templates_regional.py
Labels: api: compute, samples

#12740 feat(genai): Updates to comments
  generative_ai/batch_predict/gemini_batch_predict_bigquery.py
  generative_ai/batch_predict/gemini_batch_predict_gcs.py
Labels: samples
