Repository GoogleCloudPlatform/python-docs-samples, pull requests merged in 2024-09, with the labels that each got.

#12546 chore(automl): remove deprecated samples
  automl/beta/batch_predict.py
  automl/beta/batch_predict_test.py
  automl/beta/cancel_operation.py
  automl/beta/delete_dataset.py
  automl/beta/delete_dataset_test.py
  automl/beta/delete_model.py
  automl/beta/delete_model_test.py
  automl/beta/get_model.py
  automl/beta/get_model_evaluation.py
  automl/beta/get_model_evaluation_test.py
  automl/beta/get_model_test.py
  automl/beta/get_operation_status.py
  automl/beta/get_operation_status_test.py
  automl/beta/import_dataset.py
  automl/beta/import_dataset_test.py
  automl/beta/list_datasets.py
  automl/beta/list_datasets_test.py
  automl/beta/list_models.py
  automl/beta/list_models_test.py
  automl/beta/noxfile_config.py
  automl/beta/requirements-test.txt
  automl/beta/requirements.txt
  automl/beta/set_endpoint.py
  automl/beta/set_endpoint_test.py
  automl/beta/video_classification_create_dataset.py
  automl/beta/video_classification_create_dataset_test.py
  automl/beta/video_classification_create_model.py
  automl/beta/video_classification_create_model_test.py
  automl/beta/video_object_tracking_create_dataset.py
  automl/beta/video_object_tracking_create_dataset_test.py
  automl/beta/video_object_tracking_create_model.py
  automl/beta/video_object_tracking_create_model_test.py
Labels: api: automl, samples

#12543 feat: New text Generation Samples
  generative_ai/batch_predict/batch_code_predict.py
  generative_ai/batch_predict/batch_text_predict.py
  generative_ai/batch_predict/test_batch_predict.py
Labels: samples

#12545 chore(automl): remove deprecated samples
  automl/tables/automl_tables_dataset.py
  automl/tables/automl_tables_model.py
  automl/tables/automl_tables_predict.py
  automl/tables/automl_tables_set_endpoint.py
  automl/tables/batch_predict_test.py
  automl/tables/dataset_test.py
  automl/tables/endpoint_test.py
  automl/tables/model_test.py
  automl/tables/noxfile_config.py
  automl/tables/predict_test.py
  automl/tables/requirements-test.txt
  automl/tables/requirements.txt
Labels: api: automl, samples

#12547 chore(automl): remove deprecated samples automl/vision_edge directory
  automl/vision_edge/edge_container_predict/Dockerfile
  automl/vision_edge/edge_container_predict/README.md
  automl/vision_edge/edge_container_predict/automl_vision_edge_container_predict.py
  automl/vision_edge/edge_container_predict/automl_vision_edge_container_predict_test.py
  automl/vision_edge/edge_container_predict/cloudbuild.yaml
  automl/vision_edge/edge_container_predict/test.jpg
  automl/vision_edge/resources/test.png
Labels: api: automl, samples

#12559 chore(deps): update django
  appengine/flexible/django_cloudsql/requirements.txt
  appengine/flexible/hello_world_django/requirements.txt
  appengine/flexible_python37_and_earlier/django_cloudsql/requirements.txt
  appengine/flexible_python37_and_earlier/hello_world_django/requirements.txt
  appengine/standard_python3/bundled-services/blobstore/django/requirements.txt
  appengine/standard_python3/bundled-services/deferred/django/requirements.txt
  appengine/standard_python3/bundled-services/mail/django/requirements.txt
  appengine/standard_python3/django/requirements.txt
  kubernetes_engine/django_tutorial/requirements.txt
  run/django/requirements.txt
Labels: api: appengine, api: run, api: container, samples

#12483 feat: Batch created job with custom labels. 3 new samples
  batch/create/create_with_allocation_policy_labels.py
  batch/create/create_with_job_labels.py
  batch/create/create_with_runnables_labels.py
  batch/tests/test_basics.py
Labels: samples, api: batch

#12561 fix: remove arbitrary equality comparisons (not supported by renovate)
  appengine/flexible/websockets/requirements.txt
  appengine/flexible_python37_and_earlier/websockets/requirements.txt
  appengine/standard/endpoints-frameworks-v2/echo/requirements-test.txt
  appengine/standard/endpoints-frameworks-v2/quickstart/requirements-test.txt
  appengine/standard/firebase/firenotes/backend/requirements-test.txt
  appengine/standard/firebase/firetactoe/firetactoe.py
  appengine/standard/firebase/firetactoe/firetactoe_test.py
  appengine/standard/firebase/firetactoe/requirements-test.txt
  appengine/standard/firebase/firetactoe/rest_api.py
  appengine/standard/iap/main_test.py
  appengine/standard/iap/requirements-test.txt
  appengine/standard/mailgun/requirements-test.txt
  appengine/standard/migration/memorystore/appengine_config.py
  appengine/standard/migration/memorystore/main.py
  appengine/standard/migration/memorystore/main_test.py
  appengine/standard/migration/memorystore/requirements-test.txt
  appengine/standard/sendgrid/requirements-test.txt
Labels: api: appengine, samples

#12562 chore(deps): update google-cloud-translate to v3.16.0
  automl/snippets/requirements.txt
  bigquery/remote-function/translate/requirements-test.txt
  bigquery/remote-function/translate/requirements.txt
  functions/ocr/app/requirements.txt
  functions/v2/ocr/requirements.txt
  translate/samples/snippets/hybrid_glossaries/requirements.txt
  translate/samples/snippets/requirements.txt
  translate/samples/snippets/snippets_test.py
Labels: api: automl, api: translate, api: bigquery, api: cloudfunctions, samples

#12541 feat: compute create reservation from template sample
  compute/client_library/ingredients/instance-templates/create_reservation_from_template.py
  compute/client_library/recipes/instance_templates/create_reservation_from_template.py
  compute/client_library/snippets/instance_templates/create_reservation_from_template.py
  compute/client_library/snippets/tests/test_reservations.py
Labels: api: compute, samples

#12480 fix(secretmanager): add new regional samples
  secretmanager/snippets/regional_samples/iam_grant_access_with_regional_secret.py
  secretmanager/snippets/regional_samples/iam_revoke_access_with_regional_secret.py
  secretmanager/snippets/regional_samples/list_regional_secret_versions.py
  secretmanager/snippets/regional_samples/list_regional_secret_versions_with_filter.py
  secretmanager/snippets/regional_samples/list_regional_secrets.py
  secretmanager/snippets/regional_samples/list_regional_secrets_with_filter.py
  secretmanager/snippets/regional_samples/snippets_test.py
Labels: api: secretmanager, samples

#12477 fix:added regional samples for SM
  secretmanager/snippets/regional_samples/access_regional_secret_version.py
  secretmanager/snippets/regional_samples/add_regional_secret_version.py
  secretmanager/snippets/regional_samples/delete_regional_secret_with_etag.py
  secretmanager/snippets/regional_samples/destroy_regional_secret_version.py
  secretmanager/snippets/regional_samples/destroy_regional_secret_version_with_etag.py
  secretmanager/snippets/regional_samples/disable_regional_secret_version.py
  secretmanager/snippets/regional_samples/disable_regional_secret_version_with_etag.py
  secretmanager/snippets/regional_samples/enable_regional_secret_version.py
  secretmanager/snippets/regional_samples/enable_regional_secret_version_with_etag.py
  secretmanager/snippets/regional_samples/get_regional_secret_version.py
  secretmanager/snippets/regional_samples/iam_grant_access_with_regional_secret.py
  secretmanager/snippets/regional_samples/iam_revoke_access_with_regional_secret.py
  secretmanager/snippets/regional_samples/list_regional_secret_versions.py
  secretmanager/snippets/regional_samples/list_regional_secret_versions_with_filter.py
  secretmanager/snippets/regional_samples/list_regional_secrets.py
  secretmanager/snippets/regional_samples/list_regional_secrets_with_filter.py
  secretmanager/snippets/regional_samples/snippets_test.py
  secretmanager/snippets/regional_samples/update_regional_secret_with_etag.py
Labels: api: secretmanager, samples

#12534 chore: refactored samples, to make them follow copy-paste-run approach
  texttospeech/snippets/audio_profile.py
  texttospeech/snippets/audio_profile_test.py
  texttospeech/snippets/long_audio_quickstart.py
  texttospeech/snippets/long_audio_quickstart_test.py
  texttospeech/snippets/ssml_addresses.py
  texttospeech/snippets/ssml_addresses_test.py
  texttospeech/snippets/synthesize_text.py
  texttospeech/snippets/synthesize_text_test.py
Labels: api: texttospeech, samples

#12475 fix:added regional samples for SM
  secretmanager/snippets/regional_samples/__init__.py
  secretmanager/snippets/regional_samples/access_regional_secret_version.py
  secretmanager/snippets/regional_samples/add_regional_secret_version.py
  secretmanager/snippets/regional_samples/create_regional_secret.py
  secretmanager/snippets/regional_samples/delete_regional_secret.py
  secretmanager/snippets/regional_samples/delete_regional_secret_with_etag.py
  secretmanager/snippets/regional_samples/destroy_regional_secret_version.py
  secretmanager/snippets/regional_samples/destroy_regional_secret_version_with_etag.py
  secretmanager/snippets/regional_samples/disable_regional_secret_version.py
  secretmanager/snippets/regional_samples/disable_regional_secret_version_with_etag.py
  secretmanager/snippets/regional_samples/enable_regional_secret_version.py
  secretmanager/snippets/regional_samples/enable_regional_secret_version_with_etag.py
  secretmanager/snippets/regional_samples/get_regional_secret.py
  secretmanager/snippets/regional_samples/get_regional_secret_version.py
  secretmanager/snippets/regional_samples/iam_grant_access_with_regional_secret.py
  secretmanager/snippets/regional_samples/iam_revoke_access_with_regional_secret.py
  secretmanager/snippets/regional_samples/list_regional_secret_versions.py
  secretmanager/snippets/regional_samples/list_regional_secret_versions_with_filter.py
  secretmanager/snippets/regional_samples/list_regional_secrets.py
  secretmanager/snippets/regional_samples/list_regional_secrets_with_filter.py
  secretmanager/snippets/regional_samples/regional_quickstart.py
  secretmanager/snippets/regional_samples/snippets_test.py
  secretmanager/snippets/regional_samples/update_regional_secret.py
  secretmanager/snippets/regional_samples/update_regional_secret_with_etag.py
  secretmanager/snippets/requirements.txt
  secretmanager/snippets/snippets_test.py
Labels: api: secretmanager, samples

#12062 soft-delete-cost-analysis: fixing return type
  storage/cost-analysis/storage_soft_delete_relative_cost_analyzer.py
Labels: api: storage, samples

#12571 refactor: (GenAI) Improved Context Cache Samples (Group A)
  generative_ai/classify_news_items.py
  generative_ai/context_caching/context_caching_test.py
  generative_ai/context_caching/create_context_cache.py
  generative_ai/context_caching/delete_context_cache.py
  generative_ai/context_caching/get_context_cache.py
  generative_ai/context_caching/update_context_cache.py
  generative_ai/context_caching/use_context_cache.py
Labels: automerge, samples

#12530 docs(samples): Add Dataflow snippet to read from multiple Kafka topics
  dataflow/snippets/Dockerfile
  dataflow/snippets/read_kafka_multi_topic.py
  dataflow/snippets/tests/test_read_kafka.py
Labels: samples

#12590 updates to list manipulation to ignore the header
  composer/tools/composer_dags.py
Labels: api: composer, samples

#12158 Simplified next set of Speech Samples (set-3)
  speech/snippets/transcribe_feature_in_recognizer.py
  speech/snippets/transcribe_feature_in_recognizer_test.py
  speech/snippets/transcribe_file_v2.py
  speech/snippets/transcribe_file_v2_test.py
  speech/snippets/transcribe_gcs_v2.py
  speech/snippets/transcribe_gcs_v2_test.py
  speech/snippets/transcribe_model_selection.py
  speech/snippets/transcribe_model_selection_test.py
  speech/snippets/transcribe_model_selection_v2.py
  speech/snippets/transcribe_model_selection_v2_test.py
  speech/snippets/transcribe_multichannel_v2_test.py
Labels: api: speech, samples

#12597 docs(generativeai): update todo comments for quick start guide examples
  generative_ai/gemini_guide_example.py
  generative_ai/gemini_text_input_example.py
  generative_ai/gemini_video_audio.py
Labels: automerge, samples

#12592 Update generate_self_signed_jwt.py
  iap/generate_self_signed_jwt.py
Labels: api: iap, samples

#12564 docs(samples): Added answer_query_sample.py
  discoveryengine/answer_query_sample.py
  discoveryengine/answer_query_sample_test.py
Labels: samples, api: discoveryengine, generated: genai

#12568 docs(samples): Created session_sample.py
  discoveryengine/session_sample.py
  discoveryengine/session_sample_test.py
Labels: samples, api: discoveryengine, generated: genai

#12601 fix: (datastore) add imports to snippets
  datastore/cloud-client/snippets.py
Labels: api: datastore, samples

#12615 refactor: (GenAI) Reorganized System Instructions Sample (Group C)
  generative_ai/system_instructions/system_instructions_example.py
  generative_ai/system_instructions/system_instructions_example_test.py
Labels: samples

#12614 refactor: (GenAI) Reorganized Safety Sample (Group С)
  generative_ai/safety/safety_config_example.py
  generative_ai/safety/safety_config_example_test.py
Labels: samples

#12613 refactor: (GenAI) Reorganized Reasoning Engine Samples (Group С)
  generative_ai/reasoning_engine/create_reasoning_engine_advanced_example.py
  generative_ai/reasoning_engine/create_reasoning_engine_example.py
  generative_ai/reasoning_engine/delete_reasoning_engine_example.py
  generative_ai/reasoning_engine/get_reasoning_engine_example.py
  generative_ai/reasoning_engine/list_reasoning_engine_example.py
  generative_ai/reasoning_engine/query_reasoning_engine_example.py
  generative_ai/reasoning_engine/reasoning_engine_test.py
Labels: samples

#12605 refactor: (GenAI) Reorganized Model Tuning Samples (Group B)
  generative_ai/model_tuning/create_evaluation_task_example.py
  generative_ai/model_tuning/create_evaluation_task_example_test.py
  generative_ai/model_tuning/distillation_example.py
  generative_ai/model_tuning/distillation_example_test.py
  generative_ai/model_tuning/evaluate_model_example.py
  generative_ai/model_tuning/evaluate_model_example_test.py
  generative_ai/model_tuning/pretrained_codegen_example.py
  generative_ai/model_tuning/pretrained_examples_test.py
  generative_ai/model_tuning/pretrained_list_example.py
  generative_ai/model_tuning/pretrained_textgen_example.py
  generative_ai/model_tuning/supervised_advanced_example.py
  generative_ai/model_tuning/supervised_cancel_example.py
  generative_ai/model_tuning/supervised_example.py
  generative_ai/model_tuning/supervised_get_example.py
  generative_ai/model_tuning/supervised_list_example.py
  generative_ai/model_tuning/supervised_tuning_examples_test.py
  generative_ai/model_tuning/tune_code_generation_model.py
  generative_ai/model_tuning/tuning.py
Labels: samples

#12599 refactor: (GenAI) Reorganized Model Garden Samples (Group B)
  generative_ai/model_garden/claude_3_streaming_example.py
  generative_ai/model_garden/claude_3_tool_example.py
  generative_ai/model_garden/claude_3_unary_example.py
  generative_ai/model_garden/model_garden_test.py
Labels: samples

#12595 refactor: (GenAI) Reorganized Image Generation Samples (Group B)
  generative_ai/image_geneneration/edit_image_inpainting_insert_mask.py
  generative_ai/image_geneneration/edit_image_inpainting_insert_mask_mode.py
  generative_ai/image_geneneration/edit_image_inpainting_insert_mask_mode_test.py
  generative_ai/image_geneneration/edit_image_inpainting_insert_mask_test.py
  generative_ai/image_geneneration/edit_image_inpainting_remove_mask.py
  generative_ai/image_geneneration/edit_image_inpainting_remove_mask_mode.py
  generative_ai/image_geneneration/edit_image_inpainting_remove_mask_mode_test.py
  generative_ai/image_geneneration/edit_image_inpainting_remove_mask_test.py
  generative_ai/image_geneneration/edit_image_mask.py
  generative_ai/image_geneneration/edit_image_mask_free.py
  generative_ai/image_geneneration/edit_image_mask_free_test.py
  generative_ai/image_geneneration/edit_image_mask_test.py
  generative_ai/image_geneneration/edit_image_outpainting_mask.py
  generative_ai/image_geneneration/edit_image_outpainting_mask_test.py
  generative_ai/image_geneneration/edit_image_product_image.py
  generative_ai/image_geneneration/edit_image_product_image_test.py
  generative_ai/image_geneneration/generate_image.py
  generative_ai/image_geneneration/generate_image_test.py
  generative_ai/image_geneneration/get_short_form_image_captions.py
  generative_ai/image_geneneration/get_short_form_image_captions_test.py
  generative_ai/image_geneneration/get_short_form_image_responses.py
  generative_ai/image_geneneration/get_short_form_image_responses_test.py
  generative_ai/image_geneneration/test_resources/cat.png
  generative_ai/image_geneneration/test_resources/dog.png
  generative_ai/image_geneneration/test_resources/dog_book.png
  generative_ai/image_geneneration/test_resources/dog_newspaper.png
  generative_ai/image_geneneration/test_resources/dog_newspaper_mask.png
  generative_ai/image_geneneration/test_resources/pillow.png
  generative_ai/image_geneneration/test_resources/pillow_on_beach.png
  generative_ai/image_geneneration/test_resources/roller_skaters.png
  generative_ai/image_geneneration/test_resources/roller_skaters_downtown.png
  generative_ai/image_geneneration/test_resources/roller_skaters_mask.png
  generative_ai/image_geneneration/test_resources/sports_car.png
  generative_ai/image_geneneration/test_resources/volleyball_game.png
  generative_ai/image_geneneration/test_resources/volleyball_game_inpainting_remove_mask.png
  generative_ai/image_geneneration/test_resources/volleyball_game_single_blue_player.png
  generative_ai/image_geneneration/test_resources/woman.png
  generative_ai/image_geneneration/test_resources/woman_at_beach.png
  generative_ai/image_geneneration/test_resources/woman_inpainting_insert_mask.png
  generative_ai/image_geneneration/test_resources/woman_with_hat.png
  generative_ai/image_geneneration/verify_image_watermark.py
  generative_ai/image_geneneration/verify_image_watermark_test.py
  generative_ai/imagen/edit_image_inpainting_insert_mask_mode_test_.py
  generative_ai/imagen/edit_image_inpainting_insert_mask_test_.py
  generative_ai/imagen/edit_image_inpainting_remove_mask_mode_test_.py
  generative_ai/imagen/edit_image_inpainting_remove_mask_test_.py
  generative_ai/imagen/edit_image_mask_free_test_.py
  generative_ai/imagen/edit_image_mask_test_.py
  generative_ai/imagen/edit_image_outpainting_mask_test_.py
  generative_ai/imagen/edit_image_product_image_test_.py
  generative_ai/imagen/generate_image_test_.py
  generative_ai/imagen/get_short_form_image_captions_test_.py
  generative_ai/imagen/get_short_form_image_responses_test_.py
  generative_ai/imagen/verify_image_watermark_test_.py
Labels: samples

#12621 adding batch gemini predict sample
  generative_ai/batch_predict/gemini_batch_predict.py
  generative_ai/batch_predict/test_batch_predict.py
Labels: samples

#12622 chore(CODEOWNERS): Add cloud-samples-infra team to repo config ownership
  .github/CODEOWNERS
Labels: samples

#12623 chore(CODEOWNERS): Remove unused teams
  .github/CODEOWNERS
Labels: samples

#12610 chore(gae): update hello world to the latest python runtime
  appengine/standard_python3/hello_world/app.yaml
Labels: api: appengine, samples

#12598 feat(GenAI): Gemma2 samples for Model Garden deployments to Vertex AI endpoints
  .github/CODEOWNERS
  gemma2/gemma2_predict_gpu.py
  gemma2/gemma2_predict_tpu.py
  gemma2/gemma2_test.py
  gemma2/noxfile_config.py
  gemma2/requirements-test.txt
  gemma2/requirements.txt
Labels: samples

#12618 feat(generative ai): update the tuning example to use gemini-1.5 model
  generative_ai/gemini_tuning.py
  generative_ai/model_tuning/supervised_advanced_example.py
  generative_ai/model_tuning/supervised_cancel_example.py
  generative_ai/model_tuning/supervised_example.py
  generative_ai/model_tuning/supervised_get_example.py
  generative_ai/model_tuning/supervised_list_example.py
Labels: samples

#12624 feat(generativeai): Add sample for Prompt Optimiser
  .github/header-checker-lint.yml
  generative_ai/prompts/prompt_optimizer.py
  generative_ai/prompts/test_prompt_optimizer.py
  generative_ai/prompts/test_resources/sample_configuration.json
  generative_ai/prompts/test_resources/sample_prompt_template.txt
  generative_ai/prompts/test_resources/sample_prompts.jsonl
  generative_ai/prompts/test_resources/sample_system_instruction.txt
Labels: samples

#12628 chore(blunderbuss): Remove unused teams
  .github/blunderbuss.yml
Labels: samples

#12630 fix(generativeai): update prompt optimizer sample and tests
  generative_ai/batch_predict/gemini_batch_predict.py
  generative_ai/batch_predict/test_batch_predict.py
  generative_ai/prompts/prompt_optimizer.py
  generative_ai/prompts/test_prompt_optimizer.py
  generative_ai/prompts/test_resources/sample_configuration.json
Labels: automerge, samples

#12627 feat(generative-ai): Update Gemini Flask and Pro model names
  generative_ai/batch_predict/gemini_batch_predict.py
  generative_ai/chat_completions/chat_completions_credentials_refresher.py
  generative_ai/chat_completions/chat_completions_function_calling_config.py
  generative_ai/chat_completions/chat_completions_non_streaming_image.py
  generative_ai/chat_completions/chat_completions_non_streaming_text.py
  generative_ai/chat_completions/chat_completions_streaming_image.py
  generative_ai/chat_completions/chat_completions_streaming_text.py
  generative_ai/context_caching/create_context_cache.py
  generative_ai/controlled_generation/example_01.py
  generative_ai/controlled_generation/example_02.py
  generative_ai/controlled_generation/example_03.py
  generative_ai/controlled_generation/example_04.py
  generative_ai/controlled_generation/example_05.py
  generative_ai/controlled_generation/example_06.py
  generative_ai/controlled_generation/response_mime_type.py
  generative_ai/controlled_generation/response_schema.py
  generative_ai/function_calling.py
  generative_ai/function_calling/advanced_example.py
  generative_ai/function_calling/basic_example.py
  generative_ai/function_calling/chat_function_calling_config.py
  generative_ai/gemini_all_modalities.py
  generative_ai/gemini_audio.py
  generative_ai/gemini_chat_example.py
  generative_ai/gemini_count_token_example.py
  generative_ai/gemini_grounding_example.py
  generative_ai/gemini_guide_example.py
  generative_ai/gemini_multi_image_example.py
  generative_ai/gemini_pdf_example.py
  generative_ai/gemini_pro_basic_example.py
  generative_ai/gemini_pro_config_example.py
  generative_ai/gemini_safety_config_example.py
  generative_ai/gemini_single_turn_video_example.py
  generative_ai/gemini_system_instruction.py
  generative_ai/gemini_text_input_example.py
  generative_ai/gemini_video_audio.py
  generative_ai/inference/non_stream_multimodality_basic.py
  generative_ai/inference/non_stream_text_basic.py
  generative_ai/inference/stream_multimodality_basic.py
  generative_ai/inference/stream_text_basic.py
  generative_ai/rag.py
  generative_ai/safety/safety_config_example.py
  generative_ai/system_instructions/system_instructions_example.py
Labels: automerge, samples

#12633 feat(generativeai): Add new sample for text generation
  generative_ai/audio/__init__.py
  generative_ai/batch_predict/gemini_batch_predict.py
  generative_ai/controlled_generation/example_06.py
  generative_ai/model_garden/claude_3_streaming_example.py
  generative_ai/model_garden/model_garden_test.py
  generative_ai/text_generation/gemini_describe_http_image_example.py
  generative_ai/text_generation/gemini_describe_http_pdf_example.py
  generative_ai/text_generation/test_text_generation_examples.py
  generative_ai/video/gemini_describe_http_video_example.py
  generative_ai/video/gemini_youtube_video_key_moments_example.py
  generative_ai/video/gemini_youtube_video_summarization_example.py
  generative_ai/video/test_video_examples.py
Labels: samples

#12616 refactor: (GenAI) Reorganized Token Count Samples (Group C)
  generative_ai/token_count/api_example.py
  generative_ai/token_count/local_sdk_example.py
  generative_ai/token_count/multimodal_token_count_example.py
  generative_ai/token_count/simple_example.py
  generative_ai/token_count/token_count_test.py
Labels: samples

#12596 feat(generative-ai): Add new sample for Context Cache's list feature
  generative_ai/context_caching/context_caching_test.py
  generative_ai/context_caching/list_content_caches.py
Labels: samples

#12636 chore(generative_ai): update image_generation folder name
  generative_ai/image_generation/edit_image_inpainting_insert_mask.py
  generative_ai/image_generation/edit_image_inpainting_insert_mask_mode.py
  generative_ai/image_generation/edit_image_inpainting_insert_mask_mode_test.py
  generative_ai/image_generation/edit_image_inpainting_insert_mask_test.py
  generative_ai/image_generation/edit_image_inpainting_remove_mask.py
  generative_ai/image_generation/edit_image_inpainting_remove_mask_mode.py
  generative_ai/image_generation/edit_image_inpainting_remove_mask_mode_test.py
  generative_ai/image_generation/edit_image_inpainting_remove_mask_test.py
  generative_ai/image_generation/edit_image_mask.py
  generative_ai/image_generation/edit_image_mask_free.py
  generative_ai/image_generation/edit_image_mask_free_test.py
  generative_ai/image_generation/edit_image_mask_test.py
  generative_ai/image_generation/edit_image_outpainting_mask.py
  generative_ai/image_generation/edit_image_outpainting_mask_test.py
  generative_ai/image_generation/edit_image_product_image.py
  generative_ai/image_generation/edit_image_product_image_test.py
  generative_ai/image_generation/generate_image.py
  generative_ai/image_generation/generate_image_test.py
  generative_ai/image_generation/get_short_form_image_captions.py
  generative_ai/image_generation/get_short_form_image_captions_test.py
  generative_ai/image_generation/get_short_form_image_responses.py
  generative_ai/image_generation/get_short_form_image_responses_test.py
  generative_ai/image_generation/test_resources/cat.png
  generative_ai/image_generation/test_resources/dog.png
  generative_ai/image_generation/test_resources/dog_book.png
  generative_ai/image_generation/test_resources/dog_newspaper.png
  generative_ai/image_generation/test_resources/dog_newspaper_mask.png
  generative_ai/image_generation/test_resources/pillow.png
  generative_ai/image_generation/test_resources/pillow_on_beach.png
  generative_ai/image_generation/test_resources/roller_skaters.png
  generative_ai/image_generation/test_resources/roller_skaters_downtown.png
  generative_ai/image_generation/test_resources/roller_skaters_mask.png
  generative_ai/image_generation/test_resources/sports_car.png
  generative_ai/image_generation/test_resources/volleyball_game.png
  generative_ai/image_generation/test_resources/volleyball_game_inpainting_remove_mask.png
  generative_ai/image_generation/test_resources/volleyball_game_single_blue_player.png
  generative_ai/image_generation/test_resources/woman.png
  generative_ai/image_generation/test_resources/woman_at_beach.png
  generative_ai/image_generation/test_resources/woman_inpainting_insert_mask.png
  generative_ai/image_generation/test_resources/woman_with_hat.png
  generative_ai/image_generation/verify_image_watermark.py
  generative_ai/image_generation/verify_image_watermark_test.py
Labels: samples

#12640 fix(gemma2): Word fix in comments
  gemma2/gemma2_predict_gpu.py
  gemma2/gemma2_predict_tpu.py
Labels: samples
