Repository GoogleCloudPlatform/python-docs-samples, pull requests merged in 2025-06, with the labels that each got.

#13397 chore(generative_ai): unmark test as fixture
  generative_ai/embeddings/batch_example.py
  generative_ai/embeddings/test_embeddings_examples.py
Labels: samples

#13419 fix(retail): add region tag for Python - Update SearchWithPagination sample
  retail/interactive-tutorials/search/search_with_pagination.py
Labels: samples, api: retail

#13314 chore(modelarmor): refactored sanitization test cases and snippets args inconsistencies
  model_armor/snippets/create_template.py
  model_armor/snippets/create_template_with_advanced_sdp.py
  model_armor/snippets/create_template_with_metadata.py
  model_armor/snippets/delete_template.py
  model_armor/snippets/get_template.py
  model_armor/snippets/list_templates.py
  model_armor/snippets/list_templates_with_filter.py
  model_armor/snippets/requirements.txt
  model_armor/snippets/sanitize_user_prompt.py
  model_armor/snippets/snippets_test.py
  model_armor/snippets/update_template_metadata.py
Labels: samples

#13404 feat(genai): Live API WebSocket Example
  genai/live/hello_gemini_are_you_there.wav
  genai/live/live_websocket_audiogen_with_txt.py
  genai/live/live_websocket_audiotranscript_with_txt.py
  genai/live/live_websocket_textgen_with_audio.py
  genai/live/live_websocket_textgen_with_txt.py
  genai/live/live_with_txt.py
  genai/live/noxfile_config.py
  genai/live/requirements.txt
  genai/live/test_live_examples.py
Labels: samples

#13421 feat: update Imagen model version
  genai/image_generation/imggen_with_txt.py
Labels: samples

#13425 feat(run): add FastMCP MCP server sample
  run/mcp-server/.dockerignore
  run/mcp-server/Dockerfile
  run/mcp-server/README.md
  run/mcp-server/pyproject.toml
  run/mcp-server/server.py
  run/mcp-server/test_server.py
  run/mcp-server/uv.lock
Labels: api: run, samples

#13426 fix(functions): remove duplicate region tag
  functions/billing/main.py
Labels: api: cloudfunctions, samples

#13432 feat: set specific linting version for tests, min tested or 3.10
  noxfile-template.py
Labels: samples

#13439 feat(genai): update tuning gemini 2.5 flash base model name
  genai/tuning/tuning_job_create.py
  genai/tuning/tuning_with_checkpoints_create.py
Labels: samples

#13447 fix(retail): add region tag for Python - Update get_product.py
  retail/interactive-tutorials/product/get_product.py
Labels: samples, api: retail

#13443 fix(retail): add region tag for Python - Update delete_product.py
  retail/interactive-tutorials/product/delete_product.py
Labels: samples, api: retail

#13442 fix(retail): add region tag for Python - Update upate_product.py
  retail/interactive-tutorials/product/update_product.py
Labels: samples, api: retail

#13454 fix(genai): Use TuningDataset to set training dataset gcs uri
  genai/tuning/tuning_job_create.py
  genai/tuning/tuning_with_checkpoints_create.py
Labels: samples

#13459 feat(dataproc): Add Spark Job to Cluster sample
  dataproc/snippets/submit_spark_job_to_driver_node_group_cluster.py
  dataproc/snippets/submit_spark_job_to_driver_node_group_cluster_test.py
Labels: kokoro:force-run, api: dataproc, samples

#13469 feat(dataproc): Add Spark Job to Cluster sample (#13459)
  dataproc/snippets/submit_spark_job_to_driver_node_group_cluster.py
  dataproc/snippets/submit_spark_job_to_driver_node_group_cluster_test.py
Labels: api: dataproc, samples
