Repository GoogleCloudPlatform/python-docs-samples, pull requests merged in 2025-04, with the labels that each got.

#13281 chore(dns): delete all samples in the directory
  dns/api/README.rst
  dns/api/README.rst.in
  dns/api/main.py
  dns/api/main_test.py
  dns/api/noxfile_config.py
  dns/api/requirements-test.txt
  dns/api/requirements.txt
Labels: api: dns, samples

#13280 Update README.md
  functions/imagemagick/README.md
Labels: api: cloudfunctions, samples

#13289 chore(dns): remove entries in 'CODEOWNERS' and 'auto-label.yaml' for 'dns' product
  .github/CODEOWNERS
  .github/auto-label.yaml
Labels: api: dns, samples

#13261 fix(workflows): refactor sample 'workflows_api_quickstart' to comply with the Samples Style Guide and fix tests
  workflows/cloud-client/conftest.py
  workflows/cloud-client/main.py
  workflows/cloud-client/main_test.py
  workflows/cloud-client/noxfile_config.py
  workflows/cloud-client/requirements-test.txt
  workflows/cloud-client/requirements.txt
Labels: samples, api: workflows

#13287 docs(generative_ai): Update RAG Engine Samples to V1
  generative_ai/rag/create_corpus_example.py
  generative_ai/rag/create_corpus_pinecone_example.py
  generative_ai/rag/create_corpus_vector_search_example.py
  generative_ai/rag/create_corpus_vertex_ai_search_example.py
  generative_ai/rag/delete_corpus_example.py
  generative_ai/rag/delete_file_example.py
  generative_ai/rag/generate_content_example.py
  generative_ai/rag/get_corpus_example.py
  generative_ai/rag/get_file_example.py
  generative_ai/rag/import_files_async_example.py
  generative_ai/rag/import_files_example.py
  generative_ai/rag/list_corpora_example.py
  generative_ai/rag/list_files_example.py
  generative_ai/rag/quickstart_example.py
  generative_ai/rag/requirements.txt
  generative_ai/rag/retrieval_query_example.py
  generative_ai/rag/upload_file_example.py
Labels: samples

#13293 fix: update blur function to match other samples
  functions/imagemagick/main.py
  functions/imagemagick/main_test.py
  functions/v2/imagemagick/main.py
  functions/v2/imagemagick/main_test.py
Labels: api: cloudfunctions, samples

#13294 feat: update genai textgen_with_pdf.py example
  genai/text_generation/textgen_with_pdf.py
Labels: samples

#13292 chore(cloudrun): refactor to sample 'cloudrun_service_to_service_receive' and its test
  run/service-auth/app.py
  run/service-auth/noxfile_config.py
  run/service-auth/receive.py
  run/service-auth/receive_test.py
  run/service-auth/requirements-test.txt
  run/service-auth/requirements.txt
Labels: api: run, samples

#13296 feat: add code samples for model optimizer
  genai/text_generation/model_optimizer_textgen_with_txt.py
  genai/text_generation/test_text_generation_examples.py
Labels: samples

#13187 feat(modelarmor): created samples for model armor
  .github/CODEOWNERS
  .github/blunderbuss.yml
  model_armor/README.md
  model_armor/create_template.py
  model_armor/requirements.txt
  model_armor/sanitize_user_prompt.py
  model_armor/snippets/create_template.py
  model_armor/snippets/create_template_with_advanced_sdp.py
  model_armor/snippets/create_template_with_basic_sdp.py
  model_armor/snippets/create_template_with_labels.py
  model_armor/snippets/create_template_with_metadata.py
  model_armor/snippets/delete_template.py
  model_armor/snippets/get_folder_floor_settings.py
  model_armor/snippets/get_organization_floor_settings.py
  model_armor/snippets/get_project_floor_settings.py
  model_armor/snippets/get_template.py
  model_armor/snippets/list_templates.py
  model_armor/snippets/list_templates_with_filter.py
  model_armor/snippets/noxfile_config.py
  model_armor/snippets/quickstart.py
  model_armor/snippets/requirements-test.txt
  model_armor/snippets/requirements.txt
  model_armor/snippets/sanitize_model_response.py
  model_armor/snippets/sanitize_model_response_with_user_prompt.py
  model_armor/snippets/sanitize_user_prompt.py
  model_armor/snippets/screen_pdf_file.py
  model_armor/snippets/snippets_test.py
  model_armor/snippets/update_folder_floor_settings.py
  model_armor/snippets/update_organizations_floor_settings.py
  model_armor/snippets/update_project_floor_settings.py
  model_armor/snippets/update_template.py
  model_armor/snippets/update_template_labels.py
  model_armor/snippets/update_template_metadata.py
  model_armor/snippets/update_template_with_mask_configuration.py
  model_armor/test_templates.py
  model_armor/update_template.py
Labels: do not merge, samples

#13305 fix: refactor model_armor
  model_armor/snippets/quickstart.py
  model_armor/snippets/screen_pdf_file.py
  model_armor/snippets/snippets_test.py
  model_armor/snippets/test_sample.pdf
Labels: samples

#13300 Add script for migrating environment from Composer 2 to Composer 3
  composer/tools/composer_migrate.md
  composer/tools/composer_migrate.py
Labels: api: composer, samples

#13304 feat(Dataflow): Update Kafka snippet to use Managed I/O
  dataflow/snippets/Dockerfile
  dataflow/snippets/noxfile_config.py
  dataflow/snippets/read_kafka.py
  dataflow/snippets/requirements.txt
Labels: api: dataflow, samples

#13310 Update import_files_example.py to optionally use import_result_sink to show import result status in a written GCS file.
  generative_ai/rag/import_files_example.py
Labels: samples

#13318 chore: cleanup old code samples
  generative_ai/image_generation/verify_image_watermark.py
  generative_ai/image_generation/verify_image_watermark_test.py
Labels: samples

#13312 chore(secretmanager): Add global samples for delayed destory
  secretmanager/snippets/create_secret_with_delayed_destroy.py
  secretmanager/snippets/disable_secret_with_delayed_destroy.py
  secretmanager/snippets/snippets_test.py
  secretmanager/snippets/update_secret_with_delayed_destroy.py
Labels: api: secretmanager, samples

#13321 docs: region tags clean-up
  genai/count_tokens/counttoken_compute_with_txt.py
  genai/count_tokens/counttoken_resp_with_txt.py
  genai/count_tokens/counttoken_with_txt.py
  genai/count_tokens/counttoken_with_txt_vid.py
Labels: samples

#13320 feat(genai): Add new image generation samples
  genai/image_generation/imggen_canny_ctrl_type_with_txt_img.py
  genai/image_generation/imggen_raw_reference_with_txt_img.py
  genai/image_generation/imggen_scribble_ctrl_type_with_txt_img.py
  genai/image_generation/imggen_style_reference_with_txt_img.py
  genai/image_generation/imggen_subj_refer_ctrl_refer_with_txt_imgs.py
  genai/image_generation/noxfile_config.py
  genai/image_generation/requirements-test.txt
  genai/image_generation/requirements.txt
  genai/image_generation/test_image_generation.py
Labels: samples

#13313 Bump up runtime version to python 3.13
  appengine/standard_python3/building-an-app/building-an-app-1/app.yaml
Labels: api: appengine, samples
