Repository GoogleCloudPlatform/python-docs-samples, pull requests merged in 2025-05, with the labels that each got.

#13330 docs(discoveryengine): Add Cancel Operation Sample
  discoveryengine/cancel_operation_sample.py
  discoveryengine/operations_sample_test.py
  discoveryengine/requirements.txt
Labels: samples, api: discoveryengine

#13311 Add code samples for Connect Gateway API
  .github/CODEOWNERS
  .github/blunderbuss.yml
  connectgateway/README.md
  connectgateway/get_namespace.py
  connectgateway/get_namespace_test.py
  connectgateway/noxfile_config.py
  connectgateway/requirements-test.txt
  connectgateway/requirements.txt
Labels: samples

#13328 chore(workflows): migrate samples 'execute_without_arguments' and 'execute_with_arguments' - step 1
  workflows/cloud-client/execute_with_arguments.py
  workflows/cloud-client/execute_with_arguments_test.py
  workflows/cloud-client/execute_without_arguments.py
  workflows/cloud-client/execute_without_arguments_test.py
Labels: samples, api: workflows

#13334 feat(image-generation): Image generation using Gemini Flash
  genai/image_generation/imggen_mmflash_edit_img_with_txt_img.py
  genai/image_generation/imggen_mmflash_txt_and_img_with_txt.py
  genai/image_generation/imggen_mmflash_with_txt.py
  genai/image_generation/noxfile_config.py
  genai/image_generation/test_image_generation.py
Labels: samples

#13338 fix: Remove reference to Gemini 1.5
  generative_ai/prompts/test_resources/sample_configuration.json
Labels: samples

#13336 feat(genai): Add new sample for image gen
  genai/image_generation/imggen_with_txt.py
  genai/image_generation/test_image_generation.py
Labels: samples

#13295 fix(composer): fix version check logic for 'airflow_db_cleanup.py'
  composer/workflows/airflow_db_cleanup.py
  composer/workflows/airflow_db_cleanup_test.py
  composer/workflows/noxfile_config.py
  composer/workflows/requirements.txt
Labels: api: composer, samples

#13342 chore: fix docker build for Python 3.8
  .kokoro/docker/Dockerfile
Labels: samples

#13354 chore: Removing dee-infra from CODEOWNERS and Blunderbuss config files
  .github/CODEOWNERS
  .github/blunderbuss.yml
Labels: samples

#13358 Fix type annotations
  trace/cloud-trace-demo-app-opentelemetry/app/app.py
Labels: api: cloudtrace, samples

#13360 feat(genai): Add tuning examples
  genai/tuning/noxfile_config.py
  genai/tuning/requirements-test.txt
  genai/tuning/requirements.txt
  genai/tuning/test_tuning_examples.py
  genai/tuning/tuning_job_create.py
  genai/tuning/tuning_job_get.py
  genai/tuning/tuning_job_list.py
  genai/tuning/tuning_textgen_with_txt.py
Labels: samples

#13317 chore(secretmanager): Add regional samples for delayed destory
  secretmanager/snippets/regional_samples/create_regional_secret_with_delayed_destroy.py
  secretmanager/snippets/regional_samples/disable_regional_secret_delayed_destroy.py
  secretmanager/snippets/regional_samples/snippets_test.py
  secretmanager/snippets/regional_samples/update_regional_secret_with_delayed_destroy.py
Labels: api: secretmanager, samples, waiting-response

#13371 chore(retail): add region tag to fix broken 404
  retail/interactive-tutorials/search/search_simple_query.py
Labels: samples, api: retail

#13380 chore(gae): delete samples for Python 2.7 in 'storage' folder
  appengine/standard/storage/.gitignore
  appengine/standard/storage/api-client/README.md
  appengine/standard/storage/api-client/app.yaml
  appengine/standard/storage/api-client/appengine_config.py
  appengine/standard/storage/api-client/main.py
  appengine/standard/storage/api-client/main_test.py
  appengine/standard/storage/api-client/requirements-test.txt
  appengine/standard/storage/api-client/requirements.txt
  appengine/standard/storage/appengine-client/__init__.py
  appengine/standard/storage/appengine-client/app.yaml
  appengine/standard/storage/appengine-client/appengine_config.py
  appengine/standard/storage/appengine-client/main.py
  appengine/standard/storage/appengine-client/main_test.py
  appengine/standard/storage/appengine-client/requirements-test.txt
  appengine/standard/storage/appengine-client/requirements.txt
Labels: api: appengine, samples

#13382 feat: new image model sample update
  genai/image_generation/imggen_with_txt.py
  genai/image_generation/test_image_generation.py
  genai/image_generation/test_resources/dog_newspaper.png
Labels: samples

#13383 feat(genai): video model version update
  genai/video_generation/videogen_with_img.py
  genai/video_generation/videogen_with_txt.py
Labels: samples

#13368 docs(samples): Change sample to use Gemini Embedding model
  genai/embeddings/embeddings_docretrieval_with_txt.py
Labels: samples, waiting-response

#13386 fix(firestore): add a note for devs and asserts for `firestore_data_delete_collection`
  firestore/cloud-client/snippets_test.py
Labels: api: firestore, samples

#13388 Update model name to gemini-embedding-001 in code snipets
  generative_ai/embeddings/batch_example.py
  generative_ai/embeddings/code_retrieval_example.py
  generative_ai/embeddings/document_retrieval_example.py
  generative_ai/embeddings/test_embeddings_examples.py
Labels: samples

#13372 fix(cloudrun): fix 'cloudrun_service_to_service_receive' sample
  run/service-auth/app.py
  run/service-auth/receive.py
  run/service-auth/receive_auth_requests_test.py
  run/service-auth/requirements-test.txt
  run/service-auth/requirements.txt
Labels: api: run, samples

#13390 chore: disable global blunderbuss assignments
  .github/blunderbuss.yml
Labels: samples

#13359 fix(functions): update and fix functions_billing_stop sample
  functions/billing_stop_on_notification/requirements-test.txt
  functions/billing_stop_on_notification/requirements.txt
  functions/billing_stop_on_notification/stop_billing.py
  functions/billing_stop_on_notification/stop_billing_test.py
Labels: api: cloudfunctions, samples

#13396 fix: Revert the change in generative_ai/embeddings/batch_example.py
  generative_ai/embeddings/batch_example.py
Labels: samples

#13395 fix(translate): update sample `translate_text` to unify across languages
  translate/samples/snippets/snippets.py
  translate/samples/snippets/snippets_test.py
Labels: api: translate, samples
