Repository GoogleCloudPlatform/python-docs-samples, pull requests merged in 2025-09, with the labels that each got.

#13556 chore: remove flakybot.yaml
  .github/flakybot.yaml
Labels: samples

#13522 Add Managed Kafka Connect Connectors Examples
  managedkafka/snippets/connect/connectors/connectors_test.py
  managedkafka/snippets/connect/connectors/create_bigquery_sink_connector.py
  managedkafka/snippets/connect/connectors/create_cloud_storage_sink_connector.py
  managedkafka/snippets/connect/connectors/create_mirrormaker2_source_connector.py
  managedkafka/snippets/connect/connectors/create_pubsub_sink_connector.py
  managedkafka/snippets/connect/connectors/create_pubsub_source_connector.py
Labels: samples

#13543 chore: migrate handwritten samples from googleapis/python-bigquery-storage
  bigquery_storage/__init__.py
  bigquery_storage/conftest.py
  bigquery_storage/pyarrow/__init__.py
  bigquery_storage/pyarrow/append_rows_with_arrow.py
  bigquery_storage/pyarrow/append_rows_with_arrow_test.py
  bigquery_storage/pyarrow/noxfile_config.py
  bigquery_storage/pyarrow/requirements-test.txt
  bigquery_storage/pyarrow/requirements.txt
  bigquery_storage/quickstart/__init__.py
  bigquery_storage/quickstart/noxfile_config.py
  bigquery_storage/quickstart/quickstart.py
  bigquery_storage/quickstart/quickstart_test.py
  bigquery_storage/quickstart/requirements-test.txt
  bigquery_storage/quickstart/requirements.txt
  bigquery_storage/snippets/__init__.py
  bigquery_storage/snippets/append_rows_pending.py
  bigquery_storage/snippets/append_rows_pending_test.py
  bigquery_storage/snippets/append_rows_proto2.py
  bigquery_storage/snippets/append_rows_proto2_test.py
  bigquery_storage/snippets/conftest.py
  bigquery_storage/snippets/customer_record.proto
  bigquery_storage/snippets/customer_record_pb2.py
  bigquery_storage/snippets/customer_record_schema.json
  bigquery_storage/snippets/noxfile_config.py
  bigquery_storage/snippets/requirements-test.txt
  bigquery_storage/snippets/requirements.txt
  bigquery_storage/snippets/sample_data.proto
  bigquery_storage/snippets/sample_data_pb2.py
  bigquery_storage/snippets/sample_data_schema.json
  bigquery_storage/to_dataframe/__init__.py
  bigquery_storage/to_dataframe/jupyter_test.py
  bigquery_storage/to_dataframe/noxfile_config.py
  bigquery_storage/to_dataframe/read_query_results.py
  bigquery_storage/to_dataframe/read_query_results_test.py
  bigquery_storage/to_dataframe/read_table_bigquery.py
  bigquery_storage/to_dataframe/read_table_bigquery_test.py
  bigquery_storage/to_dataframe/read_table_bqstorage.py
  bigquery_storage/to_dataframe/read_table_bqstorage_test.py
  bigquery_storage/to_dataframe/requirements-test.txt
  bigquery_storage/to_dataframe/requirements.txt
Labels: samples, api: bigquerystorage

#13564 revert: "docs: Remove Grounded Generation Samples"
  discoveryengine/standalone_apis_sample.py
  discoveryengine/standalone_apis_sample_test.py
Labels: samples, api: discoveryengine

#13576 Fix some dag_runs removed unintentionally
  composer/workflows/airflow_db_cleanup.py
Labels: api: composer, samples
